julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119588
bytes = 5520536
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036611
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009685
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117573
bytes = 4730568
compile_seconds = 0.0
samples = 3
seconds = 0.0024876

[datasets.adlittle.primal]
allocations = 120386
bytes = 5797192
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038762
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607104
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010938
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 7.64e-5

[datasets.adlittle.sparse]
allocations = 3267
bytes = 193200
compile_seconds = 0.0
samples = 3
seconds = 0.0001388

[datasets.afiro.dual]
allocations = 27450
bytes = 1265368
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000948
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002523
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26635
bytes = 1129944
compile_seconds = 0.0
samples = 3
seconds = 0.0007607

[datasets.afiro.primal]
allocations = 27356
bytes = 1243656
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008683
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000219901
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 46256
compile_seconds = 0.0
samples = 3
seconds = 9.44e-5

[datasets.afiro.sparse]
allocations = 6386
bytes = 273392
compile_seconds = 0.0
samples = 3
seconds = 0.0001897

[datasets.flugpl.dual]
allocations = 39614
bytes = 1600528
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010227
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001359
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38943
bytes = 1490056
compile_seconds = 0.0
samples = 3
seconds = 0.0008087

[datasets.flugpl.primal]
allocations = 39963
bytes = 1645120
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000942
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000177
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 8.2e-6

[datasets.flugpl.sparse]
allocations = 6248
bytes = 234120
compile_seconds = 0.0
samples = 3
seconds = 0.0001365

[datasets.kb2.dual]
allocations = 292777
bytes = 13575344
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021348202
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007806
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291575
bytes = 13122960
compile_seconds = 0.0
samples = 3
seconds = 0.021094603

[datasets.kb2.primal]
allocations = 292944
bytes = 13588768
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023135902
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005743
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 148472
compile_seconds = 0.0
samples = 3
seconds = 9.3e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197976
compile_seconds = 0.0
samples = 3
seconds = 0.0001095

[datasets.sc50a.dual]
allocations = 102738
bytes = 4460128
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025023
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306464
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006166
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101666
bytes = 4113328
compile_seconds = 0.0
samples = 3
seconds = 0.0020091

[datasets.sc50a.primal]
allocations = 102683
bytes = 4412560
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002487301
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004952
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.24e-5

[datasets.sc50a.sparse]
allocations = 9239
bytes = 402568
compile_seconds = 0.0
samples = 3
seconds = 0.0002305

[probes.singleton]
allocations = 275
bytes = 15200
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[probes.sparse]
allocations = 285
bytes = 15632
compile_seconds = 0.0
samples = 3
seconds = 1.51e-5
