julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85374
bytes = 4159496
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003796698
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461336
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001011199
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83359
bytes = 3370280
compile_seconds = 0.0
samples = 3
seconds = 0.002203999

[datasets.adlittle.primal]
allocations = 86172
bytes = 4436568
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003682298
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607760
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001168399
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 8.72e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185152
compile_seconds = 0.0
samples = 3
seconds = 0.0001355

[datasets.afiro.dual]
allocations = 18277
bytes = 912816
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000836399
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002089
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17462
bytes = 777232
compile_seconds = 0.0
samples = 3
seconds = 0.0006495

[datasets.afiro.primal]
allocations = 18183
bytes = 890752
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000808999
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000221899
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 44816
compile_seconds = 0.0
samples = 3
seconds = 8.89e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 269776
compile_seconds = 0.0
samples = 3
seconds = 0.0001758

[datasets.flugpl.dual]
allocations = 33163
bytes = 1348720
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009128
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001611
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 32492
bytes = 1239512
compile_seconds = 0.0
samples = 3
seconds = 0.0007558

[datasets.flugpl.primal]
allocations = 33512
bytes = 1393200
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009705
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000195
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.23e-5

[datasets.flugpl.sparse]
allocations = 6013
bytes = 225336
compile_seconds = 0.0
samples = 3
seconds = 0.0001579

[datasets.kb2.dual]
allocations = 232959
bytes = 11198720
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02141119
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009604
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231757
bytes = 10744640
compile_seconds = 0.0
samples = 3
seconds = 0.02050279

[datasets.kb2.primal]
allocations = 233126
bytes = 11211280
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.02079029
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260880
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006432
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2656
bytes = 137888
compile_seconds = 0.0
samples = 3
seconds = 9.89e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197592
compile_seconds = 0.0
samples = 3
seconds = 0.0001349

[datasets.sc50a.dual]
allocations = 72627
bytes = 3354472
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021753
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306400
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005604
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3008520
compile_seconds = 0.0
samples = 3
seconds = 0.0016159

[datasets.sc50a.primal]
allocations = 72572
bytes = 3307352
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021578
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004796
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.96e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 392392
compile_seconds = 0.0
samples = 3
seconds = 0.0002302

[probes.free]
allocations = 17658
bytes = 687480
compile_seconds = 0.0
samples = 3
seconds = 0.0003855

[probes.nonzero]
allocations = 29178
bytes = 1121560
compile_seconds = 0.0
samples = 3
seconds = 0.0005824

[probes.singleton_negative]
allocations = 25341
bytes = 986720
compile_seconds = 0.0
samples = 3
seconds = 0.0004956

[probes.singleton_positive]
allocations = 25338
bytes = 985368
compile_seconds = 0.0
samples = 3
seconds = 0.00052

[probes.sparse_negative]
allocations = 44116
bytes = 1655160
compile_seconds = 0.0
samples = 3
seconds = 0.0007937

[probes.sparse_positive]
allocations = 44110
bytes = 1653608
compile_seconds = 0.0
samples = 3
seconds = 0.0008903
