julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84980
bytes = 4144320
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003551
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461240
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000959
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82965
bytes = 3353312
compile_seconds = 0.0
samples = 3
seconds = 0.0024126

[datasets.adlittle.primal]
allocations = 85778
bytes = 4420528
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038807
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607728
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001145
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 9.03e-5

[datasets.adlittle.sparse]
allocations = 2861
bytes = 177392
compile_seconds = 0.0
samples = 3
seconds = 0.0001436

[datasets.afiro.dual]
allocations = 17505
bytes = 881872
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008163
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001721
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16690
bytes = 746528
compile_seconds = 0.0
samples = 3
seconds = 0.0006343

[datasets.afiro.primal]
allocations = 17411
bytes = 859616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007834
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002015
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45024
compile_seconds = 0.0
samples = 3
seconds = 8.8e-5

[datasets.afiro.sparse]
allocations = 5517
bytes = 238664
compile_seconds = 0.0
samples = 3
seconds = 0.0001877

[datasets.flugpl.dual]
allocations = 32286
bytes = 1313128
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010163
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001259
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1203520
compile_seconds = 0.0
samples = 3
seconds = 0.0007488

[datasets.flugpl.primal]
allocations = 32635
bytes = 1357512
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010342
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001873
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.17e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 215784
compile_seconds = 0.0
samples = 3
seconds = 0.0001739

[datasets.kb2.dual]
allocations = 231270
bytes = 11133032
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0210268
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878288
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.00089
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230068
bytes = 10680792
compile_seconds = 0.0
samples = 3
seconds = 0.0201202

[datasets.kb2.primal]
allocations = 231437
bytes = 11147400
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0223659
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006602
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112160
compile_seconds = 0.0
samples = 3
seconds = 0.000111

[datasets.kb2.sparse]
allocations = 2958
bytes = 165712
compile_seconds = 0.0
samples = 3
seconds = 0.0001328

[datasets.sc50a.dual]
allocations = 69752
bytes = 3240760
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021783
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006298
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 68680
bytes = 2894296
compile_seconds = 0.0
samples = 3
seconds = 0.0016883

[datasets.sc50a.primal]
allocations = 69697
bytes = 3193864
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021661
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004804
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.sc50a.sparse]
allocations = 7434
bytes = 331008
compile_seconds = 0.0
samples = 3
seconds = 0.0002214

[probes.multiplier_negative]
allocations = 38487
bytes = 1438720
compile_seconds = 0.0
samples = 3
seconds = 0.0008481

[probes.multiplier_positive]
allocations = 38228
bytes = 1430296
compile_seconds = 0.0
samples = 3
seconds = 0.0008838

[probes.nonunit]
allocations = 39374
bytes = 1474776
compile_seconds = 0.0
samples = 3
seconds = 0.0008012

[probes.rhs_negative]
allocations = 38484
bytes = 1438616
compile_seconds = 0.0
samples = 3
seconds = 0.000827

[probes.rhs_positive]
allocations = 38228
bytes = 1431736
compile_seconds = 0.0
samples = 3
seconds = 0.0007839

[probes.zero]
allocations = 31444
bytes = 1177048
compile_seconds = 0.0
samples = 3
seconds = 0.0006506
