julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84980
bytes = 4145200
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035905
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009848
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82965
bytes = 3356192
compile_seconds = 0.0
samples = 3
seconds = 0.0023034

[datasets.adlittle.primal]
allocations = 85778
bytes = 4422480
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003821
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607696
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011277
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.49e-5

[datasets.adlittle.sparse]
allocations = 2861
bytes = 177680
compile_seconds = 0.0
samples = 3
seconds = 0.0001538

[datasets.afiro.dual]
allocations = 17554
bytes = 885808
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007841
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002118
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16739
bytes = 749808
compile_seconds = 0.0
samples = 3
seconds = 0.0006243

[datasets.afiro.primal]
allocations = 17460
bytes = 863392
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008038
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002209
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44784
compile_seconds = 0.0
samples = 3
seconds = 8.7e-5

[datasets.afiro.sparse]
allocations = 5587
bytes = 242352
compile_seconds = 0.0
samples = 3
seconds = 0.0001689

[datasets.flugpl.dual]
allocations = 32286
bytes = 1315192
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009329
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001674
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1206000
compile_seconds = 0.0
samples = 3
seconds = 0.0007674

[datasets.flugpl.primal]
allocations = 32635
bytes = 1359752
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009737
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001859
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.02e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216168
compile_seconds = 0.0
samples = 3
seconds = 0.0001568

[datasets.kb2.dual]
allocations = 231326
bytes = 11137800
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0212637
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008762
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230124
bytes = 10684776
compile_seconds = 0.0
samples = 3
seconds = 0.020695301

[datasets.kb2.primal]
allocations = 231493
bytes = 11151080
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0215928
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006397
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112544
compile_seconds = 0.0
samples = 3
seconds = 0.0001253

[datasets.kb2.sparse]
allocations = 3028
bytes = 169344
compile_seconds = 0.0
samples = 3
seconds = 0.0001366

[datasets.sc50a.dual]
allocations = 70130
bytes = 3260232
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022892
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306432
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000583
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 69058
bytes = 2914344
compile_seconds = 0.0
samples = 3
seconds = 0.0017958

[datasets.sc50a.primal]
allocations = 70075
bytes = 3212488
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022424
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005454
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.1e-5

[datasets.sc50a.sparse]
allocations = 7651
bytes = 341520
compile_seconds = 0.0
samples = 3
seconds = 0.0002616

[probes.negative_negative]
allocations = 37838
bytes = 1410120
compile_seconds = 0.0
samples = 3
seconds = 0.00077

[probes.negative_positive]
allocations = 37847
bytes = 1410688
compile_seconds = 0.0
samples = 3
seconds = 0.0007179

[probes.nonunit]
allocations = 39380
bytes = 1475688
compile_seconds = 0.0
samples = 3
seconds = 0.0007878

[probes.positive_negative]
allocations = 37079
bytes = 1388912
compile_seconds = 0.0
samples = 3
seconds = 0.0007457

[probes.positive_positive]
allocations = 37070
bytes = 1387320
compile_seconds = 0.0
samples = 3
seconds = 0.000716

[probes.singleton]
allocations = 19328
bytes = 762264
compile_seconds = 0.0
samples = 3
seconds = 0.0004577
