julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 83444
bytes = 4078952
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003537212
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461176
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000961103
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81429
bytes = 3289880
compile_seconds = 0.0
samples = 3
seconds = 0.002119607

[datasets.adlittle.primal]
allocations = 84242
bytes = 4355528
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003925614
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607536
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001238405
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642056
compile_seconds = 0.0
samples = 3
seconds = 0.000380602

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.6e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 157096
compile_seconds = 0.0
samples = 3
seconds = 0.000141801

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.afiro.dual]
allocations = 16468
bytes = 842424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000849099
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001967
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15653
bytes = 707016
compile_seconds = 0.0
samples = 3
seconds = 0.000598399

[datasets.afiro.primal]
allocations = 16374
bytes = 820744
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000799503
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000243301
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92408
compile_seconds = 0.0
samples = 3
seconds = 8.42e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40976
compile_seconds = 0.0
samples = 3
seconds = 8.3601e-5

[datasets.afiro.sparse]
allocations = 4167
bytes = 186872
compile_seconds = 0.0
samples = 3
seconds = 0.000183202

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 8.101e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 28749
bytes = 1174088
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.00102781
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000190701
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 28078
bytes = 1064512
compile_seconds = 0.0
samples = 3
seconds = 0.000779207

[datasets.flugpl.primal]
allocations = 29098
bytes = 1218664
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000985109
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000161502
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123104
compile_seconds = 0.0
samples = 3
seconds = 0.000124001

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.flugpl.sparse]
allocations = 4677
bytes = 173616
compile_seconds = 0.0
samples = 3
seconds = 0.000140202

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.kb2.dual]
allocations = 229111
bytes = 11045712
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02071367
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878000
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000801803
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227909
bytes = 10590912
compile_seconds = 0.0
samples = 3
seconds = 0.020757871

[datasets.kb2.primal]
allocations = 229278
bytes = 11058592
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021692474
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000665803
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454560
compile_seconds = 0.0
samples = 3
seconds = 0.000314801

[datasets.kb2.singleton]
allocations = 1915
bytes = 105800
compile_seconds = 0.0
samples = 3
seconds = 9.59e-5

[datasets.kb2.sparse]
allocations = 2259
bytes = 137688
compile_seconds = 0.0
samples = 3
seconds = 0.0001257

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 67374
bytes = 3147048
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002084607
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306320
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000611002
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66302
bytes = 2802344
compile_seconds = 0.0
samples = 3
seconds = 0.001671605

[datasets.sc50a.primal]
allocations = 67319
bytes = 3099624
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002021919
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000544305
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221936
compile_seconds = 0.0
samples = 3
seconds = 0.0001723

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.48e-5

[datasets.sc50a.sparse]
allocations = 6174
bytes = 282208
compile_seconds = 0.0
samples = 3
seconds = 0.0002093

[probes.fraction_negative]
allocations = 44983
bytes = 1683688
compile_seconds = 0.0
samples = 3
seconds = 0.000963513

[probes.fraction_positive]
allocations = 44983
bytes = 1683656
compile_seconds = 0.0
samples = 3
seconds = 0.000961913

[probes.free_pivot]
allocations = 29623
bytes = 1196920
compile_seconds = 0.0
samples = 3
seconds = 0.000690609

[probes.integer_negative]
allocations = 43959
bytes = 1635880
compile_seconds = 0.0
samples = 3
seconds = 0.000937912

[probes.integer_positive]
allocations = 43959
bytes = 1633976
compile_seconds = 0.0
samples = 3
seconds = 0.000944513

[probes.unequal]
allocations = 47543
bytes = 1762744
compile_seconds = 0.0
samples = 3
seconds = 0.000948613
