julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.adlittle.dual]
allocations = 83266
bytes = 4072896
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033522
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461144
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009586
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81251
bytes = 3282832
compile_seconds = 0.0
samples = 3
seconds = 0.0019791

[datasets.adlittle.primal]
allocations = 84064
bytes = 4349344
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035752
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607664
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010739
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640536
compile_seconds = 0.0
samples = 3
seconds = 0.0003604

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.06e-5

[datasets.adlittle.sparse]
allocations = 2282
bytes = 154568
compile_seconds = 0.0
samples = 3
seconds = 9.52e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.afiro.dual]
allocations = 16441
bytes = 840616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007247
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002009
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15626
bytes = 705064
compile_seconds = 0.0
samples = 3
seconds = 0.000585

[datasets.afiro.primal]
allocations = 16347
bytes = 818520
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007214
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002032
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92568
compile_seconds = 0.0
samples = 3
seconds = 8.48e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 41440
compile_seconds = 0.0
samples = 3
seconds = 9.34e-5

[datasets.afiro.sparse]
allocations = 4116
bytes = 184904
compile_seconds = 0.0
samples = 3
seconds = 0.0001461

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.flugpl.dual]
allocations = 28597
bytes = 1166608
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008627
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001436
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27926
bytes = 1057464
compile_seconds = 0.0
samples = 3
seconds = 0.0007138

[datasets.flugpl.primal]
allocations = 28946
bytes = 1211136
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008746
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001736
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123056
compile_seconds = 0.0
samples = 3
seconds = 9.59e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.flugpl.sparse]
allocations = 4646
bytes = 172072
compile_seconds = 0.0
samples = 3
seconds = 0.0001355

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.kb2.dual]
allocations = 228665
bytes = 11026432
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0204793
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008413
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227463
bytes = 10576032
compile_seconds = 0.0
samples = 3
seconds = 0.0203426

[datasets.kb2.primal]
allocations = 228832
bytes = 11042176
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0202594
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006465
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453744
compile_seconds = 0.0
samples = 3
seconds = 0.0002658

[datasets.kb2.singleton]
allocations = 1915
bytes = 105336
compile_seconds = 0.0
samples = 3
seconds = 9.64e-5

[datasets.kb2.sparse]
allocations = 2207
bytes = 135400
compile_seconds = 0.0
samples = 3
seconds = 0.0001087

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.63e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 67169
bytes = 3141720
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020177
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005373
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66097
bytes = 2795592
compile_seconds = 0.0
samples = 3
seconds = 0.0015093

[datasets.sc50a.primal]
allocations = 67114
bytes = 3094232
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018994
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005231
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221200
compile_seconds = 0.0
samples = 3
seconds = 0.0001512

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.42e-5

[datasets.sc50a.sparse]
allocations = 6081
bytes = 278960
compile_seconds = 0.0
samples = 3
seconds = 0.000195

[probes.fraction_negative]
allocations = 42295
bytes = 1572056
compile_seconds = 0.0
samples = 3
seconds = 0.0008273

[probes.fraction_positive]
allocations = 42295
bytes = 1571672
compile_seconds = 0.0
samples = 3
seconds = 0.0007356

[probes.negative]
allocations = 40503
bytes = 1489640
compile_seconds = 0.0
samples = 3
seconds = 0.0007515

[probes.nonzero_rhs]
allocations = 46647
bytes = 1715240
compile_seconds = 0.0
samples = 3
seconds = 0.0009523

[probes.positive]
allocations = 40503
bytes = 1487672
compile_seconds = 0.0
samples = 3
seconds = 0.0008236

[probes.zero_activity]
allocations = 31543
bytes = 1207160
compile_seconds = 0.0
samples = 3
seconds = 0.0006525
