julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84980
bytes = 4144224
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035024
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461016
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009979
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82965
bytes = 3353872
compile_seconds = 0.0
samples = 3
seconds = 0.0021358

[datasets.adlittle.primal]
allocations = 85778
bytes = 4421152
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039712
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607296
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011648
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.71e-5

[datasets.adlittle.sparse]
allocations = 2861
bytes = 177760
compile_seconds = 0.0
samples = 3
seconds = 0.0001374

[datasets.afiro.dual]
allocations = 17505
bytes = 883136
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007337
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002151
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16690
bytes = 746816
compile_seconds = 0.0
samples = 3
seconds = 0.0007165

[datasets.afiro.primal]
allocations = 17411
bytes = 860816
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007692
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002196
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45088
compile_seconds = 0.0
samples = 3
seconds = 9.89e-5

[datasets.afiro.sparse]
allocations = 5517
bytes = 239880
compile_seconds = 0.0
samples = 3
seconds = 0.0001836

[datasets.flugpl.dual]
allocations = 32286
bytes = 1314552
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009991
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001668
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1205200
compile_seconds = 0.0
samples = 3
seconds = 0.0008172

[datasets.flugpl.primal]
allocations = 32635
bytes = 1359224
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010436
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000205
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.44e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216488
compile_seconds = 0.0
samples = 3
seconds = 0.0001719

[datasets.kb2.dual]
allocations = 231270
bytes = 11134328
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0217992
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878048
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008813
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230068
bytes = 10681064
compile_seconds = 0.0
samples = 3
seconds = 0.020859901

[datasets.kb2.primal]
allocations = 231437
bytes = 11149576
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0212636
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260896
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006389
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112368
compile_seconds = 0.0
samples = 3
seconds = 0.0001239

[datasets.kb2.sparse]
allocations = 2958
bytes = 165872
compile_seconds = 0.0
samples = 3
seconds = 0.0001395

[datasets.sc50a.dual]
allocations = 69752
bytes = 3241992
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022341
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306416
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006081
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 68680
bytes = 2896088
compile_seconds = 0.0
samples = 3
seconds = 0.0017675

[datasets.sc50a.primal]
allocations = 69697
bytes = 3194648
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022963
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005398
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.66e-5

[datasets.sc50a.sparse]
allocations = 7434
bytes = 332304
compile_seconds = 0.0
samples = 3
seconds = 0.0002326

[probes.negative_absent]
allocations = 28751
bytes = 1099496
compile_seconds = 0.0
samples = 3
seconds = 0.000624199

[probes.negative_present]
allocations = 29142
bytes = 1109128
compile_seconds = 0.0
samples = 3
seconds = 0.000657

[probes.nonzero]
allocations = 38228
bytes = 1431480
compile_seconds = 0.0
samples = 3
seconds = 0.0009156

[probes.positive_absent]
allocations = 28751
bytes = 1099320
compile_seconds = 0.0
samples = 3
seconds = 0.0005868

[probes.positive_present]
allocations = 29142
bytes = 1107448
compile_seconds = 0.0
samples = 3
seconds = 0.0006265

[probes.singleton]
allocations = 20480
bytes = 804648
compile_seconds = 0.0
samples = 3
seconds = 0.0004446
