julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.6e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.adlittle.dual]
allocations = 83431
bytes = 4080224
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033013
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461064
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008988
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81416
bytes = 3289008
compile_seconds = 0.0
samples = 3
seconds = 0.002002999

[datasets.adlittle.primal]
allocations = 84229
bytes = 4356624
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003870599
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607088
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010457
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640840
compile_seconds = 0.0
samples = 3
seconds = 0.0003487

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.31e-5

[datasets.adlittle.sparse]
allocations = 2336
bytes = 156824
compile_seconds = 0.0
samples = 3
seconds = 0.0001212

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 16456
bytes = 841800
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007488
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001996
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15641
bytes = 706264
compile_seconds = 0.0
samples = 3
seconds = 0.0005304

[datasets.afiro.primal]
allocations = 16362
bytes = 818744
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007442
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002159
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92808
compile_seconds = 0.0
samples = 3
seconds = 9.93e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 41264
compile_seconds = 0.0
samples = 3
seconds = 8.61e-5

[datasets.afiro.sparse]
allocations = 4155
bytes = 186120
compile_seconds = 0.0
samples = 3
seconds = 0.0001601

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 28597
bytes = 1167152
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000863599
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001587
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27926
bytes = 1057336
compile_seconds = 0.0
samples = 3
seconds = 0.0006583

[datasets.flugpl.primal]
allocations = 28946
bytes = 1211584
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000825399
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001865
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123344
compile_seconds = 0.0
samples = 3
seconds = 0.0001124

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.flugpl.sparse]
allocations = 4667
bytes = 173368
compile_seconds = 0.0
samples = 3
seconds = 0.000123699

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.kb2.dual]
allocations = 229107
bytes = 11045152
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020389777
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000870099
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227905
bytes = 10590752
compile_seconds = 0.0
samples = 3
seconds = 0.0197813

[datasets.kb2.primal]
allocations = 229274
bytes = 11059472
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020381277
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000602199
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454672
compile_seconds = 0.0
samples = 3
seconds = 0.0002687

[datasets.kb2.singleton]
allocations = 1915
bytes = 105704
compile_seconds = 0.0
samples = 3
seconds = 9.45e-5

[datasets.kb2.sparse]
allocations = 2257
bytes = 137512
compile_seconds = 0.0
samples = 3
seconds = 0.0001104

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.67e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.sc50a.dual]
allocations = 67347
bytes = 3148072
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002123898
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000542199
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66275
bytes = 2801416
compile_seconds = 0.0
samples = 3
seconds = 0.001456599

[datasets.sc50a.primal]
allocations = 67292
bytes = 3100792
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001913898
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000506299
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222112
compile_seconds = 0.0
samples = 3
seconds = 0.0001677

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.4e-5

[datasets.sc50a.sparse]
allocations = 6164
bytes = 281984
compile_seconds = 0.0
samples = 3
seconds = 0.0001743

[probes.both]
allocations = 45879
bytes = 1697944
compile_seconds = 0.0
samples = 3
seconds = 0.0008565

[probes.free_pivot]
allocations = 29623
bytes = 1194952
compile_seconds = 0.0
samples = 3
seconds = 0.000707699

[probes.lower_negative]
allocations = 42807
bytes = 1598584
compile_seconds = 0.0
samples = 3
seconds = 0.0008555

[probes.lower_positive]
allocations = 42039
bytes = 1577496
compile_seconds = 0.0
samples = 3
seconds = 0.0009023

[probes.upper_negative]
allocations = 42039
bytes = 1580200
compile_seconds = 0.0
samples = 3
seconds = 0.000819

[probes.upper_positive]
allocations = 42807
bytes = 1598888
compile_seconds = 0.0
samples = 3
seconds = 0.0007893
