julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 82550
bytes = 4053608
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032644
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461816
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009388
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80535
bytes = 3262664
compile_seconds = 0.0
samples = 3
seconds = 0.0019718

[datasets.adlittle.primal]
allocations = 83348
bytes = 4329656
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034281
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607776
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011382
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640808
compile_seconds = 0.0
samples = 3
seconds = 0.0003633

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.25e-5

[datasets.adlittle.sparse]
allocations = 1706
bytes = 133064
compile_seconds = 0.0
samples = 3
seconds = 0.0001114

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 16249
bytes = 834584
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007837
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002112
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15434
bytes = 699464
compile_seconds = 0.0
samples = 3
seconds = 0.0005655

[datasets.afiro.primal]
allocations = 16155
bytes = 813000
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006402
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002232
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92328
compile_seconds = 0.0
samples = 3
seconds = 9.62e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40928
compile_seconds = 0.0
samples = 3
seconds = 7.94e-5

[datasets.afiro.sparse]
allocations = 3760
bytes = 174160
compile_seconds = 0.0
samples = 3
seconds = 0.0001367

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.flugpl.dual]
allocations = 26767
bytes = 1109152
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008202
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001518
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 26096
bytes = 999016
compile_seconds = 0.0
samples = 3
seconds = 0.0006321

[datasets.flugpl.primal]
allocations = 27116
bytes = 1153344
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008485
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001621
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123024
compile_seconds = 0.0
samples = 3
seconds = 0.0001012

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.91e-5

[datasets.flugpl.sparse]
allocations = 4068
bytes = 153272
compile_seconds = 0.0
samples = 3
seconds = 0.0001211

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.kb2.dual]
allocations = 228243
bytes = 11016152
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020608699
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008309
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227041
bytes = 10562936
compile_seconds = 0.0
samples = 3
seconds = 0.0196276

[datasets.kb2.primal]
allocations = 228410
bytes = 11030168
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0204417
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000606699
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453552
compile_seconds = 0.0
samples = 3
seconds = 0.000235

[datasets.kb2.singleton]
allocations = 1915
bytes = 105016
compile_seconds = 0.0
samples = 3
seconds = 8.5e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127480
compile_seconds = 0.0
samples = 3
seconds = 0.0001088

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.sc50a.dual]
allocations = 66189
bytes = 3113248
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019437
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306240
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005833
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 65117
bytes = 2767632
compile_seconds = 0.0
samples = 3
seconds = 0.0014474

[datasets.sc50a.primal]
allocations = 66134
bytes = 3065856
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019429
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004925
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221488
compile_seconds = 0.0
samples = 3
seconds = 0.0001531

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.03e-5

[datasets.sc50a.sparse]
allocations = 5585
bytes = 265104
compile_seconds = 0.0
samples = 3
seconds = 0.0001813

[probes.finite]
allocations = 82771
bytes = 3180512
compile_seconds = 0.0
samples = 3
seconds = 0.0014926

[probes.free_pivot]
allocations = 58579
bytes = 2422640
compile_seconds = 0.0
samples = 3
seconds = 0.0011649

[probes.lower_only]
allocations = 67291
bytes = 2779736
compile_seconds = 0.0
samples = 3
seconds = 0.001343599

[probes.negative]
allocations = 72923
bytes = 2985880
compile_seconds = 0.0
samples = 3
seconds = 0.0015

[probes.positive]
allocations = 72923
bytes = 2982984
compile_seconds = 0.0
samples = 3
seconds = 0.0016157

[probes.upper_only]
allocations = 67291
bytes = 2780280
compile_seconds = 0.0
samples = 3
seconds = 0.0013895
