julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122693
bytes = 5657720
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003619796
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461320
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000888499
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120678
bytes = 4866984
compile_seconds = 0.0
samples = 3
seconds = 0.003030397

[datasets.adlittle.primal]
allocations = 123491
bytes = 5934152
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003845096
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607152
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001153799
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 6.24e-5

[datasets.adlittle.sparse]
allocations = 3267
bytes = 192912
compile_seconds = 0.0
samples = 3
seconds = 0.000117

[datasets.afiro.dual]
allocations = 28301
bytes = 1303880
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000823599
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001705
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27486
bytes = 1168536
compile_seconds = 0.0
samples = 3
seconds = 0.0007297

[datasets.afiro.primal]
allocations = 28207
bytes = 1282424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000775199
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000207299
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 46080
compile_seconds = 0.0
samples = 3
seconds = 8.95e-5

[datasets.afiro.sparse]
allocations = 6386
bytes = 273216
compile_seconds = 0.0
samples = 3
seconds = 0.000199

[datasets.flugpl.dual]
allocations = 39829
bytes = 1614552
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009821
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001372
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39158
bytes = 1504112
compile_seconds = 0.0
samples = 3
seconds = 0.0008227

[datasets.flugpl.primal]
allocations = 40178
bytes = 1658888
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009423
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000189299
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 104
bytes = 5120
compile_seconds = 0.0
samples = 3
seconds = 1.14e-5

[datasets.flugpl.sparse]
allocations = 6252
bytes = 236168
compile_seconds = 0.0
samples = 3
seconds = 0.0001391

[datasets.kb2.dual]
allocations = 293411
bytes = 13615984
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021052578
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878096
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000820699
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292209
bytes = 13161968
compile_seconds = 0.0
samples = 3
seconds = 0.020882777

[datasets.kb2.primal]
allocations = 293578
bytes = 13630800
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021007778
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006371
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 148392
compile_seconds = 0.0
samples = 3
seconds = 0.0001246

[datasets.kb2.sparse]
allocations = 3755
bytes = 197624
compile_seconds = 0.0
samples = 3
seconds = 0.0001077

[datasets.sc50a.dual]
allocations = 106784
bytes = 4626512
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025014
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306512
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000521499
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 105712
bytes = 4279984
compile_seconds = 0.0
samples = 3
seconds = 0.002248598

[datasets.sc50a.primal]
allocations = 106729
bytes = 4579728
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002355601
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232248
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004456
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 302
bytes = 14464
compile_seconds = 0.0
samples = 3
seconds = 1.54e-5

[datasets.sc50a.sparse]
allocations = 9239
bytes = 403480
compile_seconds = 0.0
samples = 3
seconds = 0.0002257

[probes.singleton]
allocations = 8950
bytes = 353992
compile_seconds = 0.0
samples = 3
seconds = 0.0002265

[probes.sparse]
allocations = 17918
bytes = 668688
compile_seconds = 0.0
samples = 3
seconds = 0.0004248
