julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85374
bytes = 4160680
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033974
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009258
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83359
bytes = 3370600
compile_seconds = 0.0
samples = 3
seconds = 0.0020768

[datasets.adlittle.primal]
allocations = 86172
bytes = 4437384
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036264
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607696
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011756
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 5.55e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185232
compile_seconds = 0.0
samples = 3
seconds = 0.0001305

[datasets.afiro.dual]
allocations = 18263
bytes = 911392
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007955
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002031
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 775152
compile_seconds = 0.0
samples = 3
seconds = 0.0005437

[datasets.afiro.primal]
allocations = 18169
bytes = 888912
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007395
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002066
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 45168
compile_seconds = 0.0
samples = 3
seconds = 8.13e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 270208
compile_seconds = 0.0
samples = 3
seconds = 0.0001806

[datasets.flugpl.dual]
allocations = 32652
bytes = 1327880
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008998
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001552
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31981
bytes = 1218048
compile_seconds = 0.0
samples = 3
seconds = 0.0007014

[datasets.flugpl.primal]
allocations = 33001
bytes = 1372936
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000998
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001767
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.16e-5

[datasets.flugpl.sparse]
allocations = 5852
bytes = 219312
compile_seconds = 0.0
samples = 3
seconds = 0.0001497

[datasets.kb2.dual]
allocations = 232882
bytes = 11195208
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0204083
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008598
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10742664
compile_seconds = 0.0
samples = 3
seconds = 0.0200039

[datasets.kb2.primal]
allocations = 233049
bytes = 11208232
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0202592
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006226
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 135728
compile_seconds = 0.0
samples = 3
seconds = 9.86e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 198184
compile_seconds = 0.0
samples = 3
seconds = 0.0001477

[datasets.sc50a.dual]
allocations = 72627
bytes = 3354488
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002101
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006164
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3008632
compile_seconds = 0.0
samples = 3
seconds = 0.0015635

[datasets.sc50a.primal]
allocations = 72572
bytes = 3307288
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021631
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005112
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 391864
compile_seconds = 0.0
samples = 3
seconds = 0.0002202

[probes.free]
allocations = 17658
bytes = 685768
compile_seconds = 0.0
samples = 3
seconds = 0.0003571

[probes.nonunit_bound]
allocations = 29178
bytes = 1119560
compile_seconds = 0.0
samples = 3
seconds = 0.0005419

[probes.singleton_negative]
allocations = 29181
bytes = 1118816
compile_seconds = 0.0
samples = 3
seconds = 0.000535

[probes.singleton_positive]
allocations = 29178
bytes = 1117640
compile_seconds = 0.0
samples = 3
seconds = 0.0005579

[probes.sparse_negative]
allocations = 47956
bytes = 1786776
compile_seconds = 0.0
samples = 3
seconds = 0.0008397

[probes.sparse_positive]
allocations = 47950
bytes = 1785576
compile_seconds = 0.0
samples = 3
seconds = 0.000912
