julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85616
bytes = 4170336
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031222
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009334
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83601
bytes = 3380688
compile_seconds = 0.0
samples = 3
seconds = 0.0019673

[datasets.adlittle.primal]
allocations = 86414
bytes = 4446496
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033648
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607744
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011341
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 788
bytes = 67392
compile_seconds = 0.0
samples = 3
seconds = 8.39e-5

[datasets.adlittle.sparse]
allocations = 3232
bytes = 191248
compile_seconds = 0.0
samples = 3
seconds = 0.0001319

[datasets.afiro.dual]
allocations = 18384
bytes = 916640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007431
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002202
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17569
bytes = 782016
compile_seconds = 0.0
samples = 3
seconds = 0.0006093

[datasets.afiro.primal]
allocations = 18290
bytes = 894816
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006174
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000226
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 870
bytes = 45280
compile_seconds = 0.0
samples = 3
seconds = 7.93e-5

[datasets.afiro.sparse]
allocations = 6367
bytes = 272920
compile_seconds = 0.0
samples = 3
seconds = 0.0001802

[datasets.flugpl.dual]
allocations = 33384
bytes = 1358384
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008594
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001554
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 32713
bytes = 1248632
compile_seconds = 0.0
samples = 3
seconds = 0.0006883

[datasets.flugpl.primal]
allocations = 33733
bytes = 1403008
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009073
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001923
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.14e-5

[datasets.flugpl.sparse]
allocations = 6098
bytes = 229544
compile_seconds = 0.0
samples = 3
seconds = 0.0001394

[datasets.kb2.dual]
allocations = 233169
bytes = 11208360
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0206296
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878224
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008498
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231967
bytes = 10753656
compile_seconds = 0.0
samples = 3
seconds = 0.0196016

[datasets.kb2.primal]
allocations = 233336
bytes = 11221832
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020566001
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260896
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006307
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2794
bytes = 143000
compile_seconds = 0.0
samples = 3
seconds = 0.0001008

[datasets.kb2.sparse]
allocations = 3755
bytes = 197480
compile_seconds = 0.0
samples = 3
seconds = 0.0001096

[datasets.sc50a.dual]
allocations = 73064
bytes = 3371752
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019761
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005652
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71992
bytes = 3025944
compile_seconds = 0.0
samples = 3
seconds = 0.0014744

[datasets.sc50a.primal]
allocations = 73009
bytes = 3324776
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019707
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004992
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.67e-5

[datasets.sc50a.sparse]
allocations = 9173
bytes = 400768
compile_seconds = 0.0
samples = 3
seconds = 0.0002194

[probes.free]
allocations = 17658
bytes = 687320
compile_seconds = 0.0
samples = 3
seconds = 0.000338

[probes.nonzero]
allocations = 29178
bytes = 1120680
compile_seconds = 0.0
samples = 3
seconds = 0.0004896

[probes.singleton_negative]
allocations = 28541
bytes = 1105968
compile_seconds = 0.0
samples = 3
seconds = 0.0005188

[probes.singleton_positive]
allocations = 28538
bytes = 1104760
compile_seconds = 0.0
samples = 3
seconds = 0.000538999

[probes.sparse_negative]
allocations = 47316
bytes = 1774584
compile_seconds = 0.0
samples = 3
seconds = 0.0007977

[probes.sparse_positive]
allocations = 47310
bytes = 1773032
compile_seconds = 0.0
samples = 3
seconds = 0.0008768
