julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 83498
bytes = 4080440
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034714
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461240
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010595
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81483
bytes = 3292024
compile_seconds = 0.0
samples = 3
seconds = 0.0023507

[datasets.adlittle.primal]
allocations = 84296
bytes = 4356904
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003758899
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012088
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641816
compile_seconds = 0.0
samples = 3
seconds = 0.0004134

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.09e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 156984
compile_seconds = 0.0
samples = 3
seconds = 0.0001344

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.afiro.dual]
allocations = 16528
bytes = 844776
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009764
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001761
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15713
bytes = 708856
compile_seconds = 0.0
samples = 3
seconds = 0.000612

[datasets.afiro.primal]
allocations = 16434
bytes = 823048
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000738
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002193
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92776
compile_seconds = 0.0
samples = 3
seconds = 0.0001118

[datasets.afiro.singleton]
allocations = 747
bytes = 41072
compile_seconds = 0.0
samples = 3
seconds = 9.15e-5

[datasets.afiro.sparse]
allocations = 4243
bytes = 189920
compile_seconds = 0.0
samples = 3
seconds = 0.0001598

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.flugpl.dual]
allocations = 29289
bytes = 1195112
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010364
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001676
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 28618
bytes = 1085952
compile_seconds = 0.0
samples = 3
seconds = 0.0007193

[datasets.flugpl.primal]
allocations = 29638
bytes = 1239960
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010082
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001726
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123440
compile_seconds = 0.0
samples = 3
seconds = 0.0001083

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.95e-5

[datasets.flugpl.sparse]
allocations = 4849
bytes = 181104
compile_seconds = 0.0
samples = 3
seconds = 0.0001267

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 229306
bytes = 11050184
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021192599
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878160
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008893
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 228104
bytes = 10597816
compile_seconds = 0.0
samples = 3
seconds = 0.0202885

[datasets.kb2.primal]
allocations = 229473
bytes = 11064536
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020937699
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006448
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454352
compile_seconds = 0.0
samples = 3
seconds = 0.0003045

[datasets.kb2.singleton]
allocations = 1915
bytes = 105656
compile_seconds = 0.0
samples = 3
seconds = 0.0001014

[datasets.kb2.sparse]
allocations = 2364
bytes = 142424
compile_seconds = 0.0
samples = 3
seconds = 0.000112

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.77e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.sc50a.dual]
allocations = 67569
bytes = 3154984
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021503
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306416
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006211
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66497
bytes = 2809144
compile_seconds = 0.0
samples = 3
seconds = 0.0016423

[datasets.sc50a.primal]
allocations = 67514
bytes = 3107752
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002261
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000537
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221856
compile_seconds = 0.0
samples = 3
seconds = 0.0001762

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.3e-5

[datasets.sc50a.sparse]
allocations = 6234
bytes = 284656
compile_seconds = 0.0
samples = 3
seconds = 0.0001851

[probes.bound_negative]
allocations = 47543
bytes = 1756408
compile_seconds = 0.0
samples = 3
seconds = 0.0009205

[probes.bound_positive]
allocations = 47031
bytes = 1742152
compile_seconds = 0.0
samples = 3
seconds = 0.0009921

[probes.coefficient_negative]
allocations = 56773
bytes = 2121360
compile_seconds = 0.0
samples = 3
seconds = 0.0011261

[probes.coefficient_positive]
allocations = 56005
bytes = 2097296
compile_seconds = 0.0
samples = 3
seconds = 0.0012339

[probes.nonunit]
allocations = 60229
bytes = 2248400
compile_seconds = 0.0
samples = 3
seconds = 0.0011837

[probes.zero_bounds]
allocations = 42423
bytes = 1611688
compile_seconds = 0.0
samples = 3
seconds = 0.0008548
