julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85374
bytes = 4162120
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0030473
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461032
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000931
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83359
bytes = 3372280
compile_seconds = 0.0
samples = 3
seconds = 0.0019215

[datasets.adlittle.primal]
allocations = 86172
bytes = 4438808
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035931
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010511
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 7.33e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185408
compile_seconds = 0.0
samples = 3
seconds = 0.0001273

[datasets.afiro.dual]
allocations = 18263
bytes = 912576
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007657
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002071
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 777312
compile_seconds = 0.0
samples = 3
seconds = 0.000606

[datasets.afiro.primal]
allocations = 18169
bytes = 890784
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007203
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000175
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 45328
compile_seconds = 0.0
samples = 3
seconds = 7.87e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 271632
compile_seconds = 0.0
samples = 3
seconds = 0.000172

[datasets.flugpl.dual]
allocations = 32652
bytes = 1330520
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007827
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001507
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31981
bytes = 1220144
compile_seconds = 0.0
samples = 3
seconds = 0.0006391

[datasets.flugpl.primal]
allocations = 33001
bytes = 1374920
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008647
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001558
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.flugpl.sparse]
allocations = 5852
bytes = 220352
compile_seconds = 0.0
samples = 3
seconds = 0.0001287

[datasets.kb2.dual]
allocations = 232882
bytes = 11198184
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020281099
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878064
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008116
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10744680
compile_seconds = 0.0
samples = 3
seconds = 0.0194653

[datasets.kb2.primal]
allocations = 233049
bytes = 11211752
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020201199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000601
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 135760
compile_seconds = 0.0
samples = 3
seconds = 9.36e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197640
compile_seconds = 0.0
samples = 3
seconds = 0.0001202

[datasets.sc50a.dual]
allocations = 72627
bytes = 3356872
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002002199
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005532
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3010760
compile_seconds = 0.0
samples = 3
seconds = 0.0015397

[datasets.sc50a.primal]
allocations = 72572
bytes = 3309672
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018955
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005427
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.54e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 393016
compile_seconds = 0.0
samples = 3
seconds = 0.0002083

[probes.free]
allocations = 17722
bytes = 689256
compile_seconds = 0.0
samples = 3
seconds = 0.0003326

[probes.singleton_negative]
allocations = 28861
bytes = 1112352
compile_seconds = 0.0
samples = 3
seconds = 0.0005015

[probes.singleton_positive]
allocations = 28858
bytes = 1111176
compile_seconds = 0.0
samples = 3
seconds = 0.0005116

[probes.sparse_negative]
allocations = 47700
bytes = 1782136
compile_seconds = 0.0
samples = 3
seconds = 0.0008088

[probes.sparse_positive]
allocations = 47694
bytes = 1780008
compile_seconds = 0.0
samples = 3
seconds = 0.0008187

[probes.unequal]
allocations = 29178
bytes = 1121624
compile_seconds = 0.0
samples = 3
seconds = 0.000486599
