julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85374
bytes = 4159816
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003141602
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 460952
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009119
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83359
bytes = 3369640
compile_seconds = 0.0
samples = 3
seconds = 0.002264501

[datasets.adlittle.primal]
allocations = 86172
bytes = 4437048
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003262802
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607264
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001029101
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 6.27e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185056
compile_seconds = 0.0
samples = 3
seconds = 0.0001201

[datasets.afiro.dual]
allocations = 18277
bytes = 911728
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.00068041
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000189103
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17462
bytes = 776368
compile_seconds = 0.0
samples = 3
seconds = 0.0004961

[datasets.afiro.primal]
allocations = 18183
bytes = 889424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000637701
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121760
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000171802
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 45440
compile_seconds = 0.0
samples = 3
seconds = 8.43e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 269616
compile_seconds = 0.0
samples = 3
seconds = 0.00016

[datasets.flugpl.dual]
allocations = 33163
bytes = 1349072
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000843701
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001549
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 32492
bytes = 1239336
compile_seconds = 0.0
samples = 3
seconds = 0.0006714

[datasets.flugpl.primal]
allocations = 33512
bytes = 1393840
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000819199
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001557
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.flugpl.sparse]
allocations = 6013
bytes = 225608
compile_seconds = 0.0
samples = 3
seconds = 0.0001219

[datasets.kb2.dual]
allocations = 232959
bytes = 11197856
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020554412
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878352
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000800001
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231757
bytes = 10745424
compile_seconds = 0.0
samples = 3
seconds = 0.020136911

[datasets.kb2.primal]
allocations = 233126
bytes = 11211808
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021520812
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005836
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2656
bytes = 137776
compile_seconds = 0.0
samples = 3
seconds = 7.93e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197768
compile_seconds = 0.0
samples = 3
seconds = 0.000134801

[datasets.sc50a.dual]
allocations = 72627
bytes = 3354728
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001994601
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306528
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005311
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3008792
compile_seconds = 0.0
samples = 3
seconds = 0.0013974

[datasets.sc50a.primal]
allocations = 72572
bytes = 3307912
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001843901
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004706
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.17e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 391976
compile_seconds = 0.0
samples = 3
seconds = 0.0002157

[probes.free]
allocations = 16567
bytes = 660752
compile_seconds = 0.0
samples = 3
seconds = 0.0003046

[probes.nonzero]
allocations = 29178
bytes = 1119592
compile_seconds = 0.0
samples = 3
seconds = 0.000501701

[probes.singleton_negative]
allocations = 28090
bytes = 1094376
compile_seconds = 0.0
samples = 3
seconds = 0.000477301

[probes.singleton_positive]
allocations = 28087
bytes = 1093136
compile_seconds = 0.0
samples = 3
seconds = 0.000511601

[probes.sparse_negative]
allocations = 42065
bytes = 1586512
compile_seconds = 0.0
samples = 3
seconds = 0.000759001

[probes.sparse_positive]
allocations = 42059
bytes = 1585264
compile_seconds = 0.0
samples = 3
seconds = 0.000764101
