julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 82802
bytes = 4061952
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033243
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461208
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008936
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80787
bytes = 3272128
compile_seconds = 0.0
samples = 3
seconds = 0.0019786

[datasets.adlittle.primal]
allocations = 83600
bytes = 4337968
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034283
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607248
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010791
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641688
compile_seconds = 0.0
samples = 3
seconds = 0.000374

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.05e-5

[datasets.adlittle.sparse]
allocations = 1970
bytes = 143944
compile_seconds = 0.0
samples = 3
seconds = 0.0001154

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.dual]
allocations = 16249
bytes = 835512
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007684
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002118
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15434
bytes = 700136
compile_seconds = 0.0
samples = 3
seconds = 0.0005548

[datasets.afiro.primal]
allocations = 16155
bytes = 813528
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000721
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000207
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92760
compile_seconds = 0.0
samples = 3
seconds = 0.0001025

[datasets.afiro.singleton]
allocations = 747
bytes = 41296
compile_seconds = 0.0
samples = 3
seconds = 8.74e-5

[datasets.afiro.sparse]
allocations = 3820
bytes = 177000
compile_seconds = 0.0
samples = 3
seconds = 0.0001296

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.flugpl.dual]
allocations = 26767
bytes = 1109600
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009124
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001529
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 26096
bytes = 999960
compile_seconds = 0.0
samples = 3
seconds = 0.0006128

[datasets.flugpl.primal]
allocations = 27116
bytes = 1153968
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009262
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001875
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123008
compile_seconds = 0.0
samples = 3
seconds = 0.0001066

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.flugpl.sparse]
allocations = 4068
bytes = 153896
compile_seconds = 0.0
samples = 3
seconds = 9.7e-5

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 228243
bytes = 11016232
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020064
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878048
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007798
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227041
bytes = 10562888
compile_seconds = 0.0
samples = 3
seconds = 0.019281301

[datasets.kb2.primal]
allocations = 228410
bytes = 11029384
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0203949
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005941
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453824
compile_seconds = 0.0
samples = 3
seconds = 0.0002678

[datasets.kb2.singleton]
allocations = 1915
bytes = 105992
compile_seconds = 0.0
samples = 3
seconds = 9.12e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 128472
compile_seconds = 0.0
samples = 3
seconds = 0.0001063

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 66393
bytes = 3120264
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001948
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306416
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005777
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 65321
bytes = 2774664
compile_seconds = 0.0
samples = 3
seconds = 0.0014885

[datasets.sc50a.primal]
allocations = 66338
bytes = 3073464
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018835
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005186
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221184
compile_seconds = 0.0
samples = 3
seconds = 0.000154

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.33e-5

[datasets.sc50a.sparse]
allocations = 5729
bytes = 269440
compile_seconds = 0.0
samples = 3
seconds = 0.0001754

[probes.finite]
allocations = 82771
bytes = 3180592
compile_seconds = 0.0
samples = 3
seconds = 0.0016158

[probes.late_unbounded]
allocations = 84187
bytes = 3341544
compile_seconds = 0.0
samples = 3
seconds = 0.0017053

[probes.lower_only]
allocations = 70363
bytes = 2873112
compile_seconds = 0.0
samples = 3
seconds = 0.0014585

[probes.negative]
allocations = 75995
bytes = 3078600
compile_seconds = 0.0
samples = 3
seconds = 0.0015568

[probes.positive]
allocations = 75995
bytes = 3076472
compile_seconds = 0.0
samples = 3
seconds = 0.0015497

[probes.upper_only]
allocations = 70363
bytes = 2873512
compile_seconds = 0.0
samples = 3
seconds = 0.0014548
