julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4116104
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.00326291
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000954603
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326600
compile_seconds = 0.0
samples = 3
seconds = 0.001898106

[datasets.adlittle.primal]
allocations = 85246
bytes = 4393240
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003456211
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607728
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001062903
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641032
compile_seconds = 0.0
samples = 3
seconds = 0.000331701

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.47e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 173928
compile_seconds = 0.0
samples = 3
seconds = 0.0001157

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 863480
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000787102
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002086
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 727688
compile_seconds = 0.0
samples = 3
seconds = 0.000626801

[datasets.afiro.primal]
allocations = 16938
bytes = 841688
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000699002
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001964
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91848
compile_seconds = 0.0
samples = 3
seconds = 0.0001309

[datasets.afiro.singleton]
allocations = 843
bytes = 45088
compile_seconds = 0.0
samples = 3
seconds = 7.11e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213376
compile_seconds = 0.0
samples = 3
seconds = 0.0001602

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1278680
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008149
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001477
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169424
compile_seconds = 0.0
samples = 3
seconds = 0.000727

[datasets.flugpl.primal]
allocations = 31811
bytes = 1323240
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008434
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001973
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123008
compile_seconds = 0.0
samples = 3
seconds = 0.0001118

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.34e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209880
compile_seconds = 0.0
samples = 3
seconds = 0.0001286

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11093088
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021246366
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878528
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000919102
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10639792
compile_seconds = 0.0
samples = 3
seconds = 0.020880465

[datasets.kb2.primal]
allocations = 230563
bytes = 11107120
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020794565
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000638502
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454352
compile_seconds = 0.0
samples = 3
seconds = 0.000219401

[datasets.kb2.singleton]
allocations = 2060
bytes = 112096
compile_seconds = 0.0
samples = 3
seconds = 8.3e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161552
compile_seconds = 0.0
samples = 3
seconds = 0.0001129

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.62e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3190952
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020796
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000611902
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2845224
compile_seconds = 0.0
samples = 3
seconds = 0.001603005

[datasets.sc50a.primal]
allocations = 68474
bytes = 3143688
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020072
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005019
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222000
compile_seconds = 0.0
samples = 3
seconds = 0.0001507

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299280
compile_seconds = 0.0
samples = 3
seconds = 0.0001772

[probes.singleton_fraction_negative]
allocations = 28160
bytes = 1076408
compile_seconds = 0.0
samples = 3
seconds = 0.0004534

[probes.singleton_fraction_positive]
allocations = 28160
bytes = 1076712
compile_seconds = 0.0
samples = 3
seconds = 0.000464901

[probes.singleton_integer_negative]
allocations = 27648
bytes = 1049416
compile_seconds = 0.0
samples = 3
seconds = 0.000496201

[probes.singleton_integer_positive]
allocations = 27648
bytes = 1047784
compile_seconds = 0.0
samples = 3
seconds = 0.000538501

[probes.sparse_fraction_negative]
allocations = 43964
bytes = 1618504
compile_seconds = 0.0
samples = 3
seconds = 0.000798401

[probes.sparse_fraction_positive]
allocations = 43953
bytes = 1618360
compile_seconds = 0.0
samples = 3
seconds = 0.000824102

[probes.sparse_integer_negative]
allocations = 43607
bytes = 1599600
compile_seconds = 0.0
samples = 3
seconds = 0.000730902

[probes.sparse_integer_positive]
allocations = 43594
bytes = 1597480
compile_seconds = 0.0
samples = 3
seconds = 0.000745701

[probes.unequal_denominator]
allocations = 27552
bytes = 1048920
compile_seconds = 0.0
samples = 3
seconds = 0.000445001

[probes.unit_coefficient]
allocations = 25344
bytes = 963816
compile_seconds = 0.0
samples = 3
seconds = 0.000453901
