julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85366
bytes = 4158104
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034602
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 460984
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009196
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83351
bytes = 3368424
compile_seconds = 0.0
samples = 3
seconds = 0.0019282

[datasets.adlittle.primal]
allocations = 86164
bytes = 4434856
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033936
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607344
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 6.89e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185904
compile_seconds = 0.0
samples = 3
seconds = 0.0001308

[datasets.afiro.dual]
allocations = 18263
bytes = 911088
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007165
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002187
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 774320
compile_seconds = 0.0
samples = 3
seconds = 0.0005596

[datasets.afiro.primal]
allocations = 18169
bytes = 888832
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007467
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001934
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 44688
compile_seconds = 0.0
samples = 3
seconds = 9.91e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 269488
compile_seconds = 0.0
samples = 3
seconds = 0.0001703

[datasets.flugpl.dual]
allocations = 32526
bytes = 1324032
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008724
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001539
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31855
bytes = 1213864
compile_seconds = 0.0
samples = 3
seconds = 0.0007101

[datasets.flugpl.primal]
allocations = 32875
bytes = 1368480
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008379
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001929
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.17e-5

[datasets.flugpl.sparse]
allocations = 5852
bytes = 218928
compile_seconds = 0.0
samples = 3
seconds = 0.00013

[datasets.kb2.dual]
allocations = 232882
bytes = 11195960
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0200606
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878160
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008492
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10745240
compile_seconds = 0.0
samples = 3
seconds = 0.019464399

[datasets.kb2.primal]
allocations = 233049
bytes = 11209304
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0204117
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006188
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 135696
compile_seconds = 0.0
samples = 3
seconds = 9.91e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 198904
compile_seconds = 0.0
samples = 3
seconds = 0.0001259

[datasets.sc50a.dual]
allocations = 72627
bytes = 3355960
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020063
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306400
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005656
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3009944
compile_seconds = 0.0
samples = 3
seconds = 0.0015245

[datasets.sc50a.primal]
allocations = 72572
bytes = 3308456
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020051
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005383
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.63e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 392776
compile_seconds = 0.0
samples = 3
seconds = 0.0002218

[probes.inequality]
allocations = 278
bytes = 15256
compile_seconds = 0.0
samples = 3
seconds = 1.7e-5

[probes.nonzero]
allocations = 28029
bytes = 1076096
compile_seconds = 0.0
samples = 3
seconds = 0.0005031

[probes.singleton_negative]
allocations = 27008
bytes = 1054936
compile_seconds = 0.0
samples = 3
seconds = 0.0005159

[probes.singleton_positive]
allocations = 27008
bytes = 1053656
compile_seconds = 0.0
samples = 3
seconds = 0.0004886

[probes.sparse_negative]
allocations = 45783
bytes = 1722896
compile_seconds = 0.0
samples = 3
seconds = 0.0007859

[probes.sparse_positive]
allocations = 45780
bytes = 1721896
compile_seconds = 0.0
samples = 3
seconds = 0.000802
