julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 83258
bytes = 4072528
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032547
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008687
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81243
bytes = 3282560
compile_seconds = 0.0
samples = 3
seconds = 0.0020489

[datasets.adlittle.primal]
allocations = 84056
bytes = 4349712
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037219
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607392
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010888
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641448
compile_seconds = 0.0
samples = 3
seconds = 0.0003676

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.8e-5

[datasets.adlittle.sparse]
allocations = 2282
bytes = 154824
compile_seconds = 0.0
samples = 3
seconds = 0.0001382

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.afiro.dual]
allocations = 16433
bytes = 841048
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008464
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001885
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15618
bytes = 705544
compile_seconds = 0.0
samples = 3
seconds = 0.0005319

[datasets.afiro.primal]
allocations = 16339
bytes = 818520
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007437
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002553
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92232
compile_seconds = 0.0
samples = 3
seconds = 9.87e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 41056
compile_seconds = 0.0
samples = 3
seconds = 7.55e-5

[datasets.afiro.sparse]
allocations = 4116
bytes = 184920
compile_seconds = 0.0
samples = 3
seconds = 0.0001399

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.flugpl.dual]
allocations = 27847
bytes = 1139568
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007857
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001195
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27176
bytes = 1030712
compile_seconds = 0.0
samples = 3
seconds = 0.0006363

[datasets.flugpl.primal]
allocations = 28196
bytes = 1184096
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008211
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001567
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123008
compile_seconds = 0.0
samples = 3
seconds = 8.94e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.95e-5

[datasets.flugpl.sparse]
allocations = 4428
bytes = 164184
compile_seconds = 0.0
samples = 3
seconds = 0.0001134

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.kb2.dual]
allocations = 228627
bytes = 11027256
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0208795
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878000
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007809
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227425
bytes = 10574088
compile_seconds = 0.0
samples = 3
seconds = 0.0202565

[datasets.kb2.primal]
allocations = 228794
bytes = 11041320
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0213348
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005897
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453536
compile_seconds = 0.0
samples = 3
seconds = 0.000244

[datasets.kb2.singleton]
allocations = 1915
bytes = 105384
compile_seconds = 0.0
samples = 3
seconds = 9.11e-5

[datasets.kb2.sparse]
allocations = 2207
bytes = 135448
compile_seconds = 0.0
samples = 3
seconds = 9.55e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.47e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.sc50a.dual]
allocations = 67169
bytes = 3140776
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020373
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005403
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66097
bytes = 2795736
compile_seconds = 0.0
samples = 3
seconds = 0.0014681

[datasets.sc50a.primal]
allocations = 67114
bytes = 3093544
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021389
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004909
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221296
compile_seconds = 0.0
samples = 3
seconds = 0.0001362

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.85e-5

[datasets.sc50a.sparse]
allocations = 6081
bytes = 278992
compile_seconds = 0.0
samples = 3
seconds = 0.0001622

[probes.lower_only]
allocations = 39735
bytes = 1511624
compile_seconds = 0.0
samples = 3
seconds = 0.0008828

[probes.negative]
allocations = 41783
bytes = 1574328
compile_seconds = 0.0
samples = 3
seconds = 0.0009378

[probes.positive]
allocations = 41783
bytes = 1571848
compile_seconds = 0.0
samples = 3
seconds = 0.0008829

[probes.upper_only]
allocations = 39351
bytes = 1487448
compile_seconds = 0.0
samples = 3
seconds = 0.0008513

[probes.variable]
allocations = 45367
bytes = 1683496
compile_seconds = 0.0
samples = 3
seconds = 0.0010468

[probes.zero_activity]
allocations = 37943
bytes = 1446696
compile_seconds = 0.0
samples = 3
seconds = 0.0008639
