julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.adlittle.dual]
allocations = 83444
bytes = 4080600
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003542601
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461544
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009592
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81429
bytes = 3290488
compile_seconds = 0.0
samples = 3
seconds = 0.0020004

[datasets.adlittle.primal]
allocations = 84242
bytes = 4356920
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003471301
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010742
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641000
compile_seconds = 0.0
samples = 3
seconds = 0.000316

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.9e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 156264
compile_seconds = 0.0
samples = 3
seconds = 0.0001255

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 16472
bytes = 842136
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007068
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000196
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15657
bytes = 706344
compile_seconds = 0.0
samples = 3
seconds = 0.0006873

[datasets.afiro.primal]
allocations = 16378
bytes = 819512
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007028
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001824
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91880
compile_seconds = 0.0
samples = 3
seconds = 0.0001186

[datasets.afiro.singleton]
allocations = 747
bytes = 41088
compile_seconds = 0.0
samples = 3
seconds = 7.9e-5

[datasets.afiro.sparse]
allocations = 4171
bytes = 186184
compile_seconds = 0.0
samples = 3
seconds = 0.0001519

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.flugpl.dual]
allocations = 28809
bytes = 1176184
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008273
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001374
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 28138
bytes = 1067136
compile_seconds = 0.0
samples = 3
seconds = 0.000579301

[datasets.flugpl.primal]
allocations = 29158
bytes = 1220920
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008767
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001446
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122656
compile_seconds = 0.0
samples = 3
seconds = 0.0001042

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.87e-5

[datasets.flugpl.sparse]
allocations = 4699
bytes = 174712
compile_seconds = 0.0
samples = 3
seconds = 0.0001353

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.kb2.dual]
allocations = 229167
bytes = 11044584
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021165209
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000767801
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227965
bytes = 10594808
compile_seconds = 0.0
samples = 3
seconds = 0.019718309

[datasets.kb2.primal]
allocations = 229334
bytes = 11059224
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020441909
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260880
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000642901
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454272
compile_seconds = 0.0
samples = 3
seconds = 0.0003029

[datasets.kb2.singleton]
allocations = 1915
bytes = 105048
compile_seconds = 0.0
samples = 3
seconds = 8.76e-5

[datasets.kb2.sparse]
allocations = 2284
bytes = 138088
compile_seconds = 0.0
samples = 3
seconds = 0.0001118

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.79e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.sc50a.dual]
allocations = 67433
bytes = 3150560
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002006401
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005422
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66361
bytes = 2805440
compile_seconds = 0.0
samples = 3
seconds = 0.0014919

[datasets.sc50a.primal]
allocations = 67378
bytes = 3103152
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002057201
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005649
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222288
compile_seconds = 0.0
samples = 3
seconds = 0.000137

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.68e-5

[datasets.sc50a.sparse]
allocations = 6180
bytes = 282360
compile_seconds = 0.0
samples = 3
seconds = 0.000198

[probes.free_pivot]
allocations = 29623
bytes = 1195064
compile_seconds = 0.0
samples = 3
seconds = 0.0006563

[probes.lower_cancel]
allocations = 50245
bytes = 1919056
compile_seconds = 0.0
samples = 3
seconds = 0.0010174

[probes.negative]
allocations = 44983
bytes = 1694616
compile_seconds = 0.0
samples = 3
seconds = 0.0007426

[probes.noncancel]
allocations = 49335
bytes = 1827432
compile_seconds = 0.0
samples = 3
seconds = 0.0009219

[probes.positive]
allocations = 44983
bytes = 1692168
compile_seconds = 0.0
samples = 3
seconds = 0.0009654

[probes.upper_cancel]
allocations = 54341
bytes = 2059024
compile_seconds = 0.0
samples = 3
seconds = 0.0011081
