julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 84694
bytes = 4133680
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.00322991
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000962303
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82679
bytes = 3345024
compile_seconds = 0.0
samples = 3
seconds = 0.002023106

[datasets.adlittle.primal]
allocations = 85492
bytes = 4410464
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.00334141
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607520
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001089403
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.12e-5

[datasets.adlittle.sparse]
allocations = 2778
bytes = 175224
compile_seconds = 0.0
samples = 3
seconds = 0.0001243

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.199e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 864592
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000714302
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000195801
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 729136
compile_seconds = 0.0
samples = 3
seconds = 0.000520402

[datasets.afiro.primal]
allocations = 16963
bytes = 842832
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000611902
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000201001
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45616
compile_seconds = 0.0
samples = 3
seconds = 0.000101399

[datasets.afiro.sparse]
allocations = 4900
bytes = 214992
compile_seconds = 0.0
samples = 3
seconds = 0.000159799

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1290864
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000869801
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000149101
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1180280
compile_seconds = 0.0
samples = 3
seconds = 0.000699701

[datasets.flugpl.primal]
allocations = 32031
bytes = 1335264
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000914102
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000196501
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.87e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210200
compile_seconds = 0.0
samples = 3
seconds = 0.0001203

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11126704
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021500866
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000828402
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10676192
compile_seconds = 0.0
samples = 3
seconds = 0.020018662

[datasets.kb2.primal]
allocations = 231280
bytes = 11140816
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020856664
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000579301
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112992
compile_seconds = 0.0
samples = 3
seconds = 8.35e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161904
compile_seconds = 0.0
samples = 3
seconds = 0.000116401

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3193952
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002031604
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306544
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000562401
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2847728
compile_seconds = 0.0
samples = 3
seconds = 0.001563503

[datasets.sc50a.primal]
allocations = 68520
bytes = 3146992
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002006603
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000513701
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.27e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299104
compile_seconds = 0.0
samples = 3
seconds = 0.0001992

[probes.negative]
allocations = 53317
bytes = 2058336
compile_seconds = 0.0
samples = 3
seconds = 0.000867795

[probes.positive]
allocations = 53317
bytes = 2056432
compile_seconds = 0.0
samples = 3
seconds = 0.001095495

[probes.unequal]
allocations = 54085
bytes = 2077280
compile_seconds = 0.0
samples = 3
seconds = 0.000979395

[probes.unit_negative]
allocations = 51525
bytes = 1986704
compile_seconds = 0.0
samples = 3
seconds = 0.000935395

[probes.unit_positive]
allocations = 51013
bytes = 1972112
compile_seconds = 0.0
samples = 3
seconds = 0.000973695

[probes.zero_old]
allocations = 52805
bytes = 2031776
compile_seconds = 0.0
samples = 3
seconds = 0.000981395
