julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 84694
bytes = 4134336
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003136296
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461480
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000908
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82679
bytes = 3343568
compile_seconds = 0.0
samples = 3
seconds = 0.002092698

[datasets.adlittle.primal]
allocations = 85492
bytes = 4410656
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003386197
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607504
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001158499
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.38e-5

[datasets.adlittle.sparse]
allocations = 2778
bytes = 175224
compile_seconds = 0.0
samples = 3
seconds = 0.0001379

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 865136
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000739799
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001929
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 729920
compile_seconds = 0.0
samples = 3
seconds = 0.00056025

[datasets.afiro.primal]
allocations = 16963
bytes = 843072
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000688799
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002061
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45472
compile_seconds = 0.0
samples = 3
seconds = 8.64e-5

[datasets.afiro.sparse]
allocations = 4900
bytes = 214560
compile_seconds = 0.0
samples = 3
seconds = 0.0001763

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1290400
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000911603
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000160801
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1181592
compile_seconds = 0.0
samples = 3
seconds = 0.000741102

[datasets.flugpl.primal]
allocations = 32031
bytes = 1334800
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000873803
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001872
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209976
compile_seconds = 0.0
samples = 3
seconds = 0.000136001

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11129568
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020999579
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877856
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000781599
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10676752
compile_seconds = 0.0
samples = 3
seconds = 0.020160479

[datasets.kb2.primal]
allocations = 231280
bytes = 11144000
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020277279
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006231
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112128
compile_seconds = 0.0
samples = 3
seconds = 7.55e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161808
compile_seconds = 0.0
samples = 3
seconds = 0.000137

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.53e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3194400
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001949005
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000555002
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2848784
compile_seconds = 0.0
samples = 3
seconds = 0.001630804

[datasets.sc50a.primal]
allocations = 68520
bytes = 3146880
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002129306
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000504301
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.21e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299488
compile_seconds = 0.0
samples = 3
seconds = 0.0001991

[probes.negative]
allocations = 34208
bytes = 1284480
compile_seconds = 0.0
samples = 3
seconds = 0.000581399

[probes.nonzero_constant]
allocations = 34211
bytes = 1284984
compile_seconds = 0.0
samples = 3
seconds = 0.000680898

[probes.positive]
allocations = 34208
bytes = 1282928
compile_seconds = 0.0
samples = 3
seconds = 0.000574399

[probes.unit_negative]
allocations = 32416
bytes = 1212384
compile_seconds = 0.0
samples = 3
seconds = 0.000546698

[probes.unit_positive]
allocations = 31904
bytes = 1198048
compile_seconds = 0.0
samples = 3
seconds = 0.000595898

[probes.zero_rhs]
allocations = 29344
bytes = 1106672
compile_seconds = 0.0
samples = 3
seconds = 0.000590499
