julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122704
bytes = 5660696
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003518601
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000902401
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120689
bytes = 4870680
compile_seconds = 0.0
samples = 3
seconds = 0.002433901

[datasets.adlittle.primal]
allocations = 123502
bytes = 5937208
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004076101
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607104
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011424
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 7.48e-5

[datasets.adlittle.sparse]
allocations = 3277
bytes = 193664
compile_seconds = 0.0
samples = 3
seconds = 0.0001149

[datasets.afiro.dual]
allocations = 28367
bytes = 1310264
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008094
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002226
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27552
bytes = 1174376
compile_seconds = 0.0
samples = 3
seconds = 0.0007087

[datasets.afiro.primal]
allocations = 28273
bytes = 1288568
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008088
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001906
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 46304
compile_seconds = 0.0
samples = 3
seconds = 8.52e-5

[datasets.afiro.sparse]
allocations = 6496
bytes = 280144
compile_seconds = 0.0
samples = 3
seconds = 0.000168

[datasets.flugpl.dual]
allocations = 39856
bytes = 1616216
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000909601
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001384
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39185
bytes = 1507280
compile_seconds = 0.0
samples = 3
seconds = 0.000681701

[datasets.flugpl.primal]
allocations = 40205
bytes = 1661272
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000966201
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001752
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 104
bytes = 5120
compile_seconds = 0.0
samples = 3
seconds = 8.2e-6

[datasets.flugpl.sparse]
allocations = 6262
bytes = 236392
compile_seconds = 0.0
samples = 3
seconds = 0.0001398

[datasets.kb2.dual]
allocations = 293436
bytes = 13619056
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021301203
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877808
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008132
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292234
bytes = 13167520
compile_seconds = 0.0
samples = 3
seconds = 0.020420103

[datasets.kb2.primal]
allocations = 293603
bytes = 13631984
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021495103
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005919
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 148664
compile_seconds = 0.0
samples = 3
seconds = 8.74e-5

[datasets.kb2.sparse]
allocations = 3787
bytes = 199960
compile_seconds = 0.0
samples = 3
seconds = 0.000101

[datasets.sc50a.dual]
allocations = 107096
bytes = 4647920
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023866
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000603901
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106024
bytes = 4302720
compile_seconds = 0.0
samples = 3
seconds = 0.001901601

[datasets.sc50a.primal]
allocations = 107041
bytes = 4601120
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022969
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005251
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 302
bytes = 14464
compile_seconds = 0.0
samples = 3
seconds = 1.43e-5

[datasets.sc50a.sparse]
allocations = 9475
bytes = 419224
compile_seconds = 0.0
samples = 3
seconds = 0.0002315

[probes.singleton]
allocations = 9706
bytes = 377696
compile_seconds = 0.0
samples = 3
seconds = 0.0002127

[probes.sparse]
allocations = 19808
bytes = 744176
compile_seconds = 0.0
samples = 3
seconds = 0.000409401
