julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85374
bytes = 4159272
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039088
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461240
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009699
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83359
bytes = 3370232
compile_seconds = 0.0
samples = 3
seconds = 0.0022042

[datasets.adlittle.primal]
allocations = 86172
bytes = 4436152
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036831
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607472
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011592
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 8.79e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185072
compile_seconds = 0.0
samples = 3
seconds = 0.0001541

[datasets.afiro.dual]
allocations = 18263
bytes = 911280
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008504
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002054
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 775984
compile_seconds = 0.0
samples = 3
seconds = 0.0006263

[datasets.afiro.primal]
allocations = 18169
bytes = 889600
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000825899
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002189
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 44960
compile_seconds = 0.0
samples = 3
seconds = 8.77e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 270832
compile_seconds = 0.0
samples = 3
seconds = 0.0002028

[datasets.flugpl.dual]
allocations = 32652
bytes = 1328456
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010639
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001577
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31981
bytes = 1218272
compile_seconds = 0.0
samples = 3
seconds = 0.000794

[datasets.flugpl.primal]
allocations = 33001
bytes = 1373032
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010125
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000177
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.33e-5

[datasets.flugpl.sparse]
allocations = 5852
bytes = 218800
compile_seconds = 0.0
samples = 3
seconds = 0.0001528

[datasets.kb2.dual]
allocations = 232882
bytes = 11193976
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021194299
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878304
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008272
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10742040
compile_seconds = 0.0
samples = 3
seconds = 0.0207853

[datasets.kb2.primal]
allocations = 233049
bytes = 11208920
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0214774
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260912
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005748
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 135376
compile_seconds = 0.0
samples = 3
seconds = 9.5e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197000
compile_seconds = 0.0
samples = 3
seconds = 0.0001417

[datasets.sc50a.dual]
allocations = 72627
bytes = 3354456
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023162
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000566
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3008360
compile_seconds = 0.0
samples = 3
seconds = 0.0016958

[datasets.sc50a.primal]
allocations = 72572
bytes = 3307016
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025174
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005321
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.31e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 391848
compile_seconds = 0.0
samples = 3
seconds = 0.0002234

[probes.free]
allocations = 16567
bytes = 662560
compile_seconds = 0.0
samples = 3
seconds = 0.000304

[probes.nonzero]
allocations = 29178
bytes = 1122184
compile_seconds = 0.0
samples = 3
seconds = 0.0005675

[probes.singleton_negative]
allocations = 26298
bytes = 1023576
compile_seconds = 0.0
samples = 3
seconds = 0.0005399

[probes.singleton_positive]
allocations = 26295
bytes = 1022176
compile_seconds = 0.0
samples = 3
seconds = 0.0004895

[probes.sparse_negative]
allocations = 40273
bytes = 1516432
compile_seconds = 0.0
samples = 3
seconds = 0.000749

[probes.sparse_positive]
allocations = 40267
bytes = 1515008
compile_seconds = 0.0
samples = 3
seconds = 0.000804
