julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85366
bytes = 4159912
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003665404
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461272
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000973501
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83351
bytes = 3370328
compile_seconds = 0.0
samples = 3
seconds = 0.002188203

[datasets.adlittle.primal]
allocations = 86164
bytes = 4435528
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003959105
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607728
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001179101
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 8.19e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 186416
compile_seconds = 0.0
samples = 3
seconds = 0.000137801

[datasets.afiro.dual]
allocations = 18263
bytes = 911792
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000853501
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001694
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 777120
compile_seconds = 0.0
samples = 3
seconds = 0.000673601

[datasets.afiro.primal]
allocations = 18169
bytes = 890640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000846601
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002178
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 44720
compile_seconds = 0.0
samples = 3
seconds = 7.97e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 270912
compile_seconds = 0.0
samples = 3
seconds = 0.0001932

[datasets.flugpl.dual]
allocations = 32652
bytes = 1329144
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009773
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001578
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31981
bytes = 1219296
compile_seconds = 0.0
samples = 3
seconds = 0.0008458

[datasets.flugpl.primal]
allocations = 33001
bytes = 1373688
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009986
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001812
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 8.2e-6

[datasets.flugpl.sparse]
allocations = 5852
bytes = 219824
compile_seconds = 0.0
samples = 3
seconds = 0.000173

[datasets.kb2.dual]
allocations = 232882
bytes = 11193928
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021722026
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000830101
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10744408
compile_seconds = 0.0
samples = 3
seconds = 0.020400325

[datasets.kb2.primal]
allocations = 233049
bytes = 11208056
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020852126
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000656501
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 135456
compile_seconds = 0.0
samples = 3
seconds = 0.000118601

[datasets.kb2.sparse]
allocations = 3755
bytes = 197848
compile_seconds = 0.0
samples = 3
seconds = 0.000135001

[datasets.sc50a.dual]
allocations = 72627
bytes = 3355960
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002254501
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005874
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3009784
compile_seconds = 0.0
samples = 3
seconds = 0.001757202

[datasets.sc50a.primal]
allocations = 72572
bytes = 3308600
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002239201
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005245
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.8e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 393016
compile_seconds = 0.0
samples = 3
seconds = 0.000245501

[probes.free]
allocations = 17722
bytes = 688552
compile_seconds = 0.0
samples = 3
seconds = 0.0003794

[probes.singleton_negative]
allocations = 28221
bytes = 1082672
compile_seconds = 0.0
samples = 3
seconds = 0.0005541

[probes.singleton_positive]
allocations = 28218
bytes = 1081560
compile_seconds = 0.0
samples = 3
seconds = 0.000534901

[probes.sparse_negative]
allocations = 47060
bytes = 1752232
compile_seconds = 0.0
samples = 3
seconds = 0.000888101

[probes.sparse_positive]
allocations = 47054
bytes = 1750600
compile_seconds = 0.0
samples = 3
seconds = 0.0009384

[probes.unequal]
allocations = 29178
bytes = 1121464
compile_seconds = 0.0
samples = 3
seconds = 0.0005673
