julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84980
bytes = 4145632
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003217
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461048
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009066
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82965
bytes = 3355616
compile_seconds = 0.0
samples = 3
seconds = 0.0020265

[datasets.adlittle.primal]
allocations = 85778
bytes = 4422912
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033962
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607632
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010907
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.58e-5

[datasets.adlittle.sparse]
allocations = 2861
bytes = 178336
compile_seconds = 0.0
samples = 3
seconds = 0.0001233

[datasets.afiro.dual]
allocations = 17505
bytes = 883056
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007194
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002565
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16690
bytes = 748192
compile_seconds = 0.0
samples = 3
seconds = 0.0005521

[datasets.afiro.primal]
allocations = 17411
bytes = 861824
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007169
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001937
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44928
compile_seconds = 0.0
samples = 3
seconds = 8.01e-5

[datasets.afiro.sparse]
allocations = 5517
bytes = 239448
compile_seconds = 0.0
samples = 3
seconds = 0.0001684

[datasets.flugpl.dual]
allocations = 32286
bytes = 1314520
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008008
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001582
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1204624
compile_seconds = 0.0
samples = 3
seconds = 0.0006204

[datasets.flugpl.primal]
allocations = 32635
bytes = 1359064
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008319
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001868
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.22e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216552
compile_seconds = 0.0
samples = 3
seconds = 0.0001189

[datasets.kb2.dual]
allocations = 231270
bytes = 11136520
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020319599
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000806
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230068
bytes = 10683352
compile_seconds = 0.0
samples = 3
seconds = 0.019593999

[datasets.kb2.primal]
allocations = 231437
bytes = 11149672
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020316299
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000644
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111968
compile_seconds = 0.0
samples = 3
seconds = 0.0001298

[datasets.kb2.sparse]
allocations = 2958
bytes = 166432
compile_seconds = 0.0
samples = 3
seconds = 0.0001122

[datasets.sc50a.dual]
allocations = 69752
bytes = 3242456
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019408
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000537
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 68680
bytes = 2896504
compile_seconds = 0.0
samples = 3
seconds = 0.001425

[datasets.sc50a.primal]
allocations = 69697
bytes = 3195256
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018785
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004873
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.58e-5

[datasets.sc50a.sparse]
allocations = 7434
bytes = 332192
compile_seconds = 0.0
samples = 3
seconds = 0.0001753

[probes.multiplier_negative]
allocations = 38487
bytes = 1438832
compile_seconds = 0.0
samples = 3
seconds = 0.0007435

[probes.multiplier_positive]
allocations = 38231
bytes = 1429536
compile_seconds = 0.0
samples = 3
seconds = 0.0006758

[probes.nonunit]
allocations = 39383
bytes = 1475120
compile_seconds = 0.0
samples = 3
seconds = 0.0007735

[probes.term_negative]
allocations = 39383
bytes = 1474896
compile_seconds = 0.0
samples = 3
seconds = 0.0007951

[probes.term_positive]
allocations = 39380
bytes = 1475080
compile_seconds = 0.0
samples = 3
seconds = 0.000738

[probes.zero]
allocations = 29142
bytes = 1109368
compile_seconds = 0.0
samples = 3
seconds = 0.0005793
