julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.201e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.adlittle.dual]
allocations = 84962
bytes = 4144080
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003426403
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461480
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000924401
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82947
bytes = 3353920
compile_seconds = 0.0
samples = 3
seconds = 0.002107701

[datasets.adlittle.primal]
allocations = 85760
bytes = 4420080
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003711003
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607680
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001119201
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 4.81e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 178288
compile_seconds = 0.0
samples = 3
seconds = 0.0001225

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868744
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007421
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001951
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733624
compile_seconds = 0.0
samples = 3
seconds = 0.0005438

[datasets.afiro.primal]
allocations = 17051
bytes = 846920
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007029
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002139
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44800
compile_seconds = 0.0
samples = 3
seconds = 7.26e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218968
compile_seconds = 0.0
samples = 3
seconds = 0.0001744

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6

[datasets.flugpl.dual]
allocations = 32206
bytes = 1312304
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009344
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001458
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31535
bytes = 1202888
compile_seconds = 0.0
samples = 3
seconds = 0.0007127

[datasets.flugpl.primal]
allocations = 32555
bytes = 1356992
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009105
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001659
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.8e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217576
compile_seconds = 0.0
samples = 3
seconds = 0.0001176

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.8e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11133320
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020410515
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000829
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10679624
compile_seconds = 0.0
samples = 3
seconds = 0.020285815

[datasets.kb2.primal]
allocations = 231373
bytes = 11147240
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020845615
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000642
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112368
compile_seconds = 0.0
samples = 3
seconds = 8.79e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161968
compile_seconds = 0.0
samples = 3
seconds = 0.000122

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.7e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199792
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020509
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000550801
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2854560
compile_seconds = 0.0
samples = 3
seconds = 0.001584201

[datasets.sc50a.primal]
allocations = 68651
bytes = 3152320
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001933201
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004991
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.32e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300736
compile_seconds = 0.0
samples = 3
seconds = 0.0001919

[probes.both_negative]
allocations = 24631
bytes = 1013224
compile_seconds = 0.0
samples = 3
seconds = 0.0005177

[probes.finite]
allocations = 33847
bytes = 1359608
compile_seconds = 0.0
samples = 3
seconds = 0.0006591

[probes.negative_coefficient]
allocations = 24631
bytes = 1013064
compile_seconds = 0.0
samples = 3
seconds = 0.0005295

[probes.negative_rhs]
allocations = 24631
bytes = 1013336
compile_seconds = 0.0
samples = 3
seconds = 0.0004978

[probes.one_sided]
allocations = 29239
bytes = 1186440
compile_seconds = 0.0
samples = 3
seconds = 0.0005814

[probes.positive]
allocations = 24631
bytes = 1011752
compile_seconds = 0.0
samples = 3
seconds = 0.0006238
