julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85366
bytes = 4159432
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032119
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461096
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009586
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83351
bytes = 3368312
compile_seconds = 0.0
samples = 3
seconds = 0.0020602

[datasets.adlittle.primal]
allocations = 86164
bytes = 4436248
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038574
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607456
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010909
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 6.52e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185600
compile_seconds = 0.0
samples = 3
seconds = 0.0001123

[datasets.afiro.dual]
allocations = 18263
bytes = 912160
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007182
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001905
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 776000
compile_seconds = 0.0
samples = 3
seconds = 0.0005864

[datasets.afiro.primal]
allocations = 18169
bytes = 889728
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007231
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000210801
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 45616
compile_seconds = 0.0
samples = 3
seconds = 9.51e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 270352
compile_seconds = 0.0
samples = 3
seconds = 0.0002066

[datasets.flugpl.dual]
allocations = 32652
bytes = 1328296
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000954
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001519
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31981
bytes = 1218320
compile_seconds = 0.0
samples = 3
seconds = 0.0007248

[datasets.flugpl.primal]
allocations = 33001
bytes = 1372648
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000905
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001822
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.14e-5

[datasets.flugpl.sparse]
allocations = 5852
bytes = 219616
compile_seconds = 0.0
samples = 3
seconds = 0.0001245

[datasets.kb2.dual]
allocations = 232882
bytes = 11196072
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020216701
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008249
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10744040
compile_seconds = 0.0
samples = 3
seconds = 0.019418301

[datasets.kb2.primal]
allocations = 233049
bytes = 11209896
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.019893901
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005972
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 135920
compile_seconds = 0.0
samples = 3
seconds = 8.64e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197944
compile_seconds = 0.0
samples = 3
seconds = 0.0001099

[datasets.sc50a.dual]
allocations = 72627
bytes = 3354712
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021302
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005774
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3008696
compile_seconds = 0.0
samples = 3
seconds = 0.0015911

[datasets.sc50a.primal]
allocations = 72572
bytes = 3307576
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020902
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005288
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.58e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 391960
compile_seconds = 0.0
samples = 3
seconds = 0.0002129

[probes.free]
allocations = 17658
bytes = 686456
compile_seconds = 0.0
samples = 3
seconds = 0.0003476

[probes.singleton_negative]
allocations = 29181
bytes = 1118480
compile_seconds = 0.0
samples = 3
seconds = 0.0005278

[probes.singleton_positive]
allocations = 29178
bytes = 1117672
compile_seconds = 0.0
samples = 3
seconds = 0.0005719

[probes.sparse_negative]
allocations = 47956
bytes = 1786680
compile_seconds = 0.0
samples = 3
seconds = 0.0008177

[probes.sparse_positive]
allocations = 47950
bytes = 1785960
compile_seconds = 0.0
samples = 3
seconds = 0.0008533

[probes.unequal]
allocations = 29178
bytes = 1119624
compile_seconds = 0.0
samples = 3
seconds = 0.000565
