julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84676
bytes = 4131232
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003466615
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000973904
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82661
bytes = 3341648
compile_seconds = 0.0
samples = 3
seconds = 0.002197609

[datasets.adlittle.primal]
allocations = 85474
bytes = 4408176
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003619216
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607664
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001050504
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.56e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 173992
compile_seconds = 0.0
samples = 3
seconds = 0.000111

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 864160
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000758203
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000236601
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 728976
compile_seconds = 0.0
samples = 3
seconds = 0.0005987

[datasets.afiro.primal]
allocations = 16963
bytes = 842496
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000792303
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000210401
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45088
compile_seconds = 0.0
samples = 3
seconds = 0.000116

[datasets.afiro.sparse]
allocations = 4891
bytes = 213856
compile_seconds = 0.0
samples = 3
seconds = 0.0001686

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.8e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1290016
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000833101
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001749
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1180312
compile_seconds = 0.0
samples = 3
seconds = 0.000816601

[datasets.flugpl.primal]
allocations = 32031
bytes = 1334448
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000900401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002099
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.76e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209512
compile_seconds = 0.0
samples = 3
seconds = 0.0001391

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11128432
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021887703
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009106
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10673376
compile_seconds = 0.0
samples = 3
seconds = 0.021951004

[datasets.kb2.primal]
allocations = 231280
bytes = 11141632
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021152903
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006287
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112272
compile_seconds = 0.0
samples = 3
seconds = 8.96e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161712
compile_seconds = 0.0
samples = 3
seconds = 8.4001e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.62e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3192864
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002266903
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000661
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2847200
compile_seconds = 0.0
samples = 3
seconds = 0.001768602

[datasets.sc50a.primal]
allocations = 68520
bytes = 3145600
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002148802
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000545101
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.24e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298880
compile_seconds = 0.0
samples = 3
seconds = 0.0001991

[probes.negative]
allocations = 33056
bytes = 1241488
compile_seconds = 0.0
samples = 3
seconds = 0.0006182

[probes.nonzero_constant]
allocations = 34211
bytes = 1284600
compile_seconds = 0.0
samples = 3
seconds = 0.000639299

[probes.positive]
allocations = 33056
bytes = 1238880
compile_seconds = 0.0
samples = 3
seconds = 0.000674399

[probes.unit_negative]
allocations = 31264
bytes = 1168800
compile_seconds = 0.0
samples = 3
seconds = 0.000599399

[probes.unit_positive]
allocations = 30752
bytes = 1154464
compile_seconds = 0.0
samples = 3
seconds = 0.0005698

[probes.zero_rhs]
allocations = 29344
bytes = 1106512
compile_seconds = 0.0
samples = 3
seconds = 0.0005661
