julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4115576
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.00361739
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461656
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001023198
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326584
compile_seconds = 0.0
samples = 3
seconds = 0.002519695

[datasets.adlittle.primal]
allocations = 85246
bytes = 4391960
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004065689
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607744
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001159997
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640584
compile_seconds = 0.0
samples = 3
seconds = 0.000427299

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.48e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 173272
compile_seconds = 0.0
samples = 3
seconds = 0.0001101

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 861736
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000716898
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000228399
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 726776
compile_seconds = 0.0
samples = 3
seconds = 0.000562299

[datasets.afiro.primal]
allocations = 16938
bytes = 841272
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000813298
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000196799
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91752
compile_seconds = 0.0
samples = 3
seconds = 8.7599e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 44496
compile_seconds = 0.0
samples = 3
seconds = 7.92e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213456
compile_seconds = 0.0
samples = 3
seconds = 0.0001797

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1278168
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001154497
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001481
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169504
compile_seconds = 0.0
samples = 3
seconds = 0.000698298

[datasets.flugpl.primal]
allocations = 31811
bytes = 1322808
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001003801
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001821
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 121552
compile_seconds = 0.0
samples = 3
seconds = 0.0001028

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.9499e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209128
compile_seconds = 0.0
samples = 3
seconds = 0.0001325

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11091072
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020873747
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878144
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000857198
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10638032
compile_seconds = 0.0
samples = 3
seconds = 0.020843547

[datasets.kb2.primal]
allocations = 230563
bytes = 11105424
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021357945
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000605299
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453024
compile_seconds = 0.0
samples = 3
seconds = 0.000247599

[datasets.kb2.singleton]
allocations = 2060
bytes = 111824
compile_seconds = 0.0
samples = 3
seconds = 9.01e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 160752
compile_seconds = 0.0
samples = 3
seconds = 0.0001164

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.03e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191944
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002214594
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000607798
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846216
compile_seconds = 0.0
samples = 3
seconds = 0.001755295

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144520
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001981895
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000579099
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 220720
compile_seconds = 0.0
samples = 3
seconds = 0.000181099

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.47e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298144
compile_seconds = 0.0
samples = 3
seconds = 0.0001571

[probes.singleton_fraction_negative]
allocations = 27648
bytes = 1054536
compile_seconds = 0.0
samples = 3
seconds = 0.000528299

[probes.singleton_fraction_positive]
allocations = 27648
bytes = 1055000
compile_seconds = 0.0
samples = 3
seconds = 0.000510299

[probes.singleton_integer_negative]
allocations = 27136
bytes = 1027640
compile_seconds = 0.0
samples = 3
seconds = 0.000516199

[probes.singleton_integer_positive]
allocations = 27136
bytes = 1026936
compile_seconds = 0.0
samples = 3
seconds = 0.000605899

[probes.sparse_fraction_negative]
allocations = 43452
bytes = 1598328
compile_seconds = 0.0
samples = 3
seconds = 0.0008044

[probes.sparse_fraction_positive]
allocations = 43441
bytes = 1597992
compile_seconds = 0.0
samples = 3
seconds = 0.0008029

[probes.sparse_integer_negative]
allocations = 43095
bytes = 1578720
compile_seconds = 0.0
samples = 3
seconds = 0.000797

[probes.sparse_integer_positive]
allocations = 43082
bytes = 1576920
compile_seconds = 0.0
samples = 3
seconds = 0.000913201

[probes.unequal_denominator]
allocations = 27552
bytes = 1049144
compile_seconds = 0.0
samples = 3
seconds = 0.000480299

[probes.unit_coefficient]
allocations = 25344
bytes = 963592
compile_seconds = 0.0
samples = 3
seconds = 0.000450099
