julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84980
bytes = 4145232
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003340104
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461000
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000961101
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82965
bytes = 3356688
compile_seconds = 0.0
samples = 3
seconds = 0.002162403

[datasets.adlittle.primal]
allocations = 85778
bytes = 4421824
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003765404
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001181701
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.25e-5

[datasets.adlittle.sparse]
allocations = 2861
bytes = 177936
compile_seconds = 0.0
samples = 3
seconds = 0.0001255

[datasets.afiro.dual]
allocations = 17505
bytes = 882880
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000779201
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002341
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16690
bytes = 747872
compile_seconds = 0.0
samples = 3
seconds = 0.0006629

[datasets.afiro.primal]
allocations = 17411
bytes = 861024
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000821401
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002109
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44832
compile_seconds = 0.0
samples = 3
seconds = 8.7e-5

[datasets.afiro.sparse]
allocations = 5524
bytes = 240416
compile_seconds = 0.0
samples = 3
seconds = 0.0001873

[datasets.flugpl.dual]
allocations = 32286
bytes = 1315128
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000929004
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000158901
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1205728
compile_seconds = 0.0
samples = 3
seconds = 0.0007359

[datasets.flugpl.primal]
allocations = 32635
bytes = 1359544
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001059804
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000206801
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.07e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216344
compile_seconds = 0.0
samples = 3
seconds = 0.0001361

[datasets.kb2.dual]
allocations = 231270
bytes = 11136344
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021146525
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877952
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000844701
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230068
bytes = 10683864
compile_seconds = 0.0
samples = 3
seconds = 0.020501025

[datasets.kb2.primal]
allocations = 231437
bytes = 11148584
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020829425
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000698801
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112496
compile_seconds = 0.0
samples = 3
seconds = 0.0001285

[datasets.kb2.sparse]
allocations = 2958
bytes = 166256
compile_seconds = 0.0
samples = 3
seconds = 0.000132101

[datasets.sc50a.dual]
allocations = 69752
bytes = 3243928
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020737
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306496
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006258
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 68680
bytes = 2897432
compile_seconds = 0.0
samples = 3
seconds = 0.0016558

[datasets.sc50a.primal]
allocations = 69697
bytes = 3196936
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023134
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000561001
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.71e-5

[datasets.sc50a.sparse]
allocations = 7434
bytes = 332208
compile_seconds = 0.0
samples = 3
seconds = 0.0002181

[probes.negative_negative]
allocations = 29908
bytes = 1112056
compile_seconds = 0.0
samples = 3
seconds = 0.000611

[probes.negative_positive]
allocations = 29911
bytes = 1112128
compile_seconds = 0.0
samples = 3
seconds = 0.0005859

[probes.nonzero]
allocations = 37070
bytes = 1389160
compile_seconds = 0.0
samples = 3
seconds = 0.000706

[probes.positive_negative]
allocations = 29143
bytes = 1090512
compile_seconds = 0.0
samples = 3
seconds = 0.0006451

[probes.positive_positive]
allocations = 29140
bytes = 1088712
compile_seconds = 0.0
samples = 3
seconds = 0.0006881

[probes.singleton]
allocations = 17152
bytes = 679704
compile_seconds = 0.0
samples = 3
seconds = 0.000406
