julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.adlittle.dual]
allocations = 82802
bytes = 4062816
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033032
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461032
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009377
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80787
bytes = 3272656
compile_seconds = 0.0
samples = 3
seconds = 0.0018989

[datasets.adlittle.primal]
allocations = 83600
bytes = 4339824
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003300199
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607376
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010145
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641528
compile_seconds = 0.0
samples = 3
seconds = 0.0003601

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.61e-5

[datasets.adlittle.sparse]
allocations = 1970
bytes = 142792
compile_seconds = 0.0
samples = 3
seconds = 0.0001056

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.afiro.dual]
allocations = 16249
bytes = 836296
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000663
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001822
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15434
bytes = 700456
compile_seconds = 0.0
samples = 3
seconds = 0.0005419

[datasets.afiro.primal]
allocations = 16155
bytes = 813912
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008971
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001875
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92744
compile_seconds = 0.0
samples = 3
seconds = 0.0001001

[datasets.afiro.singleton]
allocations = 747
bytes = 40960
compile_seconds = 0.0
samples = 3
seconds = 7.02e-5

[datasets.afiro.sparse]
allocations = 3820
bytes = 176616
compile_seconds = 0.0
samples = 3
seconds = 0.0001338

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.flugpl.dual]
allocations = 26767
bytes = 1111248
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008427
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001277
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 26096
bytes = 1000184
compile_seconds = 0.0
samples = 3
seconds = 0.000637

[datasets.flugpl.primal]
allocations = 27116
bytes = 1155952
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000831
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001802
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123200
compile_seconds = 0.0
samples = 3
seconds = 9.54e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.45e-5

[datasets.flugpl.sparse]
allocations = 4068
bytes = 153864
compile_seconds = 0.0
samples = 3
seconds = 0.0001111

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.dual]
allocations = 228243
bytes = 11017672
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0200122
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877952
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007965
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227041
bytes = 10564120
compile_seconds = 0.0
samples = 3
seconds = 0.0198275

[datasets.kb2.primal]
allocations = 228410
bytes = 11030344
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0201042
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005797
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454592
compile_seconds = 0.0
samples = 3
seconds = 0.0002296

[datasets.kb2.singleton]
allocations = 1915
bytes = 105192
compile_seconds = 0.0
samples = 3
seconds = 7.91e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127640
compile_seconds = 0.0
samples = 3
seconds = 0.0001011

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.sc50a.dual]
allocations = 66393
bytes = 3120760
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018795
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306176
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005318
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 65321
bytes = 2774776
compile_seconds = 0.0
samples = 3
seconds = 0.0014654

[datasets.sc50a.primal]
allocations = 66338
bytes = 3074344
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018222
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004838
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222672
compile_seconds = 0.0
samples = 3
seconds = 0.0001424

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.sparse]
allocations = 5729
bytes = 270240
compile_seconds = 0.0
samples = 3
seconds = 0.0001645

[probes.free_negative]
allocations = 29623
bytes = 1196568
compile_seconds = 0.0
samples = 3
seconds = 0.0006467

[probes.free_positive]
allocations = 29623
bytes = 1196440
compile_seconds = 0.0
samples = 3
seconds = 0.0006484

[probes.negative]
allocations = 43319
bytes = 1626360
compile_seconds = 0.0
samples = 3
seconds = 0.0009426

[probes.negative_both]
allocations = 43319
bytes = 1626264
compile_seconds = 0.0
samples = 3
seconds = 0.0008737

[probes.negative_term]
allocations = 43319
bytes = 1626440
compile_seconds = 0.0
samples = 3
seconds = 0.0008909

[probes.positive]
allocations = 43319
bytes = 1624328
compile_seconds = 0.0
samples = 3
seconds = 0.0008984
