julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85052
bytes = 4145280
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003695801
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461208
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010208
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83037
bytes = 3355760
compile_seconds = 0.0
samples = 3
seconds = 0.002410301

[datasets.adlittle.primal]
allocations = 85850
bytes = 4422752
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003915202
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607504
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001249101
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.96e-5

[datasets.adlittle.sparse]
allocations = 2915
bytes = 179968
compile_seconds = 0.0
samples = 3
seconds = 0.0001407

[datasets.afiro.dual]
allocations = 17627
bytes = 887264
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008462
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002361
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16812
bytes = 750592
compile_seconds = 0.0
samples = 3
seconds = 0.0006425

[datasets.afiro.primal]
allocations = 17533
bytes = 865376
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007867
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002231
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 44960
compile_seconds = 0.0
samples = 3
seconds = 7.88e-5

[datasets.afiro.sparse]
allocations = 5681
bytes = 245800
compile_seconds = 0.0
samples = 3
seconds = 0.0001782

[datasets.flugpl.dual]
allocations = 32526
bytes = 1323664
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011065
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001601
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31855
bytes = 1213384
compile_seconds = 0.0
samples = 3
seconds = 0.000779

[datasets.flugpl.primal]
allocations = 32875
bytes = 1368128
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000937801
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002086
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.33e-5

[datasets.flugpl.sparse]
allocations = 5852
bytes = 219296
compile_seconds = 0.0
samples = 3
seconds = 0.0001475

[datasets.kb2.dual]
allocations = 231415
bytes = 11139536
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021378808
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878304
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009179
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230213
bytes = 10686096
compile_seconds = 0.0
samples = 3
seconds = 0.020483108

[datasets.kb2.primal]
allocations = 231582
bytes = 11153216
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021656308
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006407
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2085
bytes = 112968
compile_seconds = 0.0
samples = 3
seconds = 0.0001287

[datasets.kb2.sparse]
allocations = 3087
bytes = 171376
compile_seconds = 0.0
samples = 3
seconds = 0.000134701

[datasets.sc50a.dual]
allocations = 70475
bytes = 3271888
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002233501
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006222
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 69403
bytes = 2926336
compile_seconds = 0.0
samples = 3
seconds = 0.0016213

[datasets.sc50a.primal]
allocations = 70420
bytes = 3224928
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002163601
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005419
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.57e-5

[datasets.sc50a.sparse]
allocations = 7891
bytes = 350656
compile_seconds = 0.0
samples = 3
seconds = 0.0002082

[probes.inequality]
allocations = 278
bytes = 15256
compile_seconds = 0.0
samples = 3
seconds = 1.4e-5

[probes.nonzero]
allocations = 28029
bytes = 1076368
compile_seconds = 0.0
samples = 3
seconds = 0.0005489

[probes.singleton_negative]
allocations = 20480
bytes = 804584
compile_seconds = 0.0
samples = 3
seconds = 0.000443

[probes.singleton_positive]
allocations = 20480
bytes = 803224
compile_seconds = 0.0
samples = 3
seconds = 0.000456801

[probes.sparse_negative]
allocations = 39255
bytes = 1473584
compile_seconds = 0.0
samples = 3
seconds = 0.000810002

[probes.sparse_positive]
allocations = 39252
bytes = 1472152
compile_seconds = 0.0
samples = 3
seconds = 0.000770801
