julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122704
bytes = 5660632
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0040782
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461800
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009738
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120689
bytes = 4868968
compile_seconds = 0.0
samples = 3
seconds = 0.0028152

[datasets.adlittle.primal]
allocations = 123502
bytes = 5936632
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0046301
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607344
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011524
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 7.43e-5

[datasets.adlittle.sparse]
allocations = 3277
bytes = 193392
compile_seconds = 0.0
samples = 3
seconds = 0.0001219

[datasets.afiro.dual]
allocations = 28331
bytes = 1309640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009762
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002106
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27516
bytes = 1174328
compile_seconds = 0.0
samples = 3
seconds = 0.0007983

[datasets.afiro.primal]
allocations = 28237
bytes = 1287192
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009525
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002139
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 45856
compile_seconds = 0.0
samples = 3
seconds = 0.0001281

[datasets.afiro.sparse]
allocations = 6424
bytes = 278896
compile_seconds = 0.0
samples = 3
seconds = 0.0001935

[datasets.flugpl.dual]
allocations = 39856
bytes = 1617464
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001015
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001588
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39185
bytes = 1507888
compile_seconds = 0.0
samples = 3
seconds = 0.0008937

[datasets.flugpl.primal]
allocations = 40205
bytes = 1661704
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011027
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000193
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 104
bytes = 5120
compile_seconds = 0.0
samples = 3
seconds = 1.89e-5

[datasets.flugpl.sparse]
allocations = 6262
bytes = 237256
compile_seconds = 0.0
samples = 3
seconds = 0.000152

[datasets.kb2.dual]
allocations = 293436
bytes = 13619120
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022285501
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000897001
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292234
bytes = 13165488
compile_seconds = 0.0
samples = 3
seconds = 0.0212816

[datasets.kb2.primal]
allocations = 293603
bytes = 13633072
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0214676
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006508
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 148184
compile_seconds = 0.0
samples = 3
seconds = 0.0001265

[datasets.kb2.sparse]
allocations = 3787
bytes = 199816
compile_seconds = 0.0
samples = 3
seconds = 0.0001345

[datasets.sc50a.dual]
allocations = 106961
bytes = 4645024
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0027482
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306496
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006578
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 105889
bytes = 4297888
compile_seconds = 0.0
samples = 3
seconds = 0.0022713

[datasets.sc50a.primal]
allocations = 106906
bytes = 4597248
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0026095
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005313
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 302
bytes = 14464
compile_seconds = 0.0
samples = 3
seconds = 1.56e-5

[datasets.sc50a.sparse]
allocations = 9340
bytes = 415784
compile_seconds = 0.0
samples = 3
seconds = 0.000226

[probes.singleton]
allocations = 8950
bytes = 355848
compile_seconds = 0.0
samples = 3
seconds = 0.0001951

[probes.sparse]
allocations = 18296
bytes = 699312
compile_seconds = 0.0
samples = 3
seconds = 0.0003976
