julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 84790
bytes = 4138384
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032916
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461192
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000904
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82775
bytes = 3348208
compile_seconds = 0.0
samples = 3
seconds = 0.0019861

[datasets.adlittle.primal]
allocations = 85588
bytes = 4415056
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035214
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607760
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001073
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.02e-5

[datasets.adlittle.sparse]
allocations = 2842
bytes = 177560
compile_seconds = 0.0
samples = 3
seconds = 0.0001198

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868664
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007219
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000214
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733080
compile_seconds = 0.0
samples = 3
seconds = 0.0005751

[datasets.afiro.primal]
allocations = 17051
bytes = 846696
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006615
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001793
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44768
compile_seconds = 0.0
samples = 3
seconds = 0.0001

[datasets.afiro.sparse]
allocations = 4987
bytes = 218712
compile_seconds = 0.0
samples = 3
seconds = 0.0001586

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1308608
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009107
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001491
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1199672
compile_seconds = 0.0
samples = 3
seconds = 0.000713

[datasets.flugpl.primal]
allocations = 32481
bytes = 1352880
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009638
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001766
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.89e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217240
compile_seconds = 0.0
samples = 3
seconds = 0.0001456

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11134200
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0208337
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008614
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10679928
compile_seconds = 0.0
samples = 3
seconds = 0.0202416

[datasets.kb2.primal]
allocations = 231373
bytes = 11148232
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0207214
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006305
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112224
compile_seconds = 0.0
samples = 3
seconds = 8.69e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161424
compile_seconds = 0.0
samples = 3
seconds = 9.57e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.79e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3198688
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021513
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005551
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853664
compile_seconds = 0.0
samples = 3
seconds = 0.001364599

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151472
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019444
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005001
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.38e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300416
compile_seconds = 0.0
samples = 3
seconds = 0.0001815

[probes.nonunit]
allocations = 54085
bytes = 2078176
compile_seconds = 0.0
samples = 3
seconds = 0.0010105

[probes.ratio_negative]
allocations = 54085
bytes = 2078480
compile_seconds = 0.0
samples = 3
seconds = 0.0010281

[probes.ratio_positive]
allocations = 54085
bytes = 2076704
compile_seconds = 0.0
samples = 3
seconds = 0.0010432

[probes.term_negative]
allocations = 53189
bytes = 2042208
compile_seconds = 0.0
samples = 3
seconds = 0.0009822

[probes.term_positive]
allocations = 52933
bytes = 2035072
compile_seconds = 0.0
samples = 3
seconds = 0.0010532

[probes.zero_ratio]
allocations = 46405
bytes = 1805984
compile_seconds = 0.0
samples = 3
seconds = 0.0008929
