julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.adlittle.dual]
allocations = 83441
bytes = 4079648
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031721
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461224
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009034
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81426
bytes = 3289552
compile_seconds = 0.0
samples = 3
seconds = 0.0021623

[datasets.adlittle.primal]
allocations = 84239
bytes = 4356592
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035323
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607504
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010152
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641576
compile_seconds = 0.0
samples = 3
seconds = 0.0003511

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.18e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 156744
compile_seconds = 0.0
samples = 3
seconds = 0.0001258

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.afiro.dual]
allocations = 16468
bytes = 841736
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007317
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002171
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15653
bytes = 706120
compile_seconds = 0.0
samples = 3
seconds = 0.0005954

[datasets.afiro.primal]
allocations = 16374
bytes = 820088
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006416
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001634
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92536
compile_seconds = 0.0
samples = 3
seconds = 0.0001648

[datasets.afiro.singleton]
allocations = 747
bytes = 40928
compile_seconds = 0.0
samples = 3
seconds = 7.85e-5

[datasets.afiro.sparse]
allocations = 4167
bytes = 186776
compile_seconds = 0.0
samples = 3
seconds = 0.0001648

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 28597
bytes = 1167952
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009231
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001532
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27926
bytes = 1057640
compile_seconds = 0.0
samples = 3
seconds = 0.0007037

[datasets.flugpl.primal]
allocations = 28946
bytes = 1212176
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008758
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001986
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123216
compile_seconds = 0.0
samples = 3
seconds = 9.3e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.73e-5

[datasets.flugpl.sparse]
allocations = 4667
bytes = 173480
compile_seconds = 0.0
samples = 3
seconds = 0.0001269

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 229109
bytes = 11044288
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0202713
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008384
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227907
bytes = 10589696
compile_seconds = 0.0
samples = 3
seconds = 0.0206982

[datasets.kb2.primal]
allocations = 229276
bytes = 11057504
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0206646
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006138
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454368
compile_seconds = 0.0
samples = 3
seconds = 0.0002762

[datasets.kb2.singleton]
allocations = 1915
bytes = 105416
compile_seconds = 0.0
samples = 3
seconds = 8.66e-5

[datasets.kb2.sparse]
allocations = 2259
bytes = 137304
compile_seconds = 0.0
samples = 3
seconds = 0.0001129

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.46e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.sc50a.dual]
allocations = 67374
bytes = 3148408
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020724
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005453
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66302
bytes = 2802200
compile_seconds = 0.0
samples = 3
seconds = 0.0015948

[datasets.sc50a.primal]
allocations = 67319
bytes = 3101384
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020767
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004553
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222112
compile_seconds = 0.0
samples = 3
seconds = 0.0001472

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.65e-5

[datasets.sc50a.sparse]
allocations = 6174
bytes = 282400
compile_seconds = 0.0
samples = 3
seconds = 0.0001809

[probes.fraction_negative]
allocations = 63827
bytes = 2462912
compile_seconds = 0.0
samples = 3
seconds = 0.0013281

[probes.fraction_positive]
allocations = 63827
bytes = 2463024
compile_seconds = 0.0
samples = 3
seconds = 0.0013071

[probes.free_pivot]
allocations = 44115
bytes = 1846064
compile_seconds = 0.0
samples = 3
seconds = 0.001005

[probes.integer_negative]
allocations = 63315
bytes = 2435904
compile_seconds = 0.0
samples = 3
seconds = 0.0013506

[probes.integer_positive]
allocations = 63315
bytes = 2432800
compile_seconds = 0.0
samples = 3
seconds = 0.0012669

[probes.variable]
allocations = 66643
bytes = 2539792
compile_seconds = 0.0
samples = 3
seconds = 0.0013289
