julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85616
bytes = 4167856
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0037191
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461288
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001017801
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83601
bytes = 3377696
compile_seconds = 0.0
samples = 3
seconds = 0.002221501

[datasets.adlittle.primal]
allocations = 86414
bytes = 4444320
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004028
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.00118
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 788
bytes = 67392
compile_seconds = 0.0
samples = 3
seconds = 7.74e-5

[datasets.adlittle.sparse]
allocations = 3232
bytes = 191152
compile_seconds = 0.0
samples = 3
seconds = 0.000144

[datasets.afiro.dual]
allocations = 18384
bytes = 915168
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008823
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002067
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17569
bytes = 778624
compile_seconds = 0.0
samples = 3
seconds = 0.0006494

[datasets.afiro.primal]
allocations = 18290
bytes = 892784
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007679
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001858
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 870
bytes = 46096
compile_seconds = 0.0
samples = 3
seconds = 9.02e-5

[datasets.afiro.sparse]
allocations = 6367
bytes = 270664
compile_seconds = 0.0
samples = 3
seconds = 0.0002016

[datasets.flugpl.dual]
allocations = 33384
bytes = 1356576
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009638
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000169
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 32713
bytes = 1247000
compile_seconds = 0.0
samples = 3
seconds = 0.0007064

[datasets.flugpl.primal]
allocations = 33733
bytes = 1401328
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001025
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002002
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.21e-5

[datasets.flugpl.sparse]
allocations = 6098
bytes = 228664
compile_seconds = 0.0
samples = 3
seconds = 0.000161

[datasets.kb2.dual]
allocations = 233169
bytes = 11206152
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022057601
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878128
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009046
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231967
bytes = 10753464
compile_seconds = 0.0
samples = 3
seconds = 0.020828801

[datasets.kb2.primal]
allocations = 233336
bytes = 11219592
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021555301
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260880
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006759
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2794
bytes = 141912
compile_seconds = 0.0
samples = 3
seconds = 0.0001132

[datasets.kb2.sparse]
allocations = 3755
bytes = 197960
compile_seconds = 0.0
samples = 3
seconds = 0.0001537

[datasets.sc50a.dual]
allocations = 73064
bytes = 3371304
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022128
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006217
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71992
bytes = 3023016
compile_seconds = 0.0
samples = 3
seconds = 0.0017729

[datasets.sc50a.primal]
allocations = 73009
bytes = 3323736
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002242701
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005585
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.7e-5

[datasets.sc50a.sparse]
allocations = 9173
bytes = 399696
compile_seconds = 0.0
samples = 3
seconds = 0.0002455

[probes.free]
allocations = 17786
bytes = 687784
compile_seconds = 0.0
samples = 3
seconds = 0.0003845

[probes.nonunit]
allocations = 29178
bytes = 1118776
compile_seconds = 0.0
samples = 3
seconds = 0.000568

[probes.singleton_negative]
allocations = 27517
bytes = 1047920
compile_seconds = 0.0
samples = 3
seconds = 0.0005817

[probes.singleton_positive]
allocations = 27002
bytes = 1031928
compile_seconds = 0.0
samples = 3
seconds = 0.0005528

[probes.sparse_negative]
allocations = 46420
bytes = 1718584
compile_seconds = 0.0
samples = 3
seconds = 0.0008679

[probes.sparse_positive]
allocations = 45902
bytes = 1702456
compile_seconds = 0.0
samples = 3
seconds = 0.0009131
