julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 83431
bytes = 4078992
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033562
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461272
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008954
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81416
bytes = 3289616
compile_seconds = 0.0
samples = 3
seconds = 0.0018706

[datasets.adlittle.primal]
allocations = 84229
bytes = 4355984
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003422199
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607456
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0009968
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641528
compile_seconds = 0.0
samples = 3
seconds = 0.0003352

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.18e-5

[datasets.adlittle.sparse]
allocations = 2336
bytes = 156472
compile_seconds = 0.0
samples = 3
seconds = 0.0001285

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.afiro.dual]
allocations = 16456
bytes = 841624
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007328
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002246
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15641
bytes = 707000
compile_seconds = 0.0
samples = 3
seconds = 0.0006378

[datasets.afiro.primal]
allocations = 16362
bytes = 819880
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000673699
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000198
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92872
compile_seconds = 0.0
samples = 3
seconds = 0.0001065

[datasets.afiro.singleton]
allocations = 747
bytes = 40752
compile_seconds = 0.0
samples = 3
seconds = 5.92e-5

[datasets.afiro.sparse]
allocations = 4155
bytes = 186520
compile_seconds = 0.0
samples = 3
seconds = 0.000127

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.flugpl.dual]
allocations = 28597
bytes = 1168240
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007476
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001488
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27926
bytes = 1058744
compile_seconds = 0.0
samples = 3
seconds = 0.0006181

[datasets.flugpl.primal]
allocations = 28946
bytes = 1212656
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008013
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.00015
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123536
compile_seconds = 0.0
samples = 3
seconds = 8.85e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.28e-5

[datasets.flugpl.sparse]
allocations = 4667
bytes = 172984
compile_seconds = 0.0
samples = 3
seconds = 0.0001091

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.dual]
allocations = 229107
bytes = 11044016
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020438898
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000785499
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227905
bytes = 10591040
compile_seconds = 0.0
samples = 3
seconds = 0.020198798

[datasets.kb2.primal]
allocations = 229274
bytes = 11058176
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020810798
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005797
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454352
compile_seconds = 0.0
samples = 3
seconds = 0.0002689

[datasets.kb2.singleton]
allocations = 1915
bytes = 105064
compile_seconds = 0.0
samples = 3
seconds = 7.98e-5

[datasets.kb2.sparse]
allocations = 2257
bytes = 136904
compile_seconds = 0.0
samples = 3
seconds = 0.0001084

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.39e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.sc50a.dual]
allocations = 67347
bytes = 3148424
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021304
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005573
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66275
bytes = 2802488
compile_seconds = 0.0
samples = 3
seconds = 0.0014988

[datasets.sc50a.primal]
allocations = 67292
bytes = 3101176
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002014701
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005107
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222032
compile_seconds = 0.0
samples = 3
seconds = 0.0001325

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.43e-5

[datasets.sc50a.sparse]
allocations = 6164
bytes = 281824
compile_seconds = 0.0
samples = 3
seconds = 0.0001811

[probes.negative]
allocations = 43703
bytes = 1636488
compile_seconds = 0.0
samples = 3
seconds = 0.0008223

[probes.positive]
allocations = 43703
bytes = 1634840
compile_seconds = 0.0
samples = 3
seconds = 0.0008253

[probes.unit_negative]
allocations = 42551
bytes = 1590568
compile_seconds = 0.0
samples = 3
seconds = 0.0008883

[probes.unit_positive]
allocations = 41783
bytes = 1569032
compile_seconds = 0.0
samples = 3
seconds = 0.0007949

[probes.upper_free]
allocations = 40631
bytes = 1538248
compile_seconds = 0.0
samples = 3
seconds = 0.0008804

[probes.variable]
allocations = 45879
bytes = 1697688
compile_seconds = 0.0
samples = 3
seconds = 0.0009284
