julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.adlittle.dual]
allocations = 83266
bytes = 4073296
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003172
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461720
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009123
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81251
bytes = 3285056
compile_seconds = 0.0
samples = 3
seconds = 0.0018649

[datasets.adlittle.primal]
allocations = 84064
bytes = 4349920
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036113
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607536
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011309
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641800
compile_seconds = 0.0
samples = 3
seconds = 0.0003323

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.91e-5

[datasets.adlittle.sparse]
allocations = 2282
bytes = 154952
compile_seconds = 0.0
samples = 3
seconds = 0.0001005

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 16441
bytes = 841272
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008832
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002118
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15626
bytes = 706120
compile_seconds = 0.0
samples = 3
seconds = 0.0005354

[datasets.afiro.primal]
allocations = 16347
bytes = 819320
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007039
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002122
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92664
compile_seconds = 0.0
samples = 3
seconds = 8.57e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40928
compile_seconds = 0.0
samples = 3
seconds = 6.87e-5

[datasets.afiro.sparse]
allocations = 4116
bytes = 185432
compile_seconds = 0.0
samples = 3
seconds = 0.0001572

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.7e-6

[datasets.flugpl.dual]
allocations = 28027
bytes = 1145584
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000779
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001558
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27356
bytes = 1036328
compile_seconds = 0.0
samples = 3
seconds = 0.0005753

[datasets.flugpl.primal]
allocations = 28376
bytes = 1189840
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008089
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001683
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123328
compile_seconds = 0.0
samples = 3
seconds = 9.8e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.44e-5

[datasets.flugpl.sparse]
allocations = 4484
bytes = 166456
compile_seconds = 0.0
samples = 3
seconds = 9.85e-5

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.dual]
allocations = 228643
bytes = 11027592
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0206539
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007593
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227441
bytes = 10574664
compile_seconds = 0.0
samples = 3
seconds = 0.0192799

[datasets.kb2.primal]
allocations = 228810
bytes = 11042008
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0222494
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005672
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454896
compile_seconds = 0.0
samples = 3
seconds = 0.0002303

[datasets.kb2.singleton]
allocations = 1915
bytes = 105352
compile_seconds = 0.0
samples = 3
seconds = 7.95e-5

[datasets.kb2.sparse]
allocations = 2207
bytes = 135416
compile_seconds = 0.0
samples = 3
seconds = 8.47e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.71e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.sc50a.dual]
allocations = 67169
bytes = 3141848
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001973
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306656
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005752
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66097
bytes = 2796200
compile_seconds = 0.0
samples = 3
seconds = 0.0014588

[datasets.sc50a.primal]
allocations = 67114
bytes = 3094424
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018146
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004843
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222800
compile_seconds = 0.0
samples = 3
seconds = 0.0001354

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.33e-5

[datasets.sc50a.sparse]
allocations = 6081
bytes = 280160
compile_seconds = 0.0
samples = 3
seconds = 0.0001715

[probes.fraction_negative]
allocations = 40503
bytes = 1501448
compile_seconds = 0.0
samples = 3
seconds = 0.0008482

[probes.fraction_positive]
allocations = 40503
bytes = 1501576
compile_seconds = 0.0
samples = 3
seconds = 0.000841

[probes.negative]
allocations = 39223
bytes = 1446232
compile_seconds = 0.0
samples = 3
seconds = 0.000881

[probes.nonzero_rhs]
allocations = 46647
bytes = 1717016
compile_seconds = 0.0
samples = 3
seconds = 0.0010151

[probes.positive]
allocations = 39223
bytes = 1444248
compile_seconds = 0.0
samples = 3
seconds = 0.0009463

[probes.zero_activity]
allocations = 31543
bytes = 1208872
compile_seconds = 0.0
samples = 3
seconds = 0.0007078
