julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4116760
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003678303
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461656
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001039601
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3327688
compile_seconds = 0.0
samples = 3
seconds = 0.002300801

[datasets.adlittle.primal]
allocations = 85246
bytes = 4393464
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003900903
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607152
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001162401
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641096
compile_seconds = 0.0
samples = 3
seconds = 0.0004281

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.69e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174744
compile_seconds = 0.0
samples = 3
seconds = 0.000135001

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 863528
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007608
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000200301
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 727640
compile_seconds = 0.0
samples = 3
seconds = 0.000603701

[datasets.afiro.primal]
allocations = 16938
bytes = 841752
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007989
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121760
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002293
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92360
compile_seconds = 0.0
samples = 3
seconds = 9.22e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 44960
compile_seconds = 0.0
samples = 3
seconds = 0.0001343

[datasets.afiro.sparse]
allocations = 4891
bytes = 214720
compile_seconds = 0.0
samples = 3
seconds = 0.0001539

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279128
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000880502
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001614
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169632
compile_seconds = 0.0
samples = 3
seconds = 0.000724701

[datasets.flugpl.primal]
allocations = 31811
bytes = 1323880
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000795902
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000278801
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123392
compile_seconds = 0.0
samples = 3
seconds = 9.9701e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.6201e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210328
compile_seconds = 0.0
samples = 3
seconds = 0.000137301

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11094016
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020989435
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000836502
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10641744
compile_seconds = 0.0
samples = 3
seconds = 0.020363014

[datasets.kb2.primal]
allocations = 230563
bytes = 11107392
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021502235
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000609601
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453920
compile_seconds = 0.0
samples = 3
seconds = 0.0002525

[datasets.kb2.singleton]
allocations = 2060
bytes = 112000
compile_seconds = 0.0
samples = 3
seconds = 0.000109201

[datasets.kb2.sparse]
allocations = 2836
bytes = 161984
compile_seconds = 0.0
samples = 3
seconds = 0.0001283

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191912
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001850904
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306416
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000523
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846488
compile_seconds = 0.0
samples = 3
seconds = 0.001341702

[datasets.sc50a.primal]
allocations = 68474
bytes = 3145048
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001782703
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000471001
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222272
compile_seconds = 0.0
samples = 3
seconds = 0.0001312

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.27e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299568
compile_seconds = 0.0
samples = 3
seconds = 0.0001957

[probes.fraction_negative]
allocations = 45253
bytes = 1761936
compile_seconds = 0.0
samples = 3
seconds = 0.0009108

[probes.fraction_positive]
allocations = 45253
bytes = 1762128
compile_seconds = 0.0
samples = 3
seconds = 0.0008821

[probes.integer_negative]
allocations = 44741
bytes = 1734608
compile_seconds = 0.0
samples = 3
seconds = 0.0008667

[probes.integer_positive]
allocations = 44741
bytes = 1733024
compile_seconds = 0.0
samples = 3
seconds = 0.0008599

[probes.unequal_denominator]
allocations = 44997
bytes = 1748384
compile_seconds = 0.0
samples = 3
seconds = 0.0009147

[probes.unit_pivot]
allocations = 42437
bytes = 1648192
compile_seconds = 0.0
samples = 3
seconds = 0.0008797
