julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84962
bytes = 4143456
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036587
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461048
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009566
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82947
bytes = 3353568
compile_seconds = 0.0
samples = 3
seconds = 0.0021981

[datasets.adlittle.primal]
allocations = 85760
bytes = 4420064
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039257
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001201
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 9.12e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 176976
compile_seconds = 0.0
samples = 3
seconds = 0.0001412

[datasets.afiro.dual]
allocations = 17145
bytes = 868056
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000801
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002168
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 732200
compile_seconds = 0.0
samples = 3
seconds = 0.0006073

[datasets.afiro.primal]
allocations = 17051
bytes = 846264
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007994
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002171
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44704
compile_seconds = 0.0
samples = 3
seconds = 8.72e-5

[datasets.afiro.sparse]
allocations = 5003
bytes = 218256
compile_seconds = 0.0
samples = 3
seconds = 0.0001842

[datasets.flugpl.dual]
allocations = 32286
bytes = 1314696
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011287
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001682
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1204976
compile_seconds = 0.0
samples = 3
seconds = 0.0007959

[datasets.flugpl.primal]
allocations = 32635
bytes = 1359400
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002008
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.05e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216648
compile_seconds = 0.0
samples = 3
seconds = 0.0001406

[datasets.kb2.dual]
allocations = 231206
bytes = 11132392
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0209677
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878368
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000905
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10678936
compile_seconds = 0.0
samples = 3
seconds = 0.0210322

[datasets.kb2.primal]
allocations = 231373
bytes = 11145864
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0214043
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006472
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112096
compile_seconds = 0.0
samples = 3
seconds = 0.0001309

[datasets.kb2.sparse]
allocations = 2836
bytes = 161008
compile_seconds = 0.0
samples = 3
seconds = 0.0001254

[datasets.sc50a.dual]
allocations = 68706
bytes = 3198416
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021974
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005684
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853744
compile_seconds = 0.0
samples = 3
seconds = 0.0016705

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151488
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021643
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004882
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.58e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 299632
compile_seconds = 0.0
samples = 3
seconds = 0.0001863

[probes.negative_negative]
allocations = 45253
bytes = 1768576
compile_seconds = 0.0
samples = 3
seconds = 0.0009503

[probes.negative_positive]
allocations = 45253
bytes = 1768624
compile_seconds = 0.0
samples = 3
seconds = 0.0009239

[probes.nonzero_old]
allocations = 46661
bytes = 1819952
compile_seconds = 0.0
samples = 3
seconds = 0.0009926

[probes.positive_negative]
allocations = 45253
bytes = 1768704
compile_seconds = 0.0
samples = 3
seconds = 0.0009491

[probes.positive_positive]
allocations = 45253
bytes = 1765632
compile_seconds = 0.0
samples = 3
seconds = 0.0009323

[probes.zero_multiplier]
allocations = 35001
bytes = 1396888
compile_seconds = 0.0
samples = 3
seconds = 0.0007948
