julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 3.601e-6

[datasets.adlittle.dual]
allocations = 84676
bytes = 4133456
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003397533
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461256
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000981009
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82661
bytes = 3342720
compile_seconds = 0.0
samples = 3
seconds = 0.002222322

[datasets.adlittle.primal]
allocations = 85474
bytes = 4409712
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003545534
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607664
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.00111581
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.0501e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174104
compile_seconds = 0.0
samples = 3
seconds = 0.000125901

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 865552
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000800107
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000220902
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 729808
compile_seconds = 0.0
samples = 3
seconds = 0.000624

[datasets.afiro.primal]
allocations = 16963
bytes = 843360
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000728107
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000219402
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44704
compile_seconds = 0.0
samples = 3
seconds = 9.24e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214448
compile_seconds = 0.0
samples = 3
seconds = 0.0001734

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1290928
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000969302
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001772
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1182184
compile_seconds = 0.0
samples = 3
seconds = 0.000769801

[datasets.flugpl.primal]
allocations = 32031
bytes = 1335616
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000912603
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001827
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.74e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210216
compile_seconds = 0.0
samples = 3
seconds = 0.0001448

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11130080
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021603128
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877856
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000813401
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10676576
compile_seconds = 0.0
samples = 3
seconds = 0.020762527

[datasets.kb2.primal]
allocations = 231280
bytes = 11143888
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.024300531
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000644001
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111520
compile_seconds = 0.0
samples = 3
seconds = 0.0001038

[datasets.kb2.sparse]
allocations = 2836
bytes = 161568
compile_seconds = 0.0
samples = 3
seconds = 0.000118401

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 2.15e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3194208
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002084405
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000601002
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2849200
compile_seconds = 0.0
samples = 3
seconds = 0.001454504

[datasets.sc50a.primal]
allocations = 68520
bytes = 3146368
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002052305
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000498401
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.0e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299744
compile_seconds = 0.0
samples = 3
seconds = 0.000216001

[probes.cancel_fraction]
allocations = 33443
bytes = 1254536
compile_seconds = 0.0
samples = 3
seconds = 0.000630208

[probes.cancel_integer]
allocations = 32291
bytes = 1208632
compile_seconds = 0.0
samples = 3
seconds = 0.000594807

[probes.sum_fraction]
allocations = 33955
bytes = 1272008
compile_seconds = 0.0
samples = 3
seconds = 0.000690309

[probes.sum_integer]
allocations = 32803
bytes = 1228840
compile_seconds = 0.0
samples = 3
seconds = 0.000637608

[probes.unequal_denominator]
allocations = 34211
bytes = 1285656
compile_seconds = 0.0
samples = 3
seconds = 0.000701609

[probes.zero_constant]
allocations = 33056
bytes = 1242400
compile_seconds = 0.0
samples = 3
seconds = 0.000662308
