julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.adlittle.dual]
allocations = 84694
bytes = 4132576
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003579312
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461720
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000992003
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82679
bytes = 3343904
compile_seconds = 0.0
samples = 3
seconds = 0.002340808

[datasets.adlittle.primal]
allocations = 85492
bytes = 4409408
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003634812
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001158504
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.49e-5

[datasets.adlittle.sparse]
allocations = 2778
bytes = 174984
compile_seconds = 0.0
samples = 3
seconds = 0.0001061

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 863872
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000833003
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000224101
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 727248
compile_seconds = 0.0
samples = 3
seconds = 0.000611202

[datasets.afiro.primal]
allocations = 16963
bytes = 842112
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000768202
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000231201
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44560
compile_seconds = 0.0
samples = 3
seconds = 8.88e-5

[datasets.afiro.sparse]
allocations = 4900
bytes = 214112
compile_seconds = 0.0
samples = 3
seconds = 0.0002082

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.6e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1289344
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000900501
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000168
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1179832
compile_seconds = 0.0
samples = 3
seconds = 0.000719801

[datasets.flugpl.primal]
allocations = 32031
bytes = 1333904
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001009101
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001447
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.69e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209064
compile_seconds = 0.0
samples = 3
seconds = 0.0001399

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11127344
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02093292
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877888
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000797399
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10676176
compile_seconds = 0.0
samples = 3
seconds = 0.020867293

[datasets.kb2.primal]
allocations = 231280
bytes = 11141776
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020867319
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000639401
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111744
compile_seconds = 0.0
samples = 3
seconds = 9.02e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161328
compile_seconds = 0.0
samples = 3
seconds = 0.0001768

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.32e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3193808
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002031502
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000577901
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2847888
compile_seconds = 0.0
samples = 3
seconds = 0.001615202

[datasets.sc50a.primal]
allocations = 68520
bytes = 3146592
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002155002
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000508301
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.2e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298288
compile_seconds = 0.0
samples = 3
seconds = 0.0002028

[probes.cancellation]
allocations = 52677
bytes = 2029200
compile_seconds = 0.0
samples = 3
seconds = 0.0009661

[probes.fraction_negative]
allocations = 53829
bytes = 2063632
compile_seconds = 0.0
samples = 3
seconds = 0.0009856

[probes.fraction_positive]
allocations = 53829
bytes = 2063600
compile_seconds = 0.0
samples = 3
seconds = 0.0010936

[probes.integer_negative]
allocations = 52037
bytes = 1991024
compile_seconds = 0.0
samples = 3
seconds = 0.0010495

[probes.integer_positive]
allocations = 51525
bytes = 1974672
compile_seconds = 0.0
samples = 3
seconds = 0.0010582

[probes.unequal_denominator]
allocations = 54085
bytes = 2076976
compile_seconds = 0.0
samples = 3
seconds = 0.001034699
