julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4117480
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003237003
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000914901
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326744
compile_seconds = 0.0
samples = 3
seconds = 0.001753002

[datasets.adlittle.primal]
allocations = 85246
bytes = 4395080
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003402104
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607776
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001041201
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641800
compile_seconds = 0.0
samples = 3
seconds = 0.0003398

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.15e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 173896
compile_seconds = 0.0
samples = 3
seconds = 9.66e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 864232
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000712901
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002087
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 727992
compile_seconds = 0.0
samples = 3
seconds = 0.000599401

[datasets.afiro.primal]
allocations = 16938
bytes = 842264
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000695001
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001905
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92152
compile_seconds = 0.0
samples = 3
seconds = 8.75e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 44800
compile_seconds = 0.0
samples = 3
seconds = 6.76e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214800
compile_seconds = 0.0
samples = 3
seconds = 0.0001523

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 8.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1278920
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000853401
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000173
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169808
compile_seconds = 0.0
samples = 3
seconds = 0.0005945

[datasets.flugpl.primal]
allocations = 31811
bytes = 1323736
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000893301
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001987
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 121952
compile_seconds = 0.0
samples = 3
seconds = 8.7801e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 2.0e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209496
compile_seconds = 0.0
samples = 3
seconds = 0.0001237

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11093200
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02070462
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878336
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000790001
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10639872
compile_seconds = 0.0
samples = 3
seconds = 0.020209719

[datasets.kb2.primal]
allocations = 230563
bytes = 11106048
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.02041671
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006033
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454784
compile_seconds = 0.0
samples = 3
seconds = 0.000221301

[datasets.kb2.singleton]
allocations = 2060
bytes = 112160
compile_seconds = 0.0
samples = 3
seconds = 9.82e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161376
compile_seconds = 0.0
samples = 3
seconds = 0.000110801

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.46e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3192264
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001883601
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306320
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005761
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846792
compile_seconds = 0.0
samples = 3
seconds = 0.001427401

[datasets.sc50a.primal]
allocations = 68474
bytes = 3145192
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018896
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232248
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000530901
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221904
compile_seconds = 0.0
samples = 3
seconds = 0.0001395

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.44e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299216
compile_seconds = 0.0
samples = 3
seconds = 0.0001775

[probes.singleton_fraction_negative]
allocations = 27904
bytes = 1073144
compile_seconds = 0.0
samples = 3
seconds = 0.0004747

[probes.singleton_fraction_positive]
allocations = 27901
bytes = 1072480
compile_seconds = 0.0
samples = 3
seconds = 0.0004957

[probes.singleton_integer_negative]
allocations = 28032
bytes = 1075208
compile_seconds = 0.0
samples = 3
seconds = 0.0005393

[probes.singleton_integer_positive]
allocations = 28029
bytes = 1074080
compile_seconds = 0.0
samples = 3
seconds = 0.0005332

[probes.sparse_fraction_negative]
allocations = 43735
bytes = 1616192
compile_seconds = 0.0
samples = 3
seconds = 0.0007045

[probes.sparse_fraction_positive]
allocations = 43713
bytes = 1615424
compile_seconds = 0.0
samples = 3
seconds = 0.000785201

[probes.sparse_integer_negative]
allocations = 44311
bytes = 1639920
compile_seconds = 0.0
samples = 3
seconds = 0.0007444

[probes.sparse_integer_positive]
allocations = 44285
bytes = 1637728
compile_seconds = 0.0
samples = 3
seconds = 0.0008243

[probes.unequal_denominator]
allocations = 27837
bytes = 1073200
compile_seconds = 0.0
samples = 3
seconds = 0.0004983

[probes.zero_rhs]
allocations = 25661
bytes = 991232
compile_seconds = 0.0
samples = 3
seconds = 0.0004778
