julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.adlittle.dual]
allocations = 84694
bytes = 4132544
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003494304
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000868501
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82679
bytes = 3343792
compile_seconds = 0.0
samples = 3
seconds = 0.002010403

[datasets.adlittle.primal]
allocations = 85492
bytes = 4409648
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003684405
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001110202
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.69e-5

[datasets.adlittle.sparse]
allocations = 2778
bytes = 175304
compile_seconds = 0.0
samples = 3
seconds = 0.0001052

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 864128
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000799001
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002075
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 728784
compile_seconds = 0.0
samples = 3
seconds = 0.0006143

[datasets.afiro.primal]
allocations = 16963
bytes = 843104
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000787402
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000217601
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45232
compile_seconds = 0.0
samples = 3
seconds = 0.0001008

[datasets.afiro.sparse]
allocations = 4900
bytes = 214528
compile_seconds = 0.0
samples = 3
seconds = 0.0001607

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.8e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1290160
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000870601
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001615
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1180216
compile_seconds = 0.0
samples = 3
seconds = 0.0007238

[datasets.flugpl.primal]
allocations = 32031
bytes = 1334816
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000944401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001971
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.78e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209928
compile_seconds = 0.0
samples = 3
seconds = 0.0001111

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 9.8e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11128976
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.019814827
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878192
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000819001
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10675424
compile_seconds = 0.0
samples = 3
seconds = 0.019883627

[datasets.kb2.primal]
allocations = 231280
bytes = 11142624
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021288629
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000597201
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112624
compile_seconds = 0.0
samples = 3
seconds = 8.91e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161744
compile_seconds = 0.0
samples = 3
seconds = 0.000128201

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.76e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3193184
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002130902
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005691
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2847968
compile_seconds = 0.0
samples = 3
seconds = 0.001653802

[datasets.sc50a.primal]
allocations = 68520
bytes = 3145776
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002099002
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000519601
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.38e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299184
compile_seconds = 0.0
samples = 3
seconds = 0.000198

[probes.negative]
allocations = 52805
bytes = 2032208
compile_seconds = 0.0
samples = 3
seconds = 0.000964101

[probes.nonzero_cost]
allocations = 54085
bytes = 2077568
compile_seconds = 0.0
samples = 3
seconds = 0.001009901

[probes.positive]
allocations = 52805
bytes = 2030432
compile_seconds = 0.0
samples = 3
seconds = 0.0010432

[probes.unit_negative]
allocations = 51013
bytes = 1959984
compile_seconds = 0.0
samples = 3
seconds = 0.000955001

[probes.unit_positive]
allocations = 50501
bytes = 1945824
compile_seconds = 0.0
samples = 3
seconds = 0.001003801

[probes.zero_ratio]
allocations = 45253
bytes = 1777600
compile_seconds = 0.0
samples = 3
seconds = 0.0008677
