julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.adlittle.dual]
allocations = 83480
bytes = 4081032
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003575404
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461320
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000996201
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81465
bytes = 3291272
compile_seconds = 0.0
samples = 3
seconds = 0.002224002

[datasets.adlittle.primal]
allocations = 84278
bytes = 4358632
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003694003
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001233402
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642488
compile_seconds = 0.0
samples = 3
seconds = 0.0004205

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.37e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 157592
compile_seconds = 0.0
samples = 3
seconds = 0.0001369

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.afiro.dual]
allocations = 16496
bytes = 843816
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000755701
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002201
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15681
bytes = 708392
compile_seconds = 0.0
samples = 3
seconds = 0.000802901

[datasets.afiro.primal]
allocations = 16402
bytes = 822104
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008397
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000238001
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92776
compile_seconds = 0.0
samples = 3
seconds = 0.0001325

[datasets.afiro.singleton]
allocations = 747
bytes = 41632
compile_seconds = 0.0
samples = 3
seconds = 6.96e-5

[datasets.afiro.sparse]
allocations = 4202
bytes = 188496
compile_seconds = 0.0
samples = 3
seconds = 0.0001724

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6

[datasets.flugpl.dual]
allocations = 29289
bytes = 1196472
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000909901
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001175
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 28618
bytes = 1086496
compile_seconds = 0.0
samples = 3
seconds = 0.0007547

[datasets.flugpl.primal]
allocations = 29638
bytes = 1241096
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001021401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001897
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123392
compile_seconds = 0.0
samples = 3
seconds = 0.000107

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.flugpl.sparse]
allocations = 4841
bytes = 181360
compile_seconds = 0.0
samples = 3
seconds = 0.0001307

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.kb2.dual]
allocations = 229210
bytes = 11049032
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02111732
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000873201
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 228008
bytes = 10595096
compile_seconds = 0.0
samples = 3
seconds = 0.02056492

[datasets.kb2.primal]
allocations = 229377
bytes = 11062392
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021455721
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006429
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 455360
compile_seconds = 0.0
samples = 3
seconds = 0.000250401

[datasets.kb2.singleton]
allocations = 1915
bytes = 106008
compile_seconds = 0.0
samples = 3
seconds = 9.3101e-5

[datasets.kb2.sparse]
allocations = 2308
bytes = 140232
compile_seconds = 0.0
samples = 3
seconds = 0.0001019

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.91e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.sc50a.dual]
allocations = 67465
bytes = 3151768
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002231502
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306256
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006111
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66393
bytes = 2806248
compile_seconds = 0.0
samples = 3
seconds = 0.001642801

[datasets.sc50a.primal]
allocations = 67410
bytes = 3104760
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002337002
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005107
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222624
compile_seconds = 0.0
samples = 3
seconds = 0.0001477

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.11e-5

[datasets.sc50a.sparse]
allocations = 6202
bytes = 284112
compile_seconds = 0.0
samples = 3
seconds = 0.0002034

[probes.free_pivot]
allocations = 29623
bytes = 1196616
compile_seconds = 0.0
samples = 3
seconds = 0.000694501

[probes.lower_zero]
allocations = 54853
bytes = 2078400
compile_seconds = 0.0
samples = 3
seconds = 0.001150402

[probes.negative_pivot]
allocations = 40119
bytes = 1525672
compile_seconds = 0.0
samples = 3
seconds = 0.000880101

[probes.nonzero]
allocations = 59077
bytes = 2205008
compile_seconds = 0.0
samples = 3
seconds = 0.001051302

[probes.positive_pivot]
allocations = 40119
bytes = 1523912
compile_seconds = 0.0
samples = 3
seconds = 0.000784501

[probes.upper_zero]
allocations = 54853
bytes = 2078112
compile_seconds = 0.0
samples = 3
seconds = 0.000989502
