julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.adlittle.dual]
allocations = 83266
bytes = 4074048
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031314
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461032
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008872
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81251
bytes = 3284128
compile_seconds = 0.0
samples = 3
seconds = 0.002011301

[datasets.adlittle.primal]
allocations = 84064
bytes = 4350912
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034097
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607216
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001072
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641928
compile_seconds = 0.0
samples = 3
seconds = 0.0003491

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.47e-5

[datasets.adlittle.sparse]
allocations = 2282
bytes = 154808
compile_seconds = 0.0
samples = 3
seconds = 0.0001062

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 16441
bytes = 841304
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007201
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002416
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15626
bytes = 705256
compile_seconds = 0.0
samples = 3
seconds = 0.0005284

[datasets.afiro.primal]
allocations = 16347
bytes = 819464
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006898
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002057
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92440
compile_seconds = 0.0
samples = 3
seconds = 9.25e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40432
compile_seconds = 0.0
samples = 3
seconds = 7.2e-5

[datasets.afiro.sparse]
allocations = 4116
bytes = 184872
compile_seconds = 0.0
samples = 3
seconds = 0.0001568

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.flugpl.dual]
allocations = 28597
bytes = 1167488
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008115
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001321
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27926
bytes = 1058840
compile_seconds = 0.0
samples = 3
seconds = 0.0006091

[datasets.flugpl.primal]
allocations = 28946
bytes = 1212160
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000780101
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001966
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123168
compile_seconds = 0.0
samples = 3
seconds = 8.96e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.57e-5

[datasets.flugpl.sparse]
allocations = 4646
bytes = 173176
compile_seconds = 0.0
samples = 3
seconds = 0.0001016

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 228665
bytes = 11029600
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0200847
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007782
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227463
bytes = 10576624
compile_seconds = 0.0
samples = 3
seconds = 0.0197295

[datasets.kb2.primal]
allocations = 228832
bytes = 11041920
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0207454
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006894
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454928
compile_seconds = 0.0
samples = 3
seconds = 0.0002595

[datasets.kb2.singleton]
allocations = 1915
bytes = 105240
compile_seconds = 0.0
samples = 3
seconds = 0.0001168

[datasets.kb2.sparse]
allocations = 2207
bytes = 135256
compile_seconds = 0.0
samples = 3
seconds = 9.96e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.51e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.sc50a.dual]
allocations = 67169
bytes = 3142824
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018358
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306272
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005663
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66097
bytes = 2796504
compile_seconds = 0.0
samples = 3
seconds = 0.0013678

[datasets.sc50a.primal]
allocations = 67114
bytes = 3095288
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018559
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004562
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222752
compile_seconds = 0.0
samples = 3
seconds = 0.000153

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.8e-5

[datasets.sc50a.sparse]
allocations = 6081
bytes = 280080
compile_seconds = 0.0
samples = 3
seconds = 0.0001874

[probes.both]
allocations = 45879
bytes = 1698328
compile_seconds = 0.0
samples = 3
seconds = 0.0009608

[probes.free_pivot]
allocations = 29623
bytes = 1195768
compile_seconds = 0.0
samples = 3
seconds = 0.0006302

[probes.lower_negative]
allocations = 39351
bytes = 1487000
compile_seconds = 0.0
samples = 3
seconds = 0.0008249

[probes.lower_positive]
allocations = 39735
bytes = 1509608
compile_seconds = 0.0
samples = 3
seconds = 0.0008613

[probes.upper_negative]
allocations = 39735
bytes = 1511560
compile_seconds = 0.0
samples = 3
seconds = 0.0008354

[probes.upper_positive]
allocations = 39351
bytes = 1487208
compile_seconds = 0.0
samples = 3
seconds = 0.0008463
