julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4115928
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003316807
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461272
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001089502
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326904
compile_seconds = 0.0
samples = 3
seconds = 0.002267805

[datasets.adlittle.primal]
allocations = 85246
bytes = 4392024
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003759107
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607376
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001154302
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641064
compile_seconds = 0.0
samples = 3
seconds = 0.000422801

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.48e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 173656
compile_seconds = 0.0
samples = 3
seconds = 0.0001153

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 863864
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000832202
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000230501
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 727960
compile_seconds = 0.0
samples = 3
seconds = 0.000547001

[datasets.afiro.primal]
allocations = 16938
bytes = 841608
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000736801
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000196
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91768
compile_seconds = 0.0
samples = 3
seconds = 8.45e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 44704
compile_seconds = 0.0
samples = 3
seconds = 8.29e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214208
compile_seconds = 0.0
samples = 3
seconds = 0.0001895

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1278664
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000941301
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001555
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170160
compile_seconds = 0.0
samples = 3
seconds = 0.000691701

[datasets.flugpl.primal]
allocations = 31811
bytes = 1322952
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001017501
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001999
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122160
compile_seconds = 0.0
samples = 3
seconds = 0.0001005

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.75e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209512
compile_seconds = 0.0
samples = 3
seconds = 0.0001504

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11092896
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022317223
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878656
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000857901
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10639664
compile_seconds = 0.0
samples = 3
seconds = 0.02007974

[datasets.kb2.primal]
allocations = 230563
bytes = 11106400
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022136223
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000685101
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454112
compile_seconds = 0.0
samples = 3
seconds = 0.000250701

[datasets.kb2.singleton]
allocations = 2060
bytes = 112096
compile_seconds = 0.0
samples = 3
seconds = 8.98e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161040
compile_seconds = 0.0
samples = 3
seconds = 0.000110201

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.78e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191480
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002205602
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000541301
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846424
compile_seconds = 0.0
samples = 3
seconds = 0.001610602

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144168
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002582303
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000554901
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222000
compile_seconds = 0.0
samples = 3
seconds = 0.0001517

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.61e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299312
compile_seconds = 0.0
samples = 3
seconds = 0.0001579

[probes.singleton_fraction_negative]
allocations = 27648
bytes = 1049864
compile_seconds = 0.0
samples = 3
seconds = 0.0004845

[probes.singleton_fraction_positive]
allocations = 27645
bytes = 1050096
compile_seconds = 0.0
samples = 3
seconds = 0.0005204

[probes.singleton_integer_negative]
allocations = 27520
bytes = 1047880
compile_seconds = 0.0
samples = 3
seconds = 0.0005948

[probes.singleton_integer_positive]
allocations = 27517
bytes = 1046688
compile_seconds = 0.0
samples = 3
seconds = 0.000736101

[probes.sparse_fraction_negative]
allocations = 43479
bytes = 1593520
compile_seconds = 0.0
samples = 3
seconds = 0.0008169

[probes.sparse_fraction_positive]
allocations = 43457
bytes = 1592944
compile_seconds = 0.0
samples = 3
seconds = 0.0008271

[probes.sparse_integer_negative]
allocations = 43799
bytes = 1612912
compile_seconds = 0.0
samples = 3
seconds = 0.0009327

[probes.sparse_integer_positive]
allocations = 43773
bytes = 1610576
compile_seconds = 0.0
samples = 3
seconds = 0.0009903

[probes.unequal_denominator]
allocations = 27837
bytes = 1072512
compile_seconds = 0.0
samples = 3
seconds = 0.000487

[probes.zero_rhs]
allocations = 25661
bytes = 990512
compile_seconds = 0.0
samples = 3
seconds = 0.0004806
