julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 83431
bytes = 4078048
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003688901
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461448
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000987601
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81416
bytes = 3287744
compile_seconds = 0.0
samples = 3
seconds = 0.002389901

[datasets.adlittle.primal]
allocations = 84229
bytes = 4354768
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004044302
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607728
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011449
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640904
compile_seconds = 0.0
samples = 3
seconds = 0.0004471

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.16e-5

[datasets.adlittle.sparse]
allocations = 2336
bytes = 156728
compile_seconds = 0.0
samples = 3
seconds = 0.000159301

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.afiro.dual]
allocations = 16456
bytes = 840712
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000782301
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002074
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15641
bytes = 706328
compile_seconds = 0.0
samples = 3
seconds = 0.000690501

[datasets.afiro.primal]
allocations = 16362
bytes = 819400
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008283
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000208001
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92616
compile_seconds = 0.0
samples = 3
seconds = 0.0001174

[datasets.afiro.singleton]
allocations = 747
bytes = 41248
compile_seconds = 0.0
samples = 3
seconds = 9.15e-5

[datasets.afiro.sparse]
allocations = 4155
bytes = 186056
compile_seconds = 0.0
samples = 3
seconds = 0.0001929

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 28597
bytes = 1166880
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001069101
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001762
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27926
bytes = 1057304
compile_seconds = 0.0
samples = 3
seconds = 0.0008728

[datasets.flugpl.primal]
allocations = 28946
bytes = 1211280
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010804
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002021
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122656
compile_seconds = 0.0
samples = 3
seconds = 0.0001186

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.73e-5

[datasets.flugpl.sparse]
allocations = 4667
bytes = 172328
compile_seconds = 0.0
samples = 3
seconds = 0.0001697

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.kb2.dual]
allocations = 229107
bytes = 11043792
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.023044505
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008672
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227905
bytes = 10590480
compile_seconds = 0.0
samples = 3
seconds = 0.022607604

[datasets.kb2.primal]
allocations = 229274
bytes = 11057680
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022277004
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006681
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453856
compile_seconds = 0.0
samples = 3
seconds = 0.000318

[datasets.kb2.singleton]
allocations = 1915
bytes = 105368
compile_seconds = 0.0
samples = 3
seconds = 8.95e-5

[datasets.kb2.sparse]
allocations = 2257
bytes = 137192
compile_seconds = 0.0
samples = 3
seconds = 0.0001293

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.sc50a.dual]
allocations = 67347
bytes = 3145720
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022742
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306176
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006383
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66275
bytes = 2800088
compile_seconds = 0.0
samples = 3
seconds = 0.0019193

[datasets.sc50a.primal]
allocations = 67292
bytes = 3098408
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002191801
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000539301
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221072
compile_seconds = 0.0
samples = 3
seconds = 0.000204

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.38e-5

[datasets.sc50a.sparse]
allocations = 6164
bytes = 281216
compile_seconds = 0.0
samples = 3
seconds = 0.0002397

[probes.negative]
allocations = 42295
bytes = 1589064
compile_seconds = 0.0
samples = 3
seconds = 0.0011073

[probes.positive]
allocations = 42295
bytes = 1587304
compile_seconds = 0.0
samples = 3
seconds = 0.0011175

[probes.unit_negative]
allocations = 41527
bytes = 1558280
compile_seconds = 0.0
samples = 3
seconds = 0.0011245

[probes.unit_positive]
allocations = 41015
bytes = 1543912
compile_seconds = 0.0
samples = 3
seconds = 0.0010052

[probes.upper_free]
allocations = 40631
bytes = 1539080
compile_seconds = 0.0
samples = 3
seconds = 0.0012098

[probes.variable]
allocations = 45879
bytes = 1698152
compile_seconds = 0.0
samples = 3
seconds = 0.0011196
