julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4048232
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032576
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461640
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009317
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3258984
compile_seconds = 0.0
samples = 3
seconds = 0.0023437

[datasets.adlittle.primal]
allocations = 83190
bytes = 4324568
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036743
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607232
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010645
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641080
compile_seconds = 0.0
samples = 3
seconds = 0.000424

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 4.94e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 127752
compile_seconds = 0.0
samples = 3
seconds = 9.04e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 834552
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006967
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001762
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 699048
compile_seconds = 0.0
samples = 3
seconds = 0.000621501

[datasets.afiro.primal]
allocations = 16131
bytes = 812600
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000662
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001741
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92904
compile_seconds = 0.0
samples = 3
seconds = 8.02e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40800
compile_seconds = 0.0
samples = 3
seconds = 6.05e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 174400
compile_seconds = 0.0
samples = 3
seconds = 0.0001259

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 26435
bytes = 1100384
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008058
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001264
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25764
bytes = 990360
compile_seconds = 0.0
samples = 3
seconds = 0.0006386

[datasets.flugpl.primal]
allocations = 26784
bytes = 1144688
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007831
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001634
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123632
compile_seconds = 0.0
samples = 3
seconds = 8.07e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.3e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 150776
compile_seconds = 0.0
samples = 3
seconds = 0.0001028

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11014920
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020338801
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877936
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008091
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10561464
compile_seconds = 0.0
samples = 3
seconds = 0.020795701

[datasets.kb2.primal]
allocations = 228386
bytes = 11028584
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020352401
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260896
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005481
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454080
compile_seconds = 0.0
samples = 3
seconds = 0.0002556

[datasets.kb2.singleton]
allocations = 1915
bytes = 105176
compile_seconds = 0.0
samples = 3
seconds = 6.63e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127624
compile_seconds = 0.0
samples = 3
seconds = 0.0001061

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.45e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3108480
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001962
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005319
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2762432
compile_seconds = 0.0
samples = 3
seconds = 0.0014425

[datasets.sc50a.primal]
allocations = 65958
bytes = 3060960
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021863
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004555
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221648
compile_seconds = 0.0
samples = 3
seconds = 0.0001377

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.63e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 262720
compile_seconds = 0.0
samples = 3
seconds = 0.0001632

[probes.cancelled]
allocations = 28599
bytes = 1158440
compile_seconds = 0.0
samples = 3
seconds = 0.0006198

[probes.negative]
allocations = 29623
bytes = 1196888
compile_seconds = 0.0
samples = 3
seconds = 0.0007066

[probes.positive]
allocations = 29623
bytes = 1195240
compile_seconds = 0.0
samples = 3
seconds = 0.0007097

[probes.unequal]
allocations = 34231
bytes = 1370136
compile_seconds = 0.0
samples = 3
seconds = 0.0007811

[probes.zero_bound]
allocations = 27191
bytes = 1113672
compile_seconds = 0.0
samples = 3
seconds = 0.0006471

[probes.zero_shift]
allocations = 23479
bytes = 969880
compile_seconds = 0.0
samples = 3
seconds = 0.0005492
