julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 83624
bytes = 4085144
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036018
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461944
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010102
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81609
bytes = 3294248
compile_seconds = 0.0
samples = 3
seconds = 0.0025023

[datasets.adlittle.primal]
allocations = 84422
bytes = 4361448
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037769
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607776
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011696
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641304
compile_seconds = 0.0
samples = 3
seconds = 0.0004145

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.66e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 157032
compile_seconds = 0.0
samples = 3
seconds = 0.0001316

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.afiro.dual]
allocations = 16528
bytes = 843768
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007835
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001926
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15713
bytes = 708920
compile_seconds = 0.0
samples = 3
seconds = 0.0005788

[datasets.afiro.primal]
allocations = 16434
bytes = 822680
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007198
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002252
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92440
compile_seconds = 0.0
samples = 3
seconds = 0.0001031

[datasets.afiro.singleton]
allocations = 747
bytes = 40752
compile_seconds = 0.0
samples = 3
seconds = 9.03e-5

[datasets.afiro.sparse]
allocations = 4243
bytes = 190000
compile_seconds = 0.0
samples = 3
seconds = 0.0001445

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.4e-6

[datasets.flugpl.dual]
allocations = 30825
bytes = 1254760
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009123
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001536
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30154
bytes = 1145920
compile_seconds = 0.0
samples = 3
seconds = 0.0007517

[datasets.flugpl.primal]
allocations = 31174
bytes = 1299448
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009349
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002014
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123680
compile_seconds = 0.0
samples = 3
seconds = 0.000109

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.87e-5

[datasets.flugpl.sparse]
allocations = 5306
bytes = 199384
compile_seconds = 0.0
samples = 3
seconds = 0.0001302

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 229387
bytes = 11056072
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0216653
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008408
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 228185
bytes = 10600888
compile_seconds = 0.0
samples = 3
seconds = 0.0199469

[datasets.kb2.primal]
allocations = 229554
bytes = 11069320
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0216004
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006382
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454512
compile_seconds = 0.0
samples = 3
seconds = 0.0002804

[datasets.kb2.singleton]
allocations = 1915
bytes = 105848
compile_seconds = 0.0
samples = 3
seconds = 8.62e-5

[datasets.kb2.sparse]
allocations = 2380
bytes = 143280
compile_seconds = 0.0
samples = 3
seconds = 0.0001289

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.67e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 67569
bytes = 3154536
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021935
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000567
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66497
bytes = 2809048
compile_seconds = 0.0
samples = 3
seconds = 0.0016107

[datasets.sc50a.primal]
allocations = 67514
bytes = 3107032
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020544
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004986
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222320
compile_seconds = 0.0
samples = 3
seconds = 0.0001643

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.41e-5

[datasets.sc50a.sparse]
allocations = 6234
bytes = 285056
compile_seconds = 0.0
samples = 3
seconds = 0.0001773

[probes.fixed_negative]
allocations = 42423
bytes = 1611288
compile_seconds = 0.0
samples = 3
seconds = 0.0008743

[probes.fixed_positive]
allocations = 42423
bytes = 1609608
compile_seconds = 0.0
samples = 3
seconds = 0.0008529

[probes.free_pivot]
allocations = 29623
bytes = 1195912
compile_seconds = 0.0
samples = 3
seconds = 0.0006423

[probes.lower_zero]
allocations = 57157
bytes = 2164192
compile_seconds = 0.0
samples = 3
seconds = 0.0011052

[probes.nonzero_bounds]
allocations = 62533
bytes = 2334288
compile_seconds = 0.0
samples = 3
seconds = 0.0011105

[probes.upper_zero]
allocations = 57157
bytes = 2164384
compile_seconds = 0.0
samples = 3
seconds = 0.001105
