julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 83570
bytes = 4083160
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003392301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461224
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010117
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81555
bytes = 3293144
compile_seconds = 0.0
samples = 3
seconds = 0.002359701

[datasets.adlittle.primal]
allocations = 84368
bytes = 4359720
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038449
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607344
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011212
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640488
compile_seconds = 0.0
samples = 3
seconds = 0.0004144

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.73e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 156392
compile_seconds = 0.0
samples = 3
seconds = 0.000139

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 16528
bytes = 843336
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008568
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002182
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15713
bytes = 708200
compile_seconds = 0.0
samples = 3
seconds = 0.0006063

[datasets.afiro.primal]
allocations = 16434
bytes = 821832
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008276
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002194
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91592
compile_seconds = 0.0
samples = 3
seconds = 0.0001113

[datasets.afiro.singleton]
allocations = 747
bytes = 40688
compile_seconds = 0.0
samples = 3
seconds = 5.49e-5

[datasets.afiro.sparse]
allocations = 4243
bytes = 188992
compile_seconds = 0.0
samples = 3
seconds = 0.0001706

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 30015
bytes = 1223688
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.00092
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001593
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 29344
bytes = 1114096
compile_seconds = 0.0
samples = 3
seconds = 0.0007134

[datasets.flugpl.primal]
allocations = 30364
bytes = 1268264
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009665
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002009
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122288
compile_seconds = 0.0
samples = 3
seconds = 0.0001052

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.85e-5

[datasets.flugpl.sparse]
allocations = 5063
bytes = 188984
compile_seconds = 0.0
samples = 3
seconds = 0.0001311

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.dual]
allocations = 229333
bytes = 11052824
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021557902
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009005
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 228131
bytes = 10600056
compile_seconds = 0.0
samples = 3
seconds = 0.020202602

[datasets.kb2.primal]
allocations = 229500
bytes = 11065336
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021291102
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006341
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453584
compile_seconds = 0.0
samples = 3
seconds = 0.0002998

[datasets.kb2.singleton]
allocations = 1915
bytes = 105112
compile_seconds = 0.0
samples = 3
seconds = 8.74e-5

[datasets.kb2.sparse]
allocations = 2371
bytes = 142256
compile_seconds = 0.0
samples = 3
seconds = 0.0001197

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.73e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 67569
bytes = 3154936
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002189601
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306304
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005862
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66497
bytes = 2809688
compile_seconds = 0.0
samples = 3
seconds = 0.0016095

[datasets.sc50a.primal]
allocations = 67514
bytes = 3107784
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022048
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005186
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221232
compile_seconds = 0.0
samples = 3
seconds = 0.0001604

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.61e-5

[datasets.sc50a.sparse]
allocations = 6234
bytes = 284080
compile_seconds = 0.0
samples = 3
seconds = 0.0002006

[probes.free_pivot]
allocations = 29623
bytes = 1196168
compile_seconds = 0.0
samples = 3
seconds = 0.000689

[probes.lower_zero]
allocations = 56005
bytes = 2120160
compile_seconds = 0.0
samples = 3
seconds = 0.0010848

[probes.negative]
allocations = 60229
bytes = 2247184
compile_seconds = 0.0
samples = 3
seconds = 0.0011572

[probes.positive]
allocations = 60229
bytes = 2244112
compile_seconds = 0.0
samples = 3
seconds = 0.0011404

[probes.upper_zero]
allocations = 56005
bytes = 2120096
compile_seconds = 0.0
samples = 3
seconds = 0.0011452

[probes.zero_bounds]
allocations = 42423
bytes = 1611224
compile_seconds = 0.0
samples = 3
seconds = 0.0008384
