julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84962
bytes = 4144512
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033298
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461160
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009229
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82947
bytes = 3354224
compile_seconds = 0.0
samples = 3
seconds = 0.0020037

[datasets.adlittle.primal]
allocations = 85760
bytes = 4421856
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035418
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010906
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.85e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 176160
compile_seconds = 0.0
samples = 3
seconds = 0.0001283

[datasets.afiro.dual]
allocations = 17306
bytes = 874928
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000707
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16491
bytes = 739088
compile_seconds = 0.0
samples = 3
seconds = 0.000567

[datasets.afiro.primal]
allocations = 17212
bytes = 852288
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006636
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002121
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44704
compile_seconds = 0.0
samples = 3
seconds = 9.24e-5

[datasets.afiro.sparse]
allocations = 5241
bytes = 228528
compile_seconds = 0.0
samples = 3
seconds = 0.0001753

[datasets.flugpl.dual]
allocations = 32286
bytes = 1314216
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009038
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001504
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1204560
compile_seconds = 0.0
samples = 3
seconds = 0.0006996

[datasets.flugpl.primal]
allocations = 32635
bytes = 1358792
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010963
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001688
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.18e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 215976
compile_seconds = 0.0
samples = 3
seconds = 0.0001351

[datasets.kb2.dual]
allocations = 231256
bytes = 11136600
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0208347
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878480
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008695
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230054
bytes = 10681752
compile_seconds = 0.0
samples = 3
seconds = 0.0199741

[datasets.kb2.primal]
allocations = 231423
bytes = 11149384
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0201913
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005795
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111936
compile_seconds = 0.0
samples = 3
seconds = 0.000119

[datasets.kb2.sparse]
allocations = 2903
bytes = 162928
compile_seconds = 0.0
samples = 3
seconds = 0.000123

[datasets.sc50a.dual]
allocations = 69213
bytes = 3221480
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020697
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005906
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 68141
bytes = 2875848
compile_seconds = 0.0
samples = 3
seconds = 0.0015552

[datasets.sc50a.primal]
allocations = 69158
bytes = 3174856
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021113
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005106
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.sc50a.sparse]
allocations = 7011
bytes = 314368
compile_seconds = 0.0
samples = 3
seconds = 0.0002048

[probes.negative_negative]
allocations = 46149
bytes = 1804592
compile_seconds = 0.0
samples = 3
seconds = 0.0008714

[probes.negative_positive]
allocations = 46149
bytes = 1804944
compile_seconds = 0.0
samples = 3
seconds = 0.0008481

[probes.nonzero_old]
allocations = 46661
bytes = 1820176
compile_seconds = 0.0
samples = 3
seconds = 0.0008775

[probes.positive_negative]
allocations = 46149
bytes = 1804704
compile_seconds = 0.0
samples = 3
seconds = 0.0008689

[probes.positive_positive]
allocations = 46149
bytes = 1801680
compile_seconds = 0.0
samples = 3
seconds = 0.0008987

[probes.zero_multiplier]
allocations = 35001
bytes = 1397000
compile_seconds = 0.0
samples = 3
seconds = 0.0006631
