julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4115496
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035767
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461320
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001001
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3327224
compile_seconds = 0.0
samples = 3
seconds = 0.0019727

[datasets.adlittle.primal]
allocations = 85246
bytes = 4391928
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003490001
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001132501
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640104
compile_seconds = 0.0
samples = 3
seconds = 0.0003988

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.62e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 173560
compile_seconds = 0.0
samples = 3
seconds = 0.0001281

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 862728
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009009
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001641
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 727080
compile_seconds = 0.0
samples = 3
seconds = 0.0007081

[datasets.afiro.primal]
allocations = 16938
bytes = 840632
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007049
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000248301
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92504
compile_seconds = 0.0
samples = 3
seconds = 0.0001421

[datasets.afiro.singleton]
allocations = 843
bytes = 45152
compile_seconds = 0.0
samples = 3
seconds = 7.35e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213808
compile_seconds = 0.0
samples = 3
seconds = 0.0001704

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.6e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1278616
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010095
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001274
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169088
compile_seconds = 0.0
samples = 3
seconds = 0.0007895

[datasets.flugpl.primal]
allocations = 31811
bytes = 1323208
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010179
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000188
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 121952
compile_seconds = 0.0
samples = 3
seconds = 0.0001109

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.43e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209336
compile_seconds = 0.0
samples = 3
seconds = 0.000150901

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11093264
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020788205
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000903801
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10639152
compile_seconds = 0.0
samples = 3
seconds = 0.020180205

[datasets.kb2.primal]
allocations = 230563
bytes = 11106080
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020675006
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006692
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453456
compile_seconds = 0.0
samples = 3
seconds = 0.0002624

[datasets.kb2.singleton]
allocations = 2060
bytes = 112208
compile_seconds = 0.0
samples = 3
seconds = 9.46e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161008
compile_seconds = 0.0
samples = 3
seconds = 0.0001038

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.75e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191960
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002113701
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306288
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006418
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2845880
compile_seconds = 0.0
samples = 3
seconds = 0.001678701

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144632
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020851
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004964
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221440
compile_seconds = 0.0
samples = 3
seconds = 0.000187101

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.77e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298768
compile_seconds = 0.0
samples = 3
seconds = 0.0002245

[probes.fraction_negative]
allocations = 44741
bytes = 1740240
compile_seconds = 0.0
samples = 3
seconds = 0.0010033

[probes.fraction_positive]
allocations = 44741
bytes = 1740080
compile_seconds = 0.0
samples = 3
seconds = 0.0009235

[probes.integer_negative]
allocations = 44229
bytes = 1713056
compile_seconds = 0.0
samples = 3
seconds = 0.0010759

[probes.integer_positive]
allocations = 44229
bytes = 1711248
compile_seconds = 0.0
samples = 3
seconds = 0.0010347

[probes.unequal_denominator]
allocations = 44997
bytes = 1747248
compile_seconds = 0.0
samples = 3
seconds = 0.0009983

[probes.unit_pivot]
allocations = 42437
bytes = 1647088
compile_seconds = 0.0
samples = 3
seconds = 0.0008595
