julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85366
bytes = 4158504
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003734
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461256
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001025
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83351
bytes = 3368984
compile_seconds = 0.0
samples = 3
seconds = 0.0022787

[datasets.adlittle.primal]
allocations = 86164
bytes = 4435368
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039321
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012195
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 7.82e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 185856
compile_seconds = 0.0
samples = 3
seconds = 0.0001449

[datasets.afiro.dual]
allocations = 18263
bytes = 911088
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008306
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002189
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 775888
compile_seconds = 0.0
samples = 3
seconds = 0.0006252

[datasets.afiro.primal]
allocations = 18169
bytes = 888672
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007717
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002251
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 45744
compile_seconds = 0.0
samples = 3
seconds = 0.0001037

[datasets.afiro.sparse]
allocations = 6312
bytes = 269616
compile_seconds = 0.0
samples = 3
seconds = 0.0001761

[datasets.flugpl.dual]
allocations = 32526
bytes = 1324368
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009706
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001703
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31855
bytes = 1214312
compile_seconds = 0.0
samples = 3
seconds = 0.0008057

[datasets.flugpl.primal]
allocations = 32875
bytes = 1369168
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010208
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001718
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.17e-5

[datasets.flugpl.sparse]
allocations = 5852
bytes = 219392
compile_seconds = 0.0
samples = 3
seconds = 0.0001726

[datasets.kb2.dual]
allocations = 232882
bytes = 11195864
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0212451
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878224
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008911
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10742920
compile_seconds = 0.0
samples = 3
seconds = 0.020463

[datasets.kb2.primal]
allocations = 233049
bytes = 11209720
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0215881
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006107
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 135632
compile_seconds = 0.0
samples = 3
seconds = 9.77e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 198792
compile_seconds = 0.0
samples = 3
seconds = 0.0001118

[datasets.sc50a.dual]
allocations = 72627
bytes = 3355832
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023901
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006101
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3009304
compile_seconds = 0.0
samples = 3
seconds = 0.0017065

[datasets.sc50a.primal]
allocations = 72572
bytes = 3308344
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022484
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005403
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.54e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 392872
compile_seconds = 0.0
samples = 3
seconds = 0.0002306

[probes.free]
allocations = 17146
bytes = 672664
compile_seconds = 0.0
samples = 3
seconds = 0.0003824

[probes.singleton_negative]
allocations = 22909
bytes = 889040
compile_seconds = 0.0
samples = 3
seconds = 0.0005064

[probes.singleton_positive]
allocations = 22906
bytes = 886840
compile_seconds = 0.0
samples = 3
seconds = 0.0004585

[probes.sparse_negative]
allocations = 41684
bytes = 1557752
compile_seconds = 0.0
samples = 3
seconds = 0.000804999

[probes.sparse_positive]
allocations = 41678
bytes = 1556328
compile_seconds = 0.0
samples = 3
seconds = 0.0008174

[probes.unequal]
allocations = 29178
bytes = 1120792
compile_seconds = 0.0
samples = 3
seconds = 0.000603
