julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85688
bytes = 4171896
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003228601
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461080
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008746
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83673
bytes = 3382520
compile_seconds = 0.0
samples = 3
seconds = 0.0022223

[datasets.adlittle.primal]
allocations = 86486
bytes = 4448728
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003532001
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607664
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001036801
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 7.7e-5

[datasets.adlittle.sparse]
allocations = 3267
bytes = 193056
compile_seconds = 0.0
samples = 3
seconds = 0.0001301

[datasets.afiro.dual]
allocations = 18436
bytes = 919168
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007892
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001888
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17621
bytes = 783104
compile_seconds = 0.0
samples = 3
seconds = 0.0005779

[datasets.afiro.primal]
allocations = 18342
bytes = 896336
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006854
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121744
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001934
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 45568
compile_seconds = 0.0
samples = 3
seconds = 8.22e-5

[datasets.afiro.sparse]
allocations = 6386
bytes = 273552
compile_seconds = 0.0
samples = 3
seconds = 0.0001964

[datasets.flugpl.dual]
allocations = 33810
bytes = 1374848
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009175
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001583
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33139
bytes = 1265496
compile_seconds = 0.0
samples = 3
seconds = 0.0007282

[datasets.flugpl.primal]
allocations = 34159
bytes = 1419568
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000949
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001834
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.flugpl.sparse]
allocations = 6248
bytes = 235944
compile_seconds = 0.0
samples = 3
seconds = 0.0001393

[datasets.kb2.dual]
allocations = 233293
bytes = 11211832
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020391303
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008398
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 232091
bytes = 10757608
compile_seconds = 0.0
samples = 3
seconds = 0.019812903

[datasets.kb2.primal]
allocations = 233460
bytes = 11225976
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020693303
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006061
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 148520
compile_seconds = 0.0
samples = 3
seconds = 9.71e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197784
compile_seconds = 0.0
samples = 3
seconds = 0.0001242

[datasets.sc50a.dual]
allocations = 73155
bytes = 3375992
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002110501
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.00059
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72083
bytes = 3029000
compile_seconds = 0.0
samples = 3
seconds = 0.0015945

[datasets.sc50a.primal]
allocations = 73100
bytes = 3328488
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002007
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005078
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.32e-5

[datasets.sc50a.sparse]
allocations = 9239
bytes = 403848
compile_seconds = 0.0
samples = 3
seconds = 0.0002094

[probes.free]
allocations = 17786
bytes = 689368
compile_seconds = 0.0
samples = 3
seconds = 0.0003323

[probes.nonunit]
allocations = 29178
bytes = 1120824
compile_seconds = 0.0
samples = 3
seconds = 0.0005193

[probes.singleton_negative]
allocations = 29309
bytes = 1121808
compile_seconds = 0.0
samples = 3
seconds = 0.0005311

[probes.singleton_positive]
allocations = 29306
bytes = 1119976
compile_seconds = 0.0
samples = 3
seconds = 0.0005608

[probes.sparse_negative]
allocations = 48212
bytes = 1792552
compile_seconds = 0.0
samples = 3
seconds = 0.000848799

[probes.sparse_positive]
allocations = 48206
bytes = 1791000
compile_seconds = 0.0
samples = 3
seconds = 0.000857
