julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 120002
bytes = 5556552
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003785904
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461448
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000980101
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117987
bytes = 4768216
compile_seconds = 0.0
samples = 3
seconds = 0.002613203

[datasets.adlittle.primal]
allocations = 120800
bytes = 5833128
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004041804
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 606928
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001159901
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 7.83e-5

[datasets.adlittle.sparse]
allocations = 3267
bytes = 193488
compile_seconds = 0.0
samples = 3
seconds = 0.0001431

[datasets.afiro.dual]
allocations = 27653
bytes = 1281128
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009748
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000202
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26838
bytes = 1145992
compile_seconds = 0.0
samples = 3
seconds = 0.000647001

[datasets.afiro.primal]
allocations = 27559
bytes = 1260184
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000875001
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002078
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 46064
compile_seconds = 0.0
samples = 3
seconds = 8.73e-5

[datasets.afiro.sparse]
allocations = 6386
bytes = 275120
compile_seconds = 0.0
samples = 3
seconds = 0.0001784

[datasets.flugpl.dual]
allocations = 39760
bytes = 1615200
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001026102
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000105001
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1505304
compile_seconds = 0.0
samples = 3
seconds = 0.000756201

[datasets.flugpl.primal]
allocations = 40109
bytes = 1659472
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001004501
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001571
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 104
bytes = 5120
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.flugpl.sparse]
allocations = 6252
bytes = 236616
compile_seconds = 0.0
samples = 3
seconds = 0.0001196

[datasets.kb2.dual]
allocations = 293411
bytes = 13617984
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021315923
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000838901
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292209
bytes = 13164432
compile_seconds = 0.0
samples = 3
seconds = 0.021065523

[datasets.kb2.primal]
allocations = 293578
bytes = 13632624
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021148923
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260928
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006227
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 149032
compile_seconds = 0.0
samples = 3
seconds = 8.41e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197928
compile_seconds = 0.0
samples = 3
seconds = 0.0001254

[datasets.sc50a.dual]
allocations = 103085
bytes = 4489440
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002418302
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306416
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005353
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 102013
bytes = 4143472
compile_seconds = 0.0
samples = 3
seconds = 0.001871202

[datasets.sc50a.primal]
allocations = 103030
bytes = 4442192
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002236802
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000437401
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 302
bytes = 14464
compile_seconds = 0.0
samples = 3
seconds = 1.53e-5

[datasets.sc50a.sparse]
allocations = 9239
bytes = 404600
compile_seconds = 0.0
samples = 3
seconds = 0.0002313

[probes.singleton]
allocations = 8950
bytes = 356168
compile_seconds = 0.0
samples = 3
seconds = 0.000211101

[probes.sparse]
allocations = 17918
bytes = 670416
compile_seconds = 0.0
samples = 3
seconds = 0.0003593
