julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84980
bytes = 4148064
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003260398
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461304
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000945399
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82965
bytes = 3357696
compile_seconds = 0.0
samples = 3
seconds = 0.0019806

[datasets.adlittle.primal]
allocations = 85778
bytes = 4425008
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003352198
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607264
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001085199
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.27e-5

[datasets.adlittle.sparse]
allocations = 2861
bytes = 177776
compile_seconds = 0.0
samples = 3
seconds = 0.0001094

[datasets.afiro.dual]
allocations = 17505
bytes = 883456
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007466
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002051
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16690
bytes = 749072
compile_seconds = 0.0
samples = 3
seconds = 0.0005493

[datasets.afiro.primal]
allocations = 17411
bytes = 861872
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007109
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001877
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44224
compile_seconds = 0.0
samples = 3
seconds = 7.88e-5

[datasets.afiro.sparse]
allocations = 5517
bytes = 240280
compile_seconds = 0.0
samples = 3
seconds = 0.0001627

[datasets.flugpl.dual]
allocations = 32286
bytes = 1317336
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008758
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001582
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1207216
compile_seconds = 0.0
samples = 3
seconds = 0.0006849

[datasets.flugpl.primal]
allocations = 32635
bytes = 1361816
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000876799
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001806
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.23e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216776
compile_seconds = 0.0
samples = 3
seconds = 0.0001289

[datasets.kb2.dual]
allocations = 231270
bytes = 11138104
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020107492
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878096
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008523
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230068
bytes = 10685064
compile_seconds = 0.0
samples = 3
seconds = 0.019602791

[datasets.kb2.primal]
allocations = 231437
bytes = 11150904
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.019958991
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000620699
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111616
compile_seconds = 0.0
samples = 3
seconds = 0.0001188

[datasets.kb2.sparse]
allocations = 2958
bytes = 166160
compile_seconds = 0.0
samples = 3
seconds = 0.0001211

[datasets.sc50a.dual]
allocations = 69752
bytes = 3244600
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001994499
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005218
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 68680
bytes = 2898440
compile_seconds = 0.0
samples = 3
seconds = 0.001476099

[datasets.sc50a.primal]
allocations = 69697
bytes = 3197128
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021722
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004847
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.sc50a.sparse]
allocations = 7434
bytes = 332656
compile_seconds = 0.0
samples = 3
seconds = 0.000186

[probes.negative_absent]
allocations = 32207
bytes = 1227528
compile_seconds = 0.0
samples = 3
seconds = 0.000608601

[probes.negative_present]
allocations = 32726
bytes = 1239480
compile_seconds = 0.0
samples = 3
seconds = 0.000648901

[probes.nonzero]
allocations = 38228
bytes = 1432424
compile_seconds = 0.0
samples = 3
seconds = 0.000695201

[probes.positive_absent]
allocations = 32207
bytes = 1227720
compile_seconds = 0.0
samples = 3
seconds = 0.000607402

[probes.positive_present]
allocations = 32726
bytes = 1237464
compile_seconds = 0.0
samples = 3
seconds = 0.000589001

[probes.singleton]
allocations = 20480
bytes = 806248
compile_seconds = 0.0
samples = 3
seconds = 0.000443101
