julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.adlittle.dual]
allocations = 83258
bytes = 4072480
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0029841
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461080
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009319
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81243
bytes = 3282704
compile_seconds = 0.0
samples = 3
seconds = 0.0018279

[datasets.adlittle.primal]
allocations = 84056
bytes = 4349312
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0031827
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607312
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010265
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640728
compile_seconds = 0.0
samples = 3
seconds = 0.0003027

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.25e-5

[datasets.adlittle.sparse]
allocations = 2282
bytes = 154920
compile_seconds = 0.0
samples = 3
seconds = 9.62e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.afiro.dual]
allocations = 16433
bytes = 840776
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000789
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002342
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15618
bytes = 704904
compile_seconds = 0.0
samples = 3
seconds = 0.0005285

[datasets.afiro.primal]
allocations = 16339
bytes = 818728
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006192
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121792
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002554
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92968
compile_seconds = 0.0
samples = 3
seconds = 0.0001186

[datasets.afiro.singleton]
allocations = 747
bytes = 40736
compile_seconds = 0.0
samples = 3
seconds = 9.08e-5

[datasets.afiro.sparse]
allocations = 4116
bytes = 185464
compile_seconds = 0.0
samples = 3
seconds = 0.000121

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6

[datasets.flugpl.dual]
allocations = 27847
bytes = 1138784
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007077
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001406
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27176
bytes = 1029176
compile_seconds = 0.0
samples = 3
seconds = 0.0005694

[datasets.flugpl.primal]
allocations = 28196
bytes = 1183648
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007807
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001905
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123216
compile_seconds = 0.0
samples = 3
seconds = 7.7e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.24e-5

[datasets.flugpl.sparse]
allocations = 4428
bytes = 164040
compile_seconds = 0.0
samples = 3
seconds = 9.58e-5

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.kb2.dual]
allocations = 228627
bytes = 11026888
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0203032
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007902
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227425
bytes = 10574488
compile_seconds = 0.0
samples = 3
seconds = 0.0200787

[datasets.kb2.primal]
allocations = 228794
bytes = 11038808
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0210564
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260880
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005935
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453824
compile_seconds = 0.0
samples = 3
seconds = 0.0002295

[datasets.kb2.singleton]
allocations = 1915
bytes = 105256
compile_seconds = 0.0
samples = 3
seconds = 6.86e-5

[datasets.kb2.sparse]
allocations = 2207
bytes = 135304
compile_seconds = 0.0
samples = 3
seconds = 8.49e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.sc50a.dual]
allocations = 67169
bytes = 3140024
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0017658
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005728
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66097
bytes = 2795032
compile_seconds = 0.0
samples = 3
seconds = 0.0013679

[datasets.sc50a.primal]
allocations = 67114
bytes = 3093048
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018529
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004325
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221776
compile_seconds = 0.0
samples = 3
seconds = 0.0001267

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[datasets.sc50a.sparse]
allocations = 6081
bytes = 279424
compile_seconds = 0.0
samples = 3
seconds = 0.0001568

[probes.free_negative]
allocations = 29623
bytes = 1195912
compile_seconds = 0.0
samples = 3
seconds = 0.0005602

[probes.free_positive]
allocations = 29623
bytes = 1196376
compile_seconds = 0.0
samples = 3
seconds = 0.0005715

[probes.negative]
allocations = 45367
bytes = 1683048
compile_seconds = 0.0
samples = 3
seconds = 0.0008749

[probes.negative_both]
allocations = 45367
bytes = 1682936
compile_seconds = 0.0
samples = 3
seconds = 0.0008003

[probes.negative_term]
allocations = 45367
bytes = 1682968
compile_seconds = 0.0
samples = 3
seconds = 0.0008097

[probes.positive]
allocations = 45367
bytes = 1680952
compile_seconds = 0.0
samples = 3
seconds = 0.0008823
