julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.adlittle.dual]
allocations = 82550
bytes = 4052360
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003139898
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008896
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80535
bytes = 3262088
compile_seconds = 0.0
samples = 3
seconds = 0.001887499

[datasets.adlittle.primal]
allocations = 83348
bytes = 4329256
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003266598
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001017899
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 639384
compile_seconds = 0.0
samples = 3
seconds = 0.0003457

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 4.58e-5

[datasets.adlittle.sparse]
allocations = 1706
bytes = 133640
compile_seconds = 0.0
samples = 3
seconds = 9.19e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 16249
bytes = 833736
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007501
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002177
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15434
bytes = 698424
compile_seconds = 0.0
samples = 3
seconds = 0.0005368

[datasets.afiro.primal]
allocations = 16155
bytes = 812200
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006504
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002179
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91672
compile_seconds = 0.0
samples = 3
seconds = 8.95e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40640
compile_seconds = 0.0
samples = 3
seconds = 6.98e-5

[datasets.afiro.sparse]
allocations = 3760
bytes = 173520
compile_seconds = 0.0
samples = 3
seconds = 0.0001379

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 26767
bytes = 1108000
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0006985
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001193
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 26096
bytes = 998264
compile_seconds = 0.0
samples = 3
seconds = 0.0005548

[datasets.flugpl.primal]
allocations = 27116
bytes = 1152528
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009013
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000164
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 121952
compile_seconds = 0.0
samples = 3
seconds = 8.76e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.45e-5

[datasets.flugpl.sparse]
allocations = 4068
bytes = 152984
compile_seconds = 0.0
samples = 3
seconds = 9.22e-5

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 228243
bytes = 11015944
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020361287
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000833699
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227041
bytes = 10560760
compile_seconds = 0.0
samples = 3
seconds = 0.020056687

[datasets.kb2.primal]
allocations = 228410
bytes = 11029784
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020502886
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005571
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 452960
compile_seconds = 0.0
samples = 3
seconds = 0.0002715

[datasets.kb2.singleton]
allocations = 1915
bytes = 105352
compile_seconds = 0.0
samples = 3
seconds = 7.01e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127848
compile_seconds = 0.0
samples = 3
seconds = 9.51e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.81e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 66189
bytes = 3111952
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020946
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306288
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005311
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 65117
bytes = 2766912
compile_seconds = 0.0
samples = 3
seconds = 0.001350901

[datasets.sc50a.primal]
allocations = 66134
bytes = 3064992
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001765701
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005155
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 220480
compile_seconds = 0.0
samples = 3
seconds = 0.0001347

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.49e-5

[datasets.sc50a.sparse]
allocations = 5585
bytes = 264352
compile_seconds = 0.0
samples = 3
seconds = 0.0001539

[probes.finite]
allocations = 82771
bytes = 3179904
compile_seconds = 0.0
samples = 3
seconds = 0.0017134

[probes.late_unbounded]
allocations = 84187
bytes = 3341160
compile_seconds = 0.0
samples = 3
seconds = 0.0017318

[probes.lower_only]
allocations = 67291
bytes = 2780168
compile_seconds = 0.0
samples = 3
seconds = 0.001965099

[probes.negative]
allocations = 72923
bytes = 2984952
compile_seconds = 0.0
samples = 3
seconds = 0.001608001

[probes.positive]
allocations = 72923
bytes = 2982424
compile_seconds = 0.0
samples = 3
seconds = 0.0019084

[probes.upper_only]
allocations = 67291
bytes = 2780072
compile_seconds = 0.0
samples = 3
seconds = 0.0014988
