julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85007
bytes = 4146752
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032011
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461240
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000959501
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82992
bytes = 3356032
compile_seconds = 0.0
samples = 3
seconds = 0.002003701

[datasets.adlittle.primal]
allocations = 85805
bytes = 4423504
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033738
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607376
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010337
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.04e-5

[datasets.adlittle.sparse]
allocations = 2888
bytes = 177984
compile_seconds = 0.0
samples = 3
seconds = 0.000105

[datasets.afiro.dual]
allocations = 17609
bytes = 887504
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000762401
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001802
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16794
bytes = 751456
compile_seconds = 0.0
samples = 3
seconds = 0.0005169

[datasets.afiro.primal]
allocations = 17515
bytes = 865648
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006783
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002095
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44192
compile_seconds = 0.0
samples = 3
seconds = 7.61e-5

[datasets.afiro.sparse]
allocations = 5665
bytes = 245728
compile_seconds = 0.0
samples = 3
seconds = 0.0001686

[datasets.flugpl.dual]
allocations = 32286
bytes = 1315128
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009598
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001602
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1205136
compile_seconds = 0.0
samples = 3
seconds = 0.0007014

[datasets.flugpl.primal]
allocations = 32635
bytes = 1359560
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009794
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001901
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.09e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 215720
compile_seconds = 0.0
samples = 3
seconds = 0.0001424

[datasets.kb2.dual]
allocations = 231390
bytes = 11139320
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020274
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878384
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008411
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230188
bytes = 10685960
compile_seconds = 0.0
samples = 3
seconds = 0.020111

[datasets.kb2.primal]
allocations = 231557
bytes = 11153480
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020620701
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005492
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112160
compile_seconds = 0.0
samples = 3
seconds = 9.43e-5

[datasets.kb2.sparse]
allocations = 3087
bytes = 170608
compile_seconds = 0.0
samples = 3
seconds = 8.75e-5

[datasets.sc50a.dual]
allocations = 70466
bytes = 3271568
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022759
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000552
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 69394
bytes = 2926656
compile_seconds = 0.0
samples = 3
seconds = 0.0015891

[datasets.sc50a.primal]
allocations = 70411
bytes = 3224368
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020451
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005402
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.44e-5

[datasets.sc50a.sparse]
allocations = 7882
bytes = 350608
compile_seconds = 0.0
samples = 3
seconds = 0.000224

[probes.negative_negative]
allocations = 38734
bytes = 1446136
compile_seconds = 0.0
samples = 3
seconds = 0.0007763

[probes.negative_positive]
allocations = 38743
bytes = 1446336
compile_seconds = 0.0
samples = 3
seconds = 0.0007228

[probes.nonunit]
allocations = 39380
bytes = 1475080
compile_seconds = 0.0
samples = 3
seconds = 0.0006818

[probes.positive_negative]
allocations = 38231
bytes = 1431504
compile_seconds = 0.0
samples = 3
seconds = 0.0007365

[probes.positive_positive]
allocations = 38222
bytes = 1429000
compile_seconds = 0.0
samples = 3
seconds = 0.0007308

[probes.singleton]
allocations = 19328
bytes = 761112
compile_seconds = 0.0
samples = 3
seconds = 0.0004051
