julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119596
bytes = 5527048
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039234
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009453
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117581
bytes = 4736984
compile_seconds = 0.0
samples = 3
seconds = 0.0024373

[datasets.adlittle.primal]
allocations = 120394
bytes = 5803432
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041806
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011034
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 7.55e-5

[datasets.adlittle.sparse]
allocations = 3267
bytes = 193872
compile_seconds = 0.0
samples = 3
seconds = 0.0001291

[datasets.afiro.dual]
allocations = 27462
bytes = 1269992
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008877
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002193
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26647
bytes = 1133912
compile_seconds = 0.0
samples = 3
seconds = 0.0006955

[datasets.afiro.primal]
allocations = 27368
bytes = 1247944
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008793
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002024
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 46096
compile_seconds = 0.0
samples = 3
seconds = 8.93e-5

[datasets.afiro.sparse]
allocations = 6386
bytes = 273904
compile_seconds = 0.0
samples = 3
seconds = 0.0001888

[datasets.flugpl.dual]
allocations = 39638
bytes = 1606944
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009738
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001317
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38967
bytes = 1496904
compile_seconds = 0.0
samples = 3
seconds = 0.0008262

[datasets.flugpl.primal]
allocations = 39987
bytes = 1651552
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000938
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001823
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 104
bytes = 5120
compile_seconds = 0.0
samples = 3
seconds = 1.46e-5

[datasets.flugpl.sparse]
allocations = 6252
bytes = 236376
compile_seconds = 0.0
samples = 3
seconds = 0.0001495

[datasets.kb2.dual]
allocations = 292789
bytes = 13581968
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020690499
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878656
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008458
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291587
bytes = 13131296
compile_seconds = 0.0
samples = 3
seconds = 0.021179399

[datasets.kb2.primal]
allocations = 292956
bytes = 13595504
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021325199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005893
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 149288
compile_seconds = 0.0
samples = 3
seconds = 9.27e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 198552
compile_seconds = 0.0
samples = 3
seconds = 0.0001364

[datasets.sc50a.dual]
allocations = 102754
bytes = 4471040
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024801
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306368
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005207
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101682
bytes = 4124176
compile_seconds = 0.0
samples = 3
seconds = 0.0019568

[datasets.sc50a.primal]
allocations = 102699
bytes = 4423936
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025325
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005022
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 302
bytes = 14464
compile_seconds = 0.0
samples = 3
seconds = 2.1e-5

[datasets.sc50a.sparse]
allocations = 9239
bytes = 404248
compile_seconds = 0.0
samples = 3
seconds = 0.0002155

[probes.singleton]
allocations = 281
bytes = 19440
compile_seconds = 0.0
samples = 3
seconds = 2.26e-5

[probes.sparse]
allocations = 291
bytes = 19872
compile_seconds = 0.0
samples = 3
seconds = 1.94e-5
