julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85374
bytes = 4161400
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003476101
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461112
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000975001
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83359
bytes = 3370936
compile_seconds = 0.0
samples = 3
seconds = 0.0023618

[datasets.adlittle.primal]
allocations = 86172
bytes = 4438168
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003728701
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607296
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011688
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 768
bytes = 66712
compile_seconds = 0.0
samples = 3
seconds = 8.01e-5

[datasets.adlittle.sparse]
allocations = 3069
bytes = 186224
compile_seconds = 0.0
samples = 3
seconds = 0.0001148

[datasets.afiro.dual]
allocations = 18263
bytes = 913104
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007882
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002272
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17448
bytes = 777264
compile_seconds = 0.0
samples = 3
seconds = 0.0006458

[datasets.afiro.primal]
allocations = 18169
bytes = 891392
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000793601
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002211
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 45104
compile_seconds = 0.0
samples = 3
seconds = 8.92e-5

[datasets.afiro.sparse]
allocations = 6312
bytes = 270944
compile_seconds = 0.0
samples = 3
seconds = 0.0002056

[datasets.flugpl.dual]
allocations = 32652
bytes = 1329272
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009597
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001612
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31981
bytes = 1219872
compile_seconds = 0.0
samples = 3
seconds = 0.0007022

[datasets.flugpl.primal]
allocations = 33001
bytes = 1373880
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010019
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001942
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.flugpl.sparse]
allocations = 5852
bytes = 219920
compile_seconds = 0.0
samples = 3
seconds = 0.0001471

[datasets.kb2.dual]
allocations = 232882
bytes = 11197208
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021523802
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878048
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000870801
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 231680
bytes = 10743736
compile_seconds = 0.0
samples = 3
seconds = 0.021178203

[datasets.kb2.primal]
allocations = 233049
bytes = 11210392
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021212402
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006515
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2600
bytes = 136304
compile_seconds = 0.0
samples = 3
seconds = 0.0001041

[datasets.kb2.sparse]
allocations = 3755
bytes = 198568
compile_seconds = 0.0
samples = 3
seconds = 0.0001391

[datasets.sc50a.dual]
allocations = 72627
bytes = 3357528
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002079301
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006229
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 71555
bytes = 3010824
compile_seconds = 0.0
samples = 3
seconds = 0.0015869

[datasets.sc50a.primal]
allocations = 72572
bytes = 3310104
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021205
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000508901
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.78e-5

[datasets.sc50a.sparse]
allocations = 8951
bytes = 393304
compile_seconds = 0.0
samples = 3
seconds = 0.0002343

[probes.free]
allocations = 17658
bytes = 687864
compile_seconds = 0.0
samples = 3
seconds = 0.0003728

[probes.nonunit_bound]
allocations = 29178
bytes = 1122040
compile_seconds = 0.0
samples = 3
seconds = 0.0005765

[probes.singleton_negative]
allocations = 27133
bytes = 1040880
compile_seconds = 0.0
samples = 3
seconds = 0.000528701

[probes.singleton_positive]
allocations = 27130
bytes = 1039432
compile_seconds = 0.0
samples = 3
seconds = 0.000541

[probes.sparse_negative]
allocations = 45908
bytes = 1709992
compile_seconds = 0.0
samples = 3
seconds = 0.0008897

[probes.sparse_positive]
allocations = 45902
bytes = 1708712
compile_seconds = 0.0
samples = 3
seconds = 0.0009511
