julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85073
bytes = 4147680
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034382
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461304
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009433
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83058
bytes = 3358800
compile_seconds = 0.0
samples = 3
seconds = 0.0020086

[datasets.adlittle.primal]
allocations = 85871
bytes = 4424336
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035557
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607648
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011521
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 615
bytes = 61120
compile_seconds = 0.0
samples = 3
seconds = 6.2e-5

[datasets.adlittle.sparse]
allocations = 2929
bytes = 181104
compile_seconds = 0.0
samples = 3
seconds = 0.0001026

[datasets.afiro.dual]
allocations = 17669
bytes = 890128
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007759
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.00022
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16854
bytes = 754048
compile_seconds = 0.0
samples = 3
seconds = 0.0005346

[datasets.afiro.primal]
allocations = 17575
bytes = 868240
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007079
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002094
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 852
bytes = 44464
compile_seconds = 0.0
samples = 3
seconds = 8.18e-5

[datasets.afiro.sparse]
allocations = 5716
bytes = 247992
compile_seconds = 0.0
samples = 3
seconds = 0.0001686

[datasets.flugpl.dual]
allocations = 32526
bytes = 1324512
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008471
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001402
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31855
bytes = 1214680
compile_seconds = 0.0
samples = 3
seconds = 0.0006564

[datasets.flugpl.primal]
allocations = 32875
bytes = 1369152
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008672
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001892
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.17e-5

[datasets.flugpl.sparse]
allocations = 5852
bytes = 219936
compile_seconds = 0.0
samples = 3
seconds = 0.0001461

[datasets.kb2.dual]
allocations = 231492
bytes = 11144816
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020287999
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878304
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008591
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230290
bytes = 10691232
compile_seconds = 0.0
samples = 3
seconds = 0.0196925

[datasets.kb2.primal]
allocations = 231659
bytes = 11157600
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020318199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006205
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2120
bytes = 114680
compile_seconds = 0.0
samples = 3
seconds = 0.0001186

[datasets.kb2.sparse]
allocations = 3136
bytes = 173776
compile_seconds = 0.0
samples = 3
seconds = 0.0001251

[datasets.sc50a.dual]
allocations = 70685
bytes = 3282688
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020196
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306176
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005472
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 69613
bytes = 2936944
compile_seconds = 0.0
samples = 3
seconds = 0.0014707

[datasets.sc50a.primal]
allocations = 70630
bytes = 3235728
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019494
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005097
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.sparse]
allocations = 7996
bytes = 356400
compile_seconds = 0.0
samples = 3
seconds = 0.0001838

[probes.inequality]
allocations = 278
bytes = 15256
compile_seconds = 0.0
samples = 3
seconds = 1.61e-5

[probes.nonzero]
allocations = 28029
bytes = 1077568
compile_seconds = 0.0
samples = 3
seconds = 0.0005478

[probes.singleton_negative]
allocations = 21376
bytes = 844632
compile_seconds = 0.0
samples = 3
seconds = 0.0004357

[probes.singleton_positive]
allocations = 21376
bytes = 842472
compile_seconds = 0.0
samples = 3
seconds = 0.000418399

[probes.sparse_negative]
allocations = 40151
bytes = 1513584
compile_seconds = 0.0
samples = 3
seconds = 0.0007768

[probes.sparse_positive]
allocations = 40148
bytes = 1512424
compile_seconds = 0.0
samples = 3
seconds = 0.0007962
