julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.adlittle.dual]
allocations = 84676
bytes = 4134000
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034671
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008759
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82661
bytes = 3343504
compile_seconds = 0.0
samples = 3
seconds = 0.0020816

[datasets.adlittle.primal]
allocations = 85474
bytes = 4410064
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033711
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607648
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010738
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.64e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174760
compile_seconds = 0.0
samples = 3
seconds = 0.0001287

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 866000
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007712
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002127
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 730976
compile_seconds = 0.0
samples = 3
seconds = 0.0004905

[datasets.afiro.primal]
allocations = 16963
bytes = 843232
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006804
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121792
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002033
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45504
compile_seconds = 0.0
samples = 3
seconds = 9.98e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 215296
compile_seconds = 0.0
samples = 3
seconds = 0.0001442

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1289904
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009016
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001498
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1181512
compile_seconds = 0.0
samples = 3
seconds = 0.000635

[datasets.flugpl.primal]
allocations = 32031
bytes = 1334720
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009022
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001657
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.98e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210744
compile_seconds = 0.0
samples = 3
seconds = 0.0001355

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11130432
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0213067
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877936
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008265
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10676096
compile_seconds = 0.0
samples = 3
seconds = 0.0197197

[datasets.kb2.primal]
allocations = 231280
bytes = 11144496
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0206001
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005868
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112352
compile_seconds = 0.0
samples = 3
seconds = 9.58e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162128
compile_seconds = 0.0
samples = 3
seconds = 0.0001076

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.69e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3194560
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021968
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005733
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2848896
compile_seconds = 0.0
samples = 3
seconds = 0.0015901

[datasets.sc50a.primal]
allocations = 68520
bytes = 3147664
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018543
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005049
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.4e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299584
compile_seconds = 0.0
samples = 3
seconds = 0.0002064

[probes.cancel_fraction]
allocations = 33699
bytes = 1274296
compile_seconds = 0.0
samples = 3
seconds = 0.0005562

[probes.cancel_integer]
allocations = 32675
bytes = 1231192
compile_seconds = 0.0
samples = 3
seconds = 0.0007586

[probes.sum_fraction]
allocations = 34083
bytes = 1283832
compile_seconds = 0.0
samples = 3
seconds = 0.0006685

[probes.sum_integer]
allocations = 33059
bytes = 1242536
compile_seconds = 0.0
samples = 3
seconds = 0.0005889

[probes.unequal_denominator]
allocations = 34211
bytes = 1285720
compile_seconds = 0.0
samples = 3
seconds = 0.0006598

[probes.zero_constant]
allocations = 33056
bytes = 1242368
compile_seconds = 0.0
samples = 3
seconds = 0.000631
