julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 120002
bytes = 5555432
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003716401
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008927
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117987
bytes = 4767288
compile_seconds = 0.0
samples = 3
seconds = 0.0023223

[datasets.adlittle.primal]
allocations = 120800
bytes = 5832504
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003870501
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010918
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 793
bytes = 67640
compile_seconds = 0.0
samples = 3
seconds = 7.38e-5

[datasets.adlittle.sparse]
allocations = 3267
bytes = 192608
compile_seconds = 0.0
samples = 3
seconds = 0.0001132

[datasets.afiro.dual]
allocations = 27653
bytes = 1280040
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0010121
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002035
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26838
bytes = 1144808
compile_seconds = 0.0
samples = 3
seconds = 0.0008389

[datasets.afiro.primal]
allocations = 27559
bytes = 1259432
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009585
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000194
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 877
bytes = 45856
compile_seconds = 0.0
samples = 3
seconds = 9.5e-5

[datasets.afiro.sparse]
allocations = 6386
bytes = 272688
compile_seconds = 0.0
samples = 3
seconds = 0.0001945

[datasets.flugpl.dual]
allocations = 39760
bytes = 1613552
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009188
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001227
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1503896
compile_seconds = 0.0
samples = 3
seconds = 0.0007665

[datasets.flugpl.primal]
allocations = 40109
bytes = 1658176
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009475
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001677
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 104
bytes = 5120
compile_seconds = 0.0
samples = 3
seconds = 1.06e-5

[datasets.flugpl.sparse]
allocations = 6252
bytes = 235768
compile_seconds = 0.0
samples = 3
seconds = 0.0001378

[datasets.kb2.dual]
allocations = 293411
bytes = 13615600
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022471402
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000913
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292209
bytes = 13165008
compile_seconds = 0.0
samples = 3
seconds = 0.020594602

[datasets.kb2.primal]
allocations = 293578
bytes = 13630432
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020941402
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006137
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2918
bytes = 148008
compile_seconds = 0.0
samples = 3
seconds = 8.52e-5

[datasets.kb2.sparse]
allocations = 3755
bytes = 197448
compile_seconds = 0.0
samples = 3
seconds = 0.0001145

[datasets.sc50a.dual]
allocations = 103085
bytes = 4488176
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002379
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306400
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006006
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 102013
bytes = 4142768
compile_seconds = 0.0
samples = 3
seconds = 0.0019276

[datasets.sc50a.primal]
allocations = 103030
bytes = 4440960
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002486901
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000464
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 302
bytes = 14464
compile_seconds = 0.0
samples = 3
seconds = 1.29e-5

[datasets.sc50a.sparse]
allocations = 9239
bytes = 403608
compile_seconds = 0.0
samples = 3
seconds = 0.0002095

[probes.singleton]
allocations = 8950
bytes = 353416
compile_seconds = 0.0
samples = 3
seconds = 0.000237

[probes.sparse]
allocations = 15486
bytes = 598448
compile_seconds = 0.0
samples = 3
seconds = 0.0003584
