julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 82462
bytes = 4052808
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003244501
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461336
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0011896
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80447
bytes = 3260856
compile_seconds = 0.0
samples = 3
seconds = 0.0020082

[datasets.adlittle.primal]
allocations = 83260
bytes = 4329880
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003396301
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010431
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640584
compile_seconds = 0.0
samples = 3
seconds = 0.0003364

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.09e-5

[datasets.adlittle.sparse]
allocations = 1642
bytes = 130648
compile_seconds = 0.0
samples = 3
seconds = 9.06e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 834200
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007082
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001872
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 699624
compile_seconds = 0.0
samples = 3
seconds = 0.0005007

[datasets.afiro.primal]
allocations = 16131
bytes = 812184
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007353
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001692
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92552
compile_seconds = 0.0
samples = 3
seconds = 0.0001135

[datasets.afiro.singleton]
allocations = 747
bytes = 40928
compile_seconds = 0.0
samples = 3
seconds = 8.33e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 173392
compile_seconds = 0.0
samples = 3
seconds = 0.0001406

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.4e-6

[datasets.flugpl.dual]
allocations = 26435
bytes = 1100144
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008039
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001549
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25764
bytes = 990600
compile_seconds = 0.0
samples = 3
seconds = 0.0006156

[datasets.flugpl.primal]
allocations = 26784
bytes = 1144864
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008079
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001866
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122960
compile_seconds = 0.0
samples = 3
seconds = 8.66e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.74e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 149432
compile_seconds = 0.0
samples = 3
seconds = 0.0001018

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11016008
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020665802
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008615
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10561736
compile_seconds = 0.0
samples = 3
seconds = 0.020161702

[datasets.kb2.primal]
allocations = 228386
bytes = 11028776
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020689102
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005771
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453760
compile_seconds = 0.0
samples = 3
seconds = 0.0002374

[datasets.kb2.singleton]
allocations = 1915
bytes = 105272
compile_seconds = 0.0
samples = 3
seconds = 8.86e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127736
compile_seconds = 0.0
samples = 3
seconds = 0.0001351

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.42e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3108512
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018385
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306240
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005803
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2761936
compile_seconds = 0.0
samples = 3
seconds = 0.001502501

[datasets.sc50a.primal]
allocations = 65958
bytes = 3061296
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020392
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000468
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221184
compile_seconds = 0.0
samples = 3
seconds = 0.0001228

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 262064
compile_seconds = 0.0
samples = 3
seconds = 0.0001363

[probes.finite]
allocations = 82771
bytes = 3181440
compile_seconds = 0.0
samples = 3
seconds = 0.0017756

[probes.free_pivot]
allocations = 58579
bytes = 2424528
compile_seconds = 0.0
samples = 3
seconds = 0.0014046

[probes.lower_only]
allocations = 66267
bytes = 2753736
compile_seconds = 0.0
samples = 3
seconds = 0.0015379

[probes.negative]
allocations = 71899
bytes = 2958840
compile_seconds = 0.0
samples = 3
seconds = 0.0018136

[probes.positive]
allocations = 71899
bytes = 2956536
compile_seconds = 0.0
samples = 3
seconds = 0.0018151

[probes.upper_only]
allocations = 66267
bytes = 2753464
compile_seconds = 0.0
samples = 3
seconds = 0.001561701
