julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 9.3e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 83431
bytes = 4077792
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036373
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461176
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010197
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81416
bytes = 3288672
compile_seconds = 0.0
samples = 3
seconds = 0.0021483

[datasets.adlittle.primal]
allocations = 84229
bytes = 4354720
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036416
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607392
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011009
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641496
compile_seconds = 0.0
samples = 3
seconds = 0.0004032

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.94e-5

[datasets.adlittle.sparse]
allocations = 2336
bytes = 156680
compile_seconds = 0.0
samples = 3
seconds = 0.0001289

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.afiro.dual]
allocations = 16456
bytes = 841960
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007894
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002439
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15641
bytes = 705848
compile_seconds = 0.0
samples = 3
seconds = 0.0006132

[datasets.afiro.primal]
allocations = 16362
bytes = 820472
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000821
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002396
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92696
compile_seconds = 0.0
samples = 3
seconds = 0.0001046

[datasets.afiro.singleton]
allocations = 747
bytes = 41088
compile_seconds = 0.0
samples = 3
seconds = 7.5e-5

[datasets.afiro.sparse]
allocations = 4155
bytes = 185928
compile_seconds = 0.0
samples = 3
seconds = 0.0001713

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.5e-6

[datasets.flugpl.dual]
allocations = 28597
bytes = 1168096
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009641
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001532
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27926
bytes = 1058536
compile_seconds = 0.0
samples = 3
seconds = 0.000715

[datasets.flugpl.primal]
allocations = 28946
bytes = 1212736
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009686
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001963
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123552
compile_seconds = 0.0
samples = 3
seconds = 0.000115

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.86e-5

[datasets.flugpl.sparse]
allocations = 4667
bytes = 173480
compile_seconds = 0.0
samples = 3
seconds = 0.00015

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.kb2.dual]
allocations = 229107
bytes = 11043232
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021297501
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878048
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008587
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227905
bytes = 10589328
compile_seconds = 0.0
samples = 3
seconds = 0.020259701

[datasets.kb2.primal]
allocations = 229274
bytes = 11057280
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021374001
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006341
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454464
compile_seconds = 0.0
samples = 3
seconds = 0.0002714

[datasets.kb2.singleton]
allocations = 1915
bytes = 105352
compile_seconds = 0.0
samples = 3
seconds = 9.01e-5

[datasets.kb2.sparse]
allocations = 2257
bytes = 137192
compile_seconds = 0.0
samples = 3
seconds = 0.0001117

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.75e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.sc50a.dual]
allocations = 67347
bytes = 3146696
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002099701
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000597
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66275
bytes = 2801208
compile_seconds = 0.0
samples = 3
seconds = 0.0017435

[datasets.sc50a.primal]
allocations = 67292
bytes = 3099368
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020817
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000553
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222272
compile_seconds = 0.0
samples = 3
seconds = 0.0001677

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.24e-5

[datasets.sc50a.sparse]
allocations = 6164
bytes = 282016
compile_seconds = 0.0
samples = 3
seconds = 0.0002015

[probes.fraction_negative]
allocations = 62803
bytes = 2429760
compile_seconds = 0.0
samples = 3
seconds = 0.0016622

[probes.fraction_positive]
allocations = 62803
bytes = 2429632
compile_seconds = 0.0
samples = 3
seconds = 0.0013221

[probes.free_pivot]
allocations = 44115
bytes = 1846528
compile_seconds = 0.0
samples = 3
seconds = 0.0010117

[probes.integer_negative]
allocations = 62291
bytes = 2402560
compile_seconds = 0.0
samples = 3
seconds = 0.0012572

[probes.integer_positive]
allocations = 62291
bytes = 2399744
compile_seconds = 0.0
samples = 3
seconds = 0.0013215

[probes.variable]
allocations = 66643
bytes = 2540112
compile_seconds = 0.0
samples = 3
seconds = 0.00144
