julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.adlittle.dual]
allocations = 83444
bytes = 4083352
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.002974508
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461000
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000895102
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81429
bytes = 3291848
compile_seconds = 0.0
samples = 3
seconds = 0.002105006

[datasets.adlittle.primal]
allocations = 84242
bytes = 4360328
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.00341761
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 606944
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001093403
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642744
compile_seconds = 0.0
samples = 3
seconds = 0.000387701

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.46e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 155896
compile_seconds = 0.0
samples = 3
seconds = 0.000128501

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.afiro.dual]
allocations = 16468
bytes = 842616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000843603
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001795
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15653
bytes = 707752
compile_seconds = 0.0
samples = 3
seconds = 0.000601142

[datasets.afiro.primal]
allocations = 16374
bytes = 820552
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000732902
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000227701
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92568
compile_seconds = 0.0
samples = 3
seconds = 0.0001001

[datasets.afiro.singleton]
allocations = 747
bytes = 40256
compile_seconds = 0.0
samples = 3
seconds = 7.75e-5

[datasets.afiro.sparse]
allocations = 4167
bytes = 187432
compile_seconds = 0.0
samples = 3
seconds = 0.0001401

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 28809
bytes = 1178792
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008242
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001605
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 28138
bytes = 1069344
compile_seconds = 0.0
samples = 3
seconds = 0.000678399

[datasets.flugpl.primal]
allocations = 29158
bytes = 1223448
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000921499
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001933
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123968
compile_seconds = 0.0
samples = 3
seconds = 0.000103

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.69e-5

[datasets.flugpl.sparse]
allocations = 4697
bytes = 176208
compile_seconds = 0.0
samples = 3
seconds = 0.000122299

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.kb2.dual]
allocations = 229117
bytes = 11046296
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020671058
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000846702
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227915
bytes = 10594072
compile_seconds = 0.0
samples = 3
seconds = 0.019973157

[datasets.kb2.primal]
allocations = 229284
bytes = 11061384
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.02119686
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000599101
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 456400
compile_seconds = 0.0
samples = 3
seconds = 0.000236601

[datasets.kb2.singleton]
allocations = 1915
bytes = 104616
compile_seconds = 0.0
samples = 3
seconds = 7.45e-5

[datasets.kb2.sparse]
allocations = 2259
bytes = 136504
compile_seconds = 0.0
samples = 3
seconds = 0.000111201

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.85e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.sc50a.dual]
allocations = 67374
bytes = 3149656
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002088999
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000571999
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66302
bytes = 2804024
compile_seconds = 0.0
samples = 3
seconds = 0.001580398

[datasets.sc50a.primal]
allocations = 67319
bytes = 3102616
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001833998
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000491399
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 223792
compile_seconds = 0.0
samples = 3
seconds = 0.0001559

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.08e-5

[datasets.sc50a.sparse]
allocations = 6174
bytes = 283680
compile_seconds = 0.0
samples = 3
seconds = 0.0001673

[probes.fraction_negative]
allocations = 49079
bytes = 1824440
compile_seconds = 0.0
samples = 3
seconds = 0.0008662

[probes.fraction_positive]
allocations = 49079
bytes = 1824504
compile_seconds = 0.0
samples = 3
seconds = 0.000862899

[probes.free_pivot]
allocations = 29623
bytes = 1195704
compile_seconds = 0.0
samples = 3
seconds = 0.0005566

[probes.integer_negative]
allocations = 45495
bytes = 1704584
compile_seconds = 0.0
samples = 3
seconds = 0.0008924

[probes.integer_positive]
allocations = 45495
bytes = 1702104
compile_seconds = 0.0
samples = 3
seconds = 0.0007927

[probes.unequal]
allocations = 49079
bytes = 1824344
compile_seconds = 0.0
samples = 3
seconds = 0.000819
