julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 83441
bytes = 4078592
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033527
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461048
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009544
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81426
bytes = 3288384
compile_seconds = 0.0
samples = 3
seconds = 0.001863599

[datasets.adlittle.primal]
allocations = 84239
bytes = 4355152
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034457
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011615
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641240
compile_seconds = 0.0
samples = 3
seconds = 0.0003903

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.14e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 156744
compile_seconds = 0.0
samples = 3
seconds = 0.0001309

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 16468
bytes = 842104
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007933
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002191
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15653
bytes = 707160
compile_seconds = 0.0
samples = 3
seconds = 0.0005611

[datasets.afiro.primal]
allocations = 16374
bytes = 819928
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007848
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002194
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93032
compile_seconds = 0.0
samples = 3
seconds = 0.0001108

[datasets.afiro.singleton]
allocations = 747
bytes = 41344
compile_seconds = 0.0
samples = 3
seconds = 8.51e-5

[datasets.afiro.sparse]
allocations = 4167
bytes = 187480
compile_seconds = 0.0
samples = 3
seconds = 0.0001665

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.flugpl.dual]
allocations = 28717
bytes = 1171920
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000813
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001608
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 28046
bytes = 1062488
compile_seconds = 0.0
samples = 3
seconds = 0.0006498

[datasets.flugpl.primal]
allocations = 29066
bytes = 1215904
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007757
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001984
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123424
compile_seconds = 0.0
samples = 3
seconds = 9.99e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.69e-5

[datasets.flugpl.sparse]
allocations = 4667
bytes = 173240
compile_seconds = 0.0
samples = 3
seconds = 0.0001145

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 229109
bytes = 11043264
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021068299
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877936
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007888
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227907
bytes = 10590688
compile_seconds = 0.0
samples = 3
seconds = 0.0194359

[datasets.kb2.primal]
allocations = 229276
bytes = 11057344
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0200333
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005617
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453584
compile_seconds = 0.0
samples = 3
seconds = 0.0002517

[datasets.kb2.singleton]
allocations = 1915
bytes = 105576
compile_seconds = 0.0
samples = 3
seconds = 0.0001099

[datasets.kb2.sparse]
allocations = 2259
bytes = 137496
compile_seconds = 0.0
samples = 3
seconds = 0.0001026

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.sc50a.dual]
allocations = 67374
bytes = 3149032
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018004
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005473
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66302
bytes = 2801928
compile_seconds = 0.0
samples = 3
seconds = 0.0015186

[datasets.sc50a.primal]
allocations = 67319
bytes = 3101448
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020539
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004618
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221712
compile_seconds = 0.0
samples = 3
seconds = 0.0001464

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.49e-5

[datasets.sc50a.sparse]
allocations = 6174
bytes = 281968
compile_seconds = 0.0
samples = 3
seconds = 0.0001536

[probes.free_pivot]
allocations = 29623
bytes = 1195624
compile_seconds = 0.0
samples = 3
seconds = 0.0006636

[probes.negative]
allocations = 46263
bytes = 1722216
compile_seconds = 0.0
samples = 3
seconds = 0.0009139

[probes.positive]
allocations = 46263
bytes = 1719672
compile_seconds = 0.0
samples = 3
seconds = 0.0008149

[probes.unit_negative]
allocations = 43575
bytes = 1613688
compile_seconds = 0.0
samples = 3
seconds = 0.0008187

[probes.unit_positive]
allocations = 42807
bytes = 1591944
compile_seconds = 0.0
samples = 3
seconds = 0.0008739

[probes.variable]
allocations = 45879
bytes = 1697304
compile_seconds = 0.0
samples = 3
seconds = 0.0009454
