julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.adlittle.dual]
allocations = 83444
bytes = 4080952
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035415
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009586
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81429
bytes = 3290520
compile_seconds = 0.0
samples = 3
seconds = 0.0021109

[datasets.adlittle.primal]
allocations = 84242
bytes = 4357208
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003599
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607200
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011569
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641704
compile_seconds = 0.0
samples = 3
seconds = 0.0004

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.66e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 156904
compile_seconds = 0.0
samples = 3
seconds = 0.0001312

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 16468
bytes = 841880
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007989
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002103
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15653
bytes = 706376
compile_seconds = 0.0
samples = 3
seconds = 0.0006023

[datasets.afiro.primal]
allocations = 16374
bytes = 820344
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007749
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002196
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92600
compile_seconds = 0.0
samples = 3
seconds = 0.0001484

[datasets.afiro.singleton]
allocations = 747
bytes = 40976
compile_seconds = 0.0
samples = 3
seconds = 8.16e-5

[datasets.afiro.sparse]
allocations = 4167
bytes = 186920
compile_seconds = 0.0
samples = 3
seconds = 0.0001494

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 28749
bytes = 1173832
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009576
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001643
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 28078
bytes = 1064352
compile_seconds = 0.0
samples = 3
seconds = 0.0007358

[datasets.flugpl.primal]
allocations = 29098
bytes = 1218056
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009187
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002156
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122672
compile_seconds = 0.0
samples = 3
seconds = 9.96e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.69e-5

[datasets.flugpl.sparse]
allocations = 4677
bytes = 174096
compile_seconds = 0.0
samples = 3
seconds = 0.0001337

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.kb2.dual]
allocations = 229111
bytes = 11045104
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0208419
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008722
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227909
bytes = 10590928
compile_seconds = 0.0
samples = 3
seconds = 0.0195914

[datasets.kb2.primal]
allocations = 229278
bytes = 11057808
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020450599
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006431
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454672
compile_seconds = 0.0
samples = 3
seconds = 0.0002955

[datasets.kb2.singleton]
allocations = 1915
bytes = 105384
compile_seconds = 0.0
samples = 3
seconds = 9.49e-5

[datasets.kb2.sparse]
allocations = 2259
bytes = 137336
compile_seconds = 0.0
samples = 3
seconds = 0.0001323

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.8e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.sc50a.dual]
allocations = 67374
bytes = 3148616
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021365
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005636
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66302
bytes = 2803304
compile_seconds = 0.0
samples = 3
seconds = 0.001611

[datasets.sc50a.primal]
allocations = 67319
bytes = 3101416
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021187
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005409
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222352
compile_seconds = 0.0
samples = 3
seconds = 0.0001581

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[datasets.sc50a.sparse]
allocations = 6174
bytes = 282496
compile_seconds = 0.0
samples = 3
seconds = 0.0001885

[probes.fraction_negative]
allocations = 66899
bytes = 2569488
compile_seconds = 0.0
samples = 3
seconds = 0.001216

[probes.fraction_positive]
allocations = 66899
bytes = 2569856
compile_seconds = 0.0
samples = 3
seconds = 0.0012106

[probes.free_pivot]
allocations = 44115
bytes = 1846752
compile_seconds = 0.0
samples = 3
seconds = 0.0008781

[probes.integer_negative]
allocations = 66643
bytes = 2546848
compile_seconds = 0.0
samples = 3
seconds = 0.0011867

[probes.integer_positive]
allocations = 66643
bytes = 2544816
compile_seconds = 0.0
samples = 3
seconds = 0.001408399

[probes.unequal]
allocations = 69971
bytes = 2675520
compile_seconds = 0.0
samples = 3
seconds = 0.0012311
