julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.adlittle.dual]
allocations = 84772
bytes = 4137344
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003547719
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461288
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000891104
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82757
bytes = 3348224
compile_seconds = 0.0
samples = 3
seconds = 0.00193901

[datasets.adlittle.primal]
allocations = 85570
bytes = 4414336
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003665219
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607264
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001090906
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.69e-5

[datasets.adlittle.sparse]
allocations = 2824
bytes = 177784
compile_seconds = 0.0
samples = 3
seconds = 0.000128

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 17108
bytes = 867064
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000794004
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000207701
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16293
bytes = 731720
compile_seconds = 0.0
samples = 3
seconds = 0.000812801

[datasets.afiro.primal]
allocations = 17014
bytes = 845656
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000763004
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000206801
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44528
compile_seconds = 0.0
samples = 3
seconds = 7.76e-5

[datasets.afiro.sparse]
allocations = 4950
bytes = 217480
compile_seconds = 0.0
samples = 3
seconds = 0.0001544

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309808
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000923206
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000146901
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1200104
compile_seconds = 0.0
samples = 3
seconds = 0.000753306

[datasets.flugpl.primal]
allocations = 32481
bytes = 1354208
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001063807
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000192801
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.71e-5

[datasets.flugpl.sparse]
allocations = 5763
bytes = 217928
compile_seconds = 0.0
samples = 3
seconds = 0.000158801

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.dual]
allocations = 231179
bytes = 11131128
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020510808
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000796204
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229977
bytes = 10679688
compile_seconds = 0.0
samples = 3
seconds = 0.020032605

[datasets.kb2.primal]
allocations = 231346
bytes = 11145496
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020810103
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000614003
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111632
compile_seconds = 0.0
samples = 3
seconds = 0.0001004

[datasets.kb2.sparse]
allocations = 2836
bytes = 162560
compile_seconds = 0.0
samples = 3
seconds = 0.000111001

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.86e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.sc50a.dual]
allocations = 68680
bytes = 3198640
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002096401
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000551
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67608
bytes = 2854480
compile_seconds = 0.0
samples = 3
seconds = 0.001535301

[datasets.sc50a.primal]
allocations = 68625
bytes = 3151504
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002152014
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004831
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.87e-5

[datasets.sc50a.sparse]
allocations = 6635
bytes = 300368
compile_seconds = 0.0
samples = 3
seconds = 0.0002049

[probes.negative]
allocations = 45893
bytes = 1775152
compile_seconds = 0.0
samples = 3
seconds = 0.000900301

[probes.nonzero_rhs]
allocations = 54085
bytes = 2077392
compile_seconds = 0.0
samples = 3
seconds = 0.001088901

[probes.positive]
allocations = 45893
bytes = 1773056
compile_seconds = 0.0
samples = 3
seconds = 0.000915601

[probes.unit_negative]
allocations = 44357
bytes = 1707248
compile_seconds = 0.0
samples = 3
seconds = 0.000910101

[probes.unit_positive]
allocations = 43845
bytes = 1693968
compile_seconds = 0.0
samples = 3
seconds = 0.000909901

[probes.zero_ratio]
allocations = 38469
bytes = 1507040
compile_seconds = 0.0
samples = 3
seconds = 0.000857001
