julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.adlittle.dual]
allocations = 83266
bytes = 4073568
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003317903
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461032
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000948101
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81251
bytes = 3283136
compile_seconds = 0.0
samples = 3
seconds = 0.002012902

[datasets.adlittle.primal]
allocations = 84064
bytes = 4350352
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003319004
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607200
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001104701
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641176
compile_seconds = 0.0
samples = 3
seconds = 0.000338

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.03e-5

[datasets.adlittle.sparse]
allocations = 2282
bytes = 154584
compile_seconds = 0.0
samples = 3
seconds = 0.0001316

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.afiro.dual]
allocations = 16441
bytes = 841560
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000746801
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002107
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15626
bytes = 706168
compile_seconds = 0.0
samples = 3
seconds = 0.000572201

[datasets.afiro.primal]
allocations = 16347
bytes = 819016
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000696601
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000205701
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92904
compile_seconds = 0.0
samples = 3
seconds = 9.78e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40960
compile_seconds = 0.0
samples = 3
seconds = 7.91e-5

[datasets.afiro.sparse]
allocations = 4116
bytes = 185400
compile_seconds = 0.0
samples = 3
seconds = 0.0001632

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.flugpl.dual]
allocations = 28027
bytes = 1145664
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000778001
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001441
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 27356
bytes = 1036488
compile_seconds = 0.0
samples = 3
seconds = 0.0006036

[datasets.flugpl.primal]
allocations = 28376
bytes = 1190576
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007337
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001872
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123984
compile_seconds = 0.0
samples = 3
seconds = 8.18e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.flugpl.sparse]
allocations = 4484
bytes = 166584
compile_seconds = 0.0
samples = 3
seconds = 0.0001151

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.kb2.dual]
allocations = 228643
bytes = 11029528
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020321007
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000810601
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227441
bytes = 10575896
compile_seconds = 0.0
samples = 3
seconds = 0.020150719

[datasets.kb2.primal]
allocations = 228810
bytes = 11042488
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020289807
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006224
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454704
compile_seconds = 0.0
samples = 3
seconds = 0.000241401

[datasets.kb2.singleton]
allocations = 1915
bytes = 105432
compile_seconds = 0.0
samples = 3
seconds = 8.4e-5

[datasets.kb2.sparse]
allocations = 2207
bytes = 135464
compile_seconds = 0.0
samples = 3
seconds = 0.0001067

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.46e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 67169
bytes = 3142392
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0017909
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306432
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006095
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66097
bytes = 2796856
compile_seconds = 0.0
samples = 3
seconds = 0.001378301

[datasets.sc50a.primal]
allocations = 67114
bytes = 3095096
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018275
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005168
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222880
compile_seconds = 0.0
samples = 3
seconds = 0.0001391

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.61e-5

[datasets.sc50a.sparse]
allocations = 6081
bytes = 280256
compile_seconds = 0.0
samples = 3
seconds = 0.0001726

[probes.lower_only]
allocations = 39735
bytes = 1511528
compile_seconds = 0.0
samples = 3
seconds = 0.0007623

[probes.negative]
allocations = 42295
bytes = 1588408
compile_seconds = 0.0
samples = 3
seconds = 0.0008867

[probes.positive]
allocations = 42295
bytes = 1585672
compile_seconds = 0.0
samples = 3
seconds = 0.0008159

[probes.upper_only]
allocations = 39351
bytes = 1487544
compile_seconds = 0.0
samples = 3
seconds = 0.0007621

[probes.variable]
allocations = 45879
bytes = 1697384
compile_seconds = 0.0
samples = 3
seconds = 0.0008648

[probes.zero_activity]
allocations = 38967
bytes = 1479192
compile_seconds = 0.0
samples = 3
seconds = 0.0007845
