julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.adlittle.dual]
allocations = 83570
bytes = 4084296
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003346201
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009133
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 81555
bytes = 3295032
compile_seconds = 0.0
samples = 3
seconds = 0.0021418

[datasets.adlittle.primal]
allocations = 84368
bytes = 4360968
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034255
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010995
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641672
compile_seconds = 0.0
samples = 3
seconds = 0.0003958

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.95e-5

[datasets.adlittle.sparse]
allocations = 2339
bytes = 156408
compile_seconds = 0.0
samples = 3
seconds = 9.55e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 16528
bytes = 844616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007214
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001984
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15713
bytes = 708568
compile_seconds = 0.0
samples = 3
seconds = 0.0005424

[datasets.afiro.primal]
allocations = 16434
bytes = 822472
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007402
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002085
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92872
compile_seconds = 0.0
samples = 3
seconds = 9.16e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40672
compile_seconds = 0.0
samples = 3
seconds = 7.55e-5

[datasets.afiro.sparse]
allocations = 4243
bytes = 190160
compile_seconds = 0.0
samples = 3
seconds = 0.0001538

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 30015
bytes = 1224168
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008521
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001505
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 29344
bytes = 1115040
compile_seconds = 0.0
samples = 3
seconds = 0.0006728

[datasets.flugpl.primal]
allocations = 30364
bytes = 1268920
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000895
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001858
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123568
compile_seconds = 0.0
samples = 3
seconds = 8.66e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.89e-5

[datasets.flugpl.sparse]
allocations = 5063
bytes = 190472
compile_seconds = 0.0
samples = 3
seconds = 0.0001106

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.dual]
allocations = 229333
bytes = 11054264
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020489001
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008193
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 228131
bytes = 10600200
compile_seconds = 0.0
samples = 3
seconds = 0.020936301

[datasets.kb2.primal]
allocations = 229500
bytes = 11067320
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0203589
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006002
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454944
compile_seconds = 0.0
samples = 3
seconds = 0.0002544

[datasets.kb2.singleton]
allocations = 1915
bytes = 104760
compile_seconds = 0.0
samples = 3
seconds = 8.74e-5

[datasets.kb2.sparse]
allocations = 2371
bytes = 141904
compile_seconds = 0.0
samples = 3
seconds = 9.53e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.sc50a.dual]
allocations = 67569
bytes = 3156136
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019346
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306320
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005836
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 66497
bytes = 2809800
compile_seconds = 0.0
samples = 3
seconds = 0.0016139

[datasets.sc50a.primal]
allocations = 67514
bytes = 3108808
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019168
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004878
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222864
compile_seconds = 0.0
samples = 3
seconds = 0.0001514

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.13e-5

[datasets.sc50a.sparse]
allocations = 6234
bytes = 285168
compile_seconds = 0.0
samples = 3
seconds = 0.0001688

[probes.bound_negative]
allocations = 49335
bytes = 1828552
compile_seconds = 0.0
samples = 3
seconds = 0.0009128

[probes.bound_positive]
allocations = 49335
bytes = 1828600
compile_seconds = 0.0
samples = 3
seconds = 0.0009061

[probes.coefficient_negative]
allocations = 58565
bytes = 2193488
compile_seconds = 0.0
samples = 3
seconds = 0.0010804

[probes.coefficient_positive]
allocations = 58309
bytes = 2183456
compile_seconds = 0.0
samples = 3
seconds = 0.0012013

[probes.nonunit]
allocations = 60229
bytes = 2248192
compile_seconds = 0.0
samples = 3
seconds = 0.0010792

[probes.zero_bounds]
allocations = 42423
bytes = 1611288
compile_seconds = 0.0
samples = 3
seconds = 0.0007716
