julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84962
bytes = 4141824
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034465
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461240
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010362
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82947
bytes = 3351600
compile_seconds = 0.0
samples = 3
seconds = 0.002274001

[datasets.adlittle.primal]
allocations = 85760
bytes = 4418608
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038288
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012506
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 9.61e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 175664
compile_seconds = 0.0
samples = 3
seconds = 0.0001369

[datasets.afiro.dual]
allocations = 17306
bytes = 873616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0010163
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002375
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16491
bytes = 737520
compile_seconds = 0.0
samples = 3
seconds = 0.0007071

[datasets.afiro.primal]
allocations = 17212
bytes = 852192
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007417
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002248
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44928
compile_seconds = 0.0
samples = 3
seconds = 9.07e-5

[datasets.afiro.sparse]
allocations = 5241
bytes = 227872
compile_seconds = 0.0
samples = 3
seconds = 0.0002026

[datasets.flugpl.dual]
allocations = 32286
bytes = 1312776
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009234
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001609
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1203088
compile_seconds = 0.0
samples = 3
seconds = 0.000718

[datasets.flugpl.primal]
allocations = 32635
bytes = 1357336
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009701
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002126
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.23e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 214344
compile_seconds = 0.0
samples = 3
seconds = 0.0001532

[datasets.kb2.dual]
allocations = 231256
bytes = 11132808
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021239805
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878320
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008974
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230054
bytes = 10679656
compile_seconds = 0.0
samples = 3
seconds = 0.021855905

[datasets.kb2.primal]
allocations = 231423
bytes = 11146088
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021467805
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006658
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111760
compile_seconds = 0.0
samples = 3
seconds = 0.0001221

[datasets.kb2.sparse]
allocations = 2903
bytes = 162160
compile_seconds = 0.0
samples = 3
seconds = 0.0001256

[datasets.sc50a.dual]
allocations = 69213
bytes = 3219608
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002271101
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306384
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006291
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 68141
bytes = 2872680
compile_seconds = 0.0
samples = 3
seconds = 0.0016787

[datasets.sc50a.primal]
allocations = 69158
bytes = 3171592
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021302
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005959
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.83e-5

[datasets.sc50a.sparse]
allocations = 7011
bytes = 313536
compile_seconds = 0.0
samples = 3
seconds = 0.0002053

[probes.multiplier_negative]
allocations = 37591
bytes = 1401472
compile_seconds = 0.0
samples = 3
seconds = 0.0008005

[probes.multiplier_positive]
allocations = 37079
bytes = 1386176
compile_seconds = 0.0
samples = 3
seconds = 0.0007885

[probes.nonunit]
allocations = 39383
bytes = 1474336
compile_seconds = 0.0
samples = 3
seconds = 0.000769801

[probes.term_negative]
allocations = 38487
bytes = 1438128
compile_seconds = 0.0
samples = 3
seconds = 0.0008005

[probes.term_positive]
allocations = 38228
bytes = 1431160
compile_seconds = 0.0
samples = 3
seconds = 0.0007779

[probes.zero]
allocations = 29142
bytes = 1108392
compile_seconds = 0.0
samples = 3
seconds = 0.0006205
