julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.adlittle.dual]
allocations = 84708
bytes = 4132848
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003557609
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001006103
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82693
bytes = 3345520
compile_seconds = 0.0
samples = 3
seconds = 0.002369206

[datasets.adlittle.primal]
allocations = 85506
bytes = 4409408
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003806309
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001177503
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.2401e-5

[datasets.adlittle.sparse]
allocations = 2792
bytes = 176056
compile_seconds = 0.0
samples = 3
seconds = 0.000132101

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.afiro.dual]
allocations = 17092
bytes = 866216
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000852702
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000204901
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16277
bytes = 729880
compile_seconds = 0.0
samples = 3
seconds = 0.000528601

[datasets.afiro.primal]
allocations = 16998
bytes = 844424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000721901
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000218801
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45504
compile_seconds = 0.0
samples = 3
seconds = 0.0001117

[datasets.afiro.sparse]
allocations = 4935
bytes = 215704
compile_seconds = 0.0
samples = 3
seconds = 0.0001935

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1290576
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000999701
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001226
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1181224
compile_seconds = 0.0
samples = 3
seconds = 0.000656901

[datasets.flugpl.primal]
allocations = 32031
bytes = 1335184
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000899101
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000203001
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.76e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210296
compile_seconds = 0.0
samples = 3
seconds = 0.000125901

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 231134
bytes = 11129992
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0203305
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007973
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229932
bytes = 10676168
compile_seconds = 0.0
samples = 3
seconds = 0.0206769

[datasets.kb2.primal]
allocations = 231301
bytes = 11143832
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022246923
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000538801
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112656
compile_seconds = 0.0
samples = 3
seconds = 9.27e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162032
compile_seconds = 0.0
samples = 3
seconds = 0.000134101

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.51e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.sc50a.dual]
allocations = 68610
bytes = 3196024
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002174402
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000561301
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67538
bytes = 2849176
compile_seconds = 0.0
samples = 3
seconds = 0.001569202

[datasets.sc50a.primal]
allocations = 68555
bytes = 3149080
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002052502
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000515501
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.41e-5

[datasets.sc50a.sparse]
allocations = 6625
bytes = 299544
compile_seconds = 0.0
samples = 3
seconds = 0.000185

[probes.negative]
allocations = 43845
bytes = 1692448
compile_seconds = 0.0
samples = 3
seconds = 0.000959

[probes.nonzero_rhs]
allocations = 54085
bytes = 2076544
compile_seconds = 0.0
samples = 3
seconds = 0.0010509

[probes.positive]
allocations = 43845
bytes = 1690240
compile_seconds = 0.0
samples = 3
seconds = 0.0010142

[probes.unit_negative]
allocations = 42949
bytes = 1656624
compile_seconds = 0.0
samples = 3
seconds = 0.0009295

[probes.unit_positive]
allocations = 42693
bytes = 1649120
compile_seconds = 0.0
samples = 3
seconds = 0.000934

[probes.zero_ratio]
allocations = 38469
bytes = 1506608
compile_seconds = 0.0
samples = 3
seconds = 0.0008555
