julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 84980
bytes = 4147136
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003234099
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461048
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000965
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82965
bytes = 3357632
compile_seconds = 0.0
samples = 3
seconds = 0.0019045

[datasets.adlittle.primal]
allocations = 85778
bytes = 4424704
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034551
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607152
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010746
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.06e-5

[datasets.adlittle.sparse]
allocations = 2861
bytes = 177664
compile_seconds = 0.0
samples = 3
seconds = 0.0001232

[datasets.afiro.dual]
allocations = 17554
bytes = 886032
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007701
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002179
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16739
bytes = 750704
compile_seconds = 0.0
samples = 3
seconds = 0.0005607

[datasets.afiro.primal]
allocations = 17460
bytes = 864096
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006976
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002058
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44688
compile_seconds = 0.0
samples = 3
seconds = 8.93e-5

[datasets.afiro.sparse]
allocations = 5587
bytes = 243584
compile_seconds = 0.0
samples = 3
seconds = 0.0001629

[datasets.flugpl.dual]
allocations = 32286
bytes = 1315560
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008142
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001448
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31615
bytes = 1205520
compile_seconds = 0.0
samples = 3
seconds = 0.0006348

[datasets.flugpl.primal]
allocations = 32635
bytes = 1360008
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000895
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002025
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.11e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216568
compile_seconds = 0.0
samples = 3
seconds = 0.0001199

[datasets.kb2.dual]
allocations = 231326
bytes = 11143400
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.019912198
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878048
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008227
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230124
bytes = 10688024
compile_seconds = 0.0
samples = 3
seconds = 0.019309998

[datasets.kb2.primal]
allocations = 231493
bytes = 11156872
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020660898
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005999
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112240
compile_seconds = 0.0
samples = 3
seconds = 0.0001017

[datasets.kb2.sparse]
allocations = 3028
bytes = 169232
compile_seconds = 0.0
samples = 3
seconds = 0.0001224

[datasets.sc50a.dual]
allocations = 70130
bytes = 3261128
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021068
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005446
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 69058
bytes = 2914744
compile_seconds = 0.0
samples = 3
seconds = 0.0014229

[datasets.sc50a.primal]
allocations = 70075
bytes = 3213768
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018707
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000534999
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[datasets.sc50a.sparse]
allocations = 7651
bytes = 342128
compile_seconds = 0.0
samples = 3
seconds = 0.0001908

[probes.negative_negative]
allocations = 30804
bytes = 1151880
compile_seconds = 0.0
samples = 3
seconds = 0.0006307

[probes.negative_positive]
allocations = 30807
bytes = 1151808
compile_seconds = 0.0
samples = 3
seconds = 0.0006049

[probes.nonzero]
allocations = 37070
bytes = 1389640
compile_seconds = 0.0
samples = 3
seconds = 0.0006562

[probes.positive_negative]
allocations = 30039
bytes = 1129984
compile_seconds = 0.0
samples = 3
seconds = 0.0005993

[probes.positive_positive]
allocations = 30036
bytes = 1128568
compile_seconds = 0.0
samples = 3
seconds = 0.0005649

[probes.singleton]
allocations = 17152
bytes = 679992
compile_seconds = 0.0
samples = 3
seconds = 0.0003397
