julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 19
bytes = 5008
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.adlittle.dual]
allocations = 123556
bytes = 5830648
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.004066
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1330
bytes = 464328
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000889499
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 121537
bytes = 5037752
compile_seconds = 0.0
samples = 3
seconds = 0.0024791

[datasets.adlittle.primal]
allocations = 124354
bytes = 6107048
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003991099
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1903
bytes = 610672
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011262
status = "OPTIMAL"

[datasets.afiro.basic]
allocations = 19
bytes = 2448
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.afiro.dual]
allocations = 28670
bytes = 1343208
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008949
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 559
bytes = 91088
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000183
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27851
bytes = 1206056
compile_seconds = 0.0
samples = 3
seconds = 0.0006445

[datasets.afiro.primal]
allocations = 28576
bytes = 1322328
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000899
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 763
bytes = 122928
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002042
status = "OPTIMAL"

[datasets.flugpl.basic]
allocations = 19
bytes = 1792
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.flugpl.dual]
allocations = 39965
bytes = 1621976
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009621
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 380
bytes = 43488
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001478
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39290
bytes = 1511968
compile_seconds = 0.0
samples = 3
seconds = 0.0008032

[datasets.flugpl.primal]
allocations = 40314
bytes = 1666664
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010478
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 743
bytes = 92416
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002113
status = "OPTIMAL"

[datasets.kb2.basic]
allocations = 19
bytes = 3216
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.kb2.dual]
allocations = 294316
bytes = 13791776
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021531599
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1512
bytes = 879888
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008088
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 293110
bytes = 13335712
compile_seconds = 0.0
samples = 3
seconds = 0.0209065

[datasets.kb2.primal]
allocations = 294483
bytes = 13805232
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020947899
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1058
bytes = 262384
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000596799
status = "OPTIMAL"

[datasets.sc50a.basic]
allocations = 64
bytes = 19616
compile_seconds = 0.0
samples = 3
seconds = 1.38e-5

[datasets.sc50a.dual]
allocations = 107531
bytes = 4695360
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.00255
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 965
bytes = 307840
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005816
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106455
bytes = 4347792
compile_seconds = 0.0
samples = 3
seconds = 0.0022069

[datasets.sc50a.primal]
allocations = 107476
bytes = 4648400
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002627
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 968
bytes = 233928
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005187
status = "OPTIMAL"

[probes.reduced_dense]
allocations = 103
bytes = 549032
compile_seconds = 0.0
samples = 3
seconds = 0.000145

[probes.unchanged_dense]
allocations = 21
bytes = 8320
compile_seconds = 0.0
samples = 3
seconds = 3.44e-5
