julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4046856
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035692
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461656
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0011101
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3258648
compile_seconds = 0.0
samples = 3
seconds = 0.0022167

[datasets.adlittle.primal]
allocations = 83190
bytes = 4323560
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0040075
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011176
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642024
compile_seconds = 0.0
samples = 3
seconds = 0.0003954

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.84e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 128024
compile_seconds = 0.0
samples = 3
seconds = 0.0001425

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 835384
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008102
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002189
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 699480
compile_seconds = 0.0
samples = 3
seconds = 0.0005965

[datasets.afiro.primal]
allocations = 16131
bytes = 813384
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006415
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001686
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93416
compile_seconds = 0.0
samples = 3
seconds = 0.0001088

[datasets.afiro.singleton]
allocations = 747
bytes = 41568
compile_seconds = 0.0
samples = 3
seconds = 7.82e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 173920
compile_seconds = 0.0
samples = 3
seconds = 0.0001457

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.7e-6

[datasets.flugpl.dual]
allocations = 26397
bytes = 1099840
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010411
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000163
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25726
bytes = 990456
compile_seconds = 0.0
samples = 3
seconds = 0.000729001

[datasets.flugpl.primal]
allocations = 26746
bytes = 1144192
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011278
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001562
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123872
compile_seconds = 0.0
samples = 3
seconds = 0.00012

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.63e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 150088
compile_seconds = 0.0
samples = 3
seconds = 0.0001174

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11015128
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020709004
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878000
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008467
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10561128
compile_seconds = 0.0
samples = 3
seconds = 0.020611404

[datasets.kb2.primal]
allocations = 228386
bytes = 11029896
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021251104
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000568401
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454720
compile_seconds = 0.0
samples = 3
seconds = 0.0002891

[datasets.kb2.singleton]
allocations = 1915
bytes = 105448
compile_seconds = 0.0
samples = 3
seconds = 8.82e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127928
compile_seconds = 0.0
samples = 3
seconds = 0.0001101

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.63e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3108848
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021781
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306528
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006046
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2763456
compile_seconds = 0.0
samples = 3
seconds = 0.00165

[datasets.sc50a.primal]
allocations = 65958
bytes = 3061664
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002154901
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005608
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222896
compile_seconds = 0.0
samples = 3
seconds = 0.0001717

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.34e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 262832
compile_seconds = 0.0
samples = 3
seconds = 0.0001749

[probes.cancelled]
allocations = 6356
bytes = 263664
compile_seconds = 0.0
samples = 3
seconds = 0.000154901

[probes.negative]
allocations = 7124
bytes = 288912
compile_seconds = 0.0
samples = 3
seconds = 0.0001881

[probes.positive]
allocations = 7124
bytes = 287696
compile_seconds = 0.0
samples = 3
seconds = 0.000211201

[probes.unequal]
allocations = 11476
bytes = 449264
compile_seconds = 0.0
samples = 3
seconds = 0.0002793

[probes.zero_bound]
allocations = 4948
bytes = 218944
compile_seconds = 0.0
samples = 3
seconds = 0.000155901

[probes.zero_shift]
allocations = 81
bytes = 28648
compile_seconds = 0.0
samples = 3
seconds = 3.38e-5
