julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84962
bytes = 4142480
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003359803
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000902401
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82947
bytes = 3354432
compile_seconds = 0.0
samples = 3
seconds = 0.001983102

[datasets.adlittle.primal]
allocations = 85760
bytes = 4419232
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003429502
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 606992
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001113701
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.8e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 178608
compile_seconds = 0.0
samples = 3
seconds = 0.0001072

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 869160
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007072
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002165
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733576
compile_seconds = 0.0
samples = 3
seconds = 0.000544

[datasets.afiro.primal]
allocations = 17051
bytes = 847752
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007383
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001806
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44800
compile_seconds = 0.0
samples = 3
seconds = 8.17e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 219288
compile_seconds = 0.0
samples = 3
seconds = 0.0001574

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 32206
bytes = 1313680
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008309
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001359
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31535
bytes = 1203560
compile_seconds = 0.0
samples = 3
seconds = 0.000666601

[datasets.flugpl.primal]
allocations = 32555
bytes = 1358176
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000871701
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000185
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 218392
compile_seconds = 0.0
samples = 3
seconds = 0.000123301

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132504
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020776014
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000805401
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10680136
compile_seconds = 0.0
samples = 3
seconds = 0.020554914

[datasets.kb2.primal]
allocations = 231373
bytes = 11147512
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020546114
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005887
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112144
compile_seconds = 0.0
samples = 3
seconds = 8.53e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161968
compile_seconds = 0.0
samples = 3
seconds = 0.0001187

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.62e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199696
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001932301
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306352
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005068
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2854208
compile_seconds = 0.0
samples = 3
seconds = 0.001463701

[datasets.sc50a.primal]
allocations = 68651
bytes = 3152560
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002039502
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000450001
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 301776
compile_seconds = 0.0
samples = 3
seconds = 0.0001716

[probes.both_negative]
allocations = 2829
bytes = 129672
compile_seconds = 0.0
samples = 3
seconds = 9.25e-5

[probes.finite]
allocations = 12045
bytes = 478888
compile_seconds = 0.0
samples = 3
seconds = 0.0002625

[probes.negative_coefficient]
allocations = 2829
bytes = 129720
compile_seconds = 0.0
samples = 3
seconds = 7.98e-5

[probes.negative_value]
allocations = 2829
bytes = 129704
compile_seconds = 0.0
samples = 3
seconds = 9.11e-5

[probes.one_sided]
allocations = 7437
bytes = 305464
compile_seconds = 0.0
samples = 3
seconds = 0.0001804

[probes.positive]
allocations = 2829
bytes = 128712
compile_seconds = 0.0
samples = 3
seconds = 8.86e-5
