julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4138040
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003134601
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461720
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000901301
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3349080
compile_seconds = 0.0
samples = 3
seconds = 0.001807501

[datasets.adlittle.primal]
allocations = 85589
bytes = 4414760
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003224502
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607312
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010148
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.09e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 178608
compile_seconds = 0.0
samples = 3
seconds = 8.94e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 869496
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006903
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001792
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733384
compile_seconds = 0.0
samples = 3
seconds = 0.0004918

[datasets.afiro.primal]
allocations = 17051
bytes = 846968
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000629901
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001763
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44864
compile_seconds = 0.0
samples = 3
seconds = 6.75e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 219272
compile_seconds = 0.0
samples = 3
seconds = 0.0001736

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1310544
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007727
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001423
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1200648
compile_seconds = 0.0
samples = 3
seconds = 0.0006143

[datasets.flugpl.primal]
allocations = 32481
bytes = 1355088
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008484
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001528
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.82e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 218056
compile_seconds = 0.0
samples = 3
seconds = 0.0001339

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11134008
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.019996508
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007735
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10680248
compile_seconds = 0.0
samples = 3
seconds = 0.019535409

[datasets.kb2.primal]
allocations = 231373
bytes = 11146856
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020536908
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000545
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112576
compile_seconds = 0.0
samples = 3
seconds = 8.17e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162432
compile_seconds = 0.0
samples = 3
seconds = 0.0001098

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.3e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199472
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018994
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005465
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853872
compile_seconds = 0.0
samples = 3
seconds = 0.0014277

[datasets.sc50a.primal]
allocations = 68651
bytes = 3152160
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001823701
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004957
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.46e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 301408
compile_seconds = 0.0
samples = 3
seconds = 0.0001529

[probes.cancel_negative]
allocations = 7364
bytes = 293504
compile_seconds = 0.0
samples = 3
seconds = 0.0001723

[probes.cancel_positive]
allocations = 7364
bytes = 292496
compile_seconds = 0.0
samples = 3
seconds = 0.0001993

[probes.negative_sum]
allocations = 8900
bytes = 343504
compile_seconds = 0.0
samples = 3
seconds = 0.000158299

[probes.positive_sum]
allocations = 8900
bytes = 343552
compile_seconds = 0.0
samples = 3
seconds = 0.0001664

[probes.unequal_denominator]
allocations = 8900
bytes = 343536
compile_seconds = 0.0
samples = 3
seconds = 0.0001697

[probes.zero_contribution]
allocations = 1604
bytes = 75664
compile_seconds = 0.0
samples = 3
seconds = 5.67e-5
