["greenbea/mixed"]
nonzeros = 7574
rows = 2392

    ["greenbea/mixed".after]
    allocations = 9
    bytes = 140632
    compile_seconds = 0.0
    samples = 3
    seconds = 5.24e-5

    ["greenbea/mixed".before]
    allocations = 21
    bytes = 300472
    compile_seconds = 0.0
    samples = 3
    seconds = 0.0001171

["greenbea/slack"]
nonzeros = 2392
rows = 2392

    ["greenbea/slack".after]
    allocations = 9
    bytes = 57688
    compile_seconds = 0.0
    samples = 3
    seconds = 3.48e-5

    ["greenbea/slack".before]
    allocations = 21
    bytes = 134584
    compile_seconds = 0.0
    samples = 3
    seconds = 5.71e-5

["tridiagonal512/mixed"]
nonzeros = 1023
rows = 512

    ["tridiagonal512/mixed".after]
    allocations = 9
    bytes = 20760
    compile_seconds = 0.0
    samples = 3
    seconds = 1.66e-5

    ["tridiagonal512/mixed".before]
    allocations = 21
    bytes = 45688
    compile_seconds = 0.0
    samples = 3
    seconds = 3.37e-5

["tridiagonal512/slack"]
nonzeros = 512
rows = 512

    ["tridiagonal512/slack".after]
    allocations = 9
    bytes = 12568
    compile_seconds = 0.0
    samples = 3
    seconds = 1.19e-5

    ["tridiagonal512/slack".before]
    allocations = 21
    bytes = 29304
    compile_seconds = 0.0
    samples = 3
    seconds = 1.67e-5
