julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4046584
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003069203
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461864
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000980001
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3257992
compile_seconds = 0.0
samples = 3
seconds = 0.001972202

[datasets.adlittle.primal]
allocations = 83190
bytes = 4322904
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003485902
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.000998401
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641288
compile_seconds = 0.0
samples = 3
seconds = 0.00033

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.04e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 127768
compile_seconds = 0.0
samples = 3
seconds = 0.0001103

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 834728
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000744501
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002111
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 698968
compile_seconds = 0.0
samples = 3
seconds = 0.0005666

[datasets.afiro.primal]
allocations = 16131
bytes = 812888
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007129
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000213401
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93528
compile_seconds = 0.0
samples = 3
seconds = 8.08e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 41888
compile_seconds = 0.0
samples = 3
seconds = 0.000100899

[datasets.afiro.sparse]
allocations = 3736
bytes = 173648
compile_seconds = 0.0
samples = 3
seconds = 0.0001433

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 26431
bytes = 1100960
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007685
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001529
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25760
bytes = 990840
compile_seconds = 0.0
samples = 3
seconds = 0.0005829

[datasets.flugpl.primal]
allocations = 26780
bytes = 1145408
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007851
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001646
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123664
compile_seconds = 0.0
samples = 3
seconds = 9.58e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.68e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 149672
compile_seconds = 0.0
samples = 3
seconds = 0.0001062

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11014568
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020126116
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000804301
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10561176
compile_seconds = 0.0
samples = 3
seconds = 0.019761215

[datasets.kb2.primal]
allocations = 228386
bytes = 11028296
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020575416
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260928
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005804
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454176
compile_seconds = 0.0
samples = 3
seconds = 0.0002327

[datasets.kb2.singleton]
allocations = 1915
bytes = 105272
compile_seconds = 0.0
samples = 3
seconds = 8.44e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127752
compile_seconds = 0.0
samples = 3
seconds = 0.0001008

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3108400
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001941401
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306592
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005864
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2762368
compile_seconds = 0.0
samples = 3
seconds = 0.0013935

[datasets.sc50a.primal]
allocations = 65958
bytes = 3060800
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002096201
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005114
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222800
compile_seconds = 0.0
samples = 3
seconds = 0.0001432

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.28e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 262960
compile_seconds = 0.0
samples = 3
seconds = 0.0001631

[probes.cancelled]
allocations = 9940
bytes = 398336
compile_seconds = 0.0
samples = 3
seconds = 0.000194699

[probes.negative]
allocations = 11476
bytes = 448112
compile_seconds = 0.0
samples = 3
seconds = 0.000236999

[probes.positive]
allocations = 11476
bytes = 446688
compile_seconds = 0.0
samples = 3
seconds = 0.0002424

[probes.unequal]
allocations = 11476
bytes = 448144
compile_seconds = 0.0
samples = 3
seconds = 0.0002426

[probes.zero_bound]
allocations = 7124
bytes = 309424
compile_seconds = 0.0
samples = 3
seconds = 0.0001784

[probes.zero_shift]
allocations = 81
bytes = 28648
compile_seconds = 0.0
samples = 3
seconds = 2.6e-5
