julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.adlittle.dual]
allocations = 119822
bytes = 5545608
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003738899
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461688
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000957599
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117807
bytes = 4755112
compile_seconds = 0.0
samples = 3
seconds = 0.002412499

[datasets.adlittle.primal]
allocations = 120620
bytes = 5822792
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004030999
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607616
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001145499
status = "OPTIMAL"

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.dual]
allocations = 27568
bytes = 1274664
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009332
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002125
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26753
bytes = 1138248
compile_seconds = 0.0
samples = 3
seconds = 0.0006668

[datasets.afiro.primal]
allocations = 27474
bytes = 1252776
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008531
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002102
status = "OPTIMAL"

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[datasets.flugpl.dual]
allocations = 39760
bytes = 1609872
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009921
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001514
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1499320
compile_seconds = 0.0
samples = 3
seconds = 0.000820501

[datasets.flugpl.primal]
allocations = 40109
bytes = 1654336
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001007901
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001624
status = "OPTIMAL"

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[datasets.kb2.dual]
allocations = 292979
bytes = 13597504
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021155494
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878432
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008283
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291777
bytes = 13144192
compile_seconds = 0.0
samples = 3
seconds = 0.020311394

[datasets.kb2.primal]
allocations = 293146
bytes = 13610960
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020963094
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006177
status = "OPTIMAL"

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.7e-5

[datasets.sc50a.dual]
allocations = 102950
bytes = 4480080
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002608001
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000569
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101878
bytes = 4134912
compile_seconds = 0.0
samples = 3
seconds = 0.001903699

[datasets.sc50a.primal]
allocations = 102895
bytes = 4432800
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0029368
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232248
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000511
status = "OPTIMAL"

[probes.empty]
allocations = 7481
bytes = 268008
compile_seconds = 0.0
samples = 3
seconds = 0.0001302

[probes.fixed]
allocations = 12617
bytes = 512712
compile_seconds = 0.0
samples = 3
seconds = 0.0002505
