julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123628
bytes = 5861672
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003505201
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1332
bytes = 464984
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000881701
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 124436
bytes = 6139384
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038275
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1915
bytes = 611808
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0009925
status = "OPTIMAL"

[datasets.adlittle.restore_basis]
allocations = 13
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.afiro.dual]
allocations = 28734
bytes = 1349352
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008273
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 561
bytes = 91376
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001831
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28640
bytes = 1329320
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007256
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 775
bytes = 123728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001777
status = "OPTIMAL"

[datasets.afiro.restore_basis]
allocations = 13
bytes = 1024
compile_seconds = 0.0
samples = 3
seconds = 2.4e-6

[datasets.flugpl.dual]
allocations = 40017
bytes = 1623720
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008584
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 382
bytes = 43568
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001178
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40376
bytes = 1668856
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000861001
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 755
bytes = 93088
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001367
status = "OPTIMAL"

[datasets.flugpl.restore_basis]
allocations = 13
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.5e-6

[datasets.kb2.dual]
allocations = 294362
bytes = 13801520
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021834704
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1514
bytes = 880048
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000733
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 294529
bytes = 13816432
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022117204
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1060
bytes = 262512
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005422
status = "OPTIMAL"

[datasets.kb2.restore_basis]
allocations = 5
bytes = 576
compile_seconds = 0.0
samples = 3
seconds = 2.0e-6

[datasets.sc50a.dual]
allocations = 107589
bytes = 4702368
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023103
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 967
bytes = 308560
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005355
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107534
bytes = 4655344
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022584
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 970
bytes = 234056
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004223
status = "OPTIMAL"

[datasets.sc50a.restore_basis]
allocations = 5
bytes = 672
compile_seconds = 0.0
samples = 3
seconds = 2.0e-6

[probes.empty]
allocations = 3
bytes = 96
compile_seconds = 0.0
samples = 3
seconds = 1.4e-6

[probes.many_artificials]
allocations = 17
bytes = 23040
compile_seconds = 0.0
samples = 3
seconds = 8.9e-6

[probes.one_artificial]
allocations = 13
bytes = 3584
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6
