julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4136360
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035688
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010085
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3345352
compile_seconds = 0.0
samples = 3
seconds = 0.00225

[datasets.adlittle.primal]
allocations = 85589
bytes = 4412904
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038582
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607616
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011184
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.15e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177536
compile_seconds = 0.0
samples = 3
seconds = 0.0001296

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868184
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009717
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002074
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733032
compile_seconds = 0.0
samples = 3
seconds = 0.0006266

[datasets.afiro.primal]
allocations = 17051
bytes = 846040
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.00079
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002257
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45616
compile_seconds = 0.0
samples = 3
seconds = 8.84e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218968
compile_seconds = 0.0
samples = 3
seconds = 0.0001864

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.flugpl.dual]
allocations = 32168
bytes = 1310768
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010118
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001403
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31497
bytes = 1200696
compile_seconds = 0.0
samples = 3
seconds = 0.0008028

[datasets.flugpl.primal]
allocations = 32517
bytes = 1355392
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010272
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001559
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216808
compile_seconds = 0.0
samples = 3
seconds = 0.0001486

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11131640
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020970501
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877984
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000861
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10678600
compile_seconds = 0.0
samples = 3
seconds = 0.021245501

[datasets.kb2.primal]
allocations = 231373
bytes = 11146584
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021824901
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006647
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 113200
compile_seconds = 0.0
samples = 3
seconds = 0.0001004

[datasets.kb2.sparse]
allocations = 2836
bytes = 161472
compile_seconds = 0.0
samples = 3
seconds = 0.0001131

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.71e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3197840
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023665
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306448
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000602801
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853680
compile_seconds = 0.0
samples = 3
seconds = 0.0016811

[datasets.sc50a.primal]
allocations = 68651
bytes = 3150880
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021863
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005461
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.26e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300448
compile_seconds = 0.0
samples = 3
seconds = 0.0002049

[probes.negative_zero_cost]
allocations = 1604
bytes = 75168
compile_seconds = 0.0
samples = 3
seconds = 7.04e-5

[probes.negative_zero_value]
allocations = 1220
bytes = 64432
compile_seconds = 0.0
samples = 3
seconds = 5.59e-5

[probes.no_elimination]
allocations = 15
bytes = 4080
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[probes.nonzero]
allocations = 8900
bytes = 342816
compile_seconds = 0.0
samples = 3
seconds = 0.0002372

[probes.zero_cost]
allocations = 1604
bytes = 75504
compile_seconds = 0.0
samples = 3
seconds = 6.73e-5

[probes.zero_value]
allocations = 1220
bytes = 64448
compile_seconds = 0.0
samples = 3
seconds = 6.23e-5
