julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 27
bytes = 12144
compile_seconds = 0.0
samples = 3
seconds = 1.47e-5

[datasets.adlittle.dual]
allocations = 123588
bytes = 5859480
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036117
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1330
bytes = 464504
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009592
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 121569
bytes = 5066520
compile_seconds = 0.0
samples = 3
seconds = 0.0025888

[datasets.adlittle.primal]
allocations = 124386
bytes = 6135848
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039462
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1903
bytes = 610672
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010407
status = "OPTIMAL"

[datasets.afiro.basic]
allocations = 25
bytes = 4304
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.afiro.dual]
allocations = 28688
bytes = 1348376
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009047
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 559
bytes = 91072
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001864
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27869
bytes = 1212024
compile_seconds = 0.0
samples = 3
seconds = 0.000825

[datasets.afiro.primal]
allocations = 28594
bytes = 1327432
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008678
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 763
bytes = 122880
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000209
status = "OPTIMAL"

[datasets.flugpl.basic]
allocations = 25
bytes = 2864
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.flugpl.dual]
allocations = 39989
bytes = 1627192
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009628
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 380
bytes = 43472
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001387
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39314
bytes = 1516368
compile_seconds = 0.0
samples = 3
seconds = 0.0007852

[datasets.flugpl.primal]
allocations = 40338
bytes = 1671656
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010064
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 743
bytes = 92416
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001879
status = "OPTIMAL"

[datasets.kb2.basic]
allocations = 27
bytes = 8368
compile_seconds = 0.0
samples = 3
seconds = 1.21e-5

[datasets.kb2.dual]
allocations = 294340
bytes = 13805968
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021652101
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1512
bytes = 879600
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000759201
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 293134
bytes = 13352096
compile_seconds = 0.0
samples = 3
seconds = 0.0205261

[datasets.kb2.primal]
allocations = 294507
bytes = 13819280
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021046601
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1058
bytes = 262368
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000573501
status = "OPTIMAL"

[datasets.sc50a.basic]
allocations = 70
bytes = 22336
compile_seconds = 0.0
samples = 3
seconds = 1.45e-5

[datasets.sc50a.dual]
allocations = 107549
bytes = 4704352
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0026759
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 965
bytes = 307904
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005279
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106473
bytes = 4355296
compile_seconds = 0.0
samples = 3
seconds = 0.0019337

[datasets.sc50a.primal]
allocations = 107494
bytes = 4657136
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025271
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 968
bytes = 233912
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004433
status = "OPTIMAL"

[probes.reduced_dense]
allocations = 111
bytes = 808472
compile_seconds = 0.0
samples = 3
seconds = 0.0001958

[probes.unchanged_dense]
allocations = 29
bytes = 271728
compile_seconds = 0.0
samples = 3
seconds = 7.48e-5
