julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4135512
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003580198
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461688
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000909799
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3347160
compile_seconds = 0.0
samples = 3
seconds = 0.002031299

[datasets.adlittle.primal]
allocations = 85589
bytes = 4413192
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003378999
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607280
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010909
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.54e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 178592
compile_seconds = 0.0
samples = 3
seconds = 0.0001156

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868248
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007056
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002096
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 732712
compile_seconds = 0.0
samples = 3
seconds = 0.000516

[datasets.afiro.primal]
allocations = 17051
bytes = 846824
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007074
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002074
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44928
compile_seconds = 0.0
samples = 3
seconds = 8.67e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218696
compile_seconds = 0.0
samples = 3
seconds = 0.0001558

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 32168
bytes = 1310672
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007798
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001547
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31497
bytes = 1200840
compile_seconds = 0.0
samples = 3
seconds = 0.000668

[datasets.flugpl.primal]
allocations = 32517
bytes = 1355392
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009154
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001683
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.68e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 218008
compile_seconds = 0.0
samples = 3
seconds = 0.0001265

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132376
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020191393
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000834299
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10681336
compile_seconds = 0.0
samples = 3
seconds = 0.019628893

[datasets.kb2.primal]
allocations = 231373
bytes = 11146456
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020393292
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000603
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112000
compile_seconds = 0.0
samples = 3
seconds = 8.69e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162176
compile_seconds = 0.0
samples = 3
seconds = 9.24e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.96e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3198288
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018763
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306592
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.00058
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853200
compile_seconds = 0.0
samples = 3
seconds = 0.0014855

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151136
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019193
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232280
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004729
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.85e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 301152
compile_seconds = 0.0
samples = 3
seconds = 0.0001677

[probes.finite_rows]
allocations = 17732
bytes = 681216
compile_seconds = 0.0
samples = 3
seconds = 0.000343199

[probes.negative]
allocations = 8516
bytes = 332944
compile_seconds = 0.0
samples = 3
seconds = 0.000190599

[probes.negative_zero]
allocations = 8516
bytes = 332960
compile_seconds = 0.0
samples = 3
seconds = 0.000174799

[probes.nonzero_constant]
allocations = 8900
bytes = 342672
compile_seconds = 0.0
samples = 3
seconds = 0.000181899

[probes.positive]
allocations = 8516
bytes = 331872
compile_seconds = 0.0
samples = 3
seconds = 0.000197799

[probes.zero_contribution]
allocations = 1604
bytes = 75632
compile_seconds = 0.0
samples = 3
seconds = 6.7599e-5
