julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.adlittle.dual]
allocations = 119822
bytes = 5544552
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0037456
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009578
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117807
bytes = 4755000
compile_seconds = 0.0
samples = 3
seconds = 0.0026194

[datasets.adlittle.primal]
allocations = 120620
bytes = 5821240
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039315
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010679
status = "OPTIMAL"

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.dual]
allocations = 27568
bytes = 1274248
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008661
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002055
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26753
bytes = 1137944
compile_seconds = 0.0
samples = 3
seconds = 0.0006364

[datasets.afiro.primal]
allocations = 27474
bytes = 1253128
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008314
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001977
status = "OPTIMAL"

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.flugpl.dual]
allocations = 39760
bytes = 1609088
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009379
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001312
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1499608
compile_seconds = 0.0
samples = 3
seconds = 0.0007456

[datasets.flugpl.primal]
allocations = 40109
bytes = 1653456
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009305
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001585
status = "OPTIMAL"

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.kb2.dual]
allocations = 292979
bytes = 13597280
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022450699
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878352
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008409
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291777
bytes = 13143920
compile_seconds = 0.0
samples = 3
seconds = 0.021968299

[datasets.kb2.primal]
allocations = 293146
bytes = 13610576
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0208452
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005728
status = "OPTIMAL"

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.89e-5

[datasets.sc50a.dual]
allocations = 102950
bytes = 4480112
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0026962
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005614
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101878
bytes = 4132576
compile_seconds = 0.0
samples = 3
seconds = 0.0019179

[datasets.sc50a.primal]
allocations = 102895
bytes = 4432064
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025391
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000534
status = "OPTIMAL"

[probes.empty]
allocations = 7226
bytes = 258984
compile_seconds = 0.0
samples = 3
seconds = 0.0001342

[probes.fixed]
allocations = 12107
bytes = 466568
compile_seconds = 0.0
samples = 3
seconds = 0.0002887
