julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "after"
presolve = false
scaling = "off"
threads = 1

[[kernels]]
allocations = 83
basis_update = "pfi"
bytes = 84192
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.0001582
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "pfi"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 7.4e-6
stage = "assembly"
[[kernels]]
allocations = 83
basis_update = "forrest_tomlin"
bytes = 84192
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.0001564
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "forrest_tomlin"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 7.7e-6
stage = "assembly"
[[kernels]]
allocations = 83
basis_update = "suhl_suhl"
bytes = 84192
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.0001533
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "suhl_suhl"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 8.4e-6
stage = "assembly"
[[kernels]]
allocations = 83
basis_update = "bartels_golub"
bytes = 84192
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.000154
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "bartels_golub"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 9.9e-6
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "pfi"
bytes = 549384
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0004643
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "pfi"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 1.25e-5
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "forrest_tomlin"
bytes = 549384
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0004587
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "forrest_tomlin"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 1.21e-5
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "suhl_suhl"
bytes = 549384
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0003898
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "suhl_suhl"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 1.53e-5
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "bartels_golub"
bytes = 549384
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0004553
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "bartels_golub"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 1.35e-5
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "pfi"
bytes = 4273000
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 0.0020196
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "pfi"
bytes = 0
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 3.93e-5
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "forrest_tomlin"
bytes = 4273000
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 0.0020871
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "forrest_tomlin"
bytes = 0
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 3.94e-5
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "suhl_suhl"
bytes = 4273000
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 0.0020132
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "suhl_suhl"
bytes = 0
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 4.28e-5
stage = "assembly"
[[kernels]]
allocations = 88
basis_update = "bartels_golub"
bytes = 4273000
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 0.001856
stage = "refactorize"
[[kernels]]
allocations = 0
basis_update = "bartels_golub"
bytes = 0
compile_seconds = 0.0
dimension = 4096
samples = 3
seconds = 4.25e-5
stage = "assembly"

[[rows]]
algorithm = "dual"
allocations = 1790
basis_update = "pfi"
bytes = 413896
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004868
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 458
basis_update = "pfi"
bytes = 78672
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002285
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1940
basis_update = "pfi"
bytes = 416736
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004091
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 612
basis_update = "pfi"
bytes = 109008
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000206
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2020
basis_update = "forrest_tomlin"
bytes = 424424
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004677
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 712
basis_update = "forrest_tomlin"
bytes = 89808
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002642
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2172
basis_update = "forrest_tomlin"
bytes = 428448
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004222
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 874
basis_update = "forrest_tomlin"
bytes = 121072
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002731
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2022
basis_update = "suhl_suhl"
bytes = 425640
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004492
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 704
basis_update = "suhl_suhl"
bytes = 89760
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002163
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2168
basis_update = "suhl_suhl"
bytes = 428288
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004509
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 872
basis_update = "suhl_suhl"
bytes = 122336
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002538
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2136
basis_update = "bartels_golub"
bytes = 432296
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000529
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 823
basis_update = "bartels_golub"
bytes = 96480
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002574
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2260
basis_update = "bartels_golub"
bytes = 433968
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000348
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 963
basis_update = "bartels_golub"
bytes = 128448
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002708
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2030
basis_update = "pfi"
bytes = 920424
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001336299
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1183
basis_update = "pfi"
bytes = 535392
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015041
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7569
basis_update = "pfi"
bytes = 5913400
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0036225
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1222
basis_update = "pfi"
bytes = 579192
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0013372
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2690
basis_update = "forrest_tomlin"
bytes = 982776
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017658
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1817
basis_update = "forrest_tomlin"
bytes = 561712
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016035
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7991
basis_update = "forrest_tomlin"
bytes = 5934232
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0033177
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1880
basis_update = "forrest_tomlin"
bytes = 629720
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016167
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2688
basis_update = "suhl_suhl"
bytes = 996200
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0015977
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1789
basis_update = "suhl_suhl"
bytes = 560624
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015539
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7995
basis_update = "suhl_suhl"
bytes = 5936600
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0032052
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1874
basis_update = "suhl_suhl"
bytes = 634712
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017064
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2827
basis_update = "bartels_golub"
bytes = 997048
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0018665
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1984
basis_update = "bartels_golub"
bytes = 590704
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016638
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8165
basis_update = "bartels_golub"
bytes = 5949208
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003356499
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1981
basis_update = "bartels_golub"
bytes = 654232
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0019289
status = "OPTIMAL"
