julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.adlittle.dual]
allocations = 84829
bytes = 4137400
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032308
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461496
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008791
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82814
bytes = 3348872
compile_seconds = 0.0
samples = 3
seconds = 0.0020253

[datasets.adlittle.primal]
allocations = 85627
bytes = 4414472
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035841
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607344
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010169
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.0e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177616
compile_seconds = 0.0
samples = 3
seconds = 0.0001072

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 8.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868232
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007325
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001964
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 732392
compile_seconds = 0.0
samples = 3
seconds = 0.0005329

[datasets.afiro.primal]
allocations = 17051
bytes = 846456
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006509
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000198
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45824
compile_seconds = 0.0
samples = 3
seconds = 9.18e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218392
compile_seconds = 0.0
samples = 3
seconds = 0.0001685

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.flugpl.dual]
allocations = 32187
bytes = 1311624
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000952
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001576
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31516
bytes = 1202624
compile_seconds = 0.0
samples = 3
seconds = 0.0007064

[datasets.flugpl.primal]
allocations = 32536
bytes = 1356568
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008783
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001603
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.66e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217240
compile_seconds = 0.0
samples = 3
seconds = 0.000137

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132296
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020469399
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007645
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10679736
compile_seconds = 0.0
samples = 3
seconds = 0.019770299

[datasets.kb2.primal]
allocations = 231373
bytes = 11145832
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020494799
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000616
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112640
compile_seconds = 0.0
samples = 3
seconds = 8.64e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161424
compile_seconds = 0.0
samples = 3
seconds = 9.96e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.42e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3198720
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021192
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005532
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853312
compile_seconds = 0.0
samples = 3
seconds = 0.0015087

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151696
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020905
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000513
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.15e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300656
compile_seconds = 0.0
samples = 3
seconds = 0.0001773

[probes.negative_zero_cost]
allocations = 3652
bytes = 153264
compile_seconds = 0.0
samples = 3
seconds = 8.9499e-5

[probes.negative_zero_value]
allocations = 3652
bytes = 153232
compile_seconds = 0.0
samples = 3
seconds = 9.21e-5

[probes.no_elimination]
allocations = 15
bytes = 4080
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[probes.nonzero]
allocations = 8900
bytes = 342928
compile_seconds = 0.0
samples = 3
seconds = 0.0001761

[probes.zero_cost]
allocations = 3652
bytes = 151632
compile_seconds = 0.0
samples = 3
seconds = 0.0001059

[probes.zero_value]
allocations = 3652
bytes = 153232
compile_seconds = 0.0
samples = 3
seconds = 9.22e-5
