julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 84962
bytes = 4146080
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035912
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461256
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009464
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82947
bytes = 3356048
compile_seconds = 0.0
samples = 3
seconds = 0.0022485

[datasets.adlittle.primal]
allocations = 85760
bytes = 4423232
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003759901
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 606976
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011549
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 0.0001017

[datasets.adlittle.sparse]
allocations = 2843
bytes = 178240
compile_seconds = 0.0
samples = 3
seconds = 0.0001381

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 869672
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008595
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002054
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 734200
compile_seconds = 0.0
samples = 3
seconds = 0.0006913

[datasets.afiro.primal]
allocations = 17051
bytes = 847416
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008522
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002403
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 43776
compile_seconds = 0.0
samples = 3
seconds = 7.88e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 219608
compile_seconds = 0.0
samples = 3
seconds = 0.0001744

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6

[datasets.flugpl.dual]
allocations = 32206
bytes = 1313472
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010335
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001536
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31535
bytes = 1203864
compile_seconds = 0.0
samples = 3
seconds = 0.0007909

[datasets.flugpl.primal]
allocations = 32555
bytes = 1358208
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009731
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001546
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.79e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 218376
compile_seconds = 0.0
samples = 3
seconds = 0.0001371

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11136168
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022040203
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878064
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008992
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10681912
compile_seconds = 0.0
samples = 3
seconds = 0.020892004

[datasets.kb2.primal]
allocations = 231373
bytes = 11150152
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0221174
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000655
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111536
compile_seconds = 0.0
samples = 3
seconds = 0.0001059

[datasets.kb2.sparse]
allocations = 2836
bytes = 162112
compile_seconds = 0.0
samples = 3
seconds = 0.0001076

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.88e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3201632
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006348
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2855936
compile_seconds = 0.0
samples = 3
seconds = 0.0016422

[datasets.sc50a.primal]
allocations = 68651
bytes = 3153872
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022294
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005498
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.68e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 302016
compile_seconds = 0.0
samples = 3
seconds = 0.000201

[probes.basic_negative]
allocations = 14532
bytes = 553728
compile_seconds = 0.0
samples = 3
seconds = 0.0002934

[probes.basic_positive]
allocations = 14532
bytes = 552256
compile_seconds = 0.0
samples = 3
seconds = 0.0003014

[probes.doubleton]
allocations = 18072
bytes = 708496
compile_seconds = 0.0
samples = 3
seconds = 0.0004032

[probes.sparse_negative]
allocations = 48453
bytes = 1882128
compile_seconds = 0.0
samples = 3
seconds = 0.0010647

[probes.sparse_positive]
allocations = 47941
bytes = 1866336
compile_seconds = 0.0
samples = 3
seconds = 0.00114

[probes.unequal_bound]
allocations = 15556
bytes = 594912
compile_seconds = 0.0
samples = 3
seconds = 0.0003265
