julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123640
bytes = 5867240
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.00372
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1340
bytes = 468072
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009446
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 124481
bytes = 6148648
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.00396
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1956
bytes = 619824
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010323
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28746
bytes = 1352104
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008879
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 569
bytes = 92592
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000193
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28648
bytes = 1330904
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008476
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 816
bytes = 127104
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002099
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40029
bytes = 1625400
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008905
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 390
bytes = 44560
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001555
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40421
bytes = 1672888
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009173
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 796
bytes = 96784
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001582
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294374
bytes = 13807136
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020589301
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1522
bytes = 881568
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008498
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 294537
bytes = 13820208
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021681801
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1064
bytes = 263296
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006167
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107601
bytes = 4707024
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024187
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 975
bytes = 310672
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005755
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107542
bytes = 4658960
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002363701
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 974
bytes = 235048
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004907
status = "OPTIMAL"

[probes.optimality]
allocations = 10
bytes = 16656
compile_seconds = 0.0
samples = 3
seconds = 1.66e-5

[probes.reduced_cost_bounds]
allocations = 7
bytes = 16560
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6
