julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "after"
presolve = false
scaling = "off"
threads = 1

[[rows]]
algorithm = "dual"
allocations = 1880
basis_update = "pfi"
bytes = 430728
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000515299
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 461
basis_update = "pfi"
bytes = 78496
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000199299
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2038
basis_update = "pfi"
bytes = 433792
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000451299
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 616
basis_update = "pfi"
bytes = 109712
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000218099
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2110
basis_update = "forrest_tomlin"
bytes = 440456
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006214
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 715
basis_update = "forrest_tomlin"
bytes = 89632
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003032
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2270
basis_update = "forrest_tomlin"
bytes = 444432
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000455
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 878
basis_update = "forrest_tomlin"
bytes = 121776
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002273
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2112
basis_update = "suhl_suhl"
bytes = 441160
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006334
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 707
basis_update = "suhl_suhl"
bytes = 89584
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002172
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2266
basis_update = "suhl_suhl"
bytes = 444864
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005393
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 876
basis_update = "suhl_suhl"
bytes = 123040
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002433
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2226
basis_update = "bartels_golub"
bytes = 447608
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0007176
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 826
basis_update = "bartels_golub"
bytes = 96304
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003076
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2358
basis_update = "bartels_golub"
bytes = 449840
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000505799
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 967
basis_update = "bartels_golub"
bytes = 129152
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002899
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2110
basis_update = "pfi"
bytes = 944696
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0014553
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1206
basis_update = "pfi"
bytes = 541856
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001576999
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8059
basis_update = "pfi"
bytes = 6179912
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003441099
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1244
basis_update = "pfi"
bytes = 583288
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015133
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2770
basis_update = "forrest_tomlin"
bytes = 1007064
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001765
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1840
basis_update = "forrest_tomlin"
bytes = 567264
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001715599
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8481
basis_update = "forrest_tomlin"
bytes = 6200856
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003688999
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1902
basis_update = "forrest_tomlin"
bytes = 633784
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001792999
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2768
basis_update = "suhl_suhl"
bytes = 1020456
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017419
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1812
basis_update = "suhl_suhl"
bytes = 566176
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001724099
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8485
basis_update = "suhl_suhl"
bytes = 6203432
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.00287
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1896
basis_update = "suhl_suhl"
bytes = 638696
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001789501
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2907
basis_update = "bartels_golub"
bytes = 1021096
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001893701
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2007
basis_update = "bartels_golub"
bytes = 595280
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001822601
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8655
basis_update = "bartels_golub"
bytes = 6215768
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003749302
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2003
basis_update = "bartels_golub"
bytes = 658392
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0020347
status = "OPTIMAL"
