julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "before"
presolve = false
scaling = "off"
threads = 1

[[rows]]
algorithm = "dual"
allocations = 1880
basis_update = "pfi"
bytes = 430616
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000531699
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 461
basis_update = "pfi"
bytes = 78496
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002728
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2038
basis_update = "pfi"
bytes = 433952
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000550099
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 616
basis_update = "pfi"
bytes = 109712
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002652
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2152
basis_update = "forrest_tomlin"
bytes = 441784
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006635
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 761
basis_update = "forrest_tomlin"
bytes = 91232
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002597
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2302
basis_update = "forrest_tomlin"
bytes = 445232
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004993
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 914
basis_update = "forrest_tomlin"
bytes = 122896
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002802
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2152
basis_update = "suhl_suhl"
bytes = 442024
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005754
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 753
basis_update = "suhl_suhl"
bytes = 91184
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002816
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2304
basis_update = "suhl_suhl"
bytes = 445856
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005496
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 914
basis_update = "suhl_suhl"
bytes = 124256
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000227
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2268
basis_update = "bartels_golub"
bytes = 449768
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000607
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 868
basis_update = "bartels_golub"
bytes = 97520
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003103
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2390
basis_update = "bartels_golub"
bytes = 451520
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005101
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1001
basis_update = "bartels_golub"
bytes = 129952
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003352
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2110
basis_update = "pfi"
bytes = 945528
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0013725
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1206
basis_update = "pfi"
bytes = 542224
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017414
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8059
basis_update = "pfi"
bytes = 6181944
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003557699
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1244
basis_update = "pfi"
bytes = 583864
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001510499
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3038
basis_update = "forrest_tomlin"
bytes = 1032200
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0019002
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2136
basis_update = "forrest_tomlin"
bytes = 601136
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017533
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8687
basis_update = "forrest_tomlin"
bytes = 6208104
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003936699
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2142
basis_update = "forrest_tomlin"
bytes = 661880
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017299
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3028
basis_update = "suhl_suhl"
bytes = 1039256
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001802299
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2112
basis_update = "suhl_suhl"
bytes = 601600
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001652099
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8687
basis_update = "suhl_suhl"
bytes = 6208248
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003647999
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2128
basis_update = "suhl_suhl"
bytes = 663080
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017993
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3125
basis_update = "bartels_golub"
bytes = 1026328
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001892001
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2269
basis_update = "bartels_golub"
bytes = 599360
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001927401
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8861
basis_update = "bartels_golub"
bytes = 6223064
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003715202
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2199
basis_update = "bartels_golub"
bytes = 662232
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001926901
status = "OPTIMAL"
