julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16804
bytes = 722152
compile_seconds = 0.0
samples = 3
seconds = 0.0005229

[datasets.adlittle.dual]
allocations = 91021
bytes = 4415080
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003722001
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000989201
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3625784
compile_seconds = 0.0
samples = 3
seconds = 0.0022143

[datasets.adlittle.primal]
allocations = 91819
bytes = 4691480
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003884801
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607088
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001156401
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4440
bytes = 206064
compile_seconds = 0.0
samples = 3
seconds = 0.0001633

[datasets.afiro.dual]
allocations = 20268
bytes = 991328
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009556
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002165
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 19453
bytes = 856112
compile_seconds = 0.0
samples = 3
seconds = 0.0007025

[datasets.afiro.primal]
allocations = 20174
bytes = 970384
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000831401
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002144
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4158
bytes = 198016
compile_seconds = 0.0
samples = 3
seconds = 0.0001481

[datasets.flugpl.dual]
allocations = 35559
bytes = 1450072
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010744
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001604
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1340864
compile_seconds = 0.0
samples = 3
seconds = 0.0008606

[datasets.flugpl.primal]
allocations = 35908
bytes = 1494664
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011393
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001985
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80354
bytes = 3479544
compile_seconds = 0.0
samples = 3
seconds = 0.004207101

[datasets.kb2.dual]
allocations = 243066
bytes = 11633592
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021040004
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878192
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000904601
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241864
bytes = 11181448
compile_seconds = 0.0
samples = 3
seconds = 0.021231904

[datasets.kb2.primal]
allocations = 243233
bytes = 11647656
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021345008
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0007356
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 33292
bytes = 1421656
compile_seconds = 0.0
samples = 3
seconds = 0.0008816

[datasets.sc50a.dual]
allocations = 74656
bytes = 3432728
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002175601
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306400
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006171
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 73584
bytes = 3087480
compile_seconds = 0.0
samples = 3
seconds = 0.001769101

[datasets.sc50a.primal]
allocations = 74601
bytes = 3385480
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002216001
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005336
status = "OPTIMAL"

[probes.negative]
allocations = 5658
bytes = 322992
compile_seconds = 0.0
samples = 3
seconds = 0.0001393

[probes.positive]
allocations = 5658
bytes = 323664
compile_seconds = 0.0
samples = 3
seconds = 0.0001381

[probes.unequal]
allocations = 6810
bytes = 367296
compile_seconds = 0.0
samples = 3
seconds = 0.0001776

[probes.unit]
allocations = 4506
bytes = 277296
compile_seconds = 0.0
samples = 3
seconds = 0.0001203
