julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 20246
bytes = 853784
compile_seconds = 0.0
samples = 3
seconds = 0.0005172

[datasets.adlittle.dual]
allocations = 122693
bytes = 5658536
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003949301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461496
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009844
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120678
bytes = 4869240
compile_seconds = 0.0
samples = 3
seconds = 0.002441401

[datasets.adlittle.primal]
allocations = 123491
bytes = 5935656
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003949601
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001178001
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 6070
bytes = 267728
compile_seconds = 0.0
samples = 3
seconds = 0.000182503

[datasets.afiro.dual]
allocations = 28301
bytes = 1305576
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008834
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001998
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27486
bytes = 1169784
compile_seconds = 0.0
samples = 3
seconds = 0.00067421

[datasets.afiro.primal]
allocations = 28207
bytes = 1283544
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008465
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002008
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 5316
bytes = 244304
compile_seconds = 0.0
samples = 3
seconds = 0.0001604

[datasets.flugpl.dual]
allocations = 39829
bytes = 1616168
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009642
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001329
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39158
bytes = 1506720
compile_seconds = 0.0
samples = 3
seconds = 0.0007748

[datasets.flugpl.primal]
allocations = 40178
bytes = 1660552
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010115
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001612
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 97463
bytes = 4150152
compile_seconds = 0.0
samples = 3
seconds = 0.004042001

[datasets.kb2.dual]
allocations = 293411
bytes = 13615488
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022157305
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878272
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000817
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292209
bytes = 13164496
compile_seconds = 0.0
samples = 3
seconds = 0.020787705

[datasets.kb2.primal]
allocations = 293578
bytes = 13629664
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020504105
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006179
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 48123
bytes = 1971328
compile_seconds = 0.0
samples = 3
seconds = 0.000983801

[datasets.sc50a.dual]
allocations = 106784
bytes = 4629360
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002435301
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306336
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005247
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 105712
bytes = 4283712
compile_seconds = 0.0
samples = 3
seconds = 0.002015901

[datasets.sc50a.primal]
allocations = 106729
bytes = 4581872
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002471801
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000492701
status = "OPTIMAL"

[probes.nonunit]
allocations = 8342
bytes = 422016
compile_seconds = 0.0
samples = 3
seconds = 0.0001678

[probes.unit]
allocations = 8342
bytes = 420960
compile_seconds = 0.0
samples = 3
seconds = 0.0001777
