julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19175
bytes = 809912
compile_seconds = 0.0
samples = 3
seconds = 0.0004906

[datasets.adlittle.dual]
allocations = 96127
bytes = 4604264
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032475
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461560
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009332
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 94112
bytes = 3815416
compile_seconds = 0.0
samples = 3
seconds = 0.0021941

[datasets.adlittle.primal]
allocations = 96925
bytes = 4881560
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034934
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607248
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011612
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5793
bytes = 256272
compile_seconds = 0.0
samples = 3
seconds = 0.0001683

[datasets.afiro.dual]
allocations = 23488
bytes = 1108800
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009414
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001933
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22673
bytes = 973280
compile_seconds = 0.0
samples = 3
seconds = 0.0005653

[datasets.afiro.primal]
allocations = 23394
bytes = 1088032
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007106
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001874
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4731
bytes = 219216
compile_seconds = 0.0
samples = 3
seconds = 0.00012

[datasets.flugpl.dual]
allocations = 36561
bytes = 1487288
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008813
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001309
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1378272
compile_seconds = 0.0
samples = 3
seconds = 0.0006728

[datasets.flugpl.primal]
allocations = 36910
bytes = 1531896
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008868
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001605
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96854
bytes = 4125000
compile_seconds = 0.0
samples = 3
seconds = 0.0042982

[datasets.kb2.dual]
allocations = 268980
bytes = 12653976
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0209129
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007886
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 267778
bytes = 12198984
compile_seconds = 0.0
samples = 3
seconds = 0.021297599

[datasets.kb2.primal]
allocations = 269147
bytes = 12667032
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0221666
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005776
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 48034
bytes = 1967008
compile_seconds = 0.0
samples = 3
seconds = 0.0010061

[datasets.sc50a.dual]
allocations = 96854
bytes = 4233488
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022367
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006443
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 95782
bytes = 3887088
compile_seconds = 0.0
samples = 3
seconds = 0.001813099

[datasets.sc50a.primal]
allocations = 96799
bytes = 4185760
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023679
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004727
status = "OPTIMAL"

[probes.nonunit]
allocations = 22961
bytes = 885168
compile_seconds = 0.0
samples = 3
seconds = 0.0003779

[probes.unit]
allocations = 16103
bytes = 624000
compile_seconds = 0.0
samples = 3
seconds = 0.0003364

[probes.zero]
allocations = 12039
bytes = 505664
compile_seconds = 0.0
samples = 3
seconds = 0.0002326
