julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19175
bytes = 810232
compile_seconds = 0.0
samples = 3
seconds = 0.0005165

[datasets.adlittle.dual]
allocations = 96127
bytes = 4605624
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034944
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461624
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000949
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 94112
bytes = 3816744
compile_seconds = 0.0
samples = 3
seconds = 0.0020838

[datasets.adlittle.primal]
allocations = 96925
bytes = 4882856
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036046
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607584
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011114
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5789
bytes = 257472
compile_seconds = 0.0
samples = 3
seconds = 0.0001794

[datasets.afiro.dual]
allocations = 23476
bytes = 1109616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008317
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002192
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22661
bytes = 973488
compile_seconds = 0.0
samples = 3
seconds = 0.0006429

[datasets.afiro.primal]
allocations = 23382
bytes = 1087568
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008117
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002153
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4731
bytes = 220048
compile_seconds = 0.0
samples = 3
seconds = 0.000139

[datasets.flugpl.dual]
allocations = 36561
bytes = 1488152
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010534
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001623
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1378480
compile_seconds = 0.0
samples = 3
seconds = 0.0008526

[datasets.flugpl.primal]
allocations = 36910
bytes = 1532856
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010978
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001878
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96838
bytes = 4122904
compile_seconds = 0.0
samples = 3
seconds = 0.0040494

[datasets.kb2.dual]
allocations = 268904
bytes = 12649528
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021601499
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877952
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007808
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 267702
bytes = 12198056
compile_seconds = 0.0
samples = 3
seconds = 0.0198751

[datasets.kb2.primal]
allocations = 269071
bytes = 12663288
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0217951
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0007204
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 48030
bytes = 1967136
compile_seconds = 0.0
samples = 3
seconds = 0.001055

[datasets.sc50a.dual]
allocations = 96710
bytes = 4229760
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025556
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005683
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 95638
bytes = 3883216
compile_seconds = 0.0
samples = 3
seconds = 0.0018995

[datasets.sc50a.primal]
allocations = 96655
bytes = 4182368
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025217
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232248
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005057
status = "OPTIMAL"

[probes.nonunit]
allocations = 22453
bytes = 870784
compile_seconds = 0.0
samples = 3
seconds = 0.0004147

[probes.unit]
allocations = 15595
bytes = 609808
compile_seconds = 0.0
samples = 3
seconds = 0.0002988

[probes.zero]
allocations = 11531
bytes = 491248
compile_seconds = 0.0
samples = 3
seconds = 0.0002504
