julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19175
bytes = 809960
compile_seconds = 0.0
samples = 3
seconds = 0.0005348

[datasets.adlittle.dual]
allocations = 120065
bytes = 5555416
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0037824
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009389
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 118050
bytes = 4766136
compile_seconds = 0.0
samples = 3
seconds = 0.0026408

[datasets.adlittle.primal]
allocations = 120863
bytes = 5832328
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038206
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607488
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011617
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5854
bytes = 258944
compile_seconds = 0.0
samples = 3
seconds = 0.0001474

[datasets.afiro.dual]
allocations = 27653
bytes = 1278440
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009363
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001781
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26838
bytes = 1143576
compile_seconds = 0.0
samples = 3
seconds = 0.0006507

[datasets.afiro.primal]
allocations = 27559
bytes = 1257720
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000883
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000207501
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4731
bytes = 219312
compile_seconds = 0.0
samples = 3
seconds = 0.0001597

[datasets.flugpl.dual]
allocations = 39829
bytes = 1614696
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000970502
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001538
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39158
bytes = 1503952
compile_seconds = 0.0
samples = 3
seconds = 0.000786502

[datasets.flugpl.primal]
allocations = 40178
bytes = 1659016
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000940902
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001911
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 97229
bytes = 4135272
compile_seconds = 0.0
samples = 3
seconds = 0.004316001

[datasets.kb2.dual]
allocations = 293411
bytes = 13615232
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021843203
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007783
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292209
bytes = 13163552
compile_seconds = 0.0
samples = 3
seconds = 0.021424102

[datasets.kb2.primal]
allocations = 293578
bytes = 13630496
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021568903
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005492
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 48069
bytes = 1967088
compile_seconds = 0.0
samples = 3
seconds = 0.0009623

[datasets.sc50a.dual]
allocations = 103085
bytes = 4487488
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023376
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306096
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005327
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 102013
bytes = 4142064
compile_seconds = 0.0
samples = 3
seconds = 0.0018496

[datasets.sc50a.primal]
allocations = 103030
bytes = 4440496
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025405
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000486701
status = "OPTIMAL"

[probes.nonunit]
allocations = 8342
bytes = 421056
compile_seconds = 0.0
samples = 3
seconds = 0.0001559

[probes.unit]
allocations = 4886
bytes = 287424
compile_seconds = 0.0
samples = 3
seconds = 0.0001069
