julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16944
bytes = 726968
compile_seconds = 0.0
samples = 3
seconds = 0.0005271

[datasets.adlittle.dual]
allocations = 91305
bytes = 4426168
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039444
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461080
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010473
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89290
bytes = 3634696
compile_seconds = 0.0
samples = 3
seconds = 0.0024146

[datasets.adlittle.primal]
allocations = 92103
bytes = 4701400
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041715
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607248
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012965
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4739
bytes = 214984
compile_seconds = 0.0
samples = 3
seconds = 0.0001744

[datasets.afiro.dual]
allocations = 21250
bytes = 1024576
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008802
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002273
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 20435
bytes = 888496
compile_seconds = 0.0
samples = 3
seconds = 0.000729

[datasets.afiro.primal]
allocations = 21156
bytes = 1003616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009148
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001995
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4214
bytes = 199424
compile_seconds = 0.0
samples = 3
seconds = 0.0001278

[datasets.flugpl.dual]
allocations = 35559
bytes = 1450888
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010371
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001764
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1341600
compile_seconds = 0.0
samples = 3
seconds = 0.0007885

[datasets.flugpl.primal]
allocations = 35908
bytes = 1495736
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009643
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000207
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 82564
bytes = 3545080
compile_seconds = 0.0
samples = 3
seconds = 0.0047577

[datasets.kb2.dual]
allocations = 246006
bytes = 11724520
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0233531
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.00094
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 244804
bytes = 11271656
compile_seconds = 0.0
samples = 3
seconds = 0.022183001

[datasets.kb2.primal]
allocations = 246173
bytes = 11738424
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0243998
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006421
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 36604
bytes = 1507376
compile_seconds = 0.0
samples = 3
seconds = 0.0011461

[datasets.sc50a.dual]
allocations = 79606
bytes = 3572912
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025671
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005807
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 78534
bytes = 3228000
compile_seconds = 0.0
samples = 3
seconds = 0.0019728

[datasets.sc50a.primal]
allocations = 79551
bytes = 3525744
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0027882
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005553
status = "OPTIMAL"

[probes.negative]
allocations = 18009
bytes = 702192
compile_seconds = 0.0
samples = 3
seconds = 0.0003738

[probes.positive]
allocations = 18898
bytes = 737976
compile_seconds = 0.0
samples = 3
seconds = 0.0003871

[probes.unit]
allocations = 15215
bytes = 599776
compile_seconds = 0.0
samples = 3
seconds = 0.0003323
