julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 18768
bytes = 797384
compile_seconds = 0.0
samples = 3
seconds = 0.0005544

[datasets.adlittle.dual]
allocations = 95349
bytes = 4577064
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0040982
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461656
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010585
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 93334
bytes = 3786008
compile_seconds = 0.0
samples = 3
seconds = 0.0025687

[datasets.adlittle.primal]
allocations = 96147
bytes = 4853912
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0043647
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607536
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5510
bytes = 247216
compile_seconds = 0.0
samples = 3
seconds = 0.0001469

[datasets.afiro.dual]
allocations = 23105
bytes = 1095920
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000966101
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002248
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22290
bytes = 961808
compile_seconds = 0.0
samples = 3
seconds = 0.0007539

[datasets.afiro.primal]
allocations = 23011
bytes = 1074656
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000896
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002308
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4582
bytes = 215712
compile_seconds = 0.0
samples = 3
seconds = 0.0001273

[datasets.flugpl.dual]
allocations = 35973
bytes = 1466072
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009531
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000164
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35302
bytes = 1355856
compile_seconds = 0.0
samples = 3
seconds = 0.000764

[datasets.flugpl.primal]
allocations = 36322
bytes = 1510424
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010637
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001813
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96161
bytes = 4100056
compile_seconds = 0.0
samples = 3
seconds = 0.0046674

[datasets.kb2.dual]
allocations = 266923
bytes = 12574024
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0217159
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878064
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000921
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 265721
bytes = 12120472
compile_seconds = 0.0
samples = 3
seconds = 0.022031599

[datasets.kb2.primal]
allocations = 267090
bytes = 12588328
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021788799
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006135
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 47417
bytes = 1944720
compile_seconds = 0.0
samples = 3
seconds = 0.0011255

[datasets.sc50a.dual]
allocations = 94640
bytes = 4163352
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023997
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306272
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006185
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 93568
bytes = 3818008
compile_seconds = 0.0
samples = 3
seconds = 0.0018925

[datasets.sc50a.primal]
allocations = 94585
bytes = 4115784
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024187
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005167
status = "OPTIMAL"

[probes.negative]
allocations = 6810
bytes = 367808
compile_seconds = 0.0
samples = 3
seconds = 0.0001588

[probes.positive]
allocations = 6810
bytes = 367872
compile_seconds = 0.0
samples = 3
seconds = 0.0001543

[probes.unit]
allocations = 4506
bytes = 277232
compile_seconds = 0.0
samples = 3
seconds = 0.0001141
