julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19011
bytes = 805896
compile_seconds = 0.0
samples = 3
seconds = 0.0006373

[datasets.adlittle.dual]
allocations = 95817
bytes = 4594344
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0041641
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461208
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0011637
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 93802
bytes = 3804760
compile_seconds = 0.0
samples = 3
seconds = 0.0025243

[datasets.adlittle.primal]
allocations = 96615
bytes = 4871096
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0045233
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607152
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012984
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5708
bytes = 254432
compile_seconds = 0.0
samples = 3
seconds = 0.0001855

[datasets.afiro.dual]
allocations = 23339
bytes = 1104688
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009828
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002372
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22524
bytes = 969616
compile_seconds = 0.0
samples = 3
seconds = 0.0010927

[datasets.afiro.primal]
allocations = 23245
bytes = 1083056
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000993
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002318
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4681
bytes = 217552
compile_seconds = 0.0
samples = 3
seconds = 0.000148

[datasets.flugpl.dual]
allocations = 36423
bytes = 1482792
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0012221
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001711
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35752
bytes = 1373216
compile_seconds = 0.0
samples = 3
seconds = 0.0008361

[datasets.flugpl.primal]
allocations = 36772
bytes = 1527304
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001121799
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001913
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96494
bytes = 4109336
compile_seconds = 0.0
samples = 3
seconds = 0.0050216

[datasets.kb2.dual]
allocations = 267517
bytes = 12595144
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0229148
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878480
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0010092
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 266315
bytes = 12145864
compile_seconds = 0.0
samples = 3
seconds = 0.0229095

[datasets.kb2.primal]
allocations = 267684
bytes = 12609000
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0238894
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260928
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0007233
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 47835
bytes = 1961472
compile_seconds = 0.0
samples = 3
seconds = 0.0012654

[datasets.sc50a.dual]
allocations = 95216
bytes = 4184920
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0026396
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306176
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006878
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 94144
bytes = 3840056
compile_seconds = 0.0
samples = 3
seconds = 0.0022012

[datasets.sc50a.primal]
allocations = 95161
bytes = 4137816
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0026024
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005637
status = "OPTIMAL"

[probes.empty]
allocations = 649
bytes = 80400
compile_seconds = 0.0
samples = 3
seconds = 1.38e-5

[probes.nonunit]
allocations = 22073
bytes = 860512
compile_seconds = 0.0
samples = 3
seconds = 0.0004282

[probes.unit]
allocations = 15215
bytes = 599184
compile_seconds = 0.0
samples = 3
seconds = 0.0003772

[probes.zero]
allocations = 10897
bytes = 473976
compile_seconds = 0.0
samples = 3
seconds = 0.000284
