julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16944
bytes = 727816
compile_seconds = 0.0
samples = 3
seconds = 0.0004999

[datasets.adlittle.dual]
allocations = 91305
bytes = 4426456
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003252401
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461496
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009467
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89290
bytes = 3637752
compile_seconds = 0.0
samples = 3
seconds = 0.0020856

[datasets.adlittle.primal]
allocations = 92103
bytes = 4702584
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035255
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607344
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011003
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4739
bytes = 215320
compile_seconds = 0.0
samples = 3
seconds = 0.0001602

[datasets.afiro.dual]
allocations = 21250
bytes = 1025584
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000741401
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002113
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 20435
bytes = 891088
compile_seconds = 0.0
samples = 3
seconds = 0.0006808

[datasets.afiro.primal]
allocations = 21156
bytes = 1004400
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007707
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002089
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4214
bytes = 201152
compile_seconds = 0.0
samples = 3
seconds = 0.0001245

[datasets.flugpl.dual]
allocations = 35559
bytes = 1451832
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000881
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001496
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1342240
compile_seconds = 0.0
samples = 3
seconds = 0.0006492

[datasets.flugpl.primal]
allocations = 35908
bytes = 1496424
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008422
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001845
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 82564
bytes = 3548152
compile_seconds = 0.0
samples = 3
seconds = 0.0038337

[datasets.kb2.dual]
allocations = 246006
bytes = 11724776
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020138801
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008034
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 244804
bytes = 11271880
compile_seconds = 0.0
samples = 3
seconds = 0.019373102

[datasets.kb2.primal]
allocations = 246173
bytes = 11737992
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.019912202
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006096
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 36604
bytes = 1512432
compile_seconds = 0.0
samples = 3
seconds = 0.000824

[datasets.sc50a.dual]
allocations = 79606
bytes = 3573904
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022261
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306496
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005019
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 78534
bytes = 3227968
compile_seconds = 0.0
samples = 3
seconds = 0.0015645

[datasets.sc50a.primal]
allocations = 79551
bytes = 3526704
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020215
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005029
status = "OPTIMAL"

[probes.control]
allocations = 7066
bytes = 374320
compile_seconds = 0.0
samples = 3
seconds = 0.0001652

[probes.negative_scale]
allocations = 6618
bytes = 355248
compile_seconds = 0.0
samples = 3
seconds = 0.0001555

[probes.negative_value]
allocations = 6618
bytes = 355504
compile_seconds = 0.0
samples = 3
seconds = 0.0001669
