julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16762
bytes = 718904
compile_seconds = 0.0
samples = 3
seconds = 0.000541

[datasets.adlittle.dual]
allocations = 91021
bytes = 4412792
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003605699
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461528
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010353
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3623832
compile_seconds = 0.0
samples = 3
seconds = 0.0022129

[datasets.adlittle.primal]
allocations = 91819
bytes = 4689432
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039794
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607136
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011543
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4272
bytes = 198048
compile_seconds = 0.0
samples = 3
seconds = 0.0001626

[datasets.afiro.dual]
allocations = 19666
bytes = 966384
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008458
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000239
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18851
bytes = 831392
compile_seconds = 0.0
samples = 3
seconds = 0.0007621

[datasets.afiro.primal]
allocations = 19572
bytes = 944688
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008027
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002174
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 3830
bytes = 183264
compile_seconds = 0.0
samples = 3
seconds = 0.000143

[datasets.flugpl.dual]
allocations = 35559
bytes = 1449832
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010294
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001767
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1339968
compile_seconds = 0.0
samples = 3
seconds = 0.0008244

[datasets.flugpl.primal]
allocations = 35908
bytes = 1494344
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001063
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002088
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80025
bytes = 3463920
compile_seconds = 0.0
samples = 3
seconds = 0.004618299

[datasets.kb2.dual]
allocations = 242730
bytes = 11619752
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.023188598
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009585
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241528
bytes = 11166520
compile_seconds = 0.0
samples = 3
seconds = 0.020763498

[datasets.kb2.primal]
allocations = 242897
bytes = 11633896
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021540899
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000677699
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 31066
bytes = 1328712
compile_seconds = 0.0
samples = 3
seconds = 0.0009105

[datasets.sc50a.dual]
allocations = 74027
bytes = 3406560
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.00236
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006423
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3061568
compile_seconds = 0.0
samples = 3
seconds = 0.001901499

[datasets.sc50a.primal]
allocations = 73972
bytes = 3359488
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022748
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005425
status = "OPTIMAL"

[probes.equal]
allocations = 4762
bytes = 284768
compile_seconds = 0.0
samples = 3
seconds = 0.0001332

[probes.negative]
allocations = 5018
bytes = 291696
compile_seconds = 0.0
samples = 3
seconds = 0.0001491

[probes.nonunit]
allocations = 6810
bytes = 365568
compile_seconds = 0.0
samples = 3
seconds = 0.0001676

[probes.unit]
allocations = 4506
bytes = 275952
compile_seconds = 0.0
samples = 3
seconds = 0.0001364
