julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16903
bytes = 726184
compile_seconds = 0.0
samples = 3
seconds = 0.0005141

[datasets.adlittle.dual]
allocations = 91219
bytes = 4422040
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039969
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010332
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89204
bytes = 3633160
compile_seconds = 0.0
samples = 3
seconds = 0.0022677

[datasets.adlittle.primal]
allocations = 92017
bytes = 4699064
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041742
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607008
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011526
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4557
bytes = 210928
compile_seconds = 0.0
samples = 3
seconds = 0.0001872

[datasets.afiro.dual]
allocations = 20826
bytes = 1013408
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008956
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002355
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 20011
bytes = 877296
compile_seconds = 0.0
samples = 3
seconds = 0.0007261

[datasets.afiro.primal]
allocations = 20732
bytes = 991904
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008688
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002137
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4158
bytes = 198688
compile_seconds = 0.0
samples = 3
seconds = 0.0001381

[datasets.flugpl.dual]
allocations = 35559
bytes = 1450744
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009868
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001257
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1340720
compile_seconds = 0.0
samples = 3
seconds = 0.0007949

[datasets.flugpl.primal]
allocations = 35908
bytes = 1495544
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001135
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000195
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80732
bytes = 3494584
compile_seconds = 0.0
samples = 3
seconds = 0.0042465

[datasets.kb2.dual]
allocations = 243822
bytes = 11662776
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0216632
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008429
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 242620
bytes = 11210296
compile_seconds = 0.0
samples = 3
seconds = 0.0206095

[datasets.kb2.primal]
allocations = 243989
bytes = 11676968
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021105399
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260912
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006266
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 33292
bytes = 1418952
compile_seconds = 0.0
samples = 3
seconds = 0.0008972

[datasets.sc50a.dual]
allocations = 74656
bytes = 3433192
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022239
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005878
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 73584
bytes = 3088120
compile_seconds = 0.0
samples = 3
seconds = 0.0017282

[datasets.sc50a.primal]
allocations = 74601
bytes = 3385992
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022601
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005956
status = "OPTIMAL"

[probes.negative_scale]
allocations = 1623
bytes = 74320
compile_seconds = 0.0
samples = 3
seconds = 7.72e-5

[probes.nonunit_terms]
allocations = 4203
bytes = 173432
compile_seconds = 0.0
samples = 3
seconds = 0.0001185

[probes.unit_terms]
allocations = 2797
bytes = 120128
compile_seconds = 0.0
samples = 3
seconds = 9.24e-5
