julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19175
bytes = 809672
compile_seconds = 0.0
samples = 3
seconds = 0.0004898

[datasets.adlittle.dual]
allocations = 96127
bytes = 4604696
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033796
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009159
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 94112
bytes = 3815384
compile_seconds = 0.0
samples = 3
seconds = 0.002264

[datasets.adlittle.primal]
allocations = 96925
bytes = 4881480
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004112502
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011601
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5804
bytes = 257104
compile_seconds = 0.0
samples = 3
seconds = 0.0001853

[datasets.afiro.dual]
allocations = 23527
bytes = 1109936
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008294
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002273
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22712
bytes = 974160
compile_seconds = 0.0
samples = 3
seconds = 0.0006778

[datasets.afiro.primal]
allocations = 23433
bytes = 1088864
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007244
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001845
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4731
bytes = 218864
compile_seconds = 0.0
samples = 3
seconds = 0.0001392

[datasets.flugpl.dual]
allocations = 36561
bytes = 1486728
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000888601
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001207
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1377328
compile_seconds = 0.0
samples = 3
seconds = 0.0007576

[datasets.flugpl.primal]
allocations = 36910
bytes = 1531176
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000954401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001536
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96869
bytes = 4124248
compile_seconds = 0.0
samples = 3
seconds = 0.004087803

[datasets.kb2.dual]
allocations = 269368
bytes = 12665128
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021983512
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000793701
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 268166
bytes = 12210904
compile_seconds = 0.0
samples = 3
seconds = 0.020416111

[datasets.kb2.primal]
allocations = 269535
bytes = 12679288
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021318212
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005795
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 48044
bytes = 1965920
compile_seconds = 0.0
samples = 3
seconds = 0.001077701

[datasets.sc50a.dual]
allocations = 96899
bytes = 4233232
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002388401
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006341
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 95827
bytes = 3887808
compile_seconds = 0.0
samples = 3
seconds = 0.001875301

[datasets.sc50a.primal]
allocations = 96844
bytes = 4186032
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002623102
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004726
status = "OPTIMAL"

[probes.nonzero]
allocations = 20675
bytes = 798448
compile_seconds = 0.0
samples = 3
seconds = 0.0004475

[probes.zero]
allocations = 16484
bytes = 654368
compile_seconds = 0.0
samples = 3
seconds = 0.0003452
