julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16762
bytes = 718904
compile_seconds = 0.0
samples = 3
seconds = 0.0005521

[datasets.adlittle.dual]
allocations = 91021
bytes = 4414376
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0042286
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461576
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010256
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3625512
compile_seconds = 0.0
samples = 3
seconds = 0.0026597

[datasets.adlittle.primal]
allocations = 91819
bytes = 4692008
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003939999
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011893
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4272
bytes = 198192
compile_seconds = 0.0
samples = 3
seconds = 0.0001664

[datasets.afiro.dual]
allocations = 19652
bytes = 966320
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008959
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002351
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18837
bytes = 830496
compile_seconds = 0.0
samples = 3
seconds = 0.0007515

[datasets.afiro.primal]
allocations = 19558
bytes = 944544
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008316
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000227
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 3830
bytes = 183568
compile_seconds = 0.0
samples = 3
seconds = 0.0001252

[datasets.flugpl.dual]
allocations = 35559
bytes = 1450952
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011227
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001678
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1340784
compile_seconds = 0.0
samples = 3
seconds = 0.000841

[datasets.flugpl.primal]
allocations = 35908
bytes = 1495416
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010104
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001924
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80025
bytes = 3467408
compile_seconds = 0.0
samples = 3
seconds = 0.004323099

[datasets.kb2.dual]
allocations = 242681
bytes = 11619904
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021668198
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008682
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241479
bytes = 11164016
compile_seconds = 0.0
samples = 3
seconds = 0.020874698

[datasets.kb2.primal]
allocations = 242848
bytes = 11632512
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021575497
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006438
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 31066
bytes = 1331240
compile_seconds = 0.0
samples = 3
seconds = 0.000918999

[datasets.sc50a.dual]
allocations = 74027
bytes = 3407280
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021843
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306464
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000553
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3061872
compile_seconds = 0.0
samples = 3
seconds = 0.0018103

[datasets.sc50a.primal]
allocations = 73972
bytes = 3359648
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002227899
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000563
status = "OPTIMAL"

[probes.negative]
allocations = 14199
bytes = 568488
compile_seconds = 0.0
samples = 3
seconds = 0.0003098

[probes.nonunit]
allocations = 16231
bytes = 648080
compile_seconds = 0.0
samples = 3
seconds = 0.0003851

[probes.unequal]
allocations = 15215
bytes = 600624
compile_seconds = 0.0
samples = 3
seconds = 0.000329

[probes.unit]
allocations = 13691
bytes = 552776
compile_seconds = 0.0
samples = 3
seconds = 0.0002995

[probes.zero]
allocations = 10897
bytes = 473480
compile_seconds = 0.0
samples = 3
seconds = 0.0002477
