julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19011
bytes = 807560
compile_seconds = 0.0
samples = 3
seconds = 0.0005351

[datasets.adlittle.dual]
allocations = 95817
bytes = 4594376
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035249
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461128
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009601
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 93802
bytes = 3806216
compile_seconds = 0.0
samples = 3
seconds = 0.0021793

[datasets.adlittle.primal]
allocations = 96615
bytes = 4871816
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035539
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607200
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010835
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5708
bytes = 254384
compile_seconds = 0.0
samples = 3
seconds = 0.0001798

[datasets.afiro.dual]
allocations = 23339
bytes = 1105296
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.00084
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001893
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22524
bytes = 969952
compile_seconds = 0.0
samples = 3
seconds = 0.0006304

[datasets.afiro.primal]
allocations = 23245
bytes = 1083664
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007685
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001995
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4681
bytes = 219024
compile_seconds = 0.0
samples = 3
seconds = 0.0001139

[datasets.flugpl.dual]
allocations = 36423
bytes = 1483960
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000865
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001309
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35752
bytes = 1373824
compile_seconds = 0.0
samples = 3
seconds = 0.0007252

[datasets.flugpl.primal]
allocations = 36772
bytes = 1528552
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009442
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001727
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96494
bytes = 4112008
compile_seconds = 0.0
samples = 3
seconds = 0.004001801

[datasets.kb2.dual]
allocations = 267517
bytes = 12596024
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020726708
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878128
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008017
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 266315
bytes = 12145320
compile_seconds = 0.0
samples = 3
seconds = 0.0204612

[datasets.kb2.primal]
allocations = 267684
bytes = 12610712
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020969408
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000583301
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 47831
bytes = 1961328
compile_seconds = 0.0
samples = 3
seconds = 0.0009643

[datasets.sc50a.dual]
allocations = 95216
bytes = 4187512
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002223801
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000521201
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 94144
bytes = 3841656
compile_seconds = 0.0
samples = 3
seconds = 0.001866901

[datasets.sc50a.primal]
allocations = 95161
bytes = 4139528
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002237101
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000467801
status = "OPTIMAL"

[probes.negative]
allocations = 7962
bytes = 410704
compile_seconds = 0.0
samples = 3
seconds = 0.0001654

[probes.positive]
allocations = 7962
bytes = 410736
compile_seconds = 0.0
samples = 3
seconds = 0.000166

[probes.unit]
allocations = 4506
bytes = 276880
compile_seconds = 0.0
samples = 3
seconds = 0.0001013
