julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16903
bytes = 724616
compile_seconds = 0.0
samples = 3
seconds = 0.0005041

[datasets.adlittle.dual]
allocations = 91219
bytes = 4422840
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032808
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461768
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.00089
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89204
bytes = 3631736
compile_seconds = 0.0
samples = 3
seconds = 0.002022

[datasets.adlittle.primal]
allocations = 92017
bytes = 4699256
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033648
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607120
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010811
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4557
bytes = 209728
compile_seconds = 0.0
samples = 3
seconds = 0.000151

[datasets.afiro.dual]
allocations = 20826
bytes = 1011344
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007399
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002048
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 20011
bytes = 876400
compile_seconds = 0.0
samples = 3
seconds = 0.0005969

[datasets.afiro.primal]
allocations = 20732
bytes = 990416
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006838
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002039
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4158
bytes = 197920
compile_seconds = 0.0
samples = 3
seconds = 0.000108

[datasets.flugpl.dual]
allocations = 35559
bytes = 1448872
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008159
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001353
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1339760
compile_seconds = 0.0
samples = 3
seconds = 0.0007908

[datasets.flugpl.primal]
allocations = 35908
bytes = 1493464
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008814
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001615
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80732
bytes = 3490776
compile_seconds = 0.0
samples = 3
seconds = 0.0037993

[datasets.kb2.dual]
allocations = 243822
bytes = 11659464
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020443499
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878368
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008034
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 242620
bytes = 11209704
compile_seconds = 0.0
samples = 3
seconds = 0.020436999

[datasets.kb2.primal]
allocations = 243989
bytes = 11674040
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020310099
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260880
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005588
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 33292
bytes = 1420616
compile_seconds = 0.0
samples = 3
seconds = 0.0008004

[datasets.sc50a.dual]
allocations = 74656
bytes = 3432408
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001896599
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306400
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005638
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 73584
bytes = 3086792
compile_seconds = 0.0
samples = 3
seconds = 0.0014752

[datasets.sc50a.primal]
allocations = 74601
bytes = 3385176
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018807
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004808
status = "OPTIMAL"

[probes.negative]
allocations = 6810
bytes = 366272
compile_seconds = 0.0
samples = 3
seconds = 0.0001399

[probes.positive]
allocations = 6810
bytes = 366224
compile_seconds = 0.0
samples = 3
seconds = 0.0001392

[probes.unequal]
allocations = 6810
bytes = 366272
compile_seconds = 0.0
samples = 3
seconds = 0.0001355

[probes.unit]
allocations = 4506
bytes = 276400
compile_seconds = 0.0
samples = 3
seconds = 0.0001185
