julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16762
bytes = 721016
compile_seconds = 0.0
samples = 3
seconds = 0.0005364

[datasets.adlittle.dual]
allocations = 91021
bytes = 4417400
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034177
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461608
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009661
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3626600
compile_seconds = 0.0
samples = 3
seconds = 0.0020931

[datasets.adlittle.primal]
allocations = 91819
bytes = 4693944
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036613
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607264
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001103
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4272
bytes = 201088
compile_seconds = 0.0
samples = 3
seconds = 0.000161

[datasets.afiro.dual]
allocations = 19652
bytes = 967696
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007964
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002115
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18837
bytes = 832704
compile_seconds = 0.0
samples = 3
seconds = 0.0007804

[datasets.afiro.primal]
allocations = 19558
bytes = 946720
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007572
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002152
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 3830
bytes = 185120
compile_seconds = 0.0
samples = 3
seconds = 0.0001218

[datasets.flugpl.dual]
allocations = 35559
bytes = 1453160
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000908
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001504
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1343312
compile_seconds = 0.0
samples = 3
seconds = 0.000722599

[datasets.flugpl.primal]
allocations = 35908
bytes = 1497736
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009687
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001885
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80025
bytes = 3469264
compile_seconds = 0.0
samples = 3
seconds = 0.0039861

[datasets.kb2.dual]
allocations = 242681
bytes = 11619840
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0207859
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000849
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241479
bytes = 11168656
compile_seconds = 0.0
samples = 3
seconds = 0.019918399

[datasets.kb2.primal]
allocations = 242848
bytes = 11634192
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020505298
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000613
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 31066
bytes = 1332536
compile_seconds = 0.0
samples = 3
seconds = 0.0009524

[datasets.sc50a.dual]
allocations = 74027
bytes = 3410624
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020662
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306416
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000588
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3064592
compile_seconds = 0.0
samples = 3
seconds = 0.0016241

[datasets.sc50a.primal]
allocations = 73972
bytes = 3363392
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020523
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004925
status = "OPTIMAL"

[probes.negative]
allocations = 15977
bytes = 624232
compile_seconds = 0.0
samples = 3
seconds = 0.0003814

[probes.nonunit]
allocations = 18898
bytes = 739496
compile_seconds = 0.0
samples = 3
seconds = 0.0003481

[probes.unequal]
allocations = 15215
bytes = 602560
compile_seconds = 0.0
samples = 3
seconds = 0.0002907

[probes.unit]
allocations = 15215
bytes = 600048
compile_seconds = 0.0
samples = 3
seconds = 0.0003171

[probes.zero]
allocations = 10897
bytes = 475432
compile_seconds = 0.0
samples = 3
seconds = 0.0002056
