julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16804
bytes = 721432
compile_seconds = 0.0
samples = 3
seconds = 0.0005355

[datasets.adlittle.dual]
allocations = 91021
bytes = 4415656
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033494
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461480
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009314
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3626664
compile_seconds = 0.0
samples = 3
seconds = 0.0021627

[datasets.adlittle.primal]
allocations = 91819
bytes = 4692520
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036625
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607072
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010871
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4440
bytes = 205792
compile_seconds = 0.0
samples = 3
seconds = 0.000156

[datasets.afiro.dual]
allocations = 20268
bytes = 991248
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008209
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002158
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 19453
bytes = 856480
compile_seconds = 0.0
samples = 3
seconds = 0.0007709

[datasets.afiro.primal]
allocations = 20174
bytes = 969472
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000785
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002376
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4158
bytes = 199360
compile_seconds = 0.0
samples = 3
seconds = 0.0001229

[datasets.flugpl.dual]
allocations = 35559
bytes = 1451208
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009315
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001491
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1341632
compile_seconds = 0.0
samples = 3
seconds = 0.000811

[datasets.flugpl.primal]
allocations = 35908
bytes = 1495608
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009999
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001686
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80354
bytes = 3478984
compile_seconds = 0.0
samples = 3
seconds = 0.003958101

[datasets.kb2.dual]
allocations = 243066
bytes = 11634072
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020928701
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008075
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241864
bytes = 11180792
compile_seconds = 0.0
samples = 3
seconds = 0.0205083

[datasets.kb2.primal]
allocations = 243233
bytes = 11647032
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021148301
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000613
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 33292
bytes = 1422728
compile_seconds = 0.0
samples = 3
seconds = 0.0008742

[datasets.sc50a.dual]
allocations = 74656
bytes = 3434232
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022939
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005726
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 73584
bytes = 3087864
compile_seconds = 0.0
samples = 3
seconds = 0.0016756

[datasets.sc50a.primal]
allocations = 74601
bytes = 3387128
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021419
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004817
status = "OPTIMAL"

[probes.equal]
allocations = 5658
bytes = 322784
compile_seconds = 0.0
samples = 3
seconds = 0.0001349

[probes.negative]
allocations = 6810
bytes = 366352
compile_seconds = 0.0
samples = 3
seconds = 0.0001504

[probes.nonunit]
allocations = 6810
bytes = 366368
compile_seconds = 0.0
samples = 3
seconds = 0.0001598

[probes.unit]
allocations = 4506
bytes = 276944
compile_seconds = 0.0
samples = 3
seconds = 0.0001174
