julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16762
bytes = 720472
compile_seconds = 0.0
samples = 3
seconds = 0.0004992

[datasets.adlittle.dual]
allocations = 91021
bytes = 4416904
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036072
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009475
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3625672
compile_seconds = 0.0
samples = 3
seconds = 0.0021127

[datasets.adlittle.primal]
allocations = 91819
bytes = 4692904
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035069
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607600
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010938
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4272
bytes = 198704
compile_seconds = 0.0
samples = 3
seconds = 0.0001743

[datasets.afiro.dual]
allocations = 19666
bytes = 968096
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008088
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002264
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18851
bytes = 831344
compile_seconds = 0.0
samples = 3
seconds = 0.0006594

[datasets.afiro.primal]
allocations = 19572
bytes = 946096
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007244
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000221
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 3830
bytes = 183680
compile_seconds = 0.0
samples = 3
seconds = 0.0001364

[datasets.flugpl.dual]
allocations = 35559
bytes = 1451160
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008722
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000149
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1341824
compile_seconds = 0.0
samples = 3
seconds = 0.0007056

[datasets.flugpl.primal]
allocations = 35908
bytes = 1495960
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000972
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001812
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80025
bytes = 3467728
compile_seconds = 0.0
samples = 3
seconds = 0.004376

[datasets.kb2.dual]
allocations = 242730
bytes = 11621448
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0206889
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878160
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008693
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241528
bytes = 11168408
compile_seconds = 0.0
samples = 3
seconds = 0.0198845

[datasets.kb2.primal]
allocations = 242897
bytes = 11635544
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0203211
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000638
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 31066
bytes = 1330952
compile_seconds = 0.0
samples = 3
seconds = 0.0008586

[datasets.sc50a.dual]
allocations = 74027
bytes = 3410096
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020378
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306224
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005762
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3063488
compile_seconds = 0.0
samples = 3
seconds = 0.0016145

[datasets.sc50a.primal]
allocations = 73972
bytes = 3363024
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002007
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004993
status = "OPTIMAL"

[probes.negative]
allocations = 17755
bytes = 694488
compile_seconds = 0.0
samples = 3
seconds = 0.0003455

[probes.nonunit]
allocations = 18898
bytes = 737896
compile_seconds = 0.0
samples = 3
seconds = 0.0003333

[probes.unit]
allocations = 15215
bytes = 598912
compile_seconds = 0.0
samples = 3
seconds = 0.0003761

[probes.zero]
allocations = 11151
bytes = 481168
compile_seconds = 0.0
samples = 3
seconds = 0.0002405
