julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16932
bytes = 725432
compile_seconds = 0.0
samples = 3
seconds = 0.000486

[datasets.adlittle.dual]
allocations = 91281
bytes = 4424024
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003477801
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461160
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010492
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89266
bytes = 3635048
compile_seconds = 0.0
samples = 3
seconds = 0.00208

[datasets.adlittle.primal]
allocations = 92079
bytes = 4700840
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003594301
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607376
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011752
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4565
bytes = 209792
compile_seconds = 0.0
samples = 3
seconds = 0.0001767

[datasets.afiro.dual]
allocations = 20914
bytes = 1015008
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007331
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002264
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 20099
bytes = 878352
compile_seconds = 0.0
samples = 3
seconds = 0.0005958

[datasets.afiro.primal]
allocations = 20820
bytes = 993088
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007497
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002171
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4158
bytes = 197872
compile_seconds = 0.0
samples = 3
seconds = 0.0001178

[datasets.flugpl.dual]
allocations = 35559
bytes = 1449976
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009215
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001569
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1340224
compile_seconds = 0.0
samples = 3
seconds = 0.0007196

[datasets.flugpl.primal]
allocations = 35908
bytes = 1494488
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008951
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000197001
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80974
bytes = 3502512
compile_seconds = 0.0
samples = 3
seconds = 0.0038452

[datasets.kb2.dual]
allocations = 244306
bytes = 11675720
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020621903
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008702
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 243104
bytes = 11224648
compile_seconds = 0.0
samples = 3
seconds = 0.020527003

[datasets.kb2.primal]
allocations = 244473
bytes = 11690520
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021025703
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006364
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 33322
bytes = 1418016
compile_seconds = 0.0
samples = 3
seconds = 0.0008423

[datasets.sc50a.dual]
allocations = 74662
bytes = 3432400
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021477
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306544
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005828
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 73590
bytes = 3086608
compile_seconds = 0.0
samples = 3
seconds = 0.0016169

[datasets.sc50a.primal]
allocations = 74607
bytes = 3385008
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001966001
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005437
status = "OPTIMAL"

[probes.negative_scale]
allocations = 1623
bytes = 73472
compile_seconds = 0.0
samples = 3
seconds = 7.72e-5

[probes.nonunit_terms]
allocations = 4203
bytes = 171320
compile_seconds = 0.0
samples = 3
seconds = 0.0001216

[probes.unit_terms]
allocations = 3051
bytes = 125512
compile_seconds = 0.0
samples = 3
seconds = 0.0001157
