julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19175
bytes = 809960
compile_seconds = 0.0
samples = 3
seconds = 0.0005672

[datasets.adlittle.dual]
allocations = 96127
bytes = 4604488
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.004059102
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461688
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001120501
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 94112
bytes = 3813384
compile_seconds = 0.0
samples = 3
seconds = 0.0024419

[datasets.adlittle.primal]
allocations = 96925
bytes = 4881096
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004233002
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607312
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0013206
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5793
bytes = 256176
compile_seconds = 0.0
samples = 3
seconds = 0.0001744

[datasets.afiro.dual]
allocations = 23488
bytes = 1107440
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0010478
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002135
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22673
bytes = 972160
compile_seconds = 0.0
samples = 3
seconds = 0.0007249

[datasets.afiro.primal]
allocations = 23394
bytes = 1086640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009104
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001942
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4731
bytes = 218816
compile_seconds = 0.0
samples = 3
seconds = 0.000168

[datasets.flugpl.dual]
allocations = 36561
bytes = 1487464
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001320301
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001696
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1377216
compile_seconds = 0.0
samples = 3
seconds = 0.000972001

[datasets.flugpl.primal]
allocations = 36910
bytes = 1531624
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001047801
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001924
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96854
bytes = 4121016
compile_seconds = 0.0
samples = 3
seconds = 0.004948101

[datasets.kb2.dual]
allocations = 268980
bytes = 12650056
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.023478807
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.001014201
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 267778
bytes = 12196920
compile_seconds = 0.0
samples = 3
seconds = 0.021461107

[datasets.kb2.primal]
allocations = 269147
bytes = 12664152
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023697008
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0007238
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 48034
bytes = 1964992
compile_seconds = 0.0
samples = 3
seconds = 0.0012521

[datasets.sc50a.dual]
allocations = 96854
bytes = 4230848
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.003080701
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306304
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000631101
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 95782
bytes = 3885200
compile_seconds = 0.0
samples = 3
seconds = 0.002395801

[datasets.sc50a.primal]
allocations = 96799
bytes = 4183712
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002782501
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005546
status = "OPTIMAL"

[probes.nonunit]
allocations = 22961
bytes = 884624
compile_seconds = 0.0
samples = 3
seconds = 0.0004354

[probes.unit]
allocations = 16103
bytes = 623952
compile_seconds = 0.0
samples = 3
seconds = 0.0003494

[probes.zero]
allocations = 12039
bytes = 505072
compile_seconds = 0.0
samples = 3
seconds = 0.0002476
