julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 16762
bytes = 721432
compile_seconds = 0.0
samples = 3
seconds = 0.0005941

[datasets.adlittle.dual]
allocations = 91021
bytes = 4415800
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0037757
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009918
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3626600
compile_seconds = 0.0
samples = 3
seconds = 0.0025493

[datasets.adlittle.primal]
allocations = 91819
bytes = 4692408
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039239
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607072
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012097
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 4272
bytes = 198928
compile_seconds = 0.0
samples = 3
seconds = 0.0001978

[datasets.afiro.dual]
allocations = 19652
bytes = 967296
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008478
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002038
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18837
bytes = 831824
compile_seconds = 0.0
samples = 3
seconds = 0.0006871

[datasets.afiro.primal]
allocations = 19558
bytes = 947040
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000851799
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002403
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 3830
bytes = 184320
compile_seconds = 0.0
samples = 3
seconds = 0.0001389

[datasets.flugpl.dual]
allocations = 35559
bytes = 1451784
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010281
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001528
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1342400
compile_seconds = 0.0
samples = 3
seconds = 0.0008178

[datasets.flugpl.primal]
allocations = 35908
bytes = 1496104
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010066
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001987
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 80025
bytes = 3467760
compile_seconds = 0.0
samples = 3
seconds = 0.0043301

[datasets.kb2.dual]
allocations = 242681
bytes = 11619520
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021309199
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878368
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000914
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241479
bytes = 11166832
compile_seconds = 0.0
samples = 3
seconds = 0.0201266

[datasets.kb2.primal]
allocations = 242848
bytes = 11633536
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0217729
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006187
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 31066
bytes = 1332616
compile_seconds = 0.0
samples = 3
seconds = 0.0008919

[datasets.sc50a.dual]
allocations = 74027
bytes = 3409168
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021894
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005886
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3063904
compile_seconds = 0.0
samples = 3
seconds = 0.0017431

[datasets.sc50a.primal]
allocations = 73972
bytes = 3362192
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022343
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005516
status = "OPTIMAL"

[probes.negative]
allocations = 15977
bytes = 623336
compile_seconds = 0.0
samples = 3
seconds = 0.0004828

[probes.nonunit]
allocations = 18898
bytes = 738936
compile_seconds = 0.0
samples = 3
seconds = 0.0004605

[probes.unit]
allocations = 15215
bytes = 600144
compile_seconds = 0.0
samples = 3
seconds = 0.0004254

[probes.zero]
allocations = 11151
bytes = 481648
compile_seconds = 0.0
samples = 3
seconds = 0.0002654
