julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dependent]
allocations = 19175
bytes = 812440
compile_seconds = 0.0
samples = 3
seconds = 0.0005363

[datasets.adlittle.dual]
allocations = 96127
bytes = 4604168
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033976
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009038
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 94112
bytes = 3815672
compile_seconds = 0.0
samples = 3
seconds = 0.002098999

[datasets.adlittle.primal]
allocations = 96925
bytes = 4881880
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035237
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607024
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010756
status = "OPTIMAL"

[datasets.afiro.dependent]
allocations = 5785
bytes = 257648
compile_seconds = 0.0
samples = 3
seconds = 0.0001676

[datasets.afiro.dual]
allocations = 23460
bytes = 1109392
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008586
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001835
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 22645
bytes = 974080
compile_seconds = 0.0
samples = 3
seconds = 0.0006155

[datasets.afiro.primal]
allocations = 23366
bytes = 1088096
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007249
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001946
status = "OPTIMAL"

[datasets.flugpl.dependent]
allocations = 4731
bytes = 220656
compile_seconds = 0.0
samples = 3
seconds = 0.0001115

[datasets.flugpl.dual]
allocations = 36561
bytes = 1487752
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009075
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001251
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1378016
compile_seconds = 0.0
samples = 3
seconds = 0.0007675

[datasets.flugpl.primal]
allocations = 36910
bytes = 1532344
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008837
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001541
status = "OPTIMAL"

[datasets.kb2.dependent]
allocations = 96619
bytes = 4115000
compile_seconds = 0.0
samples = 3
seconds = 0.0042351

[datasets.kb2.dual]
allocations = 267764
bytes = 12603320
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0209954
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878224
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007632
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 266562
bytes = 12153224
compile_seconds = 0.0
samples = 3
seconds = 0.0208406

[datasets.kb2.primal]
allocations = 267931
bytes = 12618232
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021771101
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005758
status = "OPTIMAL"

[datasets.sc50a.dependent]
allocations = 47978
bytes = 1965488
compile_seconds = 0.0
samples = 3
seconds = 0.0009883

[datasets.sc50a.dual]
allocations = 95594
bytes = 4196152
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024049
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005488
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 94522
bytes = 3850664
compile_seconds = 0.0
samples = 3
seconds = 0.0020634

[datasets.sc50a.primal]
allocations = 95539
bytes = 4149128
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021621
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005217
status = "OPTIMAL"

[probes.empty]
allocations = 649
bytes = 80400
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[probes.nonunit]
allocations = 22453
bytes = 870720
compile_seconds = 0.0
samples = 3
seconds = 0.0004038

[probes.unit]
allocations = 15595
bytes = 609584
compile_seconds = 0.0
samples = 3
seconds = 0.0003852

[probes.zero]
allocations = 11277
bytes = 484136
compile_seconds = 0.0
samples = 3
seconds = 0.0002329
