julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4050056
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003077301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461096
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008586
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3259352
compile_seconds = 0.0
samples = 3
seconds = 0.0018896

[datasets.adlittle.primal]
allocations = 83190
bytes = 4327192
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003378101
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010816
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 639656
compile_seconds = 0.0
samples = 3
seconds = 0.0003169

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 4.23e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 127240
compile_seconds = 0.0
samples = 3
seconds = 0.0001054

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 833704
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008224
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002232
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 698536
compile_seconds = 0.0
samples = 3
seconds = 0.0006211

[datasets.afiro.primal]
allocations = 16131
bytes = 811704
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006954
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001981
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92056
compile_seconds = 0.0
samples = 3
seconds = 8.77e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 41184
compile_seconds = 0.0
samples = 3
seconds = 7.09e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 173408
compile_seconds = 0.0
samples = 3
seconds = 0.0001468

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.flugpl.dual]
allocations = 26397
bytes = 1098864
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0006867
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001307
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25726
bytes = 988584
compile_seconds = 0.0
samples = 3
seconds = 0.0005827

[datasets.flugpl.primal]
allocations = 26746
bytes = 1143040
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000796
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001701
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122320
compile_seconds = 0.0
samples = 3
seconds = 7.79e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.33e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 149208
compile_seconds = 0.0
samples = 3
seconds = 0.0001251

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11014712
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020605003
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878064
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007847
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10560808
compile_seconds = 0.0
samples = 3
seconds = 0.020377504

[datasets.kb2.primal]
allocations = 228386
bytes = 11027800
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020138403
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006008
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453056
compile_seconds = 0.0
samples = 3
seconds = 0.0002264

[datasets.kb2.singleton]
allocations = 1915
bytes = 105016
compile_seconds = 0.0
samples = 3
seconds = 7.69e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127464
compile_seconds = 0.0
samples = 3
seconds = 0.0001285

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.38e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3107920
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002010901
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005429
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2761536
compile_seconds = 0.0
samples = 3
seconds = 0.0014447

[datasets.sc50a.primal]
allocations = 65958
bytes = 3060800
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020049
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004981
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 220848
compile_seconds = 0.0
samples = 3
seconds = 0.0001435

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.66e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 262064
compile_seconds = 0.0
samples = 3
seconds = 0.000152701

[probes.fraction_negative]
allocations = 23940
bytes = 951496
compile_seconds = 0.0
samples = 3
seconds = 0.0004241

[probes.fraction_positive]
allocations = 23940
bytes = 951544
compile_seconds = 0.0
samples = 3
seconds = 0.000432

[probes.negative]
allocations = 23940
bytes = 948584
compile_seconds = 0.0
samples = 3
seconds = 0.0004679

[probes.positive]
allocations = 23940
bytes = 947672
compile_seconds = 0.0
samples = 3
seconds = 0.0004814

[probes.unequal]
allocations = 23940
bytes = 951672
compile_seconds = 0.0
samples = 3
seconds = 0.0004572

[probes.unit]
allocations = 20100
bytes = 818120
compile_seconds = 0.0
samples = 3
seconds = 0.000381101
