julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4136904
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035037
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010103
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3348616
compile_seconds = 0.0
samples = 3
seconds = 0.0022498

[datasets.adlittle.primal]
allocations = 85589
bytes = 4413112
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034511
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607776
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011846
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.09e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177824
compile_seconds = 0.0
samples = 3
seconds = 0.0001166

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009201
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89952
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002247
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733096
compile_seconds = 0.0
samples = 3
seconds = 0.0006621

[datasets.afiro.primal]
allocations = 17051
bytes = 846584
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008404
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000222
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45584
compile_seconds = 0.0
samples = 3
seconds = 0.0001011

[datasets.afiro.sparse]
allocations = 4987
bytes = 218488
compile_seconds = 0.0
samples = 3
seconds = 0.000217

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309360
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000886801
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001261
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1199736
compile_seconds = 0.0
samples = 3
seconds = 0.000760401

[datasets.flugpl.primal]
allocations = 32481
bytes = 1354000
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001018801
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001502
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.75e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217368
compile_seconds = 0.0
samples = 3
seconds = 0.0001378

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132168
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020382399
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877840
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008806
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10678328
compile_seconds = 0.0
samples = 3
seconds = 0.020268599

[datasets.kb2.primal]
allocations = 231373
bytes = 11146232
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021634418
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006266
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112464
compile_seconds = 0.0
samples = 3
seconds = 8.93e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161424
compile_seconds = 0.0
samples = 3
seconds = 0.0001333

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.31e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3198784
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002271602
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000608401
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853440
compile_seconds = 0.0
samples = 3
seconds = 0.001695901

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151648
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002328802
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005366
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.2e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300256
compile_seconds = 0.0
samples = 3
seconds = 0.000217

[probes.cancel_fraction]
allocations = 23428
bytes = 931448
compile_seconds = 0.0
samples = 3
seconds = 0.0005183

[probes.cancel_integer]
allocations = 22532
bytes = 893960
compile_seconds = 0.0
samples = 3
seconds = 0.000498299

[probes.sum_fraction]
allocations = 23940
bytes = 949128
compile_seconds = 0.0
samples = 3
seconds = 0.0005063

[probes.sum_integer]
allocations = 23044
bytes = 912520
compile_seconds = 0.0
samples = 3
seconds = 0.0005353

[probes.unequal_denominator]
allocations = 24196
bytes = 962984
compile_seconds = 0.0
samples = 3
seconds = 0.0006104

[probes.zero_constant]
allocations = 21508
bytes = 872328
compile_seconds = 0.0
samples = 3
seconds = 0.000482399
