julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4137272
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033055
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461224
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009373
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3347880
compile_seconds = 0.0
samples = 3
seconds = 0.0021037

[datasets.adlittle.primal]
allocations = 85589
bytes = 4413864
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003386199
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010696
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.0e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177408
compile_seconds = 0.0
samples = 3
seconds = 0.0001281

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868312
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008057
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.00022
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 732712
compile_seconds = 0.0
samples = 3
seconds = 0.0005921

[datasets.afiro.primal]
allocations = 17051
bytes = 846760
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000745
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002167
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45504
compile_seconds = 0.0
samples = 3
seconds = 8.69e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 217704
compile_seconds = 0.0
samples = 3
seconds = 0.0001659

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309680
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010113
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001868
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1199432
compile_seconds = 0.0
samples = 3
seconds = 0.000774899

[datasets.flugpl.primal]
allocations = 32481
bytes = 1354080
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009321
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001919
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.71e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216968
compile_seconds = 0.0
samples = 3
seconds = 0.0001238

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132632
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020917998
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877952
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007718
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10679656
compile_seconds = 0.0
samples = 3
seconds = 0.022177098

[datasets.kb2.primal]
allocations = 231373
bytes = 11145848
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020874898
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000584
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112464
compile_seconds = 0.0
samples = 3
seconds = 8.09e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161168
compile_seconds = 0.0
samples = 3
seconds = 9.64e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.85e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199392
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025221
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306368
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006086
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2854400
compile_seconds = 0.0
samples = 3
seconds = 0.0016904

[datasets.sc50a.primal]
allocations = 68651
bytes = 3152272
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021504
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005236
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.03e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 299888
compile_seconds = 0.0
samples = 3
seconds = 0.0001823

[probes.fractional]
allocations = 22020
bytes = 897816
compile_seconds = 0.0
samples = 3
seconds = 0.000452

[probes.inexact_beta]
allocations = 9092
bytes = 351880
compile_seconds = 0.0
samples = 3
seconds = 0.0002082

[probes.negative]
allocations = 22020
bytes = 895272
compile_seconds = 0.0
samples = 3
seconds = 0.0004444

[probes.nonzero_rhs]
allocations = 24196
bytes = 962312
compile_seconds = 0.0
samples = 3
seconds = 0.0004466

[probes.positive]
allocations = 22020
bytes = 893800
compile_seconds = 0.0
samples = 3
seconds = 0.000456899

[probes.unit_pivot]
allocations = 19332
bytes = 807352
compile_seconds = 0.0
samples = 3
seconds = 0.00038
