julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4135336
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003627402
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461448
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009919
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3346680
compile_seconds = 0.0
samples = 3
seconds = 0.002122201

[datasets.adlittle.primal]
allocations = 85589
bytes = 4412152
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003574402
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001145201
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.65e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 178080
compile_seconds = 0.0
samples = 3
seconds = 0.0001297

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868808
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008217
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002118
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733720
compile_seconds = 0.0
samples = 3
seconds = 0.0006386

[datasets.afiro.primal]
allocations = 17051
bytes = 847704
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008261
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002453
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45664
compile_seconds = 0.0
samples = 3
seconds = 8.97e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218152
compile_seconds = 0.0
samples = 3
seconds = 0.0001674

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309552
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001042701
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001972
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1199448
compile_seconds = 0.0
samples = 3
seconds = 0.0008611

[datasets.flugpl.primal]
allocations = 32481
bytes = 1354208
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001093801
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002177
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216744
compile_seconds = 0.0
samples = 3
seconds = 0.0001395

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11130968
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021567207
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878128
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008886
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10679192
compile_seconds = 0.0
samples = 3
seconds = 0.019913906

[datasets.kb2.primal]
allocations = 231373
bytes = 11145976
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022335207
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005638
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112816
compile_seconds = 0.0
samples = 3
seconds = 0.0001007

[datasets.kb2.sparse]
allocations = 2836
bytes = 161632
compile_seconds = 0.0
samples = 3
seconds = 0.0001211

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199344
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002165201
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306288
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006875
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2852752
compile_seconds = 0.0
samples = 3
seconds = 0.001827

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151632
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002319701
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005331
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.41e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300208
compile_seconds = 0.0
samples = 3
seconds = 0.0002109

[probes.fractional]
allocations = 22020
bytes = 899576
compile_seconds = 0.0
samples = 3
seconds = 0.0004996

[probes.inexact_beta]
allocations = 9092
bytes = 352856
compile_seconds = 0.0
samples = 3
seconds = 0.0001969

[probes.negative]
allocations = 22020
bytes = 896632
compile_seconds = 0.0
samples = 3
seconds = 0.0005037

[probes.nonzero_rhs]
allocations = 24196
bytes = 963912
compile_seconds = 0.0
samples = 3
seconds = 0.000447101

[probes.positive]
allocations = 22020
bytes = 895128
compile_seconds = 0.0
samples = 3
seconds = 0.000565901

[probes.unit_pivot]
allocations = 19332
bytes = 808984
compile_seconds = 0.0
samples = 3
seconds = 0.0004291
