julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4137000
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003422602
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010034
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3347384
compile_seconds = 0.0
samples = 3
seconds = 0.0021316

[datasets.adlittle.primal]
allocations = 85589
bytes = 4413752
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003580202
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607520
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001110701
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.9e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177920
compile_seconds = 0.0
samples = 3
seconds = 0.000142

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868872
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000863104
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89952
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000223101
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733720
compile_seconds = 0.0
samples = 3
seconds = 0.000659003

[datasets.afiro.primal]
allocations = 17051
bytes = 847144
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000709603
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000233201
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44880
compile_seconds = 0.0
samples = 3
seconds = 7.4401e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218616
compile_seconds = 0.0
samples = 3
seconds = 0.0001733

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309360
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001073001
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000161001
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1200648
compile_seconds = 0.0
samples = 3
seconds = 0.000785501

[datasets.flugpl.primal]
allocations = 32481
bytes = 1353776
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000952401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000155
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217256
compile_seconds = 0.0
samples = 3
seconds = 0.000135101

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11133544
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021667915
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878416
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009054
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10679656
compile_seconds = 0.0
samples = 3
seconds = 0.021028314

[datasets.kb2.primal]
allocations = 231373
bytes = 11147496
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022478416
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006218
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112272
compile_seconds = 0.0
samples = 3
seconds = 0.000108201

[datasets.kb2.sparse]
allocations = 2836
bytes = 161712
compile_seconds = 0.0
samples = 3
seconds = 0.0001079

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.41e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199472
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002327102
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306512
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006106
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853088
compile_seconds = 0.0
samples = 3
seconds = 0.001724401

[datasets.sc50a.primal]
allocations = 68651
bytes = 3152256
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002299201
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0006162
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 8.5e-6

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300944
compile_seconds = 0.0
samples = 3
seconds = 0.0001985

[probes.fractional]
allocations = 19972
bytes = 816568
compile_seconds = 0.0
samples = 3
seconds = 0.0004365

[probes.inexact_beta]
allocations = 9092
bytes = 353256
compile_seconds = 0.0
samples = 3
seconds = 0.0001894

[probes.negative]
allocations = 19972
bytes = 814136
compile_seconds = 0.0
samples = 3
seconds = 0.0004271

[probes.nonzero_rhs]
allocations = 24196
bytes = 963336
compile_seconds = 0.0
samples = 3
seconds = 0.000496502

[probes.positive]
allocations = 19972
bytes = 813016
compile_seconds = 0.0
samples = 3
seconds = 0.000457601

[probes.unit_pivot]
allocations = 17284
bytes = 726488
compile_seconds = 0.0
samples = 3
seconds = 0.0003802
