julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4046872
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0038912
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461720
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010976
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3257752
compile_seconds = 0.0
samples = 3
seconds = 0.0025159

[datasets.adlittle.primal]
allocations = 83190
bytes = 4323816
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041632
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607744
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012031
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 640616
compile_seconds = 0.0
samples = 3
seconds = 0.0004674

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.6e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 127976
compile_seconds = 0.0
samples = 3
seconds = 0.0001276

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 833976
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009153
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002271
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 698904
compile_seconds = 0.0
samples = 3
seconds = 0.0006976

[datasets.afiro.primal]
allocations = 16131
bytes = 812040
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009483
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002364
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92520
compile_seconds = 0.0
samples = 3
seconds = 0.0001082

[datasets.afiro.singleton]
allocations = 747
bytes = 41264
compile_seconds = 0.0
samples = 3
seconds = 8.54e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 173744
compile_seconds = 0.0
samples = 3
seconds = 0.0001758

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 26397
bytes = 1098800
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010898
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001783
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25726
bytes = 988648
compile_seconds = 0.0
samples = 3
seconds = 0.0007661

[datasets.flugpl.primal]
allocations = 26746
bytes = 1143456
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011097
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002084
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122736
compile_seconds = 0.0
samples = 3
seconds = 0.0001261

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.74e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 150408
compile_seconds = 0.0
samples = 3
seconds = 0.0001533

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 8.5e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11014248
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0234201
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878224
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009163
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10561272
compile_seconds = 0.0
samples = 3
seconds = 0.0215598

[datasets.kb2.primal]
allocations = 228386
bytes = 11028200
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022498
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006164
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 453232
compile_seconds = 0.0
samples = 3
seconds = 0.0003555

[datasets.kb2.singleton]
allocations = 1915
bytes = 105352
compile_seconds = 0.0
samples = 3
seconds = 7.95e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127816
compile_seconds = 0.0
samples = 3
seconds = 0.0001174

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 2.06e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3108000
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002368
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306224
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006652
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2761808
compile_seconds = 0.0
samples = 3
seconds = 0.0018022

[datasets.sc50a.primal]
allocations = 65958
bytes = 3060672
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023289
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005525
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 220992
compile_seconds = 0.0
samples = 3
seconds = 0.0002017

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.01e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 262464
compile_seconds = 0.0
samples = 3
seconds = 0.0001882

[probes.fraction_negative]
allocations = 22916
bytes = 911016
compile_seconds = 0.0
samples = 3
seconds = 0.0005767

[probes.fraction_positive]
allocations = 22916
bytes = 911160
compile_seconds = 0.0
samples = 3
seconds = 0.0005253

[probes.negative]
allocations = 22916
bytes = 908296
compile_seconds = 0.0
samples = 3
seconds = 0.0005505

[probes.positive]
allocations = 22916
bytes = 905896
compile_seconds = 0.0
samples = 3
seconds = 0.0005851

[probes.unequal]
allocations = 23940
bytes = 952248
compile_seconds = 0.0
samples = 3
seconds = 0.0005589

[probes.unit]
allocations = 20100
bytes = 818504
compile_seconds = 0.0
samples = 3
seconds = 0.0005191
