julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4136856
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003787007
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461512
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000941102
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3347896
compile_seconds = 0.0
samples = 3
seconds = 0.002098104

[datasets.adlittle.primal]
allocations = 85589
bytes = 4413560
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003217506
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607056
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001128602
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.53e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 178832
compile_seconds = 0.0
samples = 3
seconds = 0.0001323

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 869464
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000740401
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000199501
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733928
compile_seconds = 0.0
samples = 3
seconds = 0.000592604

[datasets.afiro.primal]
allocations = 17051
bytes = 848040
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000628102
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000201001
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45232
compile_seconds = 0.0
samples = 3
seconds = 9.6301e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 219160
compile_seconds = 0.0
samples = 3
seconds = 0.000164802

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1310720
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000755901
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001428
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1199848
compile_seconds = 0.0
samples = 3
seconds = 0.000670601

[datasets.flugpl.primal]
allocations = 32481
bytes = 1355296
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000799901
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001924
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217672
compile_seconds = 0.0
samples = 3
seconds = 0.000124701

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11133656
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022042939
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878288
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000785201
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10680840
compile_seconds = 0.0
samples = 3
seconds = 0.020379037

[datasets.kb2.primal]
allocations = 231373
bytes = 11148712
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020027635
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000581101
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112688
compile_seconds = 0.0
samples = 3
seconds = 7.96e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162352
compile_seconds = 0.0
samples = 3
seconds = 0.0001165

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.54e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3198848
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001956203
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306384
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000555801
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853088
compile_seconds = 0.0
samples = 3
seconds = 0.001480803

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151472
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002092104
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004542
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.0e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 301440
compile_seconds = 0.0
samples = 3
seconds = 0.0001537

[probes.cancel_fraction]
allocations = 7044
bytes = 297168
compile_seconds = 0.0
samples = 3
seconds = 0.000178101

[probes.cancel_integer]
allocations = 6269
bytes = 261320
compile_seconds = 0.0
samples = 3
seconds = 0.000167401

[probes.sum_fraction]
allocations = 7430
bytes = 309648
compile_seconds = 0.0
samples = 3
seconds = 0.000179801

[probes.sum_integer]
allocations = 6655
bytes = 274920
compile_seconds = 0.0
samples = 3
seconds = 0.000171101

[probes.unequal_denominator]
allocations = 7558
bytes = 312240
compile_seconds = 0.0
samples = 3
seconds = 0.000171501

[probes.zero_old]
allocations = 4870
bytes = 220528
compile_seconds = 0.0
samples = 3
seconds = 0.000134701
