julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.adlittle.dual]
allocations = 119606
bytes = 5527656
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039044
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461016
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009914
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117591
bytes = 4737736
compile_seconds = 0.0
samples = 3
seconds = 0.002597001

[datasets.adlittle.primal]
allocations = 120404
bytes = 5803624
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0042098
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607168
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011472
status = "OPTIMAL"

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.afiro.dual]
allocations = 27480
bytes = 1268856
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008477
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001957
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26665
bytes = 1132136
compile_seconds = 0.0
samples = 3
seconds = 0.0007059

[datasets.afiro.primal]
allocations = 27386
bytes = 1247528
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008665
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002058
status = "OPTIMAL"

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.2e-6

[datasets.flugpl.dual]
allocations = 39654
bytes = 1604560
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011158
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001666
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38983
bytes = 1494520
compile_seconds = 0.0
samples = 3
seconds = 0.0009475

[datasets.flugpl.primal]
allocations = 40003
bytes = 1648944
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0012673
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000202
status = "OPTIMAL"

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 292805
bytes = 13582448
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0215393
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878384
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008659
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291603
bytes = 13128720
compile_seconds = 0.0
samples = 3
seconds = 0.0212723

[datasets.kb2.primal]
allocations = 292972
bytes = 13597296
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0234906
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006309
status = "OPTIMAL"

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.sc50a.dual]
allocations = 102776
bytes = 4471024
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0027085
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006476
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101704
bytes = 4124656
compile_seconds = 0.0
samples = 3
seconds = 0.0022962

[datasets.sc50a.primal]
allocations = 102721
bytes = 4424432
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0027304
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.00055
status = "OPTIMAL"

[probes.inequalities]
allocations = 4
bytes = 4312
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[probes.wide]
allocations = 4
bytes = 4312
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5
