julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4137816
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031371
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461416
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009416
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3348536
compile_seconds = 0.0
samples = 3
seconds = 0.0018947

[datasets.adlittle.primal]
allocations = 85589
bytes = 4414456
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036421
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607616
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010982
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.48e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177520
compile_seconds = 0.0
samples = 3
seconds = 0.000118

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 869720
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000778799
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000186
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733464
compile_seconds = 0.0
samples = 3
seconds = 0.000503

[datasets.afiro.primal]
allocations = 17051
bytes = 847896
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007722
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002123
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44560
compile_seconds = 0.0
samples = 3
seconds = 7.46e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218344
compile_seconds = 0.0
samples = 3
seconds = 0.0001738

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.6e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309888
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009772
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001716
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1200680
compile_seconds = 0.0
samples = 3
seconds = 0.0007304

[datasets.flugpl.primal]
allocations = 32481
bytes = 1354816
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010185
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001844
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.83e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216600
compile_seconds = 0.0
samples = 3
seconds = 0.0001446

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11134424
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0207304
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877936
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008664
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10680696
compile_seconds = 0.0
samples = 3
seconds = 0.020115499

[datasets.kb2.primal]
allocations = 231373
bytes = 11146392
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022127199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005978
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 111808
compile_seconds = 0.0
samples = 3
seconds = 9.49e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161056
compile_seconds = 0.0
samples = 3
seconds = 0.0001182

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.71e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199584
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022763
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005869
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853776
compile_seconds = 0.0
samples = 3
seconds = 0.0016626

[datasets.sc50a.primal]
allocations = 68651
bytes = 3152384
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021223
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005136
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.01e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300944
compile_seconds = 0.0
samples = 3
seconds = 0.0001997

[probes.alpha_negative]
allocations = 24196
bytes = 963544
compile_seconds = 0.0
samples = 3
seconds = 0.0004735

[probes.alpha_positive]
allocations = 24196
bytes = 963480
compile_seconds = 0.0
samples = 3
seconds = 0.0004822

[probes.beta_negative]
allocations = 24196
bytes = 966120
compile_seconds = 0.0
samples = 3
seconds = 0.0005192

[probes.beta_positive]
allocations = 24196
bytes = 963976
compile_seconds = 0.0
samples = 3
seconds = 0.0004776

[probes.inexact_beta]
allocations = 11012
bytes = 415496
compile_seconds = 0.0
samples = 3
seconds = 0.0002259

[probes.nonunit_ratios]
allocations = 24196
bytes = 963544
compile_seconds = 0.0
samples = 3
seconds = 0.0005251
