julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4052376
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032305
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008944
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3261640
compile_seconds = 0.0
samples = 3
seconds = 0.0022897

[datasets.adlittle.primal]
allocations = 83190
bytes = 4329672
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0032901
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607520
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012539
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 643832
compile_seconds = 0.0
samples = 3
seconds = 0.0003431

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.51e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 127128
compile_seconds = 0.0
samples = 3
seconds = 0.000106

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 837688
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007535
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000198
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 702024
compile_seconds = 0.0
samples = 3
seconds = 0.0005299

[datasets.afiro.primal]
allocations = 16131
bytes = 815112
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006297
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002158
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93688
compile_seconds = 0.0
samples = 3
seconds = 8.64e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40384
compile_seconds = 0.0
samples = 3
seconds = 8.56e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 175664
compile_seconds = 0.0
samples = 3
seconds = 0.0001459

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 26397
bytes = 1102624
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008233
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001552
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25726
bytes = 992136
compile_seconds = 0.0
samples = 3
seconds = 0.000591

[datasets.flugpl.primal]
allocations = 26746
bytes = 1146848
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007973
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001478
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 124576
compile_seconds = 0.0
samples = 3
seconds = 9.7e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.79e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 151544
compile_seconds = 0.0
samples = 3
seconds = 0.0001057

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11019032
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0204683
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000786
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10565128
compile_seconds = 0.0
samples = 3
seconds = 0.019519

[datasets.kb2.primal]
allocations = 228386
bytes = 11033544
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0197526
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260944
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005864
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 457056
compile_seconds = 0.0
samples = 3
seconds = 0.0002427

[datasets.kb2.singleton]
allocations = 1915
bytes = 105080
compile_seconds = 0.0
samples = 3
seconds = 8.91e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127560
compile_seconds = 0.0
samples = 3
seconds = 9.91e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.75e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3109488
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018317
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000507199
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2764736
compile_seconds = 0.0
samples = 3
seconds = 0.0013814

[datasets.sc50a.primal]
allocations = 65958
bytes = 3062272
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019555
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000465099
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 224672
compile_seconds = 0.0
samples = 3
seconds = 0.000142

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.79e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 264624
compile_seconds = 0.0
samples = 3
seconds = 0.0001665

[probes.cancelled]
allocations = 15578
bytes = 611320
compile_seconds = 0.0
samples = 3
seconds = 0.0002987

[probes.negative]
allocations = 17114
bytes = 661208
compile_seconds = 0.0
samples = 3
seconds = 0.0003572

[probes.positive]
allocations = 17114
bytes = 660312
compile_seconds = 0.0
samples = 3
seconds = 0.000371

[probes.unequal]
allocations = 17114
bytes = 661592
compile_seconds = 0.0
samples = 3
seconds = 0.0003421

[probes.zero_bound]
allocations = 12762
bytes = 522920
compile_seconds = 0.0
samples = 3
seconds = 0.000289

[probes.zero_shift]
allocations = 7243
bytes = 296552
compile_seconds = 0.0
samples = 3
seconds = 0.000174
