julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4136024
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003761801
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010588
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3347752
compile_seconds = 0.0
samples = 3
seconds = 0.002601201

[datasets.adlittle.primal]
allocations = 85589
bytes = 4412456
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003670901
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011727
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.79e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177584
compile_seconds = 0.0
samples = 3
seconds = 0.0001359

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868840
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008465
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002013
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 732840
compile_seconds = 0.0
samples = 3
seconds = 0.0007151

[datasets.afiro.primal]
allocations = 17051
bytes = 847080
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000732
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002158
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45408
compile_seconds = 0.0
samples = 3
seconds = 8.87e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218232
compile_seconds = 0.0
samples = 3
seconds = 0.0001873

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 8.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.8e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309104
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001017001
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001675
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1198888
compile_seconds = 0.0
samples = 3
seconds = 0.000841301

[datasets.flugpl.primal]
allocations = 32481
bytes = 1353520
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001177001
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002079
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217240
compile_seconds = 0.0
samples = 3
seconds = 0.000155001

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 8.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132472
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020850807
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878000
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008294
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10680184
compile_seconds = 0.0
samples = 3
seconds = 0.021095207

[datasets.kb2.primal]
allocations = 231373
bytes = 11146632
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021772108
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000653
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112624
compile_seconds = 0.0
samples = 3
seconds = 9.43e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161104
compile_seconds = 0.0
samples = 3
seconds = 0.0001415

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.51e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3198720
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002189601
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306320
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000568201
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2852800
compile_seconds = 0.0
samples = 3
seconds = 0.001752401

[datasets.sc50a.primal]
allocations = 68651
bytes = 3151360
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002377301
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000575201
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.06e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300656
compile_seconds = 0.0
samples = 3
seconds = 0.00021

[probes.negative]
allocations = 21508
bytes = 872632
compile_seconds = 0.0
samples = 3
seconds = 0.0004991

[probes.nonzero_constant]
allocations = 24196
bytes = 963096
compile_seconds = 0.0
samples = 3
seconds = 0.0005102

[probes.positive]
allocations = 21508
bytes = 871512
compile_seconds = 0.0
samples = 3
seconds = 0.000684801

[probes.unit_negative]
allocations = 18180
bytes = 753480
compile_seconds = 0.0
samples = 3
seconds = 0.0004254

[probes.unit_positive]
allocations = 17668
bytes = 739400
compile_seconds = 0.0
samples = 3
seconds = 0.0004261

[probes.zero_alpha]
allocations = 19204
bytes = 793800
compile_seconds = 0.0
samples = 3
seconds = 0.0003994
