julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4137176
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003666206
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461624
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001020302
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3346120
compile_seconds = 0.0
samples = 3
seconds = 0.002204704

[datasets.adlittle.primal]
allocations = 85589
bytes = 4413416
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003625906
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001162102
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 8.19e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177232
compile_seconds = 0.0
samples = 3
seconds = 0.0001434

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 867992
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000740701
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000232001
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 732440
compile_seconds = 0.0
samples = 3
seconds = 0.0006037

[datasets.afiro.primal]
allocations = 17051
bytes = 846392
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000810501
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002283
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 44896
compile_seconds = 0.0
samples = 3
seconds = 9.34e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218136
compile_seconds = 0.0
samples = 3
seconds = 0.000157

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.7e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309040
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001055101
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000179101
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1198680
compile_seconds = 0.0
samples = 3
seconds = 0.000863601

[datasets.flugpl.primal]
allocations = 32481
bytes = 1353696
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001137701
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001813
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.41e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216728
compile_seconds = 0.0
samples = 3
seconds = 0.0002067

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132232
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021433535
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878288
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000930701
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10677064
compile_seconds = 0.0
samples = 3
seconds = 0.020208032

[datasets.kb2.primal]
allocations = 231373
bytes = 11146856
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020973434
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260976
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000649601
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112736
compile_seconds = 0.0
samples = 3
seconds = 0.0001063

[datasets.kb2.sparse]
allocations = 2836
bytes = 161104
compile_seconds = 0.0
samples = 3
seconds = 0.0001421

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.7e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 2.4e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3197584
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002305403
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000705901
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2852592
compile_seconds = 0.0
samples = 3
seconds = 0.001551002

[datasets.sc50a.primal]
allocations = 68651
bytes = 3150400
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002405304
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000519601
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.92e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 299952
compile_seconds = 0.0
samples = 3
seconds = 0.00023

[probes.cancel_fraction]
allocations = 6788
bytes = 275920
compile_seconds = 0.0
samples = 3
seconds = 0.0002084

[probes.cancel_integer]
allocations = 5885
bytes = 237816
compile_seconds = 0.0
samples = 3
seconds = 0.0001856

[probes.sum_fraction]
allocations = 7302
bytes = 295856
compile_seconds = 0.0
samples = 3
seconds = 0.0002017

[probes.sum_integer]
allocations = 6399
bytes = 258920
compile_seconds = 0.0
samples = 3
seconds = 0.0001969

[probes.unequal_denominator]
allocations = 7558
bytes = 310176
compile_seconds = 0.0
samples = 3
seconds = 0.000213

[probes.zero_old]
allocations = 4870
bytes = 218720
compile_seconds = 0.0
samples = 3
seconds = 0.0001385
