julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.doubleton]
allocations = 117
bytes = 11008
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.adlittle.dual]
allocations = 119822
bytes = 5545896
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003552302
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461640
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000919401
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117807
bytes = 4755048
compile_seconds = 0.0
samples = 3
seconds = 0.002248901

[datasets.adlittle.primal]
allocations = 120620
bytes = 5822696
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003665402
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607136
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010802
status = "OPTIMAL"

[datasets.afiro.doubleton]
allocations = 59
bytes = 3744
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.afiro.dual]
allocations = 27568
bytes = 1273496
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000833801
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001831
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26753
bytes = 1137480
compile_seconds = 0.0
samples = 3
seconds = 0.0006493

[datasets.afiro.primal]
allocations = 27474
bytes = 1252216
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007741
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001864
status = "OPTIMAL"

[datasets.flugpl.doubleton]
allocations = 41
bytes = 2448
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.flugpl.dual]
allocations = 39760
bytes = 1609200
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000909401
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001353
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1499336
compile_seconds = 0.0
samples = 3
seconds = 0.000726

[datasets.flugpl.primal]
allocations = 40109
bytes = 1653808
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000907601
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001787
status = "OPTIMAL"

[datasets.kb2.doubleton]
allocations = 91
bytes = 8272
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.kb2.dual]
allocations = 292979
bytes = 13595872
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02088701
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878368
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000801501
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291777
bytes = 13143040
compile_seconds = 0.0
samples = 3
seconds = 0.02075361

[datasets.kb2.primal]
allocations = 293146
bytes = 13610112
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021072411
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000613801
status = "OPTIMAL"

[datasets.sc50a.doubleton]
allocations = 104
bytes = 6352
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.sc50a.dual]
allocations = 102950
bytes = 4478976
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002294202
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005529
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101878
bytes = 4133472
compile_seconds = 0.0
samples = 3
seconds = 0.001825801

[datasets.sc50a.primal]
allocations = 102895
bytes = 4432080
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002400801
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004566
status = "OPTIMAL"

[probes.inequalities]
allocations = 261
bytes = 14672
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[probes.wide]
allocations = 389
bytes = 273744
compile_seconds = 0.0
samples = 3
seconds = 8.71e-5
