julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.adlittle.dual]
allocations = 84791
bytes = 4136792
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003181216
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000865504
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82776
bytes = 3348584
compile_seconds = 0.0
samples = 3
seconds = 0.001928509

[datasets.adlittle.primal]
allocations = 85589
bytes = 4413528
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003420818
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607664
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001048706
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.2201e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177600
compile_seconds = 0.0
samples = 3
seconds = 0.0001041

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868056
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000776204
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000209302
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 732136
compile_seconds = 0.0
samples = 3
seconds = 0.000534502

[datasets.afiro.primal]
allocations = 17051
bytes = 846392
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000628404
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000207201
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45616
compile_seconds = 0.0
samples = 3
seconds = 9.97e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 217928
compile_seconds = 0.0
samples = 3
seconds = 0.0001591

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 32132
bytes = 1309024
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007826
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001178
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31461
bytes = 1199480
compile_seconds = 0.0
samples = 3
seconds = 0.000604401

[datasets.flugpl.primal]
allocations = 32481
bytes = 1353504
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000826401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000157701
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 217192
compile_seconds = 0.0
samples = 3
seconds = 0.0001355

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132120
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020613412
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878064
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000810204
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10678136
compile_seconds = 0.0
samples = 3
seconds = 0.020620404

[datasets.kb2.primal]
allocations = 231373
bytes = 11145944
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020142911
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000626401
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112688
compile_seconds = 0.0
samples = 3
seconds = 8.41e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161248
compile_seconds = 0.0
samples = 3
seconds = 0.000120501

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3199792
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001934902
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005995
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2853232
compile_seconds = 0.0
samples = 3
seconds = 0.001437901

[datasets.sc50a.primal]
allocations = 68651
bytes = 3152400
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002025702
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004874
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.09e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 299872
compile_seconds = 0.0
samples = 3
seconds = 0.0001862

[probes.fractional]
allocations = 27268
bytes = 1055800
compile_seconds = 0.0
samples = 3
seconds = 0.000499901

[probes.inexact_ratio]
allocations = 12548
bytes = 462280
compile_seconds = 0.0
samples = 3
seconds = 0.000218201

[probes.negative]
allocations = 27268
bytes = 1055672
compile_seconds = 0.0
samples = 3
seconds = 0.000510701

[probes.no_substitution]
allocations = 4
bytes = 4312
compile_seconds = 0.0
samples = 3
seconds = 9.2e-6

[probes.positive]
allocations = 27268
bytes = 1053880
compile_seconds = 0.0
samples = 3
seconds = 0.000519801

[probes.zero_rhs]
allocations = 25988
bytes = 1028344
compile_seconds = 0.0
samples = 3
seconds = 0.0004132
