julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4046600
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.00369
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461336
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010573
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3257368
compile_seconds = 0.0
samples = 3
seconds = 0.0023512

[datasets.adlittle.primal]
allocations = 83190
bytes = 4323176
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041014
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607744
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012718
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641032
compile_seconds = 0.0
samples = 3
seconds = 0.0004345

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.95e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 127624
compile_seconds = 0.0
samples = 3
seconds = 0.0001117

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 834136
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009073
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002525
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 698760
compile_seconds = 0.0
samples = 3
seconds = 0.000724

[datasets.afiro.primal]
allocations = 16131
bytes = 812264
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008299
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001785
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91992
compile_seconds = 0.0
samples = 3
seconds = 0.000113899

[datasets.afiro.singleton]
allocations = 747
bytes = 40720
compile_seconds = 0.0
samples = 3
seconds = 8.39e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 173216
compile_seconds = 0.0
samples = 3
seconds = 0.00018

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.flugpl.dual]
allocations = 26397
bytes = 1099248
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010177
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001789
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25726
bytes = 988792
compile_seconds = 0.0
samples = 3
seconds = 0.0007289

[datasets.flugpl.primal]
allocations = 26746
bytes = 1143472
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010516
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002214
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123200
compile_seconds = 0.0
samples = 3
seconds = 0.0001079

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 150360
compile_seconds = 0.0
samples = 3
seconds = 0.0001292

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11013960
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.023106
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0010607
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10562024
compile_seconds = 0.0
samples = 3
seconds = 0.0216947

[datasets.kb2.primal]
allocations = 228386
bytes = 11027912
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022176299
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006464
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454288
compile_seconds = 0.0
samples = 3
seconds = 0.000329

[datasets.kb2.singleton]
allocations = 1915
bytes = 105368
compile_seconds = 0.0
samples = 3
seconds = 9.48e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 127832
compile_seconds = 0.0
samples = 3
seconds = 0.0001424

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.2e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3108208
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024709
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306288
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0007327
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2761856
compile_seconds = 0.0
samples = 3
seconds = 0.001870499

[datasets.sc50a.primal]
allocations = 65958
bytes = 3060816
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002396
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0006016
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221872
compile_seconds = 0.0
samples = 3
seconds = 0.0001731

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.17e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 262608
compile_seconds = 0.0
samples = 3
seconds = 0.0002149

[probes.cancelled]
allocations = 11994
bytes = 472904
compile_seconds = 0.0
samples = 3
seconds = 0.0003132

[probes.negative]
allocations = 12762
bytes = 497944
compile_seconds = 0.0
samples = 3
seconds = 0.000348

[probes.positive]
allocations = 12762
bytes = 496984
compile_seconds = 0.0
samples = 3
seconds = 0.0003538

[probes.unequal]
allocations = 17114
bytes = 657672
compile_seconds = 0.0
samples = 3
seconds = 0.0004294

[probes.zero_bound]
allocations = 10586
bytes = 428984
compile_seconds = 0.0
samples = 3
seconds = 0.0003021

[probes.zero_shift]
allocations = 7243
bytes = 293976
compile_seconds = 0.0
samples = 3
seconds = 0.0002222
