julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.adlittle.dual]
allocations = 84962
bytes = 4141344
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003413699
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461304
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009848
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82947
bytes = 3352256
compile_seconds = 0.0
samples = 3
seconds = 0.0021555

[datasets.adlittle.primal]
allocations = 85760
bytes = 4418112
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036142
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607056
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011366
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.4e-5

[datasets.adlittle.sparse]
allocations = 2843
bytes = 177872
compile_seconds = 0.0
samples = 3
seconds = 0.0001314

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.afiro.dual]
allocations = 17145
bytes = 868216
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008734
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002314
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16330
bytes = 733096
compile_seconds = 0.0
samples = 3
seconds = 0.0006718

[datasets.afiro.primal]
allocations = 17051
bytes = 846408
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000779
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002202
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 843
bytes = 45120
compile_seconds = 0.0
samples = 3
seconds = 8.16e-5

[datasets.afiro.sparse]
allocations = 4987
bytes = 218520
compile_seconds = 0.0
samples = 3
seconds = 0.0001795

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.4e-6

[datasets.flugpl.dual]
allocations = 32206
bytes = 1311440
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009106
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001573
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31535
bytes = 1201896
compile_seconds = 0.0
samples = 3
seconds = 0.0007441

[datasets.flugpl.primal]
allocations = 32555
bytes = 1355792
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010473
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002071
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.89e-5

[datasets.flugpl.sparse]
allocations = 5772
bytes = 216872
compile_seconds = 0.0
samples = 3
seconds = 0.0001536

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 231206
bytes = 11132040
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021549299
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878048
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008684
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 230004
bytes = 10678552
compile_seconds = 0.0
samples = 3
seconds = 0.020208299

[datasets.kb2.primal]
allocations = 231373
bytes = 11145256
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021539999
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260992
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006366
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 2060
bytes = 112336
compile_seconds = 0.0
samples = 3
seconds = 9.55e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161600
compile_seconds = 0.0
samples = 3
seconds = 0.0001194

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 68706
bytes = 3197776
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021239
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306528
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006069
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67634
bytes = 2851776
compile_seconds = 0.0
samples = 3
seconds = 0.0016251

[datasets.sc50a.primal]
allocations = 68651
bytes = 3150400
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024105
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005622
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.23e-5

[datasets.sc50a.sparse]
allocations = 6647
bytes = 300336
compile_seconds = 0.0
samples = 3
seconds = 0.000228

[probes.both_negative]
allocations = 7586
bytes = 311600
compile_seconds = 0.0
samples = 3
seconds = 0.0001864

[probes.finite]
allocations = 17954
bytes = 701728
compile_seconds = 0.0
samples = 3
seconds = 0.0003964

[probes.negative_alpha]
allocations = 7586
bytes = 311568
compile_seconds = 0.0
samples = 3
seconds = 0.000172699

[probes.negative_coefficient]
allocations = 7586
bytes = 311584
compile_seconds = 0.0
samples = 3
seconds = 0.0002318

[probes.one_sided]
allocations = 13346
bytes = 528688
compile_seconds = 0.0
samples = 3
seconds = 0.000299599

[probes.positive]
allocations = 7586
bytes = 309712
compile_seconds = 0.0
samples = 3
seconds = 0.0001895
