[[rows]]
dataset = "afiro"
interval = 1
iterations = 20
method = "pfi"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "afiro"
interval = 20
iterations = 20
method = "pfi"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "afiro"
interval = 1
iterations = 20
method = "forrest_tomlin"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "afiro"
interval = 20
iterations = 20
method = "forrest_tomlin"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "afiro"
interval = 1
iterations = 20
method = "suhl_suhl"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "afiro"
interval = 20
iterations = 20
method = "suhl_suhl"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "afiro"
interval = 1
iterations = 20
method = "bartels_golub"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "afiro"
interval = 20
iterations = 20
method = "bartels_golub"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 1
iterations = 97
method = "pfi"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 20
iterations = 115
method = "pfi"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 1
iterations = 101
method = "forrest_tomlin"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 20
iterations = 102
method = "forrest_tomlin"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 1
iterations = 101
method = "suhl_suhl"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 20
iterations = 102
method = "suhl_suhl"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 1
iterations = 93
method = "bartels_golub"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
[[rows]]
dataset = "adlittle"
interval = 20
iterations = 102
method = "bartels_golub"
pivot_repairs = 0
price_repairs = 0
status = "OPTIMAL"
