julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119598
bytes = 5523320
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003853
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461672
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009914
status = "OPTIMAL"

[datasets.adlittle.fixings]
allocations = 119
bytes = 39040
compile_seconds = 0.0
samples = 3
seconds = 9.14e-5

[datasets.adlittle.presolve]
allocations = 117583
bytes = 4734088
compile_seconds = 0.0
samples = 3
seconds = 0.0025384

[datasets.adlittle.primal]
allocations = 120396
bytes = 5801032
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0040464
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607168
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011989
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 27466
bytes = 1266312
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009225
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002068
status = "OPTIMAL"

[datasets.afiro.fixings]
allocations = 3
bytes = 752
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.afiro.presolve]
allocations = 26651
bytes = 1131128
compile_seconds = 0.0
samples = 3
seconds = 0.0006795

[datasets.afiro.primal]
allocations = 27372
bytes = 1245432
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009648
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002215
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 39640
bytes = 1602176
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009862
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001553
status = "OPTIMAL"

[datasets.flugpl.fixings]
allocations = 115
bytes = 10464
compile_seconds = 0.0
samples = 3
seconds = 2.05e-5

[datasets.flugpl.presolve]
allocations = 38969
bytes = 1493000
compile_seconds = 0.0
samples = 3
seconds = 0.0008494

[datasets.flugpl.primal]
allocations = 39989
bytes = 1647328
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001106
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001858
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 292793
bytes = 13580640
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021892399
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878656
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008362
status = "OPTIMAL"

[datasets.kb2.fixings]
allocations = 3
bytes = 912
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.kb2.presolve]
allocations = 291591
bytes = 13125808
compile_seconds = 0.0
samples = 3
seconds = 0.0212141

[datasets.kb2.primal]
allocations = 292960
bytes = 13595952
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021549191
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000649
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 102758
bytes = 4467760
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002766399
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005912
status = "OPTIMAL"

[datasets.sc50a.fixings]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.sc50a.presolve]
allocations = 101686
bytes = 4120128
compile_seconds = 0.0
samples = 3
seconds = 0.0020567

[datasets.sc50a.primal]
allocations = 102703
bytes = 4420752
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002497899
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005382
status = "OPTIMAL"

[probes.blocked]
allocations = 4
bytes = 2392
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[probes.selected]
allocations = 6064
bytes = 225736
compile_seconds = 0.0
samples = 3
seconds = 0.0001285
