julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.7e-6

[datasets.adlittle.dual]
allocations = 120002
bytes = 5551496
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003697901
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 460952
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009109
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117987
bytes = 4761288
compile_seconds = 0.0
samples = 3
seconds = 0.002874001

[datasets.adlittle.primal]
allocations = 120800
bytes = 5828696
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004288702
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607248
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001124101
status = "OPTIMAL"

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.dual]
allocations = 27653
bytes = 1277064
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008285
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000180001
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26838
bytes = 1141160
compile_seconds = 0.0
samples = 3
seconds = 0.000867

[datasets.afiro.primal]
allocations = 27559
bytes = 1255416
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008182
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001728
status = "OPTIMAL"

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.flugpl.dual]
allocations = 39760
bytes = 1610016
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010112
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001628
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1499240
compile_seconds = 0.0
samples = 3
seconds = 0.000802501

[datasets.flugpl.primal]
allocations = 40109
bytes = 1654640
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010426
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001974
status = "OPTIMAL"

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.kb2.dual]
allocations = 293411
bytes = 13612784
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022283107
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878336
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008199
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292209
bytes = 13158224
compile_seconds = 0.0
samples = 3
seconds = 0.021361407

[datasets.kb2.primal]
allocations = 293578
bytes = 13627312
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021568907
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000634601
status = "OPTIMAL"

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.6e-5

[datasets.sc50a.dual]
allocations = 103085
bytes = 4485312
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002699001
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005732
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 102013
bytes = 4139728
compile_seconds = 0.0
samples = 3
seconds = 0.0019645

[datasets.sc50a.primal]
allocations = 103030
bytes = 4438336
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.003098901
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005315
status = "OPTIMAL"

[probes.half]
allocations = 23964
bytes = 983560
compile_seconds = 0.0
samples = 3
seconds = 0.0007211

[probes.zero]
allocations = 4982
bytes = 278296
compile_seconds = 0.0
samples = 3
seconds = 0.00016
