julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.adlittle.dual]
allocations = 82392
bytes = 4047768
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035161
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010189
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80377
bytes = 3258296
compile_seconds = 0.0
samples = 3
seconds = 0.0022165

[datasets.adlittle.primal]
allocations = 83190
bytes = 4324232
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004113
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011326
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641448
compile_seconds = 0.0
samples = 3
seconds = 0.0004235

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.03e-5

[datasets.adlittle.sparse]
allocations = 1572
bytes = 128456
compile_seconds = 0.0
samples = 3
seconds = 0.0001131

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.afiro.dual]
allocations = 16225
bytes = 835272
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000798
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002156
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15410
bytes = 699208
compile_seconds = 0.0
samples = 3
seconds = 0.0006837

[datasets.afiro.primal]
allocations = 16131
bytes = 813288
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009742
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002411
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92680
compile_seconds = 0.0
samples = 3
seconds = 9.56e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 41072
compile_seconds = 0.0
samples = 3
seconds = 8.74e-5

[datasets.afiro.sparse]
allocations = 3736
bytes = 173728
compile_seconds = 0.0
samples = 3
seconds = 0.000156

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.flugpl.dual]
allocations = 26431
bytes = 1100528
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008074
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001562
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25760
bytes = 990968
compile_seconds = 0.0
samples = 3
seconds = 0.0006863

[datasets.flugpl.primal]
allocations = 26780
bytes = 1145120
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009449
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002063
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122752
compile_seconds = 0.0
samples = 3
seconds = 0.0001157

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.98e-5

[datasets.flugpl.sparse]
allocations = 3956
bytes = 150776
compile_seconds = 0.0
samples = 3
seconds = 0.0001275

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 228219
bytes = 11015736
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022196801
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008848
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 227017
bytes = 10562888
compile_seconds = 0.0
samples = 3
seconds = 0.022069501

[datasets.kb2.primal]
allocations = 228386
bytes = 11029704
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022527102
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006458
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454400
compile_seconds = 0.0
samples = 3
seconds = 0.0003219

[datasets.kb2.singleton]
allocations = 1915
bytes = 106008
compile_seconds = 0.0
samples = 3
seconds = 9.46e-5

[datasets.kb2.sparse]
allocations = 1999
bytes = 128504
compile_seconds = 0.0
samples = 3
seconds = 0.0001093

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.8e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6

[datasets.sc50a.dual]
allocations = 66013
bytes = 3108448
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021997
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306480
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005848
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 64941
bytes = 2762672
compile_seconds = 0.0
samples = 3
seconds = 0.0017208

[datasets.sc50a.primal]
allocations = 65958
bytes = 3061568
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021566
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005296
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221888
compile_seconds = 0.0
samples = 3
seconds = 0.000161

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.46e-5

[datasets.sc50a.sparse]
allocations = 5489
bytes = 263008
compile_seconds = 0.0
samples = 3
seconds = 0.0001931

[probes.fraction_negative]
allocations = 32823
bytes = 1312728
compile_seconds = 0.0
samples = 3
seconds = 0.0007298

[probes.fraction_positive]
allocations = 32823
bytes = 1312808
compile_seconds = 0.0
samples = 3
seconds = 0.0007456

[probes.negative]
allocations = 33719
bytes = 1342584
compile_seconds = 0.0
samples = 3
seconds = 0.0007566

[probes.positive]
allocations = 33719
bytes = 1340488
compile_seconds = 0.0
samples = 3
seconds = 0.0007756

[probes.unequal]
allocations = 33335
bytes = 1340152
compile_seconds = 0.0
samples = 3
seconds = 0.0007346

[probes.zero_shift]
allocations = 23479
bytes = 969256
compile_seconds = 0.0
samples = 3
seconds = 0.0005534
