blas_threads = 1
julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "before"
presolve = false
scaling = "off"
threads = 1
value_type = "Float32"

[[kernels]]
allocations = 5
basis_update = "pfi"
bytes = 17048
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 3.7e-5
[[kernels]]
allocations = 5
basis_update = "forrest_tomlin"
bytes = 17048
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.0001002
[[kernels]]
allocations = 5
basis_update = "suhl_suhl"
bytes = 17048
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 3.9e-5
[[kernels]]
allocations = 5
basis_update = "bartels_golub"
bytes = 17048
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.0001103
[[kernels]]
allocations = 6
basis_update = "pfi"
bytes = 1052832
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0013397
[[kernels]]
allocations = 6
basis_update = "forrest_tomlin"
bytes = 1052832
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0013317
[[kernels]]
allocations = 6
basis_update = "suhl_suhl"
bytes = 1052832
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0014215
[[kernels]]
allocations = 6
basis_update = "bartels_golub"
bytes = 1052832
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 0.0013309
[[kernels]]
allocations = 6
basis_update = "pfi"
bytes = 4202656
compile_seconds = 0.0
dimension = 1024
samples = 3
seconds = 0.0085926
[[kernels]]
allocations = 6
basis_update = "forrest_tomlin"
bytes = 4202656
compile_seconds = 0.0
dimension = 1024
samples = 3
seconds = 0.0098141
[[kernels]]
allocations = 6
basis_update = "suhl_suhl"
bytes = 4202656
compile_seconds = 0.0
dimension = 1024
samples = 3
seconds = 0.0091608
[[kernels]]
allocations = 6
basis_update = "bartels_golub"
bytes = 4202656
compile_seconds = 0.0
dimension = 1024
samples = 3
seconds = 0.0091708

[[rows]]
algorithm = "dual"
allocations = 1621
basis_update = "pfi"
bytes = 136784
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0002927
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1680
basis_update = "pfi"
bytes = 88048
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002098
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 378
basis_update = "pfi"
bytes = 82744
compile_seconds = 0.0
dataset = "afiro"
iterations = 12
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.0002248
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 1117
basis_update = "pfi"
bytes = 75472
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002126
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1877
basis_update = "forrest_tomlin"
bytes = 147936
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0003646
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 533
basis_update = "forrest_tomlin"
bytes = 44624
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0001911
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 628
basis_update = "forrest_tomlin"
bytes = 93640
compile_seconds = 0.0
dataset = "afiro"
iterations = 12
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.0002552
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 1462
basis_update = "forrest_tomlin"
bytes = 89680
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002579
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1879
basis_update = "suhl_suhl"
bytes = 148192
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0003699
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1695
basis_update = "suhl_suhl"
bytes = 90560
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002893
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 624
basis_update = "suhl_suhl"
bytes = 93496
compile_seconds = 0.0
dataset = "afiro"
iterations = 12
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.0002537
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 1460
basis_update = "suhl_suhl"
bytes = 90640
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002566
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1993
basis_update = "bartels_golub"
bytes = 152432
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0003954
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1813
basis_update = "bartels_golub"
bytes = 95568
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002954
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 716
basis_update = "bartels_golub"
bytes = 97320
compile_seconds = 0.0
dataset = "afiro"
iterations = 12
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.0002831
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 1520
basis_update = "bartels_golub"
bytes = 93160
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002749
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 371
basis_update = "pfi"
bytes = 236944
compile_seconds = 0.0
dataset = "adlittle"
iterations = 39
refactorization_interval = 1
refactorizations = 12
samples = 3
seconds = 0.000651
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 297
basis_update = "pfi"
bytes = 78456
compile_seconds = 0.0
dataset = "adlittle"
iterations = 20
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003061
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 301
basis_update = "pfi"
bytes = 146712
compile_seconds = 0.0
dataset = "adlittle"
iterations = 3
refactorization_interval = 1
refactorizations = 4
samples = 3
seconds = 0.0003055
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 365
basis_update = "pfi"
bytes = 128440
compile_seconds = 0.0
dataset = "adlittle"
iterations = 20
refactorization_interval = 20
refactorizations = 2
samples = 3
seconds = 0.0004141
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 886
basis_update = "forrest_tomlin"
bytes = 257984
compile_seconds = 0.0
dataset = "adlittle"
iterations = 38
refactorization_interval = 1
refactorizations = 12
samples = 3
seconds = 0.000673101
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 791
basis_update = "forrest_tomlin"
bytes = 99976
compile_seconds = 0.0
dataset = "adlittle"
iterations = 20
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003878
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 767
basis_update = "forrest_tomlin"
bytes = 166072
compile_seconds = 0.0
dataset = "adlittle"
iterations = 3
refactorization_interval = 1
refactorizations = 4
samples = 3
seconds = 0.0002894
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 905
basis_update = "forrest_tomlin"
bytes = 155176
compile_seconds = 0.0
dataset = "adlittle"
iterations = 20
refactorization_interval = 20
refactorizations = 2
samples = 3
seconds = 0.000478
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 879
basis_update = "suhl_suhl"
bytes = 252352
compile_seconds = 0.0
dataset = "adlittle"
iterations = 39
refactorization_interval = 1
refactorizations = 12
samples = 3
seconds = 0.000726
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 783
basis_update = "suhl_suhl"
bytes = 100184
compile_seconds = 0.0
dataset = "adlittle"
iterations = 20
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003912
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 767
basis_update = "suhl_suhl"
bytes = 166136
compile_seconds = 0.0
dataset = "adlittle"
iterations = 3
refactorization_interval = 1
refactorizations = 4
samples = 3
seconds = 0.0003291
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 887
basis_update = "suhl_suhl"
bytes = 154040
compile_seconds = 0.0
dataset = "adlittle"
iterations = 20
refactorization_interval = 20
refactorizations = 2
samples = 3
seconds = 0.000463
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1089
basis_update = "bartels_golub"
bytes = 234160
compile_seconds = 0.0
dataset = "adlittle"
iterations = 30
refactorization_interval = 1
refactorizations = 10
samples = 3
seconds = 0.0005906
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 1170
basis_update = "bartels_golub"
bytes = 157400
compile_seconds = 0.0
dataset = "adlittle"
iterations = 39
refactorization_interval = 20
refactorizations = 3
samples = 3
seconds = 0.0005967
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 942
basis_update = "bartels_golub"
bytes = 173512
compile_seconds = 0.0
dataset = "adlittle"
iterations = 3
refactorization_interval = 1
refactorizations = 4
samples = 3
seconds = 0.0003118
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "primal"
allocations = 965
basis_update = "bartels_golub"
bytes = 136176
compile_seconds = 0.0
dataset = "adlittle"
iterations = 10
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003641
status = "NUMERICAL_ERROR"
[[rows]]
algorithm = "dual"
allocations = 322
basis_update = "pfi"
bytes = 272176
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.0006518
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 268
basis_update = "pfi"
bytes = 101568
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 3
samples = 3
seconds = 0.0005019
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 782
basis_update = "pfi"
bytes = 1215960
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 65
samples = 3
seconds = 0.001713
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 435
basis_update = "pfi"
bytes = 176832
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 4
samples = 3
seconds = 0.0007686
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 624
basis_update = "forrest_tomlin"
bytes = 285888
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.0007366
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 572
basis_update = "forrest_tomlin"
bytes = 115584
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 3
samples = 3
seconds = 0.000545201
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1372
basis_update = "forrest_tomlin"
bytes = 1241112
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 65
samples = 3
seconds = 0.0018016
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1003
basis_update = "forrest_tomlin"
bytes = 201664
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 4
samples = 3
seconds = 0.0008975
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 682
basis_update = "suhl_suhl"
bytes = 289936
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.0007561
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 620
basis_update = "suhl_suhl"
bytes = 119072
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 3
samples = 3
seconds = 0.0005497
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1436
basis_update = "suhl_suhl"
bytes = 1244760
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 65
samples = 3
seconds = 0.0019815
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1051
basis_update = "suhl_suhl"
bytes = 205152
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 4
samples = 3
seconds = 0.0007833
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 756
basis_update = "bartels_golub"
bytes = 291136
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 13
samples = 3
seconds = 0.000869
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 704
basis_update = "bartels_golub"
bytes = 121088
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 3
samples = 3
seconds = 0.0006113
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1571
basis_update = "bartels_golub"
bytes = 1249544
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 1
refactorizations = 65
samples = 3
seconds = 0.0019953
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1202
basis_update = "bartels_golub"
bytes = 209840
compile_seconds = 0.0
dataset = "diagonal64"
iterations = 64
objective = 64.0
refactorization_interval = 20
refactorizations = 4
samples = 3
seconds = 0.0008636
status = "OPTIMAL"
