julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.3e-6

[datasets.adlittle.dual]
allocations = 122938
bytes = 5681432
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039847
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461528
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009428
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120923
bytes = 4892120
compile_seconds = 0.0
samples = 3
seconds = 0.0024784

[datasets.adlittle.primal]
allocations = 123736
bytes = 5958616
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038961
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607584
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001122501
status = "OPTIMAL"

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.afiro.dual]
allocations = 28527
bytes = 1318536
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0010181
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001734
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27712
bytes = 1183128
compile_seconds = 0.0
samples = 3
seconds = 0.000689701

[datasets.afiro.primal]
allocations = 28433
bytes = 1296696
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008678
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001817
status = "OPTIMAL"

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.flugpl.dual]
allocations = 39978
bytes = 1620424
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001067801
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001519
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39307
bytes = 1510176
compile_seconds = 0.0
samples = 3
seconds = 0.0008127

[datasets.flugpl.primal]
allocations = 40327
bytes = 1665000
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010318
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001735
status = "OPTIMAL"

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 8.7e-6

[datasets.kb2.dual]
allocations = 293716
bytes = 13640976
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021469602
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878560
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007967
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292514
bytes = 13189024
compile_seconds = 0.0
samples = 3
seconds = 0.020197102

[datasets.kb2.primal]
allocations = 293883
bytes = 13655616
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021725803
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005937
status = "OPTIMAL"

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.sc50a.dual]
allocations = 107388
bytes = 4664448
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025036
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005542
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106316
bytes = 4318096
compile_seconds = 0.0
samples = 3
seconds = 0.0020355

[datasets.sc50a.primal]
allocations = 107333
bytes = 4617408
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002394101
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004971
status = "OPTIMAL"

[probes.shifted]
allocations = 3692
bytes = 690608
compile_seconds = 0.0
samples = 3
seconds = 0.0002233

[probes.unchanged]
allocations = 15
bytes = 4080
compile_seconds = 0.0
samples = 3
seconds = 3.21e-5
