julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 19
bytes = 5008
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.adlittle.dual]
allocations = 122946
bytes = 5688168
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003811699
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000941799
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120931
bytes = 4898376
compile_seconds = 0.0
samples = 3
seconds = 0.002392499

[datasets.adlittle.primal]
allocations = 123744
bytes = 5964680
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004077999
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607312
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010831
status = "OPTIMAL"

[datasets.afiro.basic]
allocations = 19
bytes = 2448
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.dual]
allocations = 28539
bytes = 1322552
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008727
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002082
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27724
bytes = 1186456
compile_seconds = 0.0
samples = 3
seconds = 0.0006683

[datasets.afiro.primal]
allocations = 28445
bytes = 1300744
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.00085
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002059
status = "OPTIMAL"

[datasets.flugpl.basic]
allocations = 19
bytes = 1792
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.dual]
allocations = 39990
bytes = 1623528
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009161
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001504
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39319
bytes = 1514144
compile_seconds = 0.0
samples = 3
seconds = 0.0007361

[datasets.flugpl.primal]
allocations = 40339
bytes = 1668248
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010006
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000187701
status = "OPTIMAL"

[datasets.kb2.basic]
allocations = 19
bytes = 3216
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.kb2.dual]
allocations = 293728
bytes = 13649680
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021099202
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878432
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000798399
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292526
bytes = 13195552
compile_seconds = 0.0
samples = 3
seconds = 0.020365494

[datasets.kb2.primal]
allocations = 293895
bytes = 13663840
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021320103
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006152
status = "OPTIMAL"

[datasets.sc50a.basic]
allocations = 64
bytes = 19616
compile_seconds = 0.0
samples = 3
seconds = 1.75e-5

[datasets.sc50a.dual]
allocations = 107400
bytes = 4671744
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025739
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.00058
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106328
bytes = 4325296
compile_seconds = 0.0
samples = 3
seconds = 0.0020556

[datasets.sc50a.primal]
allocations = 107345
bytes = 4624144
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024022
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000488
status = "OPTIMAL"

[probes.shifted]
allocations = 3692
bytes = 690448
compile_seconds = 0.0
samples = 3
seconds = 0.0002148

[probes.unchanged]
allocations = 21
bytes = 8320
compile_seconds = 0.0
samples = 3
seconds = 3.95e-5
