julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[backends.BigFloat]
allocations = 22921
bytes = 2208552
compile_seconds = 0.0
samples = 3
seconds = 0.0003438

[backends.Float16]
allocations = 9
bytes = 2664
compile_seconds = 0.0
samples = 3
seconds = 3.27e-5

[backends.Float32]
allocations = 9
bytes = 67400
compile_seconds = 0.0
samples = 3
seconds = 7.72e-5

[backends.Float64]
allocations = 91
bytes = 553568
compile_seconds = 0.0
samples = 3
seconds = 0.0001928

[backends."Rational{BigInt}"]
allocations = 167726
bytes = 6886200
compile_seconds = 0.0
samples = 3
seconds = 0.002185699

[datasets.adlittle.dual]
allocations = 123696
bytes = 5895080
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003576301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1369
bytes = 483608
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008977
status = "OPTIMAL"

[datasets.adlittle.initialize]
allocations = 172
bytes = 66880
compile_seconds = 0.0
samples = 3
seconds = 5.73e-5

[datasets.adlittle.primal]
allocations = 124564
bytes = 6191896
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003986202
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 2012
bytes = 650416
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.000990201
status = "OPTIMAL"

[datasets.adlittle.refactorize]
allocations = 87
bytes = 34400
compile_seconds = 0.0
samples = 3
seconds = 4.34e-5

[datasets.afiro.dual]
allocations = 28802
bytes = 1362888
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007687
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 598
bytes = 98768
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002984
status = "OPTIMAL"

[datasets.afiro.initialize]
allocations = 170
bytes = 34064
compile_seconds = 0.0
samples = 3
seconds = 6.59e-5

[datasets.afiro.primal]
allocations = 28704
bytes = 1342056
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000775
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 872
bytes = 139536
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001898
status = "OPTIMAL"

[datasets.afiro.refactorize]
allocations = 87
bytes = 19264
compile_seconds = 0.0
samples = 3
seconds = 4.43e-5

[datasets.flugpl.dual]
allocations = 40085
bytes = 1633928
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000855801
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 419
bytes = 48768
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001223
status = "OPTIMAL"

[datasets.flugpl.initialize]
allocations = 170
bytes = 24704
compile_seconds = 0.0
samples = 3
seconds = 5.26e-5

[datasets.flugpl.primal]
allocations = 40504
bytes = 1686328
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008461
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 852
bytes = 106256
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001564
status = "OPTIMAL"

[datasets.flugpl.refactorize]
allocations = 87
bytes = 14032
compile_seconds = 0.0
samples = 3
seconds = 3.04e-5

[datasets.kb2.dual]
allocations = 294430
bytes = 13823040
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022505108
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1551
bytes = 890016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008107
status = "OPTIMAL"

[datasets.kb2.initialize]
allocations = 170
bytes = 48576
compile_seconds = 0.0
samples = 3
seconds = 5.64e-5

[datasets.kb2.primal]
allocations = 294593
bytes = 13835552
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021323607
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1093
bytes = 271856
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005938
status = "OPTIMAL"

[datasets.kb2.refactorize]
allocations = 87
bytes = 27760
compile_seconds = 0.0
samples = 3
seconds = 4.21e-5

[datasets.sc50a.dual]
allocations = 107657
bytes = 4724224
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024478
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 1004
bytes = 320800
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000580301
status = "OPTIMAL"

[datasets.sc50a.initialize]
allocations = 170
bytes = 55120
compile_seconds = 0.0
samples = 3
seconds = 4.59e-5

[datasets.sc50a.primal]
allocations = 107598
bytes = 4676176
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002333401
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 1003
bytes = 244936
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005083
status = "OPTIMAL"

[datasets.sc50a.refactorize]
allocations = 87
bytes = 31376
compile_seconds = 0.0
samples = 3
seconds = 4.13e-5
