julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[backends.BigFloat]
allocations = 22948
bytes = 2218176
compile_seconds = 0.0
samples = 3
seconds = 0.0003658

[backends.Float16]
allocations = 12
bytes = 4800
compile_seconds = 0.0
samples = 3
seconds = 1.2e-5

[backends.Float32]
allocations = 12
bytes = 133024
compile_seconds = 0.0
samples = 3
seconds = 7.39e-5

[backends.Float64]
allocations = 100
bytes = 582520
compile_seconds = 0.0
samples = 3
seconds = 0.0001981

[backends."Rational{BigInt}"]
allocations = 167814
bytes = 6903616
compile_seconds = 0.0
samples = 3
seconds = 0.0018454

[datasets.adlittle.dual]
allocations = 123744
bytes = 5921224
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003596103
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1399
bytes = 498152
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000894701
status = "OPTIMAL"

[datasets.adlittle.initialize]
allocations = 178
bytes = 68464
compile_seconds = 0.0
samples = 3
seconds = 6.93e-5

[datasets.adlittle.primal]
allocations = 124636
bytes = 6228056
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003873403
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 2054
bytes = 669616
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001050301
status = "OPTIMAL"

[datasets.adlittle.refactorize]
allocations = 93
bytes = 35984
compile_seconds = 0.0
samples = 3
seconds = 5.62e-5

[datasets.afiro.dual]
allocations = 28826
bytes = 1366632
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000899001
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 610
bytes = 100848
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002396
status = "OPTIMAL"

[datasets.afiro.initialize]
allocations = 176
bytes = 34896
compile_seconds = 0.0
samples = 3
seconds = 6.03e-5

[datasets.afiro.primal]
allocations = 28722
bytes = 1345032
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008752
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 890
bytes = 141984
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001969
status = "OPTIMAL"

[datasets.afiro.refactorize]
allocations = 93
bytes = 20096
compile_seconds = 0.0
samples = 3
seconds = 4.59e-5

[datasets.flugpl.dual]
allocations = 40103
bytes = 1635656
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000932801
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 425
bytes = 49392
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000150701
status = "OPTIMAL"

[datasets.flugpl.initialize]
allocations = 176
bytes = 25328
compile_seconds = 0.0
samples = 3
seconds = 5.44e-5

[datasets.flugpl.primal]
allocations = 40534
bytes = 1689096
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000906401
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 870
bytes = 108128
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001458
status = "OPTIMAL"

[datasets.flugpl.refactorize]
allocations = 93
bytes = 14656
compile_seconds = 0.0
samples = 3
seconds = 4.21e-5

[datasets.kb2.dual]
allocations = 294466
bytes = 13841232
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021405122
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1617
bytes = 936304
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007708
status = "OPTIMAL"

[datasets.kb2.initialize]
allocations = 176
bytes = 49808
compile_seconds = 0.0
samples = 3
seconds = 5.94e-5

[datasets.kb2.primal]
allocations = 294629
bytes = 13853344
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021210822
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1111
bytes = 280016
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005635
status = "OPTIMAL"

[datasets.kb2.refactorize]
allocations = 93
bytes = 28992
compile_seconds = 0.0
samples = 3
seconds = 5.77e-5

[datasets.sc50a.dual]
allocations = 107687
bytes = 4733360
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002440202
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 1028
bytes = 328992
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005534
status = "OPTIMAL"

[datasets.sc50a.initialize]
allocations = 176
bytes = 56576
compile_seconds = 0.0
samples = 3
seconds = 6.31e-5

[datasets.sc50a.primal]
allocations = 107622
bytes = 4682928
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002436802
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 1021
bytes = 250936
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000446301
status = "OPTIMAL"

[datasets.sc50a.refactorize]
allocations = 93
bytes = 32832
compile_seconds = 0.0
samples = 3
seconds = 4.72e-5
