julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.optimize]
allocations = 138062
bytes = 6776000
compile_seconds = 0.0
iterations = 96
objective = 225494.96316238027
samples = 3
seconds = 0.004442199
status = "OPTIMAL"

[datasets.adlittle.translation]
allocations = 3533
bytes = 238728
compile_seconds = 0.0
samples = 3
seconds = 0.000245

[datasets.afiro.optimize]
allocations = 35952
bytes = 1678248
compile_seconds = 0.0
iterations = 10
objective = -464.75314285714273
samples = 3
seconds = 0.0011181
status = "OPTIMAL"

[datasets.afiro.translation]
allocations = 1373
bytes = 75608
compile_seconds = 0.0
samples = 3
seconds = 0.0001256

[datasets.flugpl.optimize]
allocations = 41690
bytes = 1719912
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001084
status = "OPTIMAL"

[datasets.flugpl.translation]
allocations = 1036
bytes = 58360
compile_seconds = 0.0
samples = 3
seconds = 0.0001493

[datasets.greenbea.translation]
allocations = 237372
bytes = 16594000
compile_seconds = 0.0
samples = 3
seconds = 0.0071514

[datasets.kb2.optimize]
allocations = 292288
bytes = 13368024
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062056
samples = 3
seconds = 0.018083799
status = "OPTIMAL"

[datasets.kb2.translation]
allocations = 2494
bytes = 161952
compile_seconds = 0.0
samples = 3
seconds = 0.0002155

[datasets.sc50a.optimize]
allocations = 152637
bytes = 6421224
compile_seconds = 0.0
iterations = 33
objective = -64.57507705856449
samples = 3
seconds = 0.003298
status = "OPTIMAL"

[datasets.sc50a.translation]
allocations = 2236
bytes = 129416
compile_seconds = 0.0
samples = 3
seconds = 0.0001728
