julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.optimize]
allocations = 137708
bytes = 6725232
compile_seconds = 0.0
iterations = 96
objective = 225494.96316238027
samples = 3
seconds = 0.004522
status = "OPTIMAL"

[datasets.adlittle.translation]
allocations = 3179
bytes = 187224
compile_seconds = 0.0
samples = 3
seconds = 0.000255

[datasets.afiro.optimize]
allocations = 35830
bytes = 1665560
compile_seconds = 0.0
iterations = 10
objective = -464.75314285714273
samples = 3
seconds = 0.0012695
status = "OPTIMAL"

[datasets.afiro.translation]
allocations = 1251
bytes = 62616
compile_seconds = 0.0
samples = 3
seconds = 0.000131

[datasets.flugpl.optimize]
allocations = 41620
bytes = 1712952
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0013034
status = "OPTIMAL"

[datasets.flugpl.translation]
allocations = 966
bytes = 50472
compile_seconds = 0.0
samples = 3
seconds = 0.0001818

[datasets.greenbea.translation]
allocations = 192150
bytes = 12318008
compile_seconds = 0.0
samples = 3
seconds = 0.0058483

[datasets.kb2.optimize]
allocations = 292026
bytes = 13338216
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062056
samples = 3
seconds = 0.018325199
status = "OPTIMAL"

[datasets.kb2.translation]
allocations = 2232
bytes = 132400
compile_seconds = 0.0
samples = 3
seconds = 0.0002159

[datasets.sc50a.optimize]
allocations = 152426
bytes = 6400056
compile_seconds = 0.0
iterations = 33
objective = -64.57507705856449
samples = 3
seconds = 0.0036208
status = "OPTIMAL"

[datasets.sc50a.translation]
allocations = 2025
bytes = 106584
compile_seconds = 0.0
samples = 3
seconds = 0.0001791
