julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.build]
allocations = 148
bytes = 114056
compile_seconds = 0.0
samples = 3
seconds = 9.53e-5

[datasets.adlittle.parse]
allocations = 4356
bytes = 291128
compile_seconds = 0.0
samples = 3
seconds = 0.0005345

[datasets.adlittle.read_mps]
allocations = 4504
bytes = 405184
compile_seconds = 0.0
samples = 3
seconds = 0.0006087

[datasets.adlittle_fixed.build]
allocations = 148
bytes = 114056
compile_seconds = 0.0
samples = 3
seconds = 0.0001022

[datasets.adlittle_fixed.parse]
allocations = 4356
bytes = 291128
compile_seconds = 0.0
samples = 3
seconds = 0.000507

[datasets.adlittle_fixed.read_mps]
allocations = 4504
bytes = 405184
compile_seconds = 0.0
samples = 3
seconds = 0.0005783

[datasets.afiro.build]
allocations = 126
bytes = 34592
compile_seconds = 0.0
samples = 3
seconds = 3.61e-5

[datasets.afiro.parse]
allocations = 1053
bytes = 68360
compile_seconds = 0.0
samples = 3
seconds = 0.0002036

[datasets.afiro.read_mps]
allocations = 1179
bytes = 102952
compile_seconds = 0.0
samples = 3
seconds = 0.0002438

[datasets.basic_free.build]
allocations = 110
bytes = 5776
compile_seconds = 0.0
samples = 3
seconds = 1.4e-5

[datasets.basic_free.parse]
allocations = 148
bytes = 8672
compile_seconds = 0.0
samples = 3
seconds = 9.23e-5

[datasets.basic_free.read_mps]
allocations = 258
bytes = 14448
compile_seconds = 0.0
samples = 3
seconds = 8.84e-5

[datasets.flugpl.build]
allocations = 128
bytes = 27376
compile_seconds = 0.0
samples = 3
seconds = 4.67e-5

[datasets.flugpl.parse]
allocations = 1118
bytes = 74280
compile_seconds = 0.0
samples = 3
seconds = 0.0002182

[datasets.flugpl.read_mps]
allocations = 1246
bytes = 101656
compile_seconds = 0.0
samples = 3
seconds = 0.0002713

[datasets.greenbea.build]
allocations = 251
bytes = 8292520
compile_seconds = 0.0
samples = 3
seconds = 0.0026933

[datasets.greenbea.parse]
allocations = 259237
bytes = 19606312
compile_seconds = 0.0
samples = 3
seconds = 0.0239841

[datasets.greenbea.read_mps]
allocations = 259488
bytes = 27898832
compile_seconds = 0.0
samples = 3
seconds = 0.026084101

[datasets.kb2.build]
allocations = 146
bytes = 92472
compile_seconds = 0.0
samples = 3
seconds = 8.96e-5

[datasets.kb2.parse]
allocations = 2751
bytes = 191064
compile_seconds = 0.0
samples = 3
seconds = 0.0003374

[datasets.kb2.read_mps]
allocations = 2897
bytes = 283536
compile_seconds = 0.0
samples = 3
seconds = 0.0003918

[datasets.sc50a.build]
allocations = 127
bytes = 47376
compile_seconds = 0.0
samples = 3
seconds = 4.36e-5

[datasets.sc50a.parse]
allocations = 1661
bytes = 106776
compile_seconds = 0.0
samples = 3
seconds = 0.0002764

[datasets.sc50a.read_mps]
allocations = 1788
bytes = 154152
compile_seconds = 0.0
samples = 3
seconds = 0.0003039
