julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.build]
allocations = 2473
bytes = 246664
compile_seconds = 0.0
samples = 3
seconds = 0.0003264

[datasets.adlittle.parse]
allocations = 8421
bytes = 433864
compile_seconds = 0.0
samples = 3
seconds = 0.0006318

[datasets.adlittle.read_mps]
allocations = 10894
bytes = 680528
compile_seconds = 0.0
samples = 3
seconds = 0.0008394

[datasets.adlittle_fixed.build]
allocations = 2473
bytes = 246664
compile_seconds = 0.0
samples = 3
seconds = 0.00031

[datasets.adlittle_fixed.parse]
allocations = 8421
bytes = 433864
compile_seconds = 0.0
samples = 3
seconds = 0.0005237

[datasets.adlittle_fixed.read_mps]
allocations = 10894
bytes = 680528
compile_seconds = 0.0
samples = 3
seconds = 0.0008194

[datasets.afiro.build]
allocations = 566
bytes = 59856
compile_seconds = 0.0
samples = 3
seconds = 0.0001119

[datasets.afiro.parse]
allocations = 2091
bytes = 106472
compile_seconds = 0.0
samples = 3
seconds = 0.0002335

[datasets.afiro.read_mps]
allocations = 2657
bytes = 166328
compile_seconds = 0.0
samples = 3
seconds = 0.0002979

[datasets.basic_free.build]
allocations = 140
bytes = 7472
compile_seconds = 0.0
samples = 3
seconds = 3.36e-5

[datasets.basic_free.parse]
allocations = 223
bytes = 12576
compile_seconds = 0.0
samples = 3
seconds = 6.49e-5

[datasets.basic_free.read_mps]
allocations = 363
bytes = 20048
compile_seconds = 0.0
samples = 3
seconds = 0.000102

[datasets.flugpl.build]
allocations = 448
bytes = 45520
compile_seconds = 0.0
samples = 3
seconds = 9.06e-5

[datasets.flugpl.parse]
allocations = 2384
bytes = 121704
compile_seconds = 0.0
samples = 3
seconds = 0.0002547

[datasets.flugpl.read_mps]
allocations = 2832
bytes = 167224
compile_seconds = 0.0
samples = 3
seconds = 0.000294

[datasets.greenbea.build]
allocations = 157746
bytes = 17354280
compile_seconds = 0.0
samples = 3
seconds = 0.017252991

[datasets.greenbea.parse]
allocations = 504427
bytes = 27978280
compile_seconds = 0.0
samples = 3
seconds = 0.023971998

[datasets.greenbea.read_mps]
allocations = 662173
bytes = 45332560
compile_seconds = 0.0
samples = 3
seconds = 0.0427591

[datasets.kb2.build]
allocations = 1601
bytes = 176200
compile_seconds = 0.0
samples = 3
seconds = 0.000226

[datasets.kb2.parse]
allocations = 5457
bytes = 287896
compile_seconds = 0.0
samples = 3
seconds = 0.0003917

[datasets.kb2.read_mps]
allocations = 7058
bytes = 464096
compile_seconds = 0.0
samples = 3
seconds = 0.0005971

[datasets.sc50a.build]
allocations = 782
bytes = 85088
compile_seconds = 0.0
samples = 3
seconds = 0.000122

[datasets.sc50a.parse]
allocations = 3425
bytes = 173720
compile_seconds = 0.0
samples = 3
seconds = 0.00028

[datasets.sc50a.read_mps]
allocations = 4207
bytes = 258808
compile_seconds = 0.0
samples = 3
seconds = 0.0003709
