julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.bartels_golub_dual]
allocations = 126211
bytes = 6030792
compile_seconds = 0.0
iterations = 101
objective = 225494.96316238036
samples = 3
seconds = 0.004566
status = "OPTIMAL"

[datasets.adlittle.bartels_golub_dual_no_presolve]
allocations = 3473
bytes = 691104
compile_seconds = 0.0
iterations = 96
objective = 225494.96316238033
samples = 3
seconds = 0.0014353
status = "OPTIMAL"

[datasets.adlittle.bartels_golub_primal]
allocations = 128064
bytes = 6360104
compile_seconds = 0.0
iterations = 121
objective = 225494.96316238036
samples = 3
seconds = 0.0050648
status = "OPTIMAL"

[datasets.adlittle.bartels_golub_primal_no_presolve]
allocations = 3907
bytes = 746048
compile_seconds = 0.0
iterations = 87
objective = 225494.9631623804
samples = 3
seconds = 0.001640299
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_dual]
allocations = 125910
bytes = 6003480
compile_seconds = 0.0
iterations = 101
objective = 225494.9631623804
samples = 3
seconds = 0.0043558
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_dual_no_presolve]
allocations = 2977
bytes = 563400
compile_seconds = 0.0
iterations = 90
objective = 225494.96316238045
samples = 3
seconds = 0.0012471
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_primal]
allocations = 127702
bytes = 6309592
compile_seconds = 0.0
iterations = 118
objective = 225494.96316238027
samples = 3
seconds = 0.0046335
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_primal_no_presolve]
allocations = 3804
bytes = 720672
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0014457
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_dual]
allocations = 126501
bytes = 6126992
compile_seconds = 0.0
iterations = 128
objective = 225494.9631623804
samples = 3
seconds = 0.004483
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_dual_no_presolve]
allocations = 2952
bytes = 572248
compile_seconds = 0.0
iterations = 89
objective = 225494.9631623804
samples = 3
seconds = 0.001204
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_primal]
allocations = 127697
bytes = 6322200
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0044498
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_primal_no_presolve]
allocations = 3802
bytes = 731968
compile_seconds = 0.0
iterations = 87
objective = 225494.9631623804
samples = 3
seconds = 0.0013892
status = "OPTIMAL"

[datasets.afiro.bartels_golub_dual]
allocations = 29352
bytes = 1381080
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009608
status = "OPTIMAL"

[datasets.afiro.bartels_golub_dual_no_presolve]
allocations = 1046
bytes = 114256
compile_seconds = 0.0
iterations = 20
objective = -464.75314285714285
samples = 3
seconds = 0.0003659
status = "OPTIMAL"

[datasets.afiro.bartels_golub_primal]
allocations = 29051
bytes = 1350552
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008956
status = "OPTIMAL"

[datasets.afiro.bartels_golub_primal_no_presolve]
allocations = 1281
bytes = 150240
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002579
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_dual]
allocations = 29240
bytes = 1374520
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008757
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_dual_no_presolve]
allocations = 939
bytes = 108144
compile_seconds = 0.0
iterations = 20
objective = -464.75314285714285
samples = 3
seconds = 0.0002813
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_primal]
allocations = 28980
bytes = 1347000
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009088
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_primal_no_presolve]
allocations = 1194
bytes = 143184
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002536
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_dual]
allocations = 29240
bytes = 1375592
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009329
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_dual_no_presolve]
allocations = 931
bytes = 107920
compile_seconds = 0.0
iterations = 20
objective = -464.75314285714285
samples = 3
seconds = 0.0004841
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_primal]
allocations = 28978
bytes = 1347256
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000895
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_primal_no_presolve]
allocations = 1194
bytes = 144544
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002501
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_dual]
allocations = 40320
bytes = 1641720
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009903
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_dual_no_presolve]
allocations = 525
bytes = 52480
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001823
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_primal]
allocations = 40865
bytes = 1693832
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010523
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_primal_no_presolve]
allocations = 1111
bytes = 113248
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002354
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_dual]
allocations = 40277
bytes = 1639240
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009871
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_dual_no_presolve]
allocations = 498
bytes = 49744
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001682
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_primal]
allocations = 40809
bytes = 1691992
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011167
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_primal_no_presolve]
allocations = 1060
bytes = 108736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002184
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_dual]
allocations = 40269
bytes = 1638920
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010413
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_dual_no_presolve]
allocations = 496
bytes = 50560
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001801
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_primal]
allocations = 40805
bytes = 1691720
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001099
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_primal_no_presolve]
allocations = 1056
bytes = 109456
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002214
status = "OPTIMAL"

[datasets.kb2.bartels_golub_dual]
allocations = 295710
bytes = 13890992
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022835299
status = "OPTIMAL"

[datasets.kb2.bartels_golub_dual_no_presolve]
allocations = 3628
bytes = 983168
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0010888
status = "OPTIMAL"

[datasets.kb2.bartels_golub_primal]
allocations = 295902
bytes = 13913824
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0228217
status = "OPTIMAL"

[datasets.kb2.bartels_golub_primal_no_presolve]
allocations = 1833
bytes = 330000
compile_seconds = 0.0
iterations = 54
objective = -1749.900129906206
samples = 3
seconds = 0.0008787
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_dual]
allocations = 295552
bytes = 13876752
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0221514
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_dual_no_presolve]
allocations = 3570
bytes = 978256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009518
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_primal]
allocations = 295757
bytes = 13899824
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022951899
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_primal_no_presolve]
allocations = 1772
bytes = 308736
compile_seconds = 0.0
iterations = 54
objective = -1749.900129906206
samples = 3
seconds = 0.0008143
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_dual]
allocations = 295548
bytes = 13878096
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022965399
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_dual_no_presolve]
allocations = 3570
bytes = 982144
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0010367
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_primal]
allocations = 295757
bytes = 13900592
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023467699
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_primal_no_presolve]
allocations = 1772
bytes = 309808
compile_seconds = 0.0
iterations = 54
objective = -1749.900129906206
samples = 3
seconds = 0.0007902
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_dual]
allocations = 109002
bytes = 4779120
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002861
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_dual_no_presolve]
allocations = 2319
bytes = 377632
compile_seconds = 0.0
iterations = 52
objective = -64.5750770585645
samples = 3
seconds = 0.0008041
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_primal]
allocations = 108536
bytes = 4715184
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002831599
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_primal_no_presolve]
allocations = 1800
bytes = 273208
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0006741
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_dual]
allocations = 108785
bytes = 4760016
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0027273
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_dual_no_presolve]
allocations = 2137
bytes = 378432
compile_seconds = 0.0
iterations = 52
objective = -64.5750770585645
samples = 3
seconds = 0.0007566
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_primal]
allocations = 108394
bytes = 4702864
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0027513
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_primal_no_presolve]
allocations = 1694
bytes = 259720
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0006313
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_dual]
allocations = 108769
bytes = 4761328
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0028377
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_dual_no_presolve]
allocations = 2109
bytes = 368496
compile_seconds = 0.0
iterations = 52
objective = -64.5750770585645
samples = 3
seconds = 0.0006554
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_primal]
allocations = 108390
bytes = 4701536
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0028397
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_primal_no_presolve]
allocations = 1692
bytes = 259272
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0006104
status = "OPTIMAL"

[probes.BartelsGolubFactorization]
allocations = 136
bytes = 8640
compile_seconds = 0.0
samples = 3
seconds = 1.35e-5

[probes.ForrestTomlinFactorization]
allocations = 7
bytes = 2400
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[probes.SuhlSuhlFactorization]
allocations = 7
bytes = 2432
compile_seconds = 0.0
samples = 3
seconds = 8.3e-6

[probes.dense]
allocations = 6
bytes = 16656
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[probes.sparse]
allocations = 4
bytes = 192
compile_seconds = 0.0
samples = 3
seconds = 2.0e-6

[probes.zero]
allocations = 2
bytes = 64
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6
