julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.bartels_golub_dual]
allocations = 126589
bytes = 6075288
compile_seconds = 0.0
iterations = 101
objective = 225494.96316238036
samples = 3
seconds = 0.004305504
status = "OPTIMAL"

[datasets.adlittle.bartels_golub_dual_no_presolve]
allocations = 3771
bytes = 719200
compile_seconds = 0.0
iterations = 96
objective = 225494.96316238033
samples = 3
seconds = 0.001424902
status = "OPTIMAL"

[datasets.adlittle.bartels_golub_primal]
allocations = 128500
bytes = 6419992
compile_seconds = 0.0
iterations = 121
objective = 225494.96316238036
samples = 3
seconds = 0.004687704
status = "OPTIMAL"

[datasets.adlittle.bartels_golub_primal_no_presolve]
allocations = 4183
bytes = 782128
compile_seconds = 0.0
iterations = 87
objective = 225494.9631623804
samples = 3
seconds = 0.001536402
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_dual]
allocations = 126248
bytes = 6018808
compile_seconds = 0.0
iterations = 101
objective = 225494.9631623804
samples = 3
seconds = 0.004625605
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_dual_no_presolve]
allocations = 3223
bytes = 577944
compile_seconds = 0.0
iterations = 90
objective = 225494.96316238045
samples = 3
seconds = 0.001221601
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_primal]
allocations = 128104
bytes = 6350408
compile_seconds = 0.0
iterations = 118
objective = 225494.96316238027
samples = 3
seconds = 0.004428404
status = "OPTIMAL"

[datasets.adlittle.forrest_tomlin_primal_no_presolve]
allocations = 4064
bytes = 746224
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001635002
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_dual]
allocations = 126897
bytes = 6140976
compile_seconds = 0.0
iterations = 128
objective = 225494.9631623804
samples = 3
seconds = 0.004835704
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_dual_no_presolve]
allocations = 3214
bytes = 600968
compile_seconds = 0.0
iterations = 89
objective = 225494.9631623804
samples = 3
seconds = 0.001144801
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_primal]
allocations = 128079
bytes = 6351672
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004611304
status = "OPTIMAL"

[datasets.adlittle.suhl_suhl_primal_no_presolve]
allocations = 4050
bytes = 749248
compile_seconds = 0.0
iterations = 87
objective = 225494.9631623804
samples = 3
seconds = 0.001521601
status = "OPTIMAL"

[datasets.afiro.bartels_golub_dual]
allocations = 29362
bytes = 1379752
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009367
status = "OPTIMAL"

[datasets.afiro.bartels_golub_dual_no_presolve]
allocations = 1078
bytes = 117552
compile_seconds = 0.0
iterations = 20
objective = -464.75314285714285
samples = 3
seconds = 0.0002857
status = "OPTIMAL"

[datasets.afiro.bartels_golub_primal]
allocations = 29057
bytes = 1349560
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008559
status = "OPTIMAL"

[datasets.afiro.bartels_golub_primal_no_presolve]
allocations = 1291
bytes = 149856
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002529
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_dual]
allocations = 29250
bytes = 1372824
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009558
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_dual_no_presolve]
allocations = 969
bytes = 110912
compile_seconds = 0.0
iterations = 20
objective = -464.75314285714285
samples = 3
seconds = 0.0002299
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_primal]
allocations = 28986
bytes = 1344200
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000924101
status = "OPTIMAL"

[datasets.afiro.forrest_tomlin_primal_no_presolve]
allocations = 1200
bytes = 142416
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000231001
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_dual]
allocations = 29250
bytes = 1374216
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000860401
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_dual_no_presolve]
allocations = 959
bytes = 110224
compile_seconds = 0.0
iterations = 20
objective = -464.75314285714285
samples = 3
seconds = 0.0002358
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_primal]
allocations = 28984
bytes = 1344840
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000818501
status = "OPTIMAL"

[datasets.afiro.suhl_suhl_primal_no_presolve]
allocations = 1200
bytes = 143232
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002374
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_dual]
allocations = 40332
bytes = 1639512
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001114
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_dual_no_presolve]
allocations = 537
bytes = 53440
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001862
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_primal]
allocations = 40881
bytes = 1692168
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011067
status = "OPTIMAL"

[datasets.flugpl.bartels_golub_primal_no_presolve]
allocations = 1129
bytes = 114880
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002316
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_dual]
allocations = 40287
bytes = 1636648
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009866
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_dual_no_presolve]
allocations = 508
bytes = 49968
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001735
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_primal]
allocations = 40817
bytes = 1689048
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011237
status = "OPTIMAL"

[datasets.flugpl.forrest_tomlin_primal_no_presolve]
allocations = 1070
bytes = 108544
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002134
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_dual]
allocations = 40281
bytes = 1636888
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010679
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_dual_no_presolve]
allocations = 508
bytes = 52128
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001711
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_primal]
allocations = 40815
bytes = 1689080
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010308
status = "OPTIMAL"

[datasets.flugpl.suhl_suhl_primal_no_presolve]
allocations = 1072
bytes = 109968
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002189
status = "OPTIMAL"

[datasets.kb2.bartels_golub_dual]
allocations = 295868
bytes = 13919072
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021839901
status = "OPTIMAL"

[datasets.kb2.bartels_golub_dual_no_presolve]
allocations = 3838
bytes = 1034432
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.001064201
status = "OPTIMAL"

[datasets.kb2.bartels_golub_primal]
allocations = 296090
bytes = 13952752
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022691301
status = "OPTIMAL"

[datasets.kb2.bartels_golub_primal_no_presolve]
allocations = 2031
bytes = 381792
compile_seconds = 0.0
iterations = 54
objective = -1749.900129906206
samples = 3
seconds = 0.0008994
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_dual]
allocations = 295682
bytes = 13888208
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02215492
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_dual_no_presolve]
allocations = 3760
bytes = 1014912
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.001012301
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_primal]
allocations = 295921
bytes = 13918144
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.02230592
status = "OPTIMAL"

[datasets.kb2.forrest_tomlin_primal_no_presolve]
allocations = 1946
bytes = 347344
compile_seconds = 0.0
iterations = 54
objective = -1749.900129906206
samples = 3
seconds = 0.000760601
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_dual]
allocations = 295684
bytes = 13894576
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022698702
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_dual_no_presolve]
allocations = 3754
bytes = 1014880
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0010002
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_primal]
allocations = 295921
bytes = 13918640
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022667502
status = "OPTIMAL"

[datasets.kb2.suhl_suhl_primal_no_presolve]
allocations = 1942
bytes = 344800
compile_seconds = 0.0
iterations = 54
objective = -1749.900129906206
samples = 3
seconds = 0.0007522
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_dual]
allocations = 109060
bytes = 4779376
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002854001
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_dual_no_presolve]
allocations = 2421
bytes = 395792
compile_seconds = 0.0
iterations = 52
objective = -64.5750770585645
samples = 3
seconds = 0.000735
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_primal]
allocations = 108602
bytes = 4722368
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0027352
status = "OPTIMAL"

[datasets.sc50a.bartels_golub_primal_no_presolve]
allocations = 1886
bytes = 292040
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000675201
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_dual]
allocations = 108843
bytes = 4763072
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002787701
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_dual_no_presolve]
allocations = 2221
bytes = 380992
compile_seconds = 0.0
iterations = 52
objective = -64.5750770585645
samples = 3
seconds = 0.0007313
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_primal]
allocations = 108442
bytes = 4702544
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002657
status = "OPTIMAL"

[datasets.sc50a.forrest_tomlin_primal_no_presolve]
allocations = 1762
bytes = 271432
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0006077
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_dual]
allocations = 108825
bytes = 4760720
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0026758
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_dual_no_presolve]
allocations = 2187
bytes = 372912
compile_seconds = 0.0
iterations = 52
objective = -64.5750770585645
samples = 3
seconds = 0.0006504
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_primal]
allocations = 108438
bytes = 4701248
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0027839
status = "OPTIMAL"

[datasets.sc50a.suhl_suhl_primal_no_presolve]
allocations = 1750
bytes = 269848
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005475
status = "OPTIMAL"

[probes.BartelsGolubFactorization]
allocations = 142
bytes = 9696
compile_seconds = 0.0
samples = 3
seconds = 1.38e-5

[probes.ForrestTomlinFactorization]
allocations = 13
bytes = 3456
compile_seconds = 0.0
samples = 3
seconds = 7.6e-6

[probes.SuhlSuhlFactorization]
allocations = 13
bytes = 3488
compile_seconds = 0.0
samples = 3
seconds = 9.8e-6

[probes.dense]
allocations = 18
bytes = 33920
compile_seconds = 0.0
samples = 3
seconds = 1.14e-5

[probes.sparse]
allocations = 4
bytes = 160
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[probes.zero]
allocations = 2
bytes = 64
compile_seconds = 0.0
samples = 3
seconds = 1.4e-6
