julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 96175
bytes = 4601496
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003335201
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009399
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1698
bytes = 78808
compile_seconds = 0.0
samples = 3
seconds = 0.0001128

[datasets.adlittle.presolve]
allocations = 94160
bytes = 3811400
compile_seconds = 0.0
samples = 3
seconds = 0.0022541

[datasets.adlittle.primal]
allocations = 96973
bytes = 4877800
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036991
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001158301
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 23843
bytes = 1120496
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008165
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002169
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.22e-5

[datasets.afiro.presolve]
allocations = 23028
bytes = 984784
compile_seconds = 0.0
samples = 3
seconds = 0.0006238

[datasets.afiro.primal]
allocations = 23749
bytes = 1099072
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000792
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001758
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 36561
bytes = 1484520
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009463
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001377
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 1.05e-5

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1373728
compile_seconds = 0.0
samples = 3
seconds = 0.0007591

[datasets.flugpl.primal]
allocations = 36910
bytes = 1529224
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010236
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001711
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 274923
bytes = 12878536
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020756801
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878144
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000837
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 4942
bytes = 190344
compile_seconds = 0.0
samples = 3
seconds = 0.0001284

[datasets.kb2.presolve]
allocations = 273721
bytes = 12423480
compile_seconds = 0.0
samples = 3
seconds = 0.020123901

[datasets.kb2.primal]
allocations = 275090
bytes = 12893064
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021063101
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006047
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 98051
bytes = 4272416
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002459301
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005523
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 490
bytes = 26352
compile_seconds = 0.0
samples = 3
seconds = 7.84e-5

[datasets.sc50a.presolve]
allocations = 96979
bytes = 3926768
compile_seconds = 0.0
samples = 3
seconds = 0.0018485

[datasets.sc50a.primal]
allocations = 97996
bytes = 4224992
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023509
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005002
status = "OPTIMAL"

[probes.negative]
allocations = 15291
bytes = 521664
compile_seconds = 0.0
samples = 3
seconds = 0.0002987

[probes.nonunit]
allocations = 15291
bytes = 519936
compile_seconds = 0.0
samples = 3
seconds = 0.0003177

[probes.unit]
allocations = 12219
bytes = 403952
compile_seconds = 0.0
samples = 3
seconds = 0.0002414
