julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 91021
bytes = 4415480
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003338701
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461496
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009006
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1686
bytes = 78224
compile_seconds = 0.0
samples = 3
seconds = 0.0001084

[datasets.adlittle.presolve]
allocations = 89006
bytes = 3625272
compile_seconds = 0.0
samples = 3
seconds = 0.002122601

[datasets.adlittle.primal]
allocations = 91819
bytes = 4691544
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003601701
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607104
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010454
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 19652
bytes = 965440
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000871701
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000201
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.14e-5

[datasets.afiro.presolve]
allocations = 18837
bytes = 830064
compile_seconds = 0.0
samples = 3
seconds = 0.0006147

[datasets.afiro.primal]
allocations = 19558
bytes = 945264
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007802
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002011
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 35559
bytes = 1448728
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000839
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001613
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 1.03e-5

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1339728
compile_seconds = 0.0
samples = 3
seconds = 0.000679301

[datasets.flugpl.primal]
allocations = 35908
bytes = 1493480
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009292
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001848
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 242681
bytes = 11617232
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020860808
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000807901
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 4906
bytes = 189424
compile_seconds = 0.0
samples = 3
seconds = 0.0001178

[datasets.kb2.presolve]
allocations = 241479
bytes = 11164080
compile_seconds = 0.0
samples = 3
seconds = 0.020095908

[datasets.kb2.primal]
allocations = 242848
bytes = 11631920
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020717708
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005952
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 74027
bytes = 3408000
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002112901
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005678
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 478
bytes = 25992
compile_seconds = 0.0
samples = 3
seconds = 5.72e-5

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3061616
compile_seconds = 0.0
samples = 3
seconds = 0.001495401

[datasets.sc50a.primal]
allocations = 73972
bytes = 3360640
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001913101
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005052
status = "OPTIMAL"

[probes.negative]
allocations = 14651
bytes = 505536
compile_seconds = 0.0
samples = 3
seconds = 0.0002693

[probes.positive]
allocations = 14651
bytes = 504560
compile_seconds = 0.0
samples = 3
seconds = 0.0003356

[probes.unequal]
allocations = 15291
bytes = 522592
compile_seconds = 0.0
samples = 3
seconds = 0.0002753

[probes.unit]
allocations = 10043
bytes = 341472
compile_seconds = 0.0
samples = 3
seconds = 0.0002081

[probes.unit_unequal]
allocations = 10683
bytes = 358336
compile_seconds = 0.0
samples = 3
seconds = 0.0002125
