julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 96175
bytes = 4602136
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003520603
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000960501
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1698
bytes = 79384
compile_seconds = 0.0
samples = 3
seconds = 0.0001129

[datasets.adlittle.presolve]
allocations = 94160
bytes = 3813800
compile_seconds = 0.0
samples = 3
seconds = 0.002200202

[datasets.adlittle.primal]
allocations = 96973
bytes = 4878920
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004027803
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607488
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001082601
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 23843
bytes = 1121920
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000802501
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002114
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.41e-5

[datasets.afiro.presolve]
allocations = 23028
bytes = 985520
compile_seconds = 0.0
samples = 3
seconds = 0.000771001

[datasets.afiro.primal]
allocations = 23749
bytes = 1099712
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000793601
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002079
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 36561
bytes = 1484552
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009504
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001524
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 8.4e-6

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1374800
compile_seconds = 0.0
samples = 3
seconds = 0.0007167

[datasets.flugpl.primal]
allocations = 36910
bytes = 1529080
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000914601
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001708
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 274923
bytes = 12877896
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020668106
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878192
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008394
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 4942
bytes = 191144
compile_seconds = 0.0
samples = 3
seconds = 0.000128

[datasets.kb2.presolve]
allocations = 273721
bytes = 12427640
compile_seconds = 0.0
samples = 3
seconds = 0.020165506

[datasets.kb2.primal]
allocations = 275090
bytes = 12891880
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020657406
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260880
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000590201
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 98051
bytes = 4272928
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002436501
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005275
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 490
bytes = 26352
compile_seconds = 0.0
samples = 3
seconds = 5.95e-5

[datasets.sc50a.presolve]
allocations = 96979
bytes = 3926256
compile_seconds = 0.0
samples = 3
seconds = 0.001890301

[datasets.sc50a.primal]
allocations = 97996
bytes = 4225952
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002356001
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004714
status = "OPTIMAL"

[probes.negative]
allocations = 15291
bytes = 522400
compile_seconds = 0.0
samples = 3
seconds = 0.0003134

[probes.nonunit]
allocations = 15291
bytes = 522320
compile_seconds = 0.0
samples = 3
seconds = 0.0002997

[probes.unit]
allocations = 12219
bytes = 403392
compile_seconds = 0.0
samples = 3
seconds = 0.0002479
