julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 96311
bytes = 4605000
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035943
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461336
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001030301
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1749
bytes = 81040
compile_seconds = 0.0
samples = 3
seconds = 0.0001018

[datasets.adlittle.presolve]
allocations = 94296
bytes = 3815496
compile_seconds = 0.0
samples = 3
seconds = 0.002079301

[datasets.adlittle.primal]
allocations = 97109
bytes = 4881560
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035853
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001134
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 23877
bytes = 1121376
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007777
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002016
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.26e-5

[datasets.afiro.presolve]
allocations = 23062
bytes = 985120
compile_seconds = 0.0
samples = 3
seconds = 0.0008164

[datasets.afiro.primal]
allocations = 23783
bytes = 1098848
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007435
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002134
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 36629
bytes = 1486472
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011644
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001613
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 1.23e-5

[datasets.flugpl.presolve]
allocations = 35958
bytes = 1376256
compile_seconds = 0.0
samples = 3
seconds = 0.000972

[datasets.flugpl.primal]
allocations = 36978
bytes = 1531352
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011417
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002083
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 275637
bytes = 12902264
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022100902
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877856
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008474
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 5299
bytes = 203664
compile_seconds = 0.0
samples = 3
seconds = 0.0001353

[datasets.kb2.presolve]
allocations = 274435
bytes = 12451192
compile_seconds = 0.0
samples = 3
seconds = 0.022508802

[datasets.kb2.primal]
allocations = 275804
bytes = 12916056
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023978303
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000634501
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 98255
bytes = 4278672
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0027747
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306320
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005943
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 541
bytes = 28104
compile_seconds = 0.0
samples = 3
seconds = 5.9e-5

[datasets.sc50a.presolve]
allocations = 97183
bytes = 3933376
compile_seconds = 0.0
samples = 3
seconds = 0.0022398

[datasets.sc50a.primal]
allocations = 98200
bytes = 4231472
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025858
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005567
status = "OPTIMAL"

[probes.nonzero]
allocations = 18875
bytes = 645872
compile_seconds = 0.0
samples = 3
seconds = 0.0003242

[probes.unit]
allocations = 12219
bytes = 403472
compile_seconds = 0.0
samples = 3
seconds = 0.000249

[probes.zero]
allocations = 17467
bytes = 595632
compile_seconds = 0.0
samples = 3
seconds = 0.0003583
