julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119602
bytes = 5527368
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003577308
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000979303
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1751
bytes = 80960
compile_seconds = 0.0
samples = 3
seconds = 0.0001224

[datasets.adlittle.presolve]
allocations = 117587
bytes = 4738024
compile_seconds = 0.0
samples = 3
seconds = 0.002438106

[datasets.adlittle.primal]
allocations = 120400
bytes = 5803448
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004361611
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607552
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001102203
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 27472
bytes = 1269208
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000852102
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002093
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 127
bytes = 8336
compile_seconds = 0.0
samples = 3
seconds = 1.22e-5

[datasets.afiro.presolve]
allocations = 26657
bytes = 1133128
compile_seconds = 0.0
samples = 3
seconds = 0.0006578

[datasets.afiro.primal]
allocations = 27378
bytes = 1247256
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000842702
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000224001
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 39646
bytes = 1604896
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010734
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001606
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 91
bytes = 6016
compile_seconds = 0.0
samples = 3
seconds = 1.26e-5

[datasets.flugpl.presolve]
allocations = 38975
bytes = 1495272
compile_seconds = 0.0
samples = 3
seconds = 0.0008014

[datasets.flugpl.primal]
allocations = 39995
bytes = 1649760
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001212399
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001648
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 292797
bytes = 13582848
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020811452
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000939102
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 5301
bytes = 204560
compile_seconds = 0.0
samples = 3
seconds = 0.000139401

[datasets.kb2.presolve]
allocations = 291595
bytes = 13128912
compile_seconds = 0.0
samples = 3
seconds = 0.020420851

[datasets.kb2.primal]
allocations = 292964
bytes = 13597392
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020479896
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000596501
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 102764
bytes = 4470096
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024148
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005537
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 543
bytes = 28584
compile_seconds = 0.0
samples = 3
seconds = 6.98e-5

[datasets.sc50a.presolve]
allocations = 101692
bytes = 4123568
compile_seconds = 0.0
samples = 3
seconds = 0.0020561

[datasets.sc50a.primal]
allocations = 102709
bytes = 4422464
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002575499
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005409
status = "OPTIMAL"

[probes.repeated]
allocations = 9274
bytes = 309360
compile_seconds = 0.0
samples = 3
seconds = 0.0002294

[probes.unique]
allocations = 534
bytes = 32240
compile_seconds = 0.0
samples = 3
seconds = 2.14e-5
