julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 120002
bytes = 5554632
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003757002
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461496
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000963001
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1796
bytes = 83984
compile_seconds = 0.0
samples = 3
seconds = 0.0001192

[datasets.adlittle.presolve]
allocations = 117987
bytes = 4764696
compile_seconds = 0.0
samples = 3
seconds = 0.002412201

[datasets.adlittle.primal]
allocations = 120800
bytes = 5831144
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003971102
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607344
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001102401
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 27653
bytes = 1279416
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009241
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002002
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 127
bytes = 8336
compile_seconds = 0.0
samples = 3
seconds = 1.17e-5

[datasets.afiro.presolve]
allocations = 26838
bytes = 1143048
compile_seconds = 0.0
samples = 3
seconds = 0.0006497

[datasets.afiro.primal]
allocations = 27559
bytes = 1256984
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000829
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000216
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 39760
bytes = 1610752
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001069201
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001237
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 91
bytes = 6016
compile_seconds = 0.0
samples = 3
seconds = 1.04e-5

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1501832
compile_seconds = 0.0
samples = 3
seconds = 0.000793101

[datasets.flugpl.primal]
allocations = 40109
bytes = 1655712
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010131
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001888
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 293411
bytes = 13613424
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021007007
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877664
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008379
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 5517
bytes = 213216
compile_seconds = 0.0
samples = 3
seconds = 0.0001286

[datasets.kb2.presolve]
allocations = 292209
bytes = 13161632
compile_seconds = 0.0
samples = 3
seconds = 0.020623507

[datasets.kb2.primal]
allocations = 293578
bytes = 13627104
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021332708
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006185
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 103085
bytes = 4486992
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002409601
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005828
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 570
bytes = 29592
compile_seconds = 0.0
samples = 3
seconds = 4.67e-5

[datasets.sc50a.presolve]
allocations = 102013
bytes = 4141200
compile_seconds = 0.0
samples = 3
seconds = 0.001976001

[datasets.sc50a.primal]
allocations = 103030
bytes = 4440384
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002445001
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000488
status = "OPTIMAL"

[probes.nonunit]
allocations = 18362
bytes = 637056
compile_seconds = 0.0
samples = 3
seconds = 0.0003278

[probes.unit]
allocations = 18362
bytes = 635056
compile_seconds = 0.0
samples = 3
seconds = 0.0003343
