julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90829
bytes = 4408776
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033453
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009746
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1638
bytes = 76576
compile_seconds = 0.0
samples = 3
seconds = 9.51e-5

[datasets.adlittle.presolve]
allocations = 88814
bytes = 3617816
compile_seconds = 0.0
samples = 3
seconds = 0.0019894

[datasets.adlittle.primal]
allocations = 91627
bytes = 4685528
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035767
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607248
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010015
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 19553
bytes = 963136
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007102
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002101
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.2e-5

[datasets.afiro.presolve]
allocations = 18738
bytes = 827104
compile_seconds = 0.0
samples = 3
seconds = 0.0007266

[datasets.afiro.primal]
allocations = 19459
bytes = 942448
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000665599
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001963
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 35559
bytes = 1448536
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008475
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001293
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 9.7e-6

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1338976
compile_seconds = 0.0
samples = 3
seconds = 0.0006754

[datasets.flugpl.primal]
allocations = 35908
bytes = 1492936
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008843
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001627
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 242249
bytes = 11603984
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0205106
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008268
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 4690
bytes = 182432
compile_seconds = 0.0
samples = 3
seconds = 0.00012

[datasets.kb2.presolve]
allocations = 241047
bytes = 11152176
compile_seconds = 0.0
samples = 3
seconds = 0.020352

[datasets.kb2.primal]
allocations = 242416
bytes = 11618512
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020707
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006019
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 74027
bytes = 3406912
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019279
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005923
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 478
bytes = 25992
compile_seconds = 0.0
samples = 3
seconds = 7.46e-5

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3060640
compile_seconds = 0.0
samples = 3
seconds = 0.0014763

[datasets.sc50a.primal]
allocations = 73972
bytes = 3359376
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019518
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005252
status = "OPTIMAL"

[probes.negative]
allocations = 14907
bytes = 496864
compile_seconds = 0.0
samples = 3
seconds = 0.0002901

[probes.nonunit]
allocations = 16699
bytes = 571440
compile_seconds = 0.0
samples = 3
seconds = 0.0002638

[probes.positive]
allocations = 16699
bytes = 571600
compile_seconds = 0.0
samples = 3
seconds = 0.0002831

[probes.unit]
allocations = 11067
bytes = 367872
compile_seconds = 0.0
samples = 3
seconds = 0.0002058

[probes.zero]
allocations = 13499
bytes = 449504
compile_seconds = 0.0
samples = 3
seconds = 0.0002353
