julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 96127
bytes = 4598936
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003203
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009014
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1686
bytes = 78160
compile_seconds = 0.0
samples = 3
seconds = 0.0001069

[datasets.adlittle.presolve]
allocations = 94112
bytes = 3809384
compile_seconds = 0.0
samples = 3
seconds = 0.002273901

[datasets.adlittle.primal]
allocations = 96925
bytes = 4875208
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003597701
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607104
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010952
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 23819
bytes = 1119360
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007548
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001862
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.14e-5

[datasets.afiro.presolve]
allocations = 23004
bytes = 983664
compile_seconds = 0.0
samples = 3
seconds = 0.0005977

[datasets.afiro.primal]
allocations = 23725
bytes = 1098400
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000811
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002081
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 36561
bytes = 1484312
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008709
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001575
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 9.6e-6

[datasets.flugpl.presolve]
allocations = 35890
bytes = 1374016
compile_seconds = 0.0
samples = 3
seconds = 0.0006808

[datasets.flugpl.primal]
allocations = 36910
bytes = 1528696
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008682
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001584
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 274851
bytes = 12876264
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020999598
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878160
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008394
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 4906
bytes = 189280
compile_seconds = 0.0
samples = 3
seconds = 0.000123

[datasets.kb2.presolve]
allocations = 273649
bytes = 12422440
compile_seconds = 0.0
samples = 3
seconds = 0.019768898

[datasets.kb2.primal]
allocations = 275018
bytes = 12890760
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020910098
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005832
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 97979
bytes = 4270896
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024071
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306240
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005273
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 478
bytes = 25992
compile_seconds = 0.0
samples = 3
seconds = 7.01e-5

[datasets.sc50a.presolve]
allocations = 96907
bytes = 3924272
compile_seconds = 0.0
samples = 3
seconds = 0.0018009

[datasets.sc50a.primal]
allocations = 97924
bytes = 4223456
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021977
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232312
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004795
status = "OPTIMAL"

[probes.negative]
allocations = 15291
bytes = 521520
compile_seconds = 0.0
samples = 3
seconds = 0.0003078

[probes.nonunit]
allocations = 15291
bytes = 521664
compile_seconds = 0.0
samples = 3
seconds = 0.0002822

[probes.unit]
allocations = 10683
bytes = 356096
compile_seconds = 0.0
samples = 3
seconds = 0.000236601
