julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90829
bytes = 4406888
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033597
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461736
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009398
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1638
bytes = 75568
compile_seconds = 0.0
samples = 3
seconds = 0.0001128

[datasets.adlittle.presolve]
allocations = 88814
bytes = 3617560
compile_seconds = 0.0
samples = 3
seconds = 0.0021031

[datasets.adlittle.primal]
allocations = 91627
bytes = 4683656
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036997
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010603
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 19553
bytes = 962880
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007957
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002029
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.25e-5

[datasets.afiro.presolve]
allocations = 18738
bytes = 826192
compile_seconds = 0.0
samples = 3
seconds = 0.0006968

[datasets.afiro.primal]
allocations = 19459
bytes = 941936
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007534
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002045
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 35559
bytes = 1448584
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009085
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001543
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 1.03e-5

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1338720
compile_seconds = 0.0
samples = 3
seconds = 0.000734

[datasets.flugpl.primal]
allocations = 35908
bytes = 1493288
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009571
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001919
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 242249
bytes = 11604096
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0220819
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008855
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 4690
bytes = 182000
compile_seconds = 0.0
samples = 3
seconds = 0.0001461

[datasets.kb2.presolve]
allocations = 241047
bytes = 11150688
compile_seconds = 0.0
samples = 3
seconds = 0.0208593

[datasets.kb2.primal]
allocations = 242416
bytes = 11619600
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0217456
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260944
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006105
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 74027
bytes = 3405088
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022475
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006041
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 478
bytes = 25992
compile_seconds = 0.0
samples = 3
seconds = 7.95e-5

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3059552
compile_seconds = 0.0
samples = 3
seconds = 0.0016604

[datasets.sc50a.primal]
allocations = 73972
bytes = 3357856
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021073
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005155
status = "OPTIMAL"

[probes.equal]
allocations = 9275
bytes = 323168
compile_seconds = 0.0
samples = 3
seconds = 0.0002005

[probes.negative]
allocations = 15291
bytes = 520064
compile_seconds = 0.0
samples = 3
seconds = 0.0002821

[probes.nonunit]
allocations = 15291
bytes = 520992
compile_seconds = 0.0
samples = 3
seconds = 0.000274

[probes.positive]
allocations = 15291
bytes = 521056
compile_seconds = 0.0
samples = 3
seconds = 0.0002824

[probes.unit]
allocations = 10683
bytes = 356832
compile_seconds = 0.0
samples = 3
seconds = 0.0002074
