julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119822
bytes = 5546760
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036126
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009718
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1751
bytes = 81728
compile_seconds = 0.0
samples = 3
seconds = 0.0001061

[datasets.adlittle.presolve]
allocations = 117807
bytes = 4756776
compile_seconds = 0.0
samples = 3
seconds = 0.0024747

[datasets.adlittle.primal]
allocations = 120620
bytes = 5823544
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041893
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607312
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010245
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 27568
bytes = 1274456
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009153
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002053
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 127
bytes = 8336
compile_seconds = 0.0
samples = 3
seconds = 1.18e-5

[datasets.afiro.presolve]
allocations = 26753
bytes = 1139320
compile_seconds = 0.0
samples = 3
seconds = 0.0006871

[datasets.afiro.primal]
allocations = 27474
bytes = 1252824
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008765
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002156
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 39760
bytes = 1610704
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009097
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001478
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 91
bytes = 6016
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[datasets.flugpl.presolve]
allocations = 39089
bytes = 1500904
compile_seconds = 0.0
samples = 3
seconds = 0.0007441

[datasets.flugpl.primal]
allocations = 40109
bytes = 1654656
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008725
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001622
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 292979
bytes = 13597296
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0218665
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878160
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008326
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 5301
bytes = 204240
compile_seconds = 0.0
samples = 3
seconds = 0.0001313

[datasets.kb2.presolve]
allocations = 291777
bytes = 13142736
compile_seconds = 0.0
samples = 3
seconds = 0.0207224

[datasets.kb2.primal]
allocations = 293146
bytes = 13611152
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0219141
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005612
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 102950
bytes = 4479824
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023531
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306400
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006228
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 543
bytes = 28584
compile_seconds = 0.0
samples = 3
seconds = 4.99e-5

[datasets.sc50a.presolve]
allocations = 101878
bytes = 4134912
compile_seconds = 0.0
samples = 3
seconds = 0.0019584

[datasets.sc50a.primal]
allocations = 102895
bytes = 4432400
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023144
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005117
status = "OPTIMAL"

[probes.nonunit]
allocations = 18362
bytes = 636336
compile_seconds = 0.0
samples = 3
seconds = 0.0002925

[probes.unit]
allocations = 12346
bytes = 407440
compile_seconds = 0.0
samples = 3
seconds = 0.0002624
