julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 96311
bytes = 4607704
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003458602
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461656
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009222
status = "OPTIMAL"

[datasets.adlittle.parallel]
allocations = 1749
bytes = 80720
compile_seconds = 0.0
samples = 3
seconds = 0.0001272

[datasets.adlittle.presolve]
allocations = 94296
bytes = 3818328
compile_seconds = 0.0
samples = 3
seconds = 0.002311001

[datasets.adlittle.primal]
allocations = 97109
bytes = 4884264
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003549702
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010251
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 23877
bytes = 1120832
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000802201
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002032
status = "OPTIMAL"

[datasets.afiro.parallel]
allocations = 125
bytes = 8064
compile_seconds = 0.0
samples = 3
seconds = 1.19e-5

[datasets.afiro.presolve]
allocations = 23062
bytes = 986032
compile_seconds = 0.0
samples = 3
seconds = 0.000660901

[datasets.afiro.primal]
allocations = 23783
bytes = 1100672
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008089
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000188
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 36629
bytes = 1487592
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000884201
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001372
status = "OPTIMAL"

[datasets.flugpl.parallel]
allocations = 89
bytes = 5808
compile_seconds = 0.0
samples = 3
seconds = 9.7e-6

[datasets.flugpl.presolve]
allocations = 35958
bytes = 1376880
compile_seconds = 0.0
samples = 3
seconds = 0.0007445

[datasets.flugpl.primal]
allocations = 36978
bytes = 1531416
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000906701
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001877
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 275637
bytes = 12904104
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020919509
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878144
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000838
status = "OPTIMAL"

[datasets.kb2.parallel]
allocations = 5299
bytes = 202448
compile_seconds = 0.0
samples = 3
seconds = 0.0001316

[datasets.kb2.presolve]
allocations = 274435
bytes = 12452264
compile_seconds = 0.0
samples = 3
seconds = 0.020845212

[datasets.kb2.primal]
allocations = 275804
bytes = 12917816
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020854409
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000634
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 98255
bytes = 4280112
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002326601
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005169
status = "OPTIMAL"

[datasets.sc50a.parallel]
allocations = 541
bytes = 28104
compile_seconds = 0.0
samples = 3
seconds = 6.42e-5

[datasets.sc50a.presolve]
allocations = 97183
bytes = 3934448
compile_seconds = 0.0
samples = 3
seconds = 0.0018712

[datasets.sc50a.primal]
allocations = 98200
bytes = 4232736
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002245701
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004833
status = "OPTIMAL"

[probes.negative]
allocations = 17467
bytes = 596512
compile_seconds = 0.0
samples = 3
seconds = 0.0003147

[probes.nonunit]
allocations = 17467
bytes = 595152
compile_seconds = 0.0
samples = 3
seconds = 0.0002865

[probes.unit]
allocations = 12219
bytes = 403136
compile_seconds = 0.0
samples = 3
seconds = 0.0002329
