julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123825
bytes = 5978048
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0040087
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1455
bytes = 539184
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009583
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 124753
bytes = 6311256
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041882
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 2124
bytes = 727632
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011955
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28866
bytes = 1375432
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007793
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 633
bytes = 106080
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002415
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28745
bytes = 1349240
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008553
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 910
bytes = 144800
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002171
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40126
bytes = 1640536
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010394
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 431
bytes = 50032
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001552
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40571
bytes = 1695208
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010285
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 890
bytes = 110240
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001955
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294528
bytes = 13899312
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0242356
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1724
bytes = 1033712
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008844
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 294691
bytes = 13911600
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0220127
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1142
bytes = 306104
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006324
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107738
bytes = 4755424
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025904
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 1073
bytes = 350960
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000656
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107656
bytes = 4698464
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002759
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 1049
bytes = 264728
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005415
status = "OPTIMAL"

[updates.dense]
allocations = 9
bytes = 8496
compile_seconds = 0.0
samples = 3
seconds = 1.08e-5

[updates.sparse]
allocations = 7
bytes = 352
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6
