julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 124211
bytes = 6076864
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0040666
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1721
bytes = 606656
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009513
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 125159
bytes = 6407240
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039372
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 2404
bytes = 794432
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011218
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28878
bytes = 1376104
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008327
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 663
bytes = 110976
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001898
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28757
bytes = 1349208
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000805
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 932
bytes = 147152
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000187199
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40134
bytes = 1639064
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009051
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 443
bytes = 51600
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001296
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40589
bytes = 1695000
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000922
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 908
bytes = 112896
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001762
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294666
bytes = 13929376
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021681099
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1886
bytes = 1070240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008384
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 294871
bytes = 13951664
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021477899
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1346
bytes = 353208
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005922
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107804
bytes = 4768656
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023984
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 1171
bytes = 370560
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006038
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107754
bytes = 4720496
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023676
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 1211
bytes = 301160
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004971
status = "OPTIMAL"

[updates.dense]
allocations = 19
bytes = 17344
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[updates.sparse]
allocations = 7
bytes = 352
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6
