["BigFloat/BigFloat/128/dense"]
repetitions = 10

    ["BigFloat/BigFloat/128/dense".after]
    allocations = 2910
    bytes = 279040
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0001359

    ["BigFloat/BigFloat/128/dense".before]
    allocations = 2990
    bytes = 317600
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0001334

["BigFloat/BigFloat/128/sparse"]
repetitions = 10

    ["BigFloat/BigFloat/128/sparse".after]
    allocations = 410
    bytes = 18560
    compile_seconds = 0.0
    samples = 5
    seconds = 2.74e-5

    ["BigFloat/BigFloat/128/sparse".before]
    allocations = 410
    bytes = 18560
    compile_seconds = 0.0
    samples = 5
    seconds = 4.01e-5

["Float32/Float32/128/dense"]
repetitions = 100

    ["Float32/Float32/128/dense".after]
    allocations = 600
    bytes = 176000
    compile_seconds = 0.0
    samples = 5
    seconds = 3.07e-5

    ["Float32/Float32/128/dense".before]
    allocations = 1300
    bytes = 466400
    compile_seconds = 0.0
    samples = 5
    seconds = 7.86e-5

["Float32/Float32/128/sparse"]
repetitions = 100

    ["Float32/Float32/128/sparse".after]
    allocations = 600
    bytes = 24000
    compile_seconds = 0.0
    samples = 5
    seconds = 1.52e-5

    ["Float32/Float32/128/sparse".before]
    allocations = 600
    bytes = 24000
    compile_seconds = 0.0
    samples = 5
    seconds = 1.1e-5

["Float64/Float64/512/dense"]
repetitions = 1000

    ["Float64/Float64/512/dense".after]
    allocations = 8000
    bytes = 8400000
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0013718

    ["Float64/Float64/512/dense".before]
    allocations = 18000
    bytes = 17248000
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0017872

["Float64/Float64/512/sparse"]
repetitions = 1000

    ["Float64/Float64/512/sparse".after]
    allocations = 6000
    bytes = 256000
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0003622

    ["Float64/Float64/512/sparse".before]
    allocations = 6000
    bytes = 256000
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0002715

["Float64/Float64/8192/dense"]
repetitions = 100

    ["Float64/Float64/8192/dense".after]
    allocations = 800
    bytes = 13128000
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0016157

    ["Float64/Float64/8192/dense".before]
    allocations = 3400
    bytes = 42204800
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0026249

["Float64/Float64/8192/sparse"]
repetitions = 100

    ["Float64/Float64/8192/sparse".after]
    allocations = 600
    bytes = 25600
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0005178

    ["Float64/Float64/8192/sparse".before]
    allocations = 600
    bytes = 25600
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0004131

["Rational{BigInt}/Float64/128/dense"]
repetitions = 10

    ["Rational{BigInt}/Float64/128/dense".after]
    allocations = 29550
    bytes = 1065616
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0005033

    ["Rational{BigInt}/Float64/128/dense".before]
    allocations = 29550
    bytes = 1066128
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0004564

["Rational{BigInt}/Float64/128/sparse"]
repetitions = 10

    ["Rational{BigInt}/Float64/128/sparse".after]
    allocations = 11970
    bytes = 393120
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0002158

    ["Rational{BigInt}/Float64/128/sparse".before]
    allocations = 11970
    bytes = 392224
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0001867

["Rational{BigInt}/Rational{BigInt}/128/dense"]
repetitions = 10

    ["Rational{BigInt}/Rational{BigInt}/128/dense".after]
    allocations = 14120
    bytes = 544560
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0002066

    ["Rational{BigInt}/Rational{BigInt}/128/dense".before]
    allocations = 14190
    bytes = 601024
    compile_seconds = 0.0
    samples = 5
    seconds = 0.0002084

["Rational{BigInt}/Rational{BigInt}/128/sparse"]
repetitions = 10

    ["Rational{BigInt}/Rational{BigInt}/128/sparse".after]
    allocations = 360
    bytes = 13120
    compile_seconds = 0.0
    samples = 5
    seconds = 2.66e-5

    ["Rational{BigInt}/Rational{BigInt}/128/sparse".before]
    allocations = 360
    bytes = 13120
    compile_seconds = 0.0
    samples = 5
    seconds = 2.84e-5
