julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "before"
presolve = false
scaling = "off"
threads = 1

[[kernels]]
allocations = 4
basis_refactorization = "native"
bytes = 1152
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 2.5e-6
updates = 1
[[kernels]]
allocations = 80
basis_refactorization = "native"
bytes = 23040
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 5.2e-6
updates = 20
[[kernels]]
allocations = 6
basis_refactorization = "native"
bytes = 8336
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 1.43e-5
updates = 1
[[kernels]]
allocations = 120
basis_refactorization = "native"
bytes = 166720
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 6.27e-5
updates = 20
[[kernels]]
allocations = 4
basis_refactorization = "markowitz"
bytes = 1152
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 3.2e-6
updates = 1
[[kernels]]
allocations = 80
basis_refactorization = "markowitz"
bytes = 23040
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 4.9e-6
updates = 20
[[kernels]]
allocations = 6
basis_refactorization = "markowitz"
bytes = 8336
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 2.07e-5
updates = 1
[[kernels]]
allocations = 120
basis_refactorization = "markowitz"
bytes = 166720
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 7.75e-5
updates = 20

[[rows]]
algorithm = "dual"
allocations = 1792
basis_update = "pfi"
bytes = 414280
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000506
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 460
basis_update = "pfi"
bytes = 78768
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002384
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1942
basis_update = "pfi"
bytes = 418000
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000438
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 614
basis_update = "pfi"
bytes = 109104
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002286
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2020
basis_update = "forrest_tomlin"
bytes = 424776
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000569
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 712
basis_update = "forrest_tomlin"
bytes = 89808
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002493
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2172
basis_update = "forrest_tomlin"
bytes = 428464
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004066
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 874
basis_update = "forrest_tomlin"
bytes = 121072
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002551
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2022
basis_update = "suhl_suhl"
bytes = 425816
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006063
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 704
basis_update = "suhl_suhl"
bytes = 89760
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002389
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2168
basis_update = "suhl_suhl"
bytes = 428896
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004015
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 872
basis_update = "suhl_suhl"
bytes = 122336
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002592
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2136
basis_update = "bartels_golub"
bytes = 432840
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006618
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 823
basis_update = "bartels_golub"
bytes = 96496
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003318
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2260
basis_update = "bartels_golub"
bytes = 434816
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004299
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 963
basis_update = "bartels_golub"
bytes = 128496
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002784
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2032
basis_update = "pfi"
bytes = 920328
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0014285
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1185
basis_update = "pfi"
bytes = 535488
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015129
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7571
basis_update = "pfi"
bytes = 5913240
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0035347
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1224
basis_update = "pfi"
bytes = 579288
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015921
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2690
basis_update = "forrest_tomlin"
bytes = 982392
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0018825
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1817
basis_update = "forrest_tomlin"
bytes = 561616
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017676
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7991
basis_update = "forrest_tomlin"
bytes = 5933944
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0036148
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1880
basis_update = "forrest_tomlin"
bytes = 629672
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017796
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2688
basis_update = "suhl_suhl"
bytes = 995864
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017802
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1789
basis_update = "suhl_suhl"
bytes = 560528
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015914
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7995
basis_update = "suhl_suhl"
bytes = 5936616
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0034661
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1874
basis_update = "suhl_suhl"
bytes = 634600
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017715
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2827
basis_update = "bartels_golub"
bytes = 996744
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017169
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1984
basis_update = "bartels_golub"
bytes = 590688
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0018
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8165
basis_update = "bartels_golub"
bytes = 5949128
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0037525
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1981
basis_update = "bartels_golub"
bytes = 654264
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0021172
status = "OPTIMAL"
