julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "after"
presolve = false
scaling = "off"
threads = 1

[[kernels]]
allocations = 0
basis_refactorization = "native"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 3.3e-6
updates = 1
[[kernels]]
allocations = 0
basis_refactorization = "native"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 7.5e-6
updates = 20
[[kernels]]
allocations = 0
basis_refactorization = "native"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 4.8e-6
updates = 1
[[kernels]]
allocations = 0
basis_refactorization = "native"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 3.06e-5
updates = 20
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 4.3e-6
updates = 1
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 8.1e-6
updates = 20
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 5.5e-6
updates = 1
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
bytes = 0
compile_seconds = 0.0
dimension = 512
samples = 3
seconds = 2.86e-5
updates = 20

[[rows]]
algorithm = "dual"
allocations = 1734
basis_update = "pfi"
bytes = 412696
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004645
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 460
basis_update = "pfi"
bytes = 78768
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002211
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1887
basis_update = "pfi"
bytes = 413664
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004346
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 614
basis_update = "pfi"
bytes = 109104
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000215
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2020
basis_update = "forrest_tomlin"
bytes = 424952
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005286
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 712
basis_update = "forrest_tomlin"
bytes = 89824
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002032
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2172
basis_update = "forrest_tomlin"
bytes = 428304
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004131
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 874
basis_update = "forrest_tomlin"
bytes = 121072
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002122
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2022
basis_update = "suhl_suhl"
bytes = 425496
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005178
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 704
basis_update = "suhl_suhl"
bytes = 89760
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002278
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2168
basis_update = "suhl_suhl"
bytes = 428512
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0003971
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 872
basis_update = "suhl_suhl"
bytes = 122336
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002365
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2136
basis_update = "bartels_golub"
bytes = 432856
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0008921
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 823
basis_update = "bartels_golub"
bytes = 96480
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002806
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2260
basis_update = "bartels_golub"
bytes = 434560
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004976
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 963
basis_update = "bartels_golub"
bytes = 128448
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000258
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1763
basis_update = "pfi"
bytes = 903080
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0014173
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 920
basis_update = "pfi"
bytes = 508128
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016054
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7252
basis_update = "pfi"
bytes = 5877688
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0037481
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1025
basis_update = "pfi"
bytes = 567160
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0014481
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2690
basis_update = "forrest_tomlin"
bytes = 982488
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0019031
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1817
basis_update = "forrest_tomlin"
bytes = 561760
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015442
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7991
basis_update = "forrest_tomlin"
bytes = 5932264
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0035186
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1880
basis_update = "forrest_tomlin"
bytes = 629624
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017551
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2688
basis_update = "suhl_suhl"
bytes = 995880
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017262
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1789
basis_update = "suhl_suhl"
bytes = 560640
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016049
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7995
basis_update = "suhl_suhl"
bytes = 5935160
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0035236
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1874
basis_update = "suhl_suhl"
bytes = 634488
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017278
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2827
basis_update = "bartels_golub"
bytes = 996760
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001818
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1984
basis_update = "bartels_golub"
bytes = 590752
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017619
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8165
basis_update = "bartels_golub"
bytes = 5947672
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0034769
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1981
basis_update = "bartels_golub"
bytes = 654184
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001988199
status = "OPTIMAL"
