julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123628
bytes = 5861400
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036112
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1332
bytes = 465032
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008687
status = "OPTIMAL"

[datasets.adlittle.phase_one]
allocations = 473
bytes = 181088
compile_seconds = 0.0
samples = 3
seconds = 0.0001009

[datasets.adlittle.primal]
allocations = 124469
bytes = 6142824
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038129
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1948
bytes = 615888
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010206
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28734
bytes = 1349944
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007813
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 561
bytes = 91248
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002207
status = "OPTIMAL"

[datasets.afiro.phase_one]
allocations = 462
bytes = 90336
compile_seconds = 0.0
samples = 3
seconds = 7.02e-5

[datasets.afiro.primal]
allocations = 28640
bytes = 1329272
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007557
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 808
bytes = 125712
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001837
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40017
bytes = 1624184
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008756
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 382
bytes = 43568
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001073
status = "OPTIMAL"

[datasets.flugpl.phase_one]
allocations = 468
bytes = 69104
compile_seconds = 0.0
samples = 3
seconds = 6.65e-5

[datasets.flugpl.primal]
allocations = 40409
bytes = 1671304
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000974
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 788
bytes = 95728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001852
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294362
bytes = 13802192
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021535599
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1514
bytes = 879952
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007236
status = "OPTIMAL"

[datasets.kb2.phase_one]
allocations = 153
bytes = 43200
compile_seconds = 0.0
samples = 3
seconds = 5.4399e-5

[datasets.kb2.primal]
allocations = 294529
bytes = 13817216
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0215352
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1060
bytes = 262496
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006078
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107589
bytes = 4702816
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002329299
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 967
bytes = 308624
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005441
status = "OPTIMAL"

[datasets.sc50a.phase_one]
allocations = 153
bytes = 48784
compile_seconds = 0.0
samples = 3
seconds = 4.53e-5

[datasets.sc50a.primal]
allocations = 107534
bytes = 4655536
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023063
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 970
bytes = 234040
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004514
status = "OPTIMAL"

[probes.dense_artificials]
allocations = 46
bytes = 132632
compile_seconds = 0.0
samples = 3
seconds = 2.82e-5

[probes.empty]
allocations = 20
bytes = 720
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[probes.few_artificials]
allocations = 38
bytes = 42616
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5
