julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123628
bytes = 5860808
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039607
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1332
bytes = 465112
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009389
status = "OPTIMAL"

[datasets.adlittle.phase_one]
allocations = 440
bytes = 177152
compile_seconds = 0.0
samples = 3
seconds = 0.0001252

[datasets.adlittle.primal]
allocations = 124436
bytes = 6138728
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004009
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1915
bytes = 612272
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011657
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28734
bytes = 1351272
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008669
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 561
bytes = 91200
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002177
status = "OPTIMAL"

[datasets.afiro.phase_one]
allocations = 429
bytes = 88272
compile_seconds = 0.0
samples = 3
seconds = 7.56e-5

[datasets.afiro.primal]
allocations = 28640
bytes = 1330952
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008767
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 775
bytes = 123728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002134
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40017
bytes = 1625208
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010406
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 382
bytes = 43568
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001449
status = "OPTIMAL"

[datasets.flugpl.phase_one]
allocations = 435
bytes = 66464
compile_seconds = 0.0
samples = 3
seconds = 9.54e-5

[datasets.flugpl.primal]
allocations = 40376
bytes = 1670296
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011024
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 755
bytes = 93088
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001839
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294362
bytes = 13803056
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021966
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1514
bytes = 879584
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008071
status = "OPTIMAL"

[datasets.kb2.phase_one]
allocations = 153
bytes = 43216
compile_seconds = 0.0
samples = 3
seconds = 6.05e-5

[datasets.kb2.primal]
allocations = 294529
bytes = 13817824
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021745499
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1060
bytes = 262496
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006188
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107589
bytes = 4702640
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025869
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 967
bytes = 308496
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005784
status = "OPTIMAL"

[datasets.sc50a.phase_one]
allocations = 153
bytes = 48784
compile_seconds = 0.0
samples = 3
seconds = 6.13e-5

[datasets.sc50a.primal]
allocations = 107534
bytes = 4655888
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0027824
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 970
bytes = 234056
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004971
status = "OPTIMAL"

[probes.empty]
allocations = 5
bytes = 272
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[probes.few_artificials]
allocations = 11
bytes = 41544
compile_seconds = 0.0
samples = 3
seconds = 1.19e-5

[probes.many_artificials]
allocations = 12
bytes = 82328
compile_seconds = 0.0
samples = 3
seconds = 1.39e-5
