julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 87788
bytes = 4251728
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033502
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461704
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009598
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 85773
bytes = 3463216
compile_seconds = 0.0
samples = 3
seconds = 0.0020905

[datasets.adlittle.primal]
allocations = 88586
bytes = 4528256
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003725
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607680
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010678
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 19142
bytes = 680312
compile_seconds = 0.0
samples = 3
seconds = 0.0003836

[datasets.afiro.dual]
allocations = 18955
bytes = 937408
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007836
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002045
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18140
bytes = 801728
compile_seconds = 0.0
samples = 3
seconds = 0.0005866

[datasets.afiro.primal]
allocations = 18861
bytes = 914768
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007745
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002003
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2617
bytes = 97144
compile_seconds = 0.0
samples = 3
seconds = 9.97e-5

[datasets.flugpl.dual]
allocations = 34477
bytes = 1398648
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009077
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001147
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33806
bytes = 1288672
compile_seconds = 0.0
samples = 3
seconds = 0.0007521

[datasets.flugpl.primal]
allocations = 34826
bytes = 1443560
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009486
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001525
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3685
bytes = 139776
compile_seconds = 0.0
samples = 3
seconds = 9.51e-5

[datasets.kb2.dual]
allocations = 236863
bytes = 11351528
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0204609
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878288
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008416
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 235661
bytes = 10898440
compile_seconds = 0.0
samples = 3
seconds = 0.0196324

[datasets.kb2.primal]
allocations = 237030
bytes = 11364776
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0199683
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006086
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14699
bytes = 524712
compile_seconds = 0.0
samples = 3
seconds = 0.0002902

[datasets.sc50a.dual]
allocations = 73525
bytes = 3386056
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002107
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306336
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005762
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72453
bytes = 3039400
compile_seconds = 0.0
samples = 3
seconds = 0.0016667

[datasets.sc50a.primal]
allocations = 73470
bytes = 3338776
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021466
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005346
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6663
bytes = 244824
compile_seconds = 0.0
samples = 3
seconds = 0.0001811

[probes.negative]
allocations = 13558
bytes = 481248
compile_seconds = 0.0
samples = 3
seconds = 0.0002173

[probes.negative_unit]
allocations = 9974
bytes = 334704
compile_seconds = 0.0
samples = 3
seconds = 0.0001901

[probes.positive]
allocations = 13558
bytes = 479696
compile_seconds = 0.0
samples = 3
seconds = 0.0002348

[probes.unequal]
allocations = 15094
bytes = 527264
compile_seconds = 0.0
samples = 3
seconds = 0.000252

[probes.unit]
allocations = 8438
bytes = 289152
compile_seconds = 0.0
samples = 3
seconds = 0.0001632
