julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 87788
bytes = 4251744
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035703
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461192
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010133
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 85773
bytes = 3461696
compile_seconds = 0.0
samples = 3
seconds = 0.0024857

[datasets.adlittle.primal]
allocations = 88586
bytes = 4528384
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038259
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607232
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011206
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 19142
bytes = 680360
compile_seconds = 0.0
samples = 3
seconds = 0.0004352

[datasets.afiro.dual]
allocations = 18955
bytes = 936960
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008975
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002216
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18140
bytes = 801008
compile_seconds = 0.0
samples = 3
seconds = 0.000627

[datasets.afiro.primal]
allocations = 18861
bytes = 914224
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008265
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002304
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2617
bytes = 96376
compile_seconds = 0.0
samples = 3
seconds = 0.0001646

[datasets.flugpl.dual]
allocations = 34477
bytes = 1397720
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0012631
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001638
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33806
bytes = 1287808
compile_seconds = 0.0
samples = 3
seconds = 0.0009095

[datasets.flugpl.primal]
allocations = 34826
bytes = 1442632
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011905
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001756
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3685
bytes = 139120
compile_seconds = 0.0
samples = 3
seconds = 0.0001054

[datasets.kb2.dual]
allocations = 236863
bytes = 11351240
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0214866
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008976
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 235661
bytes = 10896024
compile_seconds = 0.0
samples = 3
seconds = 0.0213697

[datasets.kb2.primal]
allocations = 237030
bytes = 11364072
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021604
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006505
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14699
bytes = 524088
compile_seconds = 0.0
samples = 3
seconds = 0.0003346

[datasets.sc50a.dual]
allocations = 73525
bytes = 3385080
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022621
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306240
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005959
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72453
bytes = 3040104
compile_seconds = 0.0
samples = 3
seconds = 0.0018853

[datasets.sc50a.primal]
allocations = 73470
bytes = 3337688
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024811
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0006062
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6663
bytes = 244472
compile_seconds = 0.0
samples = 3
seconds = 0.0001916

[probes.negative]
allocations = 18515
bytes = 656368
compile_seconds = 0.0
samples = 3
seconds = 0.0004203

[probes.positive]
allocations = 18771
bytes = 663408
compile_seconds = 0.0
samples = 3
seconds = 0.0003489

[probes.unequal]
allocations = 30937
bytes = 1110688
compile_seconds = 0.0
samples = 3
seconds = 0.0004837

[probes.unit]
allocations = 13907
bytes = 481968
compile_seconds = 0.0
samples = 3
seconds = 0.000238

[probes.upper_only]
allocations = 21977
bytes = 786960
compile_seconds = 0.0
samples = 3
seconds = 0.0003697
