julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 106159
bytes = 4995672
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003452
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000995
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 104144
bytes = 4206264
compile_seconds = 0.0
samples = 3
seconds = 0.0022404

[datasets.adlittle.primal]
allocations = 106957
bytes = 5272488
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036271
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607216
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011022
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 24409
bytes = 900552
compile_seconds = 0.0
samples = 3
seconds = 0.0004453

[datasets.afiro.dual]
allocations = 25649
bytes = 1193672
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008361
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002025
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 24834
bytes = 1058456
compile_seconds = 0.0
samples = 3
seconds = 0.0006366

[datasets.afiro.primal]
allocations = 25555
bytes = 1171752
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000812
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002056
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 4029
bytes = 154448
compile_seconds = 0.0
samples = 3
seconds = 0.0001204

[datasets.flugpl.dual]
allocations = 38156
bytes = 1543776
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009432
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001204
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 37485
bytes = 1434424
compile_seconds = 0.0
samples = 3
seconds = 0.0007831

[datasets.flugpl.primal]
allocations = 38505
bytes = 1588448
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008911
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001806
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 5017
bytes = 197064
compile_seconds = 0.0
samples = 3
seconds = 0.000115

[datasets.kb2.dual]
allocations = 284027
bytes = 13237728
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0211856
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878288
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007734
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 282825
bytes = 12783584
compile_seconds = 0.0
samples = 3
seconds = 0.0204862

[datasets.kb2.primal]
allocations = 284194
bytes = 13252224
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0216629
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005742
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 20510
bytes = 770440
compile_seconds = 0.0
samples = 3
seconds = 0.0003341

[datasets.sc50a.dual]
allocations = 100709
bytes = 4378880
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0025333
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005816
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 99637
bytes = 4034288
compile_seconds = 0.0
samples = 3
seconds = 0.0019032

[datasets.sc50a.primal]
allocations = 100654
bytes = 4331520
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023683
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004691
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 10592
bytes = 406320
compile_seconds = 0.0
samples = 3
seconds = 0.0002033

[probes.nonzero]
allocations = 22081
bytes = 810464
compile_seconds = 0.0
samples = 3
seconds = 0.000416

[probes.zero]
allocations = 19393
bytes = 712144
compile_seconds = 0.0
samples = 3
seconds = 0.000379
