julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.adlittle.dual]
allocations = 84676
bytes = 4134480
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003454203
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461416
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000967701
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82661
bytes = 3344128
compile_seconds = 0.0
samples = 3
seconds = 0.002189902

[datasets.adlittle.primal]
allocations = 85474
bytes = 4411648
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003867404
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607504
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001202102
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18243
bytes = 647032
compile_seconds = 0.0
samples = 3
seconds = 0.0003869

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.45e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174472
compile_seconds = 0.0
samples = 3
seconds = 0.000116

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.afiro.dual]
allocations = 17057
bytes = 865168
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000717601
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000198102
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16242
bytes = 730512
compile_seconds = 0.0
samples = 3
seconds = 0.000552204

[datasets.afiro.primal]
allocations = 16963
bytes = 843920
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000717401
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000213
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92536
compile_seconds = 0.0
samples = 3
seconds = 9.8301e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 44736
compile_seconds = 0.0
samples = 3
seconds = 7.8201e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214976
compile_seconds = 0.0
samples = 3
seconds = 0.000158001

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.flugpl.dual]
allocations = 31682
bytes = 1291008
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000795501
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001381
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 31011
bytes = 1182536
compile_seconds = 0.0
samples = 3
seconds = 0.0005914

[datasets.flugpl.primal]
allocations = 32031
bytes = 1335712
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008039
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000169
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3297
bytes = 126168
compile_seconds = 0.0
samples = 3
seconds = 8.22e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.27e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209784
compile_seconds = 0.0
samples = 3
seconds = 0.0001135

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.dual]
allocations = 231113
bytes = 11131056
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021170324
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878160
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000872101
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229911
bytes = 10676256
compile_seconds = 0.0
samples = 3
seconds = 0.020888724

[datasets.kb2.primal]
allocations = 231280
bytes = 11144400
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020995424
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000634
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13262
bytes = 472376
compile_seconds = 0.0
samples = 3
seconds = 0.000267401

[datasets.kb2.singleton]
allocations = 2060
bytes = 111856
compile_seconds = 0.0
samples = 3
seconds = 9.6e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161840
compile_seconds = 0.0
samples = 3
seconds = 0.000137701

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 2.11e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3195072
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002015802
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000545301
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2849936
compile_seconds = 0.0
samples = 3
seconds = 0.001546902

[datasets.sc50a.primal]
allocations = 68520
bytes = 3147808
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001914502
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004826
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6064
bytes = 224728
compile_seconds = 0.0
samples = 3
seconds = 0.0001537

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.96e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299328
compile_seconds = 0.0
samples = 3
seconds = 0.000187301

[probes.fraction_negative]
allocations = 61900
bytes = 2142456
compile_seconds = 0.0
samples = 3
seconds = 0.0008984

[probes.fraction_positive]
allocations = 62284
bytes = 2154296
compile_seconds = 0.0
samples = 3
seconds = 0.0008687

[probes.integer_negative]
allocations = 58060
bytes = 1982856
compile_seconds = 0.0
samples = 3
seconds = 0.000923

[probes.integer_positive]
allocations = 57164
bytes = 1955928
compile_seconds = 0.0
samples = 3
seconds = 0.0007409

[probes.unbounded]
allocations = 9635
bytes = 312128
compile_seconds = 0.0
samples = 3
seconds = 0.0001627

[probes.unequal_denominator]
allocations = 41292
bytes = 1479688
compile_seconds = 0.0
samples = 3
seconds = 0.000622301
