julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 88034
bytes = 4261856
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003832301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461320
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001007
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 86019
bytes = 3471072
compile_seconds = 0.0
samples = 3
seconds = 0.0025709

[datasets.adlittle.primal]
allocations = 88832
bytes = 4539072
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003587
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607456
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010948
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 19298
bytes = 686464
compile_seconds = 0.0
samples = 3
seconds = 0.0004

[datasets.afiro.dual]
allocations = 18973
bytes = 937344
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008076
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002283
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18158
bytes = 802416
compile_seconds = 0.0
samples = 3
seconds = 0.00065

[datasets.afiro.primal]
allocations = 18879
bytes = 915904
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009691
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002336
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2692
bytes = 99504
compile_seconds = 0.0
samples = 3
seconds = 0.0001067

[datasets.flugpl.dual]
allocations = 34540
bytes = 1400968
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010519
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001588
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33869
bytes = 1291088
compile_seconds = 0.0
samples = 3
seconds = 0.0008404

[datasets.flugpl.primal]
allocations = 34889
bytes = 1445272
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010759
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000203
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3742
bytes = 141416
compile_seconds = 0.0
samples = 3
seconds = 0.0001352

[datasets.kb2.dual]
allocations = 237007
bytes = 11354856
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.023478101
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009393
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 235805
bytes = 10901944
compile_seconds = 0.0
samples = 3
seconds = 0.022868401

[datasets.kb2.primal]
allocations = 237174
bytes = 11367592
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021866501
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000686101
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14843
bytes = 529288
compile_seconds = 0.0
samples = 3
seconds = 0.0002979

[datasets.sc50a.dual]
allocations = 73561
bytes = 3388680
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002380901
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306384
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006217
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72489
bytes = 3042552
compile_seconds = 0.0
samples = 3
seconds = 0.0017777

[datasets.sc50a.primal]
allocations = 73506
bytes = 3341272
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022464
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000514
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6843
bytes = 250312
compile_seconds = 0.0
samples = 3
seconds = 0.0001753

[probes.equal]
allocations = 15443
bytes = 528480
compile_seconds = 0.0
samples = 3
seconds = 0.0002922

[probes.negative]
allocations = 30681
bytes = 1102976
compile_seconds = 0.0
samples = 3
seconds = 0.0004943

[probes.positive]
allocations = 30937
bytes = 1109104
compile_seconds = 0.0
samples = 3
seconds = 0.0004812

[probes.tightening]
allocations = 19141
bytes = 707648
compile_seconds = 0.0
samples = 3
seconds = 0.0003912

[probes.unit]
allocations = 21209
bytes = 746768
compile_seconds = 0.0
samples = 3
seconds = 0.000376
