julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.adlittle.dual]
allocations = 84550
bytes = 4122664
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.002931009
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461064
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000918002
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82535
bytes = 3333064
compile_seconds = 0.0
samples = 3
seconds = 0.001753906

[datasets.adlittle.primal]
allocations = 85348
bytes = 4399432
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.00346801
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607024
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001061204
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18219
bytes = 643464
compile_seconds = 0.0
samples = 3
seconds = 0.000327601

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.06e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174728
compile_seconds = 0.0
samples = 3
seconds = 9.67e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 863992
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000784702
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000211201
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 728824
compile_seconds = 0.0
samples = 3
seconds = 0.0006328

[datasets.afiro.primal]
allocations = 16938
bytes = 842424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000711602
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121808
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002465
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92392
compile_seconds = 0.0
samples = 3
seconds = 9.16e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 45024
compile_seconds = 0.0
samples = 3
seconds = 0.0001141

[datasets.afiro.sparse]
allocations = 4891
bytes = 214720
compile_seconds = 0.0
samples = 3
seconds = 0.0001616

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.flugpl.dual]
allocations = 31518
bytes = 1281736
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008798
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001052
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30847
bytes = 1172272
compile_seconds = 0.0
samples = 3
seconds = 0.000628601

[datasets.flugpl.primal]
allocations = 31867
bytes = 1326040
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000830101
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001775
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3257
bytes = 123792
compile_seconds = 0.0
samples = 3
seconds = 8.98e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.5e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210952
compile_seconds = 0.0
samples = 3
seconds = 0.0001221

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 230698
bytes = 11106864
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02019556
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878192
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000862502
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229496
bytes = 10654528
compile_seconds = 0.0
samples = 3
seconds = 0.01995726

[datasets.kb2.primal]
allocations = 230865
bytes = 11120448
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.01984656
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000593901
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13096
bytes = 461280
compile_seconds = 0.0
samples = 3
seconds = 0.0002389

[datasets.kb2.singleton]
allocations = 2060
bytes = 112288
compile_seconds = 0.0
samples = 3
seconds = 9.32e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162112
compile_seconds = 0.0
samples = 3
seconds = 9.69e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.36e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.sc50a.dual]
allocations = 68545
bytes = 3194008
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002077806
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306352
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000545601
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67473
bytes = 2848456
compile_seconds = 0.0
samples = 3
seconds = 0.001503404

[datasets.sc50a.primal]
allocations = 68490
bytes = 3146904
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001655201
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000498101
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6044
bytes = 223888
compile_seconds = 0.0
samples = 3
seconds = 0.0001154

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.35e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299936
compile_seconds = 0.0
samples = 3
seconds = 0.000187901

[probes.fraction_negative_lower]
allocations = 33868
bytes = 1210728
compile_seconds = 0.0
samples = 3
seconds = 0.000521105

[probes.fraction_negative_upper]
allocations = 34124
bytes = 1218728
compile_seconds = 0.0
samples = 3
seconds = 0.000518205

[probes.fraction_positive_lower]
allocations = 34124
bytes = 1218968
compile_seconds = 0.0
samples = 3
seconds = 0.000477805

[probes.fraction_positive_upper]
allocations = 34124
bytes = 1218856
compile_seconds = 0.0
samples = 3
seconds = 0.000476005

[probes.integer_negative_lower]
allocations = 32844
bytes = 1156328
compile_seconds = 0.0
samples = 3
seconds = 0.000496005

[probes.integer_negative_upper]
allocations = 33100
bytes = 1164520
compile_seconds = 0.0
samples = 3
seconds = 0.000551706

[probes.integer_positive_lower]
allocations = 33100
bytes = 1164600
compile_seconds = 0.0
samples = 3
seconds = 0.000636107

[probes.integer_positive_upper]
allocations = 33100
bytes = 1162904
compile_seconds = 0.0
samples = 3
seconds = 0.000644707

[probes.unequal_denominator]
allocations = 35148
bytes = 1229672
compile_seconds = 0.0
samples = 3
seconds = 0.000577206

[probes.unit_coefficient]
allocations = 24268
bytes = 852984
compile_seconds = 0.0
samples = 3
seconds = 0.000412004
