julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4116056
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003764208
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000924402
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326584
compile_seconds = 0.0
samples = 3
seconds = 0.002349705

[datasets.adlittle.primal]
allocations = 85246
bytes = 4392024
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003612307
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001082702
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641704
compile_seconds = 0.0
samples = 3
seconds = 0.000470101

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.61e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174376
compile_seconds = 0.0
samples = 3
seconds = 0.0001293

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 863544
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000974902
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000209001
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 728952
compile_seconds = 0.0
samples = 3
seconds = 0.000687901

[datasets.afiro.primal]
allocations = 16938
bytes = 841784
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000776702
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002024
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92536
compile_seconds = 0.0
samples = 3
seconds = 0.0001051

[datasets.afiro.singleton]
allocations = 843
bytes = 45056
compile_seconds = 0.0
samples = 3
seconds = 8.14e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214800
compile_seconds = 0.0
samples = 3
seconds = 0.0001902

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 8.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279112
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001025402
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001138
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169776
compile_seconds = 0.0
samples = 3
seconds = 0.000802301

[datasets.flugpl.primal]
allocations = 31811
bytes = 1323896
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001073901
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001922
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123056
compile_seconds = 0.0
samples = 3
seconds = 8.62e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.58e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209560
compile_seconds = 0.0
samples = 3
seconds = 0.000146

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11090896
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021754442
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000899902
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10639296
compile_seconds = 0.0
samples = 3
seconds = 0.020032239

[datasets.kb2.primal]
allocations = 230563
bytes = 11103680
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023563426
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000650601
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454608
compile_seconds = 0.0
samples = 3
seconds = 0.0002798

[datasets.kb2.singleton]
allocations = 2060
bytes = 112272
compile_seconds = 0.0
samples = 3
seconds = 7.54e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161824
compile_seconds = 0.0
samples = 3
seconds = 0.0001393

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.7e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3192088
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002087703
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306304
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006116
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846184
compile_seconds = 0.0
samples = 3
seconds = 0.001533402

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144280
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002332103
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000617801
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222016
compile_seconds = 0.0
samples = 3
seconds = 0.0001848

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299376
compile_seconds = 0.0
samples = 3
seconds = 0.0002417

[probes.cancelled_fraction]
allocations = 43212
bytes = 1452808
compile_seconds = 0.0
samples = 3
seconds = 0.000657301

[probes.cancelled_integer]
allocations = 31948
bytes = 1039496
compile_seconds = 0.0
samples = 3
seconds = 0.0005389

[probes.fixed_fraction]
allocations = 22215
bytes = 750872
compile_seconds = 0.0
samples = 3
seconds = 0.0003841

[probes.fixed_integer]
allocations = 17863
bytes = 616584
compile_seconds = 0.0
samples = 3
seconds = 0.0003615

[probes.nonfixed]
allocations = 53580
bytes = 1779032
compile_seconds = 0.0
samples = 3
seconds = 0.000788701

[probes.prefix_fraction]
allocations = 55756
bytes = 1866024
compile_seconds = 0.0
samples = 3
seconds = 0.000866401

[probes.prefix_integer]
allocations = 49356
bytes = 1630776
compile_seconds = 0.0
samples = 3
seconds = 0.000897301

[probes.unbounded]
allocations = 9635
bytes = 312608
compile_seconds = 0.0
samples = 3
seconds = 0.0001965
