julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 87777
bytes = 4252272
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003235899
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461592
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009324
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 85762
bytes = 3462160
compile_seconds = 0.0
samples = 3
seconds = 0.0019364

[datasets.adlittle.primal]
allocations = 88575
bytes = 4528464
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033971
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607104
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001072
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 19142
bytes = 680760
compile_seconds = 0.0
samples = 3
seconds = 0.000377

[datasets.afiro.dual]
allocations = 18955
bytes = 936368
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000783
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001978
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18140
bytes = 801008
compile_seconds = 0.0
samples = 3
seconds = 0.0005691

[datasets.afiro.primal]
allocations = 18861
bytes = 915008
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007278
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001648
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2617
bytes = 97608
compile_seconds = 0.0
samples = 3
seconds = 0.0001056

[datasets.flugpl.dual]
allocations = 34389
bytes = 1394728
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008095
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001529
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33718
bytes = 1284848
compile_seconds = 0.0
samples = 3
seconds = 0.000649199

[datasets.flugpl.primal]
allocations = 34738
bytes = 1439064
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008281
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001533
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3655
bytes = 139120
compile_seconds = 0.0
samples = 3
seconds = 9.68e-5

[datasets.kb2.dual]
allocations = 236863
bytes = 11350600
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020099999
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878016
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008079
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 235661
bytes = 10895160
compile_seconds = 0.0
samples = 3
seconds = 0.0199473

[datasets.kb2.primal]
allocations = 237030
bytes = 11363240
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020472199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260880
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005977
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14699
bytes = 525672
compile_seconds = 0.0
samples = 3
seconds = 0.0002709

[datasets.sc50a.dual]
allocations = 73525
bytes = 3385256
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020483
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306336
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005677
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72453
bytes = 3040472
compile_seconds = 0.0
samples = 3
seconds = 0.0015595

[datasets.sc50a.primal]
allocations = 73470
bytes = 3337720
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020202
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005265
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6663
bytes = 245096
compile_seconds = 0.0
samples = 3
seconds = 0.0001631

[probes.equality]
allocations = 7877
bytes = 334160
compile_seconds = 0.0
samples = 3
seconds = 0.0001753

[probes.lower_only]
allocations = 6082
bytes = 248616
compile_seconds = 0.0
samples = 3
seconds = 0.0001504

[probes.nonzero]
allocations = 12997
bytes = 502192
compile_seconds = 0.0
samples = 3
seconds = 0.0002662

[probes.unbounded]
allocations = 2494
bytes = 102128
compile_seconds = 0.0
samples = 3
seconds = 7.43e-5

[probes.upper_only]
allocations = 6082
bytes = 249704
compile_seconds = 0.0
samples = 3
seconds = 0.0001416
