julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85688
bytes = 4169208
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035153
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461224
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009798
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83673
bytes = 3379528
compile_seconds = 0.0
samples = 3
seconds = 0.0021798

[datasets.adlittle.primal]
allocations = 86486
bytes = 4445032
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037416
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607808
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010563
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18243
bytes = 646392
compile_seconds = 0.0
samples = 3
seconds = 0.0004276

[datasets.afiro.dual]
allocations = 18436
bytes = 918288
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008109
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002755
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17621
bytes = 782320
compile_seconds = 0.0
samples = 3
seconds = 0.0006384

[datasets.afiro.primal]
allocations = 18342
bytes = 896576
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008221
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002466
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 90808
compile_seconds = 0.0
samples = 3
seconds = 0.0001118

[datasets.flugpl.dual]
allocations = 33810
bytes = 1374560
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010117
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001659
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33139
bytes = 1264632
compile_seconds = 0.0
samples = 3
seconds = 0.0008497

[datasets.flugpl.primal]
allocations = 34159
bytes = 1419072
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011084
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002077
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3297
bytes = 124552
compile_seconds = 0.0
samples = 3
seconds = 0.0001266

[datasets.kb2.dual]
allocations = 233293
bytes = 11211544
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0215969
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877952
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008512
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 232091
bytes = 10759352
compile_seconds = 0.0
samples = 3
seconds = 0.0211953

[datasets.kb2.primal]
allocations = 233460
bytes = 11226152
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0214336
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260928
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006514
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13262
bytes = 470152
compile_seconds = 0.0
samples = 3
seconds = 0.0003543

[datasets.sc50a.dual]
allocations = 73155
bytes = 3375432
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022583
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000576
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72083
bytes = 3028504
compile_seconds = 0.0
samples = 3
seconds = 0.0017006

[datasets.sc50a.primal]
allocations = 73100
bytes = 3327688
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024729
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005475
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6064
bytes = 223896
compile_seconds = 0.0
samples = 3
seconds = 0.0001733

[probes.negative]
allocations = 14167
bytes = 544744
compile_seconds = 0.0
samples = 3
seconds = 0.0003117

[probes.positive]
allocations = 14295
bytes = 547736
compile_seconds = 0.0
samples = 3
seconds = 0.0003551

[probes.unequal]
allocations = 17623
bytes = 668872
compile_seconds = 0.0
samples = 3
seconds = 0.000372

[probes.unit]
allocations = 11991
bytes = 461608
compile_seconds = 0.0
samples = 3
seconds = 0.0002849

[probes.zero_other]
allocations = 14036
bytes = 533552
compile_seconds = 0.0
samples = 3
seconds = 0.0003155
