julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 97990
bytes = 4665560
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032988
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461224
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008784
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 95975
bytes = 3877160
compile_seconds = 0.0
samples = 3
seconds = 0.0021818

[datasets.adlittle.primal]
allocations = 98788
bytes = 4942648
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037246
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607584
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011005
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20928
bytes = 761048
compile_seconds = 0.0
samples = 3
seconds = 0.0003907

[datasets.afiro.dual]
allocations = 24191
bytes = 1134400
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008804
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000218
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 23376
bytes = 999136
compile_seconds = 0.0
samples = 3
seconds = 0.0006556

[datasets.afiro.primal]
allocations = 24097
bytes = 1113264
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007892
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002137
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 3094
bytes = 114576
compile_seconds = 0.0
samples = 3
seconds = 0.0001065

[datasets.flugpl.dual]
allocations = 37245
bytes = 1510424
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009451
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001524
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 36574
bytes = 1400784
compile_seconds = 0.0
samples = 3
seconds = 0.0007072

[datasets.flugpl.primal]
allocations = 37594
bytes = 1554984
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009445
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001917
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4605
bytes = 182040
compile_seconds = 0.0
samples = 3
seconds = 0.0001294

[datasets.kb2.dual]
allocations = 277469
bytes = 12969192
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0205923
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878528
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008543
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 276267
bytes = 12517272
compile_seconds = 0.0
samples = 3
seconds = 0.0201542

[datasets.kb2.primal]
allocations = 277636
bytes = 12983512
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0212028
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000605
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 17434
bytes = 642792
compile_seconds = 0.0
samples = 3
seconds = 0.0003072

[datasets.sc50a.dual]
allocations = 98706
bytes = 4298096
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024941
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005622
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 97634
bytes = 3951968
compile_seconds = 0.0
samples = 3
seconds = 0.0018705

[datasets.sc50a.primal]
allocations = 98651
bytes = 4250864
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023191
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005165
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 8521
bytes = 318864
compile_seconds = 0.0
samples = 3
seconds = 0.0001757

[probes.both]
allocations = 29781
bytes = 1103696
compile_seconds = 0.0
samples = 3
seconds = 0.0004721

[probes.lower]
allocations = 21845
bytes = 795504
compile_seconds = 0.0
samples = 3
seconds = 0.0003588

[probes.upper]
allocations = 21845
bytes = 793760
compile_seconds = 0.0
samples = 3
seconds = 0.0004779
