julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85688
bytes = 4171464
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003163
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461688
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009178
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83673
bytes = 3382392
compile_seconds = 0.0
samples = 3
seconds = 0.0019712

[datasets.adlittle.primal]
allocations = 86486
bytes = 4448872
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035422
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607584
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010766
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18243
bytes = 645704
compile_seconds = 0.0
samples = 3
seconds = 0.0003841

[datasets.afiro.dual]
allocations = 18436
bytes = 918160
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007645
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002062
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17621
bytes = 781600
compile_seconds = 0.0
samples = 3
seconds = 0.0005648

[datasets.afiro.primal]
allocations = 18342
bytes = 896192
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007123
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002142
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 90504
compile_seconds = 0.0
samples = 3
seconds = 9.05e-5

[datasets.flugpl.dual]
allocations = 33810
bytes = 1374160
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008949
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001663
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33139
bytes = 1263928
compile_seconds = 0.0
samples = 3
seconds = 0.0007021

[datasets.flugpl.primal]
allocations = 34159
bytes = 1418576
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009364
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001903
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3297
bytes = 125224
compile_seconds = 0.0
samples = 3
seconds = 0.0001082

[datasets.kb2.dual]
allocations = 233293
bytes = 11214248
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020642199
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000866
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 232091
bytes = 10758024
compile_seconds = 0.0
samples = 3
seconds = 0.020361199

[datasets.kb2.primal]
allocations = 233460
bytes = 11227176
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020115199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006037
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13262
bytes = 470024
compile_seconds = 0.0
samples = 3
seconds = 0.00027

[datasets.sc50a.dual]
allocations = 73155
bytes = 3374360
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021463
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306096
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005342
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72083
bytes = 3028952
compile_seconds = 0.0
samples = 3
seconds = 0.0015732

[datasets.sc50a.primal]
allocations = 73100
bytes = 3327640
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022446
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004779
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6064
bytes = 224232
compile_seconds = 0.0
samples = 3
seconds = 0.0001632

[probes.maximum]
allocations = 36175
bytes = 1287792
compile_seconds = 0.0
samples = 3
seconds = 0.0006029

[probes.minimum]
allocations = 36303
bytes = 1289856
compile_seconds = 0.0
samples = 3
seconds = 0.0006424

[probes.nonzero]
allocations = 36303
bytes = 1291568
compile_seconds = 0.0
samples = 3
seconds = 0.000581

[probes.unbounded]
allocations = 22860
bytes = 816040
compile_seconds = 0.0
samples = 3
seconds = 0.000393

[probes.unit]
allocations = 31311
bytes = 1079136
compile_seconds = 0.0
samples = 3
seconds = 0.0005471
