julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.adlittle.dual]
allocations = 84647
bytes = 4128808
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033317
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009788
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82632
bytes = 3339896
compile_seconds = 0.0
samples = 3
seconds = 0.0021351

[datasets.adlittle.primal]
allocations = 85445
bytes = 4405272
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033289
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607376
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001087799
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18234
bytes = 645992
compile_seconds = 0.0
samples = 3
seconds = 0.000339

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.22e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174984
compile_seconds = 0.0
samples = 3
seconds = 0.0001309

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.afiro.dual]
allocations = 17044
bytes = 865712
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008165
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002124
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16229
bytes = 729984
compile_seconds = 0.0
samples = 3
seconds = 0.0006494

[datasets.afiro.primal]
allocations = 16950
bytes = 844000
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006987
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.00022
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93496
compile_seconds = 0.0
samples = 3
seconds = 9.89e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 45616
compile_seconds = 0.0
samples = 3
seconds = 9.63e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 215792
compile_seconds = 0.0
samples = 3
seconds = 0.0001705

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.flugpl.dual]
allocations = 31630
bytes = 1290040
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.00089
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001506
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30959
bytes = 1179424
compile_seconds = 0.0
samples = 3
seconds = 0.0006211

[datasets.flugpl.primal]
allocations = 31979
bytes = 1334696
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009535
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002049
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3283
bytes = 125944
compile_seconds = 0.0
samples = 3
seconds = 9.33e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.75e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 211368
compile_seconds = 0.0
samples = 3
seconds = 0.0001296

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.dual]
allocations = 230923
bytes = 11118648
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020146299
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007897
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229721
bytes = 10665496
compile_seconds = 0.0
samples = 3
seconds = 0.0197437

[datasets.kb2.primal]
allocations = 231090
bytes = 11132488
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0213308
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006356
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13194
bytes = 468088
compile_seconds = 0.0
samples = 3
seconds = 0.0002775

[datasets.kb2.singleton]
allocations = 2060
bytes = 112224
compile_seconds = 0.0
samples = 3
seconds = 9.07e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162480
compile_seconds = 0.0
samples = 3
seconds = 0.0001234

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.83e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3194944
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021042
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306272
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005647
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2849248
compile_seconds = 0.0
samples = 3
seconds = 0.0014208

[datasets.sc50a.primal]
allocations = 68520
bytes = 3147584
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020398
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005086
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6058
bytes = 225416
compile_seconds = 0.0
samples = 3
seconds = 0.0001547

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.37e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 300176
compile_seconds = 0.0
samples = 3
seconds = 0.0001879

[probes.cancel_fraction]
allocations = 45004
bytes = 1528104
compile_seconds = 0.0
samples = 3
seconds = 0.0007339

[probes.cancel_integer]
allocations = 33996
bytes = 1118840
compile_seconds = 0.0
samples = 3
seconds = 0.0006119

[probes.fraction_negative]
allocations = 61132
bytes = 2073432
compile_seconds = 0.0
samples = 3
seconds = 0.0009217

[probes.fraction_positive]
allocations = 61516
bytes = 2085880
compile_seconds = 0.0
samples = 3
seconds = 0.0009446

[probes.integer_negative]
allocations = 56524
bytes = 1900440
compile_seconds = 0.0
samples = 3
seconds = 0.0009917

[probes.integer_positive]
allocations = 55628
bytes = 1873400
compile_seconds = 0.0
samples = 3
seconds = 0.0009454

[probes.unbounded]
allocations = 9635
bytes = 312032
compile_seconds = 0.0
samples = 3
seconds = 0.0002075

[probes.unequal_denominator]
allocations = 34124
bytes = 1189176
compile_seconds = 0.0
samples = 3
seconds = 0.0004852
