julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119556
bytes = 5521400
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.00357
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461528
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009271
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117541
bytes = 4731864
compile_seconds = 0.0
samples = 3
seconds = 0.0024482

[datasets.adlittle.primal]
allocations = 120354
bytes = 5797816
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0039037
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607088
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011391
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 30628
bytes = 1148200
compile_seconds = 0.0
samples = 3
seconds = 0.0004799

[datasets.afiro.dual]
allocations = 27432
bytes = 1265304
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008691
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002078
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26617
bytes = 1129656
compile_seconds = 0.0
samples = 3
seconds = 0.0006206

[datasets.afiro.primal]
allocations = 27338
bytes = 1243976
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007723
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002095
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 5090
bytes = 199168
compile_seconds = 0.0
samples = 3
seconds = 0.0001126

[datasets.flugpl.dual]
allocations = 39596
bytes = 1601536
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009034
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001546
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38925
bytes = 1491512
compile_seconds = 0.0
samples = 3
seconds = 0.000737

[datasets.flugpl.primal]
allocations = 39945
bytes = 1645824
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008787
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001835
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 5787
bytes = 228504
compile_seconds = 0.0
samples = 3
seconds = 0.0001327

[datasets.kb2.dual]
allocations = 292761
bytes = 13577296
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0209737
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878320
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007592
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291559
bytes = 13123936
compile_seconds = 0.0
samples = 3
seconds = 0.0211829

[datasets.kb2.primal]
allocations = 292928
bytes = 13590816
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0208551
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000589
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 24781
bytes = 938536
compile_seconds = 0.0
samples = 3
seconds = 0.0003838

[datasets.sc50a.dual]
allocations = 102738
bytes = 4462272
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002349
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306304
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0004991
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101666
bytes = 4118064
compile_seconds = 0.0
samples = 3
seconds = 0.0018851

[datasets.sc50a.primal]
allocations = 102683
bytes = 4414720
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023519
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004835
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 12939
bytes = 500336
compile_seconds = 0.0
samples = 3
seconds = 0.000223

[probes.nonunit]
allocations = 17132
bytes = 615904
compile_seconds = 0.0
samples = 3
seconds = 0.0002562

[probes.unit]
allocations = 17132
bytes = 614784
compile_seconds = 0.0
samples = 3
seconds = 0.0002586
