julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 117014
bytes = 5420072
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003883
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461752
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008856
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 114999
bytes = 4630232
compile_seconds = 0.0
samples = 3
seconds = 0.0022208

[datasets.adlittle.primal]
allocations = 117812
bytes = 5696488
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003763099
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607536
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011178
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 29716
bytes = 1109720
compile_seconds = 0.0
samples = 3
seconds = 0.000479

[datasets.afiro.dual]
allocations = 27174
bytes = 1253432
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008733
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001996
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26359
bytes = 1117784
compile_seconds = 0.0
samples = 3
seconds = 0.0008249

[datasets.afiro.primal]
allocations = 27080
bytes = 1232136
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007899
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001817
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 4842
bytes = 188032
compile_seconds = 0.0
samples = 3
seconds = 0.0001863

[datasets.flugpl.dual]
allocations = 39110
bytes = 1580944
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009322
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001492
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38439
bytes = 1471640
compile_seconds = 0.0
samples = 3
seconds = 0.0007552

[datasets.flugpl.primal]
allocations = 39459
bytes = 1625424
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009108
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001831
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 5591
bytes = 220200
compile_seconds = 0.0
samples = 3
seconds = 0.0001344

[datasets.kb2.dual]
allocations = 291795
bytes = 13538096
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020913398
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878208
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008205
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 290593
bytes = 13086912
compile_seconds = 0.0
samples = 3
seconds = 0.020162599

[datasets.kb2.primal]
allocations = 291962
bytes = 13552096
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021483899
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006215
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 24193
bytes = 914152
compile_seconds = 0.0
samples = 3
seconds = 0.0003892

[datasets.sc50a.dual]
allocations = 102328
bytes = 4445984
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022937
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005508
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101256
bytes = 4100848
compile_seconds = 0.0
samples = 3
seconds = 0.0019227

[datasets.sc50a.primal]
allocations = 102273
bytes = 4398368
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002348799
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005093
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 12521
bytes = 482576
compile_seconds = 0.0
samples = 3
seconds = 0.0002166

[probes.nonunit]
allocations = 26049
bytes = 974128
compile_seconds = 0.0
samples = 3
seconds = 0.000405

[probes.unit]
allocations = 23745
bytes = 882016
compile_seconds = 0.0
samples = 3
seconds = 0.0003938
