julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 84554
bytes = 4119864
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.00316831
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461528
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000861803
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82539
bytes = 3330696
compile_seconds = 0.0
samples = 3
seconds = 0.001891806

[datasets.adlittle.primal]
allocations = 85352
bytes = 4396488
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003669512
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607408
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001061204
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18219
bytes = 643544
compile_seconds = 0.0
samples = 3
seconds = 0.000354201

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 4.38e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174520
compile_seconds = 0.0
samples = 3
seconds = 0.000102401

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.4e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 863432
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000805103
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000221501
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 728760
compile_seconds = 0.0
samples = 3
seconds = 0.000583002

[datasets.afiro.primal]
allocations = 16938
bytes = 841960
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000685302
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000198401
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93496
compile_seconds = 0.0
samples = 3
seconds = 9.77e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 45440
compile_seconds = 0.0
samples = 3
seconds = 7.66e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 215296
compile_seconds = 0.0
samples = 3
seconds = 0.0001713

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.dual]
allocations = 31564
bytes = 1284768
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007739
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001494
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30893
bytes = 1174968
compile_seconds = 0.0
samples = 3
seconds = 0.00066911

[datasets.flugpl.primal]
allocations = 31913
bytes = 1329312
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007944
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001717
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3269
bytes = 124720
compile_seconds = 0.0
samples = 3
seconds = 9.8302e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.83e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210680
compile_seconds = 0.0
samples = 3
seconds = 0.000116902

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.kb2.dual]
allocations = 230698
bytes = 11104896
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020308766
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000819603
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229496
bytes = 10652192
compile_seconds = 0.0
samples = 3
seconds = 0.019144463

[datasets.kb2.primal]
allocations = 230865
bytes = 11118176
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020254097
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005841
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13096
bytes = 460464
compile_seconds = 0.0
samples = 3
seconds = 0.000282501

[datasets.kb2.singleton]
allocations = 2060
bytes = 112128
compile_seconds = 0.0
samples = 3
seconds = 9.0501e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162176
compile_seconds = 0.0
samples = 3
seconds = 8.8201e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.63e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.sc50a.dual]
allocations = 68553
bytes = 3192968
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.00198533
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000581508
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67481
bytes = 2847384
compile_seconds = 0.0
samples = 3
seconds = 0.001469622

[datasets.sc50a.primal]
allocations = 68498
bytes = 3145768
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002040531
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000570608
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6056
bytes = 224112
compile_seconds = 0.0
samples = 3
seconds = 0.000121702

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.33e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299552
compile_seconds = 0.0
samples = 3
seconds = 0.000167302

[probes.fraction_negative_lower]
allocations = 31692
bytes = 1123464
compile_seconds = 0.0
samples = 3
seconds = 0.0005218

[probes.fraction_negative_upper]
allocations = 31948
bytes = 1131864
compile_seconds = 0.0
samples = 3
seconds = 0.0005152

[probes.fraction_positive_lower]
allocations = 31948
bytes = 1131896
compile_seconds = 0.0
samples = 3
seconds = 0.000531601

[probes.fraction_positive_upper]
allocations = 31948
bytes = 1131784
compile_seconds = 0.0
samples = 3
seconds = 0.0005211

[probes.integer_negative_lower]
allocations = 27212
bytes = 953992
compile_seconds = 0.0
samples = 3
seconds = 0.0004934

[probes.integer_negative_upper]
allocations = 27468
bytes = 962168
compile_seconds = 0.0
samples = 3
seconds = 0.0004987

[probes.integer_positive_lower]
allocations = 26444
bytes = 931928
compile_seconds = 0.0
samples = 3
seconds = 0.0005305

[probes.integer_positive_upper]
allocations = 26444
bytes = 931048
compile_seconds = 0.0
samples = 3
seconds = 0.000483401

[probes.unequal_denominator]
allocations = 31052
bytes = 1046248
compile_seconds = 0.0
samples = 3
seconds = 0.0005432

[probes.zero_endpoint]
allocations = 26572
bytes = 934152
compile_seconds = 0.0
samples = 3
seconds = 0.000480001
