julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90733
bytes = 4406088
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033224
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009864
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88718
bytes = 3616968
compile_seconds = 0.0
samples = 3
seconds = 0.0022061

[datasets.adlittle.primal]
allocations = 91531
bytes = 4682920
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003488902
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607232
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010915
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20352
bytes = 742984
compile_seconds = 0.0
samples = 3
seconds = 0.0003943

[datasets.afiro.dual]
allocations = 19382
bytes = 957912
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008198
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002185
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18567
bytes = 821864
compile_seconds = 0.0
samples = 3
seconds = 0.0005972

[datasets.afiro.primal]
allocations = 19288
bytes = 936312
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007695
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000196
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2781
bytes = 104480
compile_seconds = 0.0
samples = 3
seconds = 9.75e-5

[datasets.flugpl.dual]
allocations = 35363
bytes = 1444488
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001018001
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001449
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34692
bytes = 1333760
compile_seconds = 0.0
samples = 3
seconds = 0.0006832

[datasets.flugpl.primal]
allocations = 35712
bytes = 1488760
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000893001
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001847
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4211
bytes = 166936
compile_seconds = 0.0
samples = 3
seconds = 0.0001248

[datasets.kb2.dual]
allocations = 241354
bytes = 11569008
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02088891
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008024
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 240152
bytes = 11117328
compile_seconds = 0.0
samples = 3
seconds = 0.02052911

[datasets.kb2.primal]
allocations = 241521
bytes = 11581952
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.02081111
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000608901
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16258
bytes = 601624
compile_seconds = 0.0
samples = 3
seconds = 0.000314

[datasets.sc50a.dual]
allocations = 73796
bytes = 3397016
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002029801
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306336
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000544401
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72724
bytes = 3052808
compile_seconds = 0.0
samples = 3
seconds = 0.001449401

[datasets.sc50a.primal]
allocations = 73741
bytes = 3349848
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002079401
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005386
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 7468
bytes = 279688
compile_seconds = 0.0
samples = 3
seconds = 0.0001801

[probes.negative]
allocations = 10821
bytes = 451088
compile_seconds = 0.0
samples = 3
seconds = 0.0002256

[probes.negative_unit]
allocations = 9541
bytes = 387632
compile_seconds = 0.0
samples = 3
seconds = 0.000198

[probes.nonzero]
allocations = 12997
bytes = 503696
compile_seconds = 0.0
samples = 3
seconds = 0.0002435

[probes.positive]
allocations = 10949
bytes = 454192
compile_seconds = 0.0
samples = 3
seconds = 0.0002491

[probes.unit]
allocations = 9157
bytes = 376928
compile_seconds = 0.0
samples = 3
seconds = 0.000176001
