julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90665
bytes = 4403768
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003756801
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010114
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88650
bytes = 3615256
compile_seconds = 0.0
samples = 3
seconds = 0.002268201

[datasets.adlittle.primal]
allocations = 91463
bytes = 4680728
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003828501
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607616
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012222
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20329
bytes = 741032
compile_seconds = 0.0
samples = 3
seconds = 0.0004582

[datasets.afiro.dual]
allocations = 19278
bytes = 953640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008863
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002218
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18463
bytes = 815880
compile_seconds = 0.0
samples = 3
seconds = 0.0007467

[datasets.afiro.primal]
allocations = 19184
bytes = 930792
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008499
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002075
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2737
bytes = 101400
compile_seconds = 0.0
samples = 3
seconds = 0.0001162

[datasets.flugpl.dual]
allocations = 35219
bytes = 1438136
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0011029
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001454
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34548
bytes = 1327056
compile_seconds = 0.0
samples = 3
seconds = 0.000819001

[datasets.flugpl.primal]
allocations = 35568
bytes = 1482552
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010891
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002112
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4131
bytes = 161496
compile_seconds = 0.0
samples = 3
seconds = 0.0001413

[datasets.kb2.dual]
allocations = 241058
bytes = 11558208
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021576502
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877952
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000879301
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 239856
bytes = 11106240
compile_seconds = 0.0
samples = 3
seconds = 0.021739903

[datasets.kb2.primal]
allocations = 241225
bytes = 11571600
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021547402
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006531
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16075
bytes = 593064
compile_seconds = 0.0
samples = 3
seconds = 0.0003309

[datasets.sc50a.dual]
allocations = 73676
bytes = 3394240
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022269
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000607001
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72604
bytes = 3048928
compile_seconds = 0.0
samples = 3
seconds = 0.001747

[datasets.sc50a.primal]
allocations = 73621
bytes = 3346960
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023442
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005544
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 7196
bytes = 268776
compile_seconds = 0.0
samples = 3
seconds = 0.0002075

[probes.free]
allocations = 10693
bytes = 414592
compile_seconds = 0.0
samples = 3
seconds = 0.0002988

[probes.negative]
allocations = 19013
bytes = 703248
compile_seconds = 0.0
samples = 3
seconds = 0.0003917

[probes.positive]
allocations = 19141
bytes = 705840
compile_seconds = 0.0
samples = 3
seconds = 0.000428

[probes.unequal]
allocations = 38617
bytes = 1443696
compile_seconds = 0.0
samples = 3
seconds = 0.0006806

[probes.unit]
allocations = 14277
bytes = 524720
compile_seconds = 0.0
samples = 3
seconds = 0.0003543
