julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90665
bytes = 4405176
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003281
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461528
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009513
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88650
bytes = 3614984
compile_seconds = 0.0
samples = 3
seconds = 0.0020676

[datasets.adlittle.primal]
allocations = 91463
bytes = 4681336
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034662
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607472
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001220799
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20329
bytes = 742040
compile_seconds = 0.0
samples = 3
seconds = 0.0003847

[datasets.afiro.dual]
allocations = 19278
bytes = 953656
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000705
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000223
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18463
bytes = 817976
compile_seconds = 0.0
samples = 3
seconds = 0.000539

[datasets.afiro.primal]
allocations = 19184
bytes = 931512
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006776
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002242
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2737
bytes = 101576
compile_seconds = 0.0
samples = 3
seconds = 0.0001

[datasets.flugpl.dual]
allocations = 35219
bytes = 1438168
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008745
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001567
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34548
bytes = 1328528
compile_seconds = 0.0
samples = 3
seconds = 0.0007213

[datasets.flugpl.primal]
allocations = 35568
bytes = 1483048
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008528
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000163
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4131
bytes = 162664
compile_seconds = 0.0
samples = 3
seconds = 0.0001

[datasets.kb2.dual]
allocations = 241058
bytes = 11558832
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0207292
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878336
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007685
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 239856
bytes = 11106816
compile_seconds = 0.0
samples = 3
seconds = 0.021063499

[datasets.kb2.primal]
allocations = 241225
bytes = 11573056
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0217104
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005871
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16075
bytes = 592584
compile_seconds = 0.0
samples = 3
seconds = 0.0003066

[datasets.sc50a.dual]
allocations = 73676
bytes = 3395168
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019657
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306304
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005423
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72604
bytes = 3049840
compile_seconds = 0.0
samples = 3
seconds = 0.0015678

[datasets.sc50a.primal]
allocations = 73621
bytes = 3348048
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019402
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004422
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 7196
bytes = 268952
compile_seconds = 0.0
samples = 3
seconds = 0.0001769

[probes.equal]
allocations = 15443
bytes = 528672
compile_seconds = 0.0
samples = 3
seconds = 0.0002744

[probes.negative]
allocations = 38361
bytes = 1435856
compile_seconds = 0.0
samples = 3
seconds = 0.0006756

[probes.positive]
allocations = 38617
bytes = 1442608
compile_seconds = 0.0
samples = 3
seconds = 0.0007547

[probes.tightening]
allocations = 19141
bytes = 707696
compile_seconds = 0.0
samples = 3
seconds = 0.0003784

[probes.unit]
allocations = 28889
bytes = 1079344
compile_seconds = 0.0
samples = 3
seconds = 0.0005505
