julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 117014
bytes = 5416760
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0041361
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008739
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 114999
bytes = 4627128
compile_seconds = 0.0
samples = 3
seconds = 0.0023383

[datasets.adlittle.primal]
allocations = 117812
bytes = 5693672
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038268
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607296
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010236
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 29716
bytes = 1107912
compile_seconds = 0.0
samples = 3
seconds = 0.000531401

[datasets.afiro.dual]
allocations = 27174
bytes = 1252328
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008549
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001938
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26359
bytes = 1117528
compile_seconds = 0.0
samples = 3
seconds = 0.0006897

[datasets.afiro.primal]
allocations = 27080
bytes = 1230408
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009733
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001752
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 4842
bytes = 187568
compile_seconds = 0.0
samples = 3
seconds = 0.000117

[datasets.flugpl.dual]
allocations = 39110
bytes = 1579360
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009147
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001204
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38439
bytes = 1469928
compile_seconds = 0.0
samples = 3
seconds = 0.0007505

[datasets.flugpl.primal]
allocations = 39459
bytes = 1623920
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009972
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001657
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 5591
bytes = 218776
compile_seconds = 0.0
samples = 3
seconds = 0.0001192

[datasets.kb2.dual]
allocations = 291795
bytes = 13536784
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021781702
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878272
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008121
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 290593
bytes = 13083904
compile_seconds = 0.0
samples = 3
seconds = 0.020539602

[datasets.kb2.primal]
allocations = 291962
bytes = 13550960
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022132502
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005624
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 24193
bytes = 912648
compile_seconds = 0.0
samples = 3
seconds = 0.0003953

[datasets.sc50a.dual]
allocations = 102328
bytes = 4442944
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0026182
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306352
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005516
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101256
bytes = 4097152
compile_seconds = 0.0
samples = 3
seconds = 0.0019364

[datasets.sc50a.primal]
allocations = 102273
bytes = 4395568
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022889
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005132
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 12521
bytes = 481536
compile_seconds = 0.0
samples = 3
seconds = 0.0002129

[probes.nonunit]
allocations = 17132
bytes = 614944
compile_seconds = 0.0
samples = 3
seconds = 0.0002577

[probes.unit]
allocations = 12524
bytes = 431632
compile_seconds = 0.0
samples = 3
seconds = 0.0002097
