julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.adlittle.dual]
allocations = 84647
bytes = 4128408
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003453605
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461432
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000988901
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82632
bytes = 3338936
compile_seconds = 0.0
samples = 3
seconds = 0.002239903

[datasets.adlittle.primal]
allocations = 85445
bytes = 4404392
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003659105
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607104
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001250802
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18234
bytes = 644264
compile_seconds = 0.0
samples = 3
seconds = 0.000376601

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.64e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 173576
compile_seconds = 0.0
samples = 3
seconds = 0.0001464

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.afiro.dual]
allocations = 17044
bytes = 864336
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000892601
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000258901
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16229
bytes = 729200
compile_seconds = 0.0
samples = 3
seconds = 0.000544706

[datasets.afiro.primal]
allocations = 16950
bytes = 842224
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007428
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002393
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92232
compile_seconds = 0.0
samples = 3
seconds = 0.000107102

[datasets.afiro.singleton]
allocations = 843
bytes = 45120
compile_seconds = 0.0
samples = 3
seconds = 8.9601e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214256
compile_seconds = 0.0
samples = 3
seconds = 0.000173602

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.7e-6

[datasets.flugpl.dual]
allocations = 31630
bytes = 1287112
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001004901
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001663
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30959
bytes = 1178176
compile_seconds = 0.0
samples = 3
seconds = 0.000677501

[datasets.flugpl.primal]
allocations = 31979
bytes = 1331992
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000971402
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000186001
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3283
bytes = 123800
compile_seconds = 0.0
samples = 3
seconds = 0.0001179

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.52e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209608
compile_seconds = 0.0
samples = 3
seconds = 0.0001399

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 8.7e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.dual]
allocations = 230923
bytes = 11118120
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02151753
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000877901
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229721
bytes = 10664168
compile_seconds = 0.0
samples = 3
seconds = 0.019891228

[datasets.kb2.primal]
allocations = 231090
bytes = 11132120
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021083929
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000651701
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13194
bytes = 466824
compile_seconds = 0.0
samples = 3
seconds = 0.000259701

[datasets.kb2.singleton]
allocations = 2060
bytes = 112064
compile_seconds = 0.0
samples = 3
seconds = 9.8e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161088
compile_seconds = 0.0
samples = 3
seconds = 0.0001156

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.74e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.sc50a.dual]
allocations = 68575
bytes = 3194544
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002334804
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306368
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000687401
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67503
bytes = 2848768
compile_seconds = 0.0
samples = 3
seconds = 0.001487402

[datasets.sc50a.primal]
allocations = 68520
bytes = 3147600
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001881303
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232248
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005444
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6058
bytes = 223016
compile_seconds = 0.0
samples = 3
seconds = 0.0001795

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.7e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298608
compile_seconds = 0.0
samples = 3
seconds = 0.000176201

[probes.fraction_negative]
allocations = 61132
bytes = 2072968
compile_seconds = 0.0
samples = 3
seconds = 0.000888009

[probes.fraction_positive]
allocations = 61516
bytes = 2085464
compile_seconds = 0.0
samples = 3
seconds = 0.001098111

[probes.integer_negative]
allocations = 56524
bytes = 1899912
compile_seconds = 0.0
samples = 3
seconds = 0.001055111

[probes.integer_positive]
allocations = 55628
bytes = 1873032
compile_seconds = 0.0
samples = 3
seconds = 0.000995297

[probes.unbounded]
allocations = 9635
bytes = 310976
compile_seconds = 0.0
samples = 3
seconds = 0.000246002

[probes.unequal_denominator]
allocations = 41292
bytes = 1478408
compile_seconds = 0.0
samples = 3
seconds = 0.000703007
