julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90685
bytes = 4405736
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033338
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461176
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009246
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88670
bytes = 3615848
compile_seconds = 0.0
samples = 3
seconds = 0.0021026

[datasets.adlittle.primal]
allocations = 91483
bytes = 4682152
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035166
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607648
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010074
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20337
bytes = 742168
compile_seconds = 0.0
samples = 3
seconds = 0.0003985

[datasets.afiro.dual]
allocations = 19310
bytes = 953224
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007856
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001965
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18495
bytes = 818344
compile_seconds = 0.0
samples = 3
seconds = 0.0005594

[datasets.afiro.primal]
allocations = 19216
bytes = 931912
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000711
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001896
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2737
bytes = 101960
compile_seconds = 0.0
samples = 3
seconds = 9.23e-5

[datasets.flugpl.dual]
allocations = 35255
bytes = 1438712
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008657
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001282
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34584
bytes = 1329456
compile_seconds = 0.0
samples = 3
seconds = 0.0007575

[datasets.flugpl.primal]
allocations = 35604
bytes = 1483128
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009417
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001702
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4151
bytes = 162648
compile_seconds = 0.0
samples = 3
seconds = 0.0001192

[datasets.kb2.dual]
allocations = 241134
bytes = 11559328
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021101499
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878640
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007775
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 239932
bytes = 11108000
compile_seconds = 0.0
samples = 3
seconds = 0.020136

[datasets.kb2.primal]
allocations = 241301
bytes = 11574912
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0208948
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005637
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16127
bytes = 593896
compile_seconds = 0.0
samples = 3
seconds = 0.0003004

[datasets.sc50a.dual]
allocations = 73692
bytes = 3395856
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020011
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005289
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72620
bytes = 3048768
compile_seconds = 0.0
samples = 3
seconds = 0.0015346

[datasets.sc50a.primal]
allocations = 73637
bytes = 3348368
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020804
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000497
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 7280
bytes = 270984
compile_seconds = 0.0
samples = 3
seconds = 0.0001731

[probes.free]
allocations = 10693
bytes = 414320
compile_seconds = 0.0
samples = 3
seconds = 0.000262

[probes.negative]
allocations = 20037
bytes = 732048
compile_seconds = 0.0
samples = 3
seconds = 0.0003759

[probes.positive]
allocations = 20165
bytes = 733824
compile_seconds = 0.0
samples = 3
seconds = 0.0003656

[probes.unequal]
allocations = 38617
bytes = 1442512
compile_seconds = 0.0
samples = 3
seconds = 0.0006157

[probes.unit]
allocations = 15301
bytes = 552848
compile_seconds = 0.0
samples = 3
seconds = 0.0002897
