julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 85688
bytes = 4168968
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003835
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001025401
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 83673
bytes = 3380504
compile_seconds = 0.0
samples = 3
seconds = 0.002151701

[datasets.adlittle.primal]
allocations = 86486
bytes = 4445544
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003780601
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607440
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011406
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18243
bytes = 644648
compile_seconds = 0.0
samples = 3
seconds = 0.0004004

[datasets.afiro.dual]
allocations = 18436
bytes = 917168
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007956
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002277
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17621
bytes = 781088
compile_seconds = 0.0
samples = 3
seconds = 0.0006476

[datasets.afiro.primal]
allocations = 18342
bytes = 896288
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007611
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002212
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 90792
compile_seconds = 0.0
samples = 3
seconds = 0.0001033

[datasets.flugpl.dual]
allocations = 33810
bytes = 1373360
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010716
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001634
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33139
bytes = 1263240
compile_seconds = 0.0
samples = 3
seconds = 0.000825

[datasets.flugpl.primal]
allocations = 34159
bytes = 1417792
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001012601
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001991
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3297
bytes = 124136
compile_seconds = 0.0
samples = 3
seconds = 0.0001121

[datasets.kb2.dual]
allocations = 233293
bytes = 11211080
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021161205
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008088
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 232091
bytes = 10756632
compile_seconds = 0.0
samples = 3
seconds = 0.020625805

[datasets.kb2.primal]
allocations = 233460
bytes = 11223560
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021457105
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000643401
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13262
bytes = 468696
compile_seconds = 0.0
samples = 3
seconds = 0.0002705

[datasets.sc50a.dual]
allocations = 73155
bytes = 3374456
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002233301
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006132
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72083
bytes = 3028200
compile_seconds = 0.0
samples = 3
seconds = 0.001860001

[datasets.sc50a.primal]
allocations = 73100
bytes = 3326616
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002363501
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000557601
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6064
bytes = 223336
compile_seconds = 0.0
samples = 3
seconds = 0.000208601

[probes.maximum]
allocations = 34383
bytes = 1215664
compile_seconds = 0.0
samples = 3
seconds = 0.0007085

[probes.minimum]
allocations = 34511
bytes = 1218160
compile_seconds = 0.0
samples = 3
seconds = 0.0006157

[probes.nonzero]
allocations = 36303
bytes = 1292480
compile_seconds = 0.0
samples = 3
seconds = 0.0006017

[probes.unbounded]
allocations = 22860
bytes = 816328
compile_seconds = 0.0
samples = 3
seconds = 0.0004093

[probes.unit]
allocations = 29519
bytes = 1007600
compile_seconds = 0.0
samples = 3
seconds = 0.0005442
