julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 100569
bytes = 4763560
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033141
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461560
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009429
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 98554
bytes = 3974248
compile_seconds = 0.0
samples = 3
seconds = 0.0022668

[datasets.adlittle.primal]
allocations = 101367
bytes = 5040152
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038844
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607152
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010285
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 22113
bytes = 805832
compile_seconds = 0.0
samples = 3
seconds = 0.0004582

[datasets.afiro.dual]
allocations = 24686
bytes = 1153424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000871
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002055
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 23871
bytes = 1017888
compile_seconds = 0.0
samples = 3
seconds = 0.0006715

[datasets.afiro.primal]
allocations = 24592
bytes = 1132416
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008188
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000213
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 3361
bytes = 124784
compile_seconds = 0.0
samples = 3
seconds = 0.0001215

[datasets.flugpl.dual]
allocations = 37911
bytes = 1536216
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009792
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001389
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 37240
bytes = 1426896
compile_seconds = 0.0
samples = 3
seconds = 0.0007659

[datasets.flugpl.primal]
allocations = 38260
bytes = 1580840
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009991
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001676
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4969
bytes = 196328
compile_seconds = 0.0
samples = 3
seconds = 0.000149

[datasets.kb2.dual]
allocations = 279272
bytes = 13036536
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0205808
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878592
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008073
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 278070
bytes = 12583992
compile_seconds = 0.0
samples = 3
seconds = 0.0205763

[datasets.kb2.primal]
allocations = 279439
bytes = 13050616
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0208172
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000621
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 18210
bytes = 673016
compile_seconds = 0.0
samples = 3
seconds = 0.0003725

[datasets.sc50a.dual]
allocations = 99289
bytes = 4320000
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023791
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000571
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 98217
bytes = 3973776
compile_seconds = 0.0
samples = 3
seconds = 0.0019551

[datasets.sc50a.primal]
allocations = 99234
bytes = 4272864
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023591
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005207
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 9356
bytes = 351552
compile_seconds = 0.0
samples = 3
seconds = 0.0002023

[probes.nonzero]
allocations = 32085
bytes = 1191536
compile_seconds = 0.0
samples = 3
seconds = 0.000598

[probes.zero]
allocations = 19393
bytes = 713616
compile_seconds = 0.0
samples = 3
seconds = 0.0003625
