julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90829
bytes = 4410856
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032022
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009253
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88814
bytes = 3621832
compile_seconds = 0.0
samples = 3
seconds = 0.0020065

[datasets.adlittle.primal]
allocations = 91627
bytes = 4687352
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034263
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607456
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010776
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20408
bytes = 744024
compile_seconds = 0.0
samples = 3
seconds = 0.0003657

[datasets.afiro.dual]
allocations = 19553
bytes = 964144
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007182
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000189
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18738
bytes = 828224
compile_seconds = 0.0
samples = 3
seconds = 0.0005961

[datasets.afiro.primal]
allocations = 19459
bytes = 942640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006938
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001738
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2877
bytes = 108368
compile_seconds = 0.0
samples = 3
seconds = 9.43e-5

[datasets.flugpl.dual]
allocations = 35559
bytes = 1451048
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008093
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001455
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34888
bytes = 1341232
compile_seconds = 0.0
samples = 3
seconds = 0.0006909

[datasets.flugpl.primal]
allocations = 35908
bytes = 1495464
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008622
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001562
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4351
bytes = 171368
compile_seconds = 0.0
samples = 3
seconds = 0.0001066

[datasets.kb2.dual]
allocations = 242249
bytes = 11607616
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0210878
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878160
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008508
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 241047
bytes = 11154080
compile_seconds = 0.0
samples = 3
seconds = 0.0204936

[datasets.kb2.primal]
allocations = 242416
bytes = 11620400
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0211401
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005556
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16526
bytes = 612136
compile_seconds = 0.0
samples = 3
seconds = 0.0002789

[datasets.sc50a.dual]
allocations = 74027
bytes = 3408512
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019388
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306176
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005155
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72955
bytes = 3062528
compile_seconds = 0.0
samples = 3
seconds = 0.001506

[datasets.sc50a.primal]
allocations = 73972
bytes = 3361200
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019354
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004533
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 8007
bytes = 302848
compile_seconds = 0.0
samples = 3
seconds = 0.0001788

[probes.negative]
allocations = 15094
bytes = 526752
compile_seconds = 0.0
samples = 3
seconds = 0.0002509

[probes.nonunit]
allocations = 15094
bytes = 528016
compile_seconds = 0.0
samples = 3
seconds = 0.0002285

[probes.positive]
allocations = 15094
bytes = 528112
compile_seconds = 0.0
samples = 3
seconds = 0.0002398

[probes.unit]
allocations = 9974
bytes = 336640
compile_seconds = 0.0
samples = 3
seconds = 0.0001932

[probes.zero]
allocations = 10992
bytes = 379024
compile_seconds = 0.0
samples = 3
seconds = 0.0002053
