julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90787
bytes = 4406856
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032787
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461480
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000915
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88772
bytes = 3617224
compile_seconds = 0.0
samples = 3
seconds = 0.0020784

[datasets.adlittle.primal]
allocations = 91585
bytes = 4682824
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034189
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010932
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20387
bytes = 742384
compile_seconds = 0.0
samples = 3
seconds = 0.0003848

[datasets.afiro.dual]
allocations = 19483
bytes = 960880
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000865
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002138
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18668
bytes = 824176
compile_seconds = 0.0
samples = 3
seconds = 0.0006641

[datasets.afiro.primal]
allocations = 19389
bytes = 939200
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007546
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001913
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2877
bytes = 107088
compile_seconds = 0.0
samples = 3
seconds = 0.0001189

[datasets.flugpl.dual]
allocations = 35461
bytes = 1445528
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009982
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001292
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34790
bytes = 1336304
compile_seconds = 0.0
samples = 3
seconds = 0.0007524

[datasets.flugpl.primal]
allocations = 35810
bytes = 1490072
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009683
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001974
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4281
bytes = 169528
compile_seconds = 0.0
samples = 3
seconds = 0.0001201

[datasets.kb2.dual]
allocations = 242032
bytes = 11596680
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0212296
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878192
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008018
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 240830
bytes = 11142232
compile_seconds = 0.0
samples = 3
seconds = 0.0202628

[datasets.kb2.primal]
allocations = 242199
bytes = 11610136
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0221588
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006172
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16491
bytes = 608944
compile_seconds = 0.0
samples = 3
seconds = 0.0003741

[datasets.sc50a.dual]
allocations = 73915
bytes = 3401632
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022457
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306352
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005934
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72843
bytes = 3056208
compile_seconds = 0.0
samples = 3
seconds = 0.0016568

[datasets.sc50a.primal]
allocations = 73860
bytes = 3354560
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019736
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005439
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 7769
bytes = 292048
compile_seconds = 0.0
samples = 3
seconds = 0.0001949

[probes.negative]
allocations = 11510
bytes = 379744
compile_seconds = 0.0
samples = 3
seconds = 0.000225

[probes.nonunit]
allocations = 15094
bytes = 527104
compile_seconds = 0.0
samples = 3
seconds = 0.000248

[probes.positive]
allocations = 15094
bytes = 527088
compile_seconds = 0.0
samples = 3
seconds = 0.0002589

[probes.unit]
allocations = 9974
bytes = 335712
compile_seconds = 0.0
samples = 3
seconds = 0.0002235

[probes.zero]
allocations = 9200
bytes = 304816
compile_seconds = 0.0
samples = 3
seconds = 0.0001956
