julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 96311
bytes = 4608504
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033132
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461144
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010062
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 94296
bytes = 3819448
compile_seconds = 0.0
samples = 3
seconds = 0.0023564

[datasets.adlittle.primal]
allocations = 97109
bytes = 4884680
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038583
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 606960
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011501
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20408
bytes = 743320
compile_seconds = 0.0
samples = 3
seconds = 0.0003989

[datasets.afiro.dual]
allocations = 23891
bytes = 1123504
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009096
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002299
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 23076
bytes = 987824
compile_seconds = 0.0
samples = 3
seconds = 0.0007738

[datasets.afiro.primal]
allocations = 23797
bytes = 1101600
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008489
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001999
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2877
bytes = 108128
compile_seconds = 0.0
samples = 3
seconds = 0.0001135

[datasets.flugpl.dual]
allocations = 36629
bytes = 1488376
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009112
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001424
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 35958
bytes = 1378688
compile_seconds = 0.0
samples = 3
seconds = 0.00075

[datasets.flugpl.primal]
allocations = 36978
bytes = 1532984
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009614
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001875
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4351
bytes = 171176
compile_seconds = 0.0
samples = 3
seconds = 0.0001263

[datasets.kb2.dual]
allocations = 275637
bytes = 12906024
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020797201
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878128
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008525
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 274435
bytes = 12451592
compile_seconds = 0.0
samples = 3
seconds = 0.0201295

[datasets.kb2.primal]
allocations = 275804
bytes = 12918984
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021763201
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005796
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16526
bytes = 610120
compile_seconds = 0.0
samples = 3
seconds = 0.0002898

[datasets.sc50a.dual]
allocations = 98255
bytes = 4280640
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002358801
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005664
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 97183
bytes = 3935008
compile_seconds = 0.0
samples = 3
seconds = 0.0019269

[datasets.sc50a.primal]
allocations = 98200
bytes = 4233504
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024338
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004424
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 8007
bytes = 301472
compile_seconds = 0.0
samples = 3
seconds = 0.0001815

[probes.empty]
allocations = 152
bytes = 7168
compile_seconds = 0.0
samples = 3
seconds = 9.3e-6

[probes.many]
allocations = 6890
bytes = 227408
compile_seconds = 0.0
samples = 3
seconds = 0.0001423
