julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.3e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 84550
bytes = 4118920
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003735903
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461128
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000955901
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82535
bytes = 3329400
compile_seconds = 0.0
samples = 3
seconds = 0.002315802

[datasets.adlittle.primal]
allocations = 85348
bytes = 4395240
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003581603
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001155301
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18219
bytes = 641864
compile_seconds = 0.0
samples = 3
seconds = 0.0003858

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.4301e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174472
compile_seconds = 0.0
samples = 3
seconds = 0.0001344

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 862712
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000799301
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000225401
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 727048
compile_seconds = 0.0
samples = 3
seconds = 0.000617101

[datasets.afiro.primal]
allocations = 16938
bytes = 840664
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000698
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002246
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92920
compile_seconds = 0.0
samples = 3
seconds = 9.98e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 45520
compile_seconds = 0.0
samples = 3
seconds = 9.34e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214480
compile_seconds = 0.0
samples = 3
seconds = 0.000169

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.2e-6

[datasets.flugpl.dual]
allocations = 31518
bytes = 1280744
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001008201
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001539
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30847
bytes = 1170528
compile_seconds = 0.0
samples = 3
seconds = 0.000696501

[datasets.flugpl.primal]
allocations = 31867
bytes = 1325624
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010162
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000203
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3257
bytes = 122752
compile_seconds = 0.0
samples = 3
seconds = 0.000101

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.81e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209336
compile_seconds = 0.0
samples = 3
seconds = 0.0001429

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.kb2.dual]
allocations = 230698
bytes = 11105024
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020876318
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878144
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008668
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229496
bytes = 10651648
compile_seconds = 0.0
samples = 3
seconds = 0.020534018

[datasets.kb2.primal]
allocations = 230865
bytes = 11117328
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021909719
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000615701
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 13096
bytes = 458976
compile_seconds = 0.0
samples = 3
seconds = 0.000252001

[datasets.kb2.singleton]
allocations = 2060
bytes = 112272
compile_seconds = 0.0
samples = 3
seconds = 9.49e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161616
compile_seconds = 0.0
samples = 3
seconds = 0.0001093

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.55e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.sc50a.dual]
allocations = 68545
bytes = 3191256
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002036402
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306352
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000546201
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67473
bytes = 2844920
compile_seconds = 0.0
samples = 3
seconds = 0.001485102

[datasets.sc50a.primal]
allocations = 68490
bytes = 3143896
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002346902
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000534501
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6044
bytes = 221648
compile_seconds = 0.0
samples = 3
seconds = 0.0001755

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.34e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298384
compile_seconds = 0.0
samples = 3
seconds = 0.000169201

[probes.fraction_negative_lower]
allocations = 31436
bytes = 1099496
compile_seconds = 0.0
samples = 3
seconds = 0.0004382

[probes.fraction_negative_upper]
allocations = 31692
bytes = 1107240
compile_seconds = 0.0
samples = 3
seconds = 0.0005529

[probes.fraction_positive_lower]
allocations = 31692
bytes = 1107688
compile_seconds = 0.0
samples = 3
seconds = 0.0004675

[probes.fraction_positive_upper]
allocations = 31692
bytes = 1107416
compile_seconds = 0.0
samples = 3
seconds = 0.0004666

[probes.integer_negative_lower]
allocations = 26700
bytes = 925624
compile_seconds = 0.0
samples = 3
seconds = 0.0004366

[probes.integer_negative_upper]
allocations = 26956
bytes = 933816
compile_seconds = 0.0
samples = 3
seconds = 0.0004606

[probes.integer_positive_lower]
allocations = 25932
bytes = 903544
compile_seconds = 0.0
samples = 3
seconds = 0.0004759

[probes.integer_positive_upper]
allocations = 25932
bytes = 903208
compile_seconds = 0.0
samples = 3
seconds = 0.0004572

[probes.unequal_denominator]
allocations = 31052
bytes = 1044952
compile_seconds = 0.0
samples = 3
seconds = 0.0004651

[probes.zero_endpoint]
allocations = 26572
bytes = 933000
compile_seconds = 0.0
samples = 3
seconds = 0.000421101
