julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90705
bytes = 4405768
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031988
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461160
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009782
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88690
bytes = 3616280
compile_seconds = 0.0
samples = 3
seconds = 0.0020871

[datasets.adlittle.primal]
allocations = 91503
bytes = 4681208
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034217
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607360
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001056
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20345
bytes = 741816
compile_seconds = 0.0
samples = 3
seconds = 0.0003872

[datasets.afiro.dual]
allocations = 19350
bytes = 956568
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007916
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002049
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18535
bytes = 820328
compile_seconds = 0.0
samples = 3
seconds = 0.0006005

[datasets.afiro.primal]
allocations = 19256
bytes = 933784
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000749
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002148
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2737
bytes = 102584
compile_seconds = 0.0
samples = 3
seconds = 0.0001201

[datasets.flugpl.dual]
allocations = 35300
bytes = 1440600
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008622
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001491
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34629
bytes = 1330640
compile_seconds = 0.0
samples = 3
seconds = 0.0006903

[datasets.flugpl.primal]
allocations = 35649
bytes = 1485480
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000932
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001869
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4176
bytes = 164808
compile_seconds = 0.0
samples = 3
seconds = 0.0001299

[datasets.kb2.dual]
allocations = 241222
bytes = 11566112
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020522699
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878800
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008071
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 240020
bytes = 11113360
compile_seconds = 0.0
samples = 3
seconds = 0.0195874

[datasets.kb2.primal]
allocations = 241389
bytes = 11580448
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0198939
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006153
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16190
bytes = 597288
compile_seconds = 0.0
samples = 3
seconds = 0.000305

[datasets.sc50a.dual]
allocations = 73712
bytes = 3394928
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019313
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005803
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72640
bytes = 3049824
compile_seconds = 0.0
samples = 3
seconds = 0.001516

[datasets.sc50a.primal]
allocations = 73657
bytes = 3347968
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020242
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004739
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 7370
bytes = 276088
compile_seconds = 0.0
samples = 3
seconds = 0.0001814

[probes.free]
allocations = 10693
bytes = 415712
compile_seconds = 0.0
samples = 3
seconds = 0.0002294

[probes.negative]
allocations = 21317
bytes = 792080
compile_seconds = 0.0
samples = 3
seconds = 0.0003926

[probes.positive]
allocations = 21445
bytes = 793616
compile_seconds = 0.0
samples = 3
seconds = 0.0003908

[probes.unequal]
allocations = 38617
bytes = 1444944
compile_seconds = 0.0
samples = 3
seconds = 0.00066

[probes.unit]
allocations = 16581
bytes = 613072
compile_seconds = 0.0
samples = 3
seconds = 0.0003285
