julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 87788
bytes = 4253552
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031708
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461784
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009383
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 85773
bytes = 3465264
compile_seconds = 0.0
samples = 3
seconds = 0.002080401

[datasets.adlittle.primal]
allocations = 88586
bytes = 4530656
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003373601
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607456
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001127701
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 19142
bytes = 682328
compile_seconds = 0.0
samples = 3
seconds = 0.0003701

[datasets.afiro.dual]
allocations = 18955
bytes = 938272
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007573
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002095
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18140
bytes = 802864
compile_seconds = 0.0
samples = 3
seconds = 0.0005807

[datasets.afiro.primal]
allocations = 18861
bytes = 916032
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006853
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002083
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2617
bytes = 98328
compile_seconds = 0.0
samples = 3
seconds = 9.31e-5

[datasets.flugpl.dual]
allocations = 34417
bytes = 1398936
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009543
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001595
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33746
bytes = 1288256
compile_seconds = 0.0
samples = 3
seconds = 0.0006464

[datasets.flugpl.primal]
allocations = 34766
bytes = 1443480
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008708
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001715
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3655
bytes = 140208
compile_seconds = 0.0
samples = 3
seconds = 9.68e-5

[datasets.kb2.dual]
allocations = 236863
bytes = 11352312
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020430305
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878224
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007937
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 235661
bytes = 10899336
compile_seconds = 0.0
samples = 3
seconds = 0.020261905

[datasets.kb2.primal]
allocations = 237030
bytes = 11366408
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020773506
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000586
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14699
bytes = 526456
compile_seconds = 0.0
samples = 3
seconds = 0.000255

[datasets.sc50a.dual]
allocations = 73525
bytes = 3387016
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020425
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306448
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005335
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72453
bytes = 3042408
compile_seconds = 0.0
samples = 3
seconds = 0.001507501

[datasets.sc50a.primal]
allocations = 73470
bytes = 3340328
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001929301
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005208
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6663
bytes = 247000
compile_seconds = 0.0
samples = 3
seconds = 0.0001729

[probes.negative]
allocations = 8894
bytes = 310176
compile_seconds = 0.0
samples = 3
seconds = 0.0001769

[probes.positive]
allocations = 8894
bytes = 308880
compile_seconds = 0.0
samples = 3
seconds = 0.0001737

[probes.unbounded]
allocations = 7102
bytes = 254864
compile_seconds = 0.0
samples = 3
seconds = 0.0001351

[probes.unequal]
allocations = 11710
bytes = 405216
compile_seconds = 0.0
samples = 3
seconds = 0.0002053

[probes.zero]
allocations = 6462
bytes = 232192
compile_seconds = 0.0
samples = 3
seconds = 0.0001308
