julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 87453
bytes = 4242976
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031695
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461416
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008994
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 85438
bytes = 3453456
compile_seconds = 0.0
samples = 3
seconds = 0.0019237

[datasets.adlittle.primal]
allocations = 88251
bytes = 4519760
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035316
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607488
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011511
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18971
bytes = 676008
compile_seconds = 0.0
samples = 3
seconds = 0.0003425

[datasets.afiro.dual]
allocations = 18730
bytes = 930320
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007569
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002054
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17915
bytes = 794144
compile_seconds = 0.0
samples = 3
seconds = 0.0005594

[datasets.afiro.primal]
allocations = 18636
bytes = 908320
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007047
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002129
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91128
compile_seconds = 0.0
samples = 3
seconds = 8.97e-5

[datasets.flugpl.dual]
allocations = 34209
bytes = 1390648
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008751
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001565
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33538
bytes = 1281104
compile_seconds = 0.0
samples = 3
seconds = 0.0006568

[datasets.flugpl.primal]
allocations = 34558
bytes = 1435288
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008756
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001874
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3556
bytes = 136064
compile_seconds = 0.0
samples = 3
seconds = 0.0001085

[datasets.kb2.dual]
allocations = 236098
bytes = 11327416
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0201371
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877968
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008332
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 234896
bytes = 10875560
compile_seconds = 0.0
samples = 3
seconds = 0.019667899

[datasets.kb2.primal]
allocations = 236265
bytes = 11339752
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0208101
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005852
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14312
bytes = 513400
compile_seconds = 0.0
samples = 3
seconds = 0.000268

[datasets.sc50a.dual]
allocations = 73183
bytes = 3376632
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019698
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000575299
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72111
bytes = 3031080
compile_seconds = 0.0
samples = 3
seconds = 0.0015181

[datasets.sc50a.primal]
allocations = 73128
bytes = 3329432
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019686
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004812
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6312
bytes = 234872
compile_seconds = 0.0
samples = 3
seconds = 0.000154

[probes.negative]
allocations = 15959
bytes = 617016
compile_seconds = 0.0
samples = 3
seconds = 0.0003007

[probes.positive]
allocations = 16087
bytes = 619560
compile_seconds = 0.0
samples = 3
seconds = 0.0003467

[probes.unequal]
allocations = 17623
bytes = 667688
compile_seconds = 0.0
samples = 3
seconds = 0.0003114

[probes.unit]
allocations = 13783
bytes = 533896
compile_seconds = 0.0
samples = 3
seconds = 0.000263

[probes.zero_other]
allocations = 14036
bytes = 532416
compile_seconds = 0.0
samples = 3
seconds = 0.0002578
