julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.6e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4114792
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003560807
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461736
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001019802
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326616
compile_seconds = 0.0
samples = 3
seconds = 0.002254304

[datasets.adlittle.primal]
allocations = 85246
bytes = 4391624
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003954104
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001163603
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641336
compile_seconds = 0.0
samples = 3
seconds = 0.0003969

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.18e-5

[datasets.adlittle.sparse]
allocations = 2751
bytes = 174808
compile_seconds = 0.0
samples = 3
seconds = 0.0001133

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 9.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 863352
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000924301
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002113
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 728200
compile_seconds = 0.0
samples = 3
seconds = 0.000647001

[datasets.afiro.primal]
allocations = 16938
bytes = 841512
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000848701
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002272
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93096
compile_seconds = 0.0
samples = 3
seconds = 0.0001017

[datasets.afiro.singleton]
allocations = 843
bytes = 45456
compile_seconds = 0.0
samples = 3
seconds = 6.8601e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214784
compile_seconds = 0.0
samples = 3
seconds = 0.0001808

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.3e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279384
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000981501
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42752
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001875
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169424
compile_seconds = 0.0
samples = 3
seconds = 0.000678301

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324232
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009256
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002036
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122544
compile_seconds = 0.0
samples = 3
seconds = 0.0001271

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 2.04e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209576
compile_seconds = 0.0
samples = 3
seconds = 0.0001153

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 1.09e-5

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11090928
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021074916
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000861601
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10640064
compile_seconds = 0.0
samples = 3
seconds = 0.020551416

[datasets.kb2.primal]
allocations = 230563
bytes = 11104816
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021841917
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006826
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454064
compile_seconds = 0.0
samples = 3
seconds = 0.0002815

[datasets.kb2.singleton]
allocations = 2060
bytes = 112512
compile_seconds = 0.0
samples = 3
seconds = 0.000100001

[datasets.kb2.sparse]
allocations = 2836
bytes = 161856
compile_seconds = 0.0
samples = 3
seconds = 0.000130001

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.83e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191912
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002480802
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006078
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846392
compile_seconds = 0.0
samples = 3
seconds = 0.001759401

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144664
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002153702
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004864
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221248
compile_seconds = 0.0
samples = 3
seconds = 0.0001611

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.34e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298912
compile_seconds = 0.0
samples = 3
seconds = 0.0001907

[probes.fraction_negative_lower]
allocations = 32844
bytes = 1169272
compile_seconds = 0.0
samples = 3
seconds = 0.000602

[probes.fraction_negative_upper]
allocations = 33100
bytes = 1177416
compile_seconds = 0.0
samples = 3
seconds = 0.0005984

[probes.fraction_positive_lower]
allocations = 33100
bytes = 1177416
compile_seconds = 0.0
samples = 3
seconds = 0.0006077

[probes.fraction_positive_upper]
allocations = 33100
bytes = 1177448
compile_seconds = 0.0
samples = 3
seconds = 0.0006867

[probes.integer_negative_lower]
allocations = 31820
bytes = 1114536
compile_seconds = 0.0
samples = 3
seconds = 0.0006505

[probes.integer_negative_upper]
allocations = 32076
bytes = 1122856
compile_seconds = 0.0
samples = 3
seconds = 0.0006794

[probes.integer_positive_lower]
allocations = 32076
bytes = 1122936
compile_seconds = 0.0
samples = 3
seconds = 0.0005493

[probes.integer_positive_upper]
allocations = 32076
bytes = 1120408
compile_seconds = 0.0
samples = 3
seconds = 0.0006626

[probes.unequal_denominator]
allocations = 35148
bytes = 1229352
compile_seconds = 0.0
samples = 3
seconds = 0.0005763

[probes.unit_coefficient]
allocations = 24268
bytes = 852728
compile_seconds = 0.0
samples = 3
seconds = 0.0004906
