julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122704
bytes = 5656200
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0042104
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461528
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009176
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120689
bytes = 4866216
compile_seconds = 0.0
samples = 3
seconds = 0.0023358

[datasets.adlittle.primal]
allocations = 123502
bytes = 5933352
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004117
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607280
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010991
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 30628
bytes = 1147384
compile_seconds = 0.0
samples = 3
seconds = 0.000481

[datasets.afiro.dual]
allocations = 28367
bytes = 1308856
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008199
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000175
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27552
bytes = 1172840
compile_seconds = 0.0
samples = 3
seconds = 0.0006621

[datasets.afiro.primal]
allocations = 28273
bytes = 1286808
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007886
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001931
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 5090
bytes = 198832
compile_seconds = 0.0
samples = 3
seconds = 0.0001227

[datasets.flugpl.dual]
allocations = 39856
bytes = 1615560
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000944501
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001421
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39185
bytes = 1504816
compile_seconds = 0.0
samples = 3
seconds = 0.0007905

[datasets.flugpl.primal]
allocations = 40205
bytes = 1659640
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000974501
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001933
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 5787
bytes = 228792
compile_seconds = 0.0
samples = 3
seconds = 0.0001453

[datasets.kb2.dual]
allocations = 293436
bytes = 13616800
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021839501
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007997
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292234
bytes = 13165280
compile_seconds = 0.0
samples = 3
seconds = 0.020894902

[datasets.kb2.primal]
allocations = 293603
bytes = 13630848
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021718205
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000566101
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 24781
bytes = 937688
compile_seconds = 0.0
samples = 3
seconds = 0.000415

[datasets.sc50a.dual]
allocations = 107096
bytes = 4646832
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024533
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000539
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106024
bytes = 4301136
compile_seconds = 0.0
samples = 3
seconds = 0.001939101

[datasets.sc50a.primal]
allocations = 107041
bytes = 4599328
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002698801
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005198
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 12939
bytes = 500896
compile_seconds = 0.0
samples = 3
seconds = 0.0002585

[probes.no_tightening]
allocations = 102
bytes = 69320
compile_seconds = 0.0
samples = 3
seconds = 5.4e-5

[probes.tightening]
allocations = 429
bytes = 15968
compile_seconds = 0.0
samples = 3
seconds = 4.65e-5
