julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 98971
bytes = 4703992
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034052
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461576
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008941
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 96956
bytes = 3912504
compile_seconds = 0.0
samples = 3
seconds = 0.0021638

[datasets.adlittle.primal]
allocations = 99769
bytes = 4980344
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037496
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607216
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010596
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 21261
bytes = 773848
compile_seconds = 0.0
samples = 3
seconds = 0.0004062

[datasets.afiro.dual]
allocations = 24353
bytes = 1140672
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008501
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002056
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 23538
bytes = 1005920
compile_seconds = 0.0
samples = 3
seconds = 0.0006113

[datasets.afiro.primal]
allocations = 24259
bytes = 1119648
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007937
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002153
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 3112
bytes = 115280
compile_seconds = 0.0
samples = 3
seconds = 0.0001064

[datasets.flugpl.dual]
allocations = 37839
bytes = 1533816
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000879
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001125
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 37168
bytes = 1424352
compile_seconds = 0.0
samples = 3
seconds = 0.0007455

[datasets.flugpl.primal]
allocations = 38188
bytes = 1578328
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009405
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000196
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4911
bytes = 194664
compile_seconds = 0.0
samples = 3
seconds = 0.0001365

[datasets.kb2.dual]
allocations = 278621
bytes = 13013592
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0209357
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878224
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008011
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 277419
bytes = 12560152
compile_seconds = 0.0
samples = 3
seconds = 0.0207056

[datasets.kb2.primal]
allocations = 278788
bytes = 13026648
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0208577
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006201
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 18010
bytes = 665048
compile_seconds = 0.0
samples = 3
seconds = 0.0003397

[datasets.sc50a.dual]
allocations = 98859
bytes = 4303488
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024543
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005449
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 97787
bytes = 3958208
compile_seconds = 0.0
samples = 3
seconds = 0.0018686

[datasets.sc50a.primal]
allocations = 98804
bytes = 4256272
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024559
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005001
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 8854
bytes = 331760
compile_seconds = 0.0
samples = 3
seconds = 0.0001995

[probes.nonzero]
allocations = 12786
bytes = 438304
compile_seconds = 0.0
samples = 3
seconds = 0.0002132

[probes.zero]
allocations = 8166
bytes = 263920
compile_seconds = 0.0
samples = 3
seconds = 0.0001628
