julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 101727
bytes = 4812568
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003419596
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461448
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000915199
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 99712
bytes = 4022808
compile_seconds = 0.0
samples = 3
seconds = 0.002274298

[datasets.adlittle.primal]
allocations = 102525
bytes = 5088888
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003689796
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607472
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001075699
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 22137
bytes = 806184
compile_seconds = 0.0
samples = 3
seconds = 0.0004193

[datasets.afiro.dual]
allocations = 24977
bytes = 1165944
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000843799
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000200399
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 24162
bytes = 1029800
compile_seconds = 0.0
samples = 3
seconds = 0.000683199

[datasets.afiro.primal]
allocations = 24883
bytes = 1145320
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000851499
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002033
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 3613
bytes = 136224
compile_seconds = 0.0
samples = 3
seconds = 0.0001331

[datasets.flugpl.dual]
allocations = 38076
bytes = 1542256
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009459
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001529
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 37405
bytes = 1432872
compile_seconds = 0.0
samples = 3
seconds = 0.0007723

[datasets.flugpl.primal]
allocations = 38425
bytes = 1586480
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010309
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001904
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4969
bytes = 195752
compile_seconds = 0.0
samples = 3
seconds = 0.0001331

[datasets.kb2.dual]
allocations = 280043
bytes = 13070880
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021195178
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878080
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000836799
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 278841
bytes = 12620128
compile_seconds = 0.0
samples = 3
seconds = 0.020405479

[datasets.kb2.primal]
allocations = 280210
bytes = 13085088
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0205764
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006211
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 18510
bytes = 686072
compile_seconds = 0.0
samples = 3
seconds = 0.000339099

[datasets.sc50a.dual]
allocations = 99805
bytes = 4344000
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023792
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306464
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005605
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 98733
bytes = 3997408
compile_seconds = 0.0
samples = 3
seconds = 0.0020094

[datasets.sc50a.primal]
allocations = 99750
bytes = 4296416
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023448
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000521
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 9920
bytes = 377760
compile_seconds = 0.0
samples = 3
seconds = 0.0002176

[probes.different]
allocations = 27471
bytes = 1015264
compile_seconds = 0.0
samples = 3
seconds = 0.0004841

[probes.equal]
allocations = 26703
bytes = 995088
compile_seconds = 0.0
samples = 3
seconds = 0.0004959
