julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 101727
bytes = 4811240
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032405
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008999
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 99712
bytes = 4023416
compile_seconds = 0.0
samples = 3
seconds = 0.0021347

[datasets.adlittle.primal]
allocations = 102525
bytes = 5088344
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0043434
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607344
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010297
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 22137
bytes = 805272
compile_seconds = 0.0
samples = 3
seconds = 0.0004044

[datasets.afiro.dual]
allocations = 24977
bytes = 1166616
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008367
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002154
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 24162
bytes = 1030456
compile_seconds = 0.0
samples = 3
seconds = 0.0008789

[datasets.afiro.primal]
allocations = 24883
bytes = 1143928
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007684
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002176
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 3613
bytes = 136608
compile_seconds = 0.0
samples = 3
seconds = 0.0001282

[datasets.flugpl.dual]
allocations = 38076
bytes = 1541584
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009486
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001525
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 37405
bytes = 1432584
compile_seconds = 0.0
samples = 3
seconds = 0.0007788

[datasets.flugpl.primal]
allocations = 38425
bytes = 1586176
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009657
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001836
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4969
bytes = 195400
compile_seconds = 0.0
samples = 3
seconds = 0.0001401

[datasets.kb2.dual]
allocations = 280043
bytes = 13072960
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021157502
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878384
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000782
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 278841
bytes = 12616848
compile_seconds = 0.0
samples = 3
seconds = 0.021327302

[datasets.kb2.primal]
allocations = 280210
bytes = 13086016
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021257903
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005908
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 18510
bytes = 686328
compile_seconds = 0.0
samples = 3
seconds = 0.0003025

[datasets.sc50a.dual]
allocations = 99805
bytes = 4343872
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024614
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000547
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 98733
bytes = 3997728
compile_seconds = 0.0
samples = 3
seconds = 0.0018035

[datasets.sc50a.primal]
allocations = 99750
bytes = 4296624
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002374901
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232248
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005389
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 9920
bytes = 378656
compile_seconds = 0.0
samples = 3
seconds = 0.0001866

[probes.nonzero]
allocations = 26945
bytes = 993328
compile_seconds = 0.0
samples = 3
seconds = 0.0004822

[probes.zero]
allocations = 22977
bytes = 847808
compile_seconds = 0.0
samples = 3
seconds = 0.0004529
