julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 87453
bytes = 4240608
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035585
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461512
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010033
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 85438
bytes = 3451984
compile_seconds = 0.0
samples = 3
seconds = 0.0022052

[datasets.adlittle.primal]
allocations = 88251
bytes = 4516704
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038085
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607072
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011435
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18971
bytes = 676152
compile_seconds = 0.0
samples = 3
seconds = 0.0004365

[datasets.afiro.dual]
allocations = 18730
bytes = 929280
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008435
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002068
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 17915
bytes = 793424
compile_seconds = 0.0
samples = 3
seconds = 0.0006444

[datasets.afiro.primal]
allocations = 18636
bytes = 908016
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008071
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002182
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 91368
compile_seconds = 0.0
samples = 3
seconds = 0.0001078

[datasets.flugpl.dual]
allocations = 34209
bytes = 1389960
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000985
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001693
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33538
bytes = 1279216
compile_seconds = 0.0
samples = 3
seconds = 0.000803799

[datasets.flugpl.primal]
allocations = 34558
bytes = 1434408
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010995
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001951
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3556
bytes = 136048
compile_seconds = 0.0
samples = 3
seconds = 0.0001132

[datasets.kb2.dual]
allocations = 236098
bytes = 11325896
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0211289
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878128
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008427
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 234896
bytes = 10870632
compile_seconds = 0.0
samples = 3
seconds = 0.020986599

[datasets.kb2.primal]
allocations = 236265
bytes = 11339080
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021550199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006423
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14312
bytes = 513592
compile_seconds = 0.0
samples = 3
seconds = 0.0002936

[datasets.sc50a.dual]
allocations = 73183
bytes = 3372920
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002276
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306336
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006378
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72111
bytes = 3027976
compile_seconds = 0.0
samples = 3
seconds = 0.0017851

[datasets.sc50a.primal]
allocations = 73128
bytes = 3325848
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023035
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005076
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6312
bytes = 234408
compile_seconds = 0.0
samples = 3
seconds = 0.0001744

[probes.equality]
allocations = 6725
bytes = 296816
compile_seconds = 0.0
samples = 3
seconds = 0.0001722

[probes.lower_only]
allocations = 4930
bytes = 210600
compile_seconds = 0.0
samples = 3
seconds = 0.000127

[probes.nonzero]
allocations = 12997
bytes = 502144
compile_seconds = 0.0
samples = 3
seconds = 0.0002815

[probes.unbounded]
allocations = 2494
bytes = 102368
compile_seconds = 0.0
samples = 3
seconds = 8.26e-5

[probes.upper_only]
allocations = 4930
bytes = 211960
compile_seconds = 0.0
samples = 3
seconds = 0.0001404
