julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 90733
bytes = 4403784
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036949
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461192
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010415
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 88718
bytes = 3614408
compile_seconds = 0.0
samples = 3
seconds = 0.0023012

[datasets.adlittle.primal]
allocations = 91531
bytes = 4680920
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038603
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607632
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001127
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 20352
bytes = 740360
compile_seconds = 0.0
samples = 3
seconds = 0.0004677

[datasets.afiro.dual]
allocations = 19382
bytes = 955720
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008884
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002164
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18567
bytes = 819064
compile_seconds = 0.0
samples = 3
seconds = 0.0006674

[datasets.afiro.primal]
allocations = 19288
bytes = 933640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008333
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002134
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2781
bytes = 102352
compile_seconds = 0.0
samples = 3
seconds = 0.0001278

[datasets.flugpl.dual]
allocations = 35363
bytes = 1441560
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008538
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001159
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 34692
bytes = 1332496
compile_seconds = 0.0
samples = 3
seconds = 0.0006606

[datasets.flugpl.primal]
allocations = 35712
bytes = 1486280
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008607
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001545
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 4211
bytes = 165592
compile_seconds = 0.0
samples = 3
seconds = 0.0001101

[datasets.kb2.dual]
allocations = 241354
bytes = 11568000
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0212226
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878496
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009417
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 240152
bytes = 11116080
compile_seconds = 0.0
samples = 3
seconds = 0.020656

[datasets.kb2.primal]
allocations = 241521
bytes = 11581744
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0204267
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006242
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 16258
bytes = 598792
compile_seconds = 0.0
samples = 3
seconds = 0.0003595

[datasets.sc50a.dual]
allocations = 73796
bytes = 3396728
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019299
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005547
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72724
bytes = 3050664
compile_seconds = 0.0
samples = 3
seconds = 0.0018313

[datasets.sc50a.primal]
allocations = 73741
bytes = 3349592
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018875
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004988
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 7468
bytes = 278264
compile_seconds = 0.0
samples = 3
seconds = 0.0001696

[probes.negative]
allocations = 31193
bytes = 1143216
compile_seconds = 0.0
samples = 3
seconds = 0.0007244

[probes.nonunit]
allocations = 38361
bytes = 1434336
compile_seconds = 0.0
samples = 3
seconds = 0.0006315

[probes.positive]
allocations = 38617
bytes = 1442400
compile_seconds = 0.0
samples = 3
seconds = 0.0006807

[probes.unit]
allocations = 28889
bytes = 1077968
compile_seconds = 0.0
samples = 3
seconds = 0.0005965

[probes.upper_only]
allocations = 20441
bytes = 734512
compile_seconds = 0.0
samples = 3
seconds = 0.0004095
