julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 87788
bytes = 4250640
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033723
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461768
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009619
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 85773
bytes = 3461536
compile_seconds = 0.0
samples = 3
seconds = 0.0022324

[datasets.adlittle.primal]
allocations = 88586
bytes = 4527872
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038205
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011519
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 19142
bytes = 679128
compile_seconds = 0.0
samples = 3
seconds = 0.0003941

[datasets.afiro.dual]
allocations = 18955
bytes = 935520
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008182
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000228799
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 18140
bytes = 799488
compile_seconds = 0.0
samples = 3
seconds = 0.000622

[datasets.afiro.primal]
allocations = 18861
bytes = 914544
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007955
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002216
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2617
bytes = 96920
compile_seconds = 0.0
samples = 3
seconds = 0.000109

[datasets.flugpl.dual]
allocations = 34417
bytes = 1395144
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000940801
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001232
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 33746
bytes = 1285392
compile_seconds = 0.0
samples = 3
seconds = 0.0007375

[datasets.flugpl.primal]
allocations = 34766
bytes = 1439912
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000973801
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002085
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3655
bytes = 138000
compile_seconds = 0.0
samples = 3
seconds = 0.0001077

[datasets.kb2.dual]
allocations = 236863
bytes = 11349144
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020588899
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008736
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 235661
bytes = 10896344
compile_seconds = 0.0
samples = 3
seconds = 0.019992399

[datasets.kb2.primal]
allocations = 237030
bytes = 11362760
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022682299
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006215
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 14699
bytes = 523640
compile_seconds = 0.0
samples = 3
seconds = 0.0002833

[datasets.sc50a.dual]
allocations = 73525
bytes = 3384360
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002125802
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306160
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000612201
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 72453
bytes = 3038248
compile_seconds = 0.0
samples = 3
seconds = 0.001736501

[datasets.sc50a.primal]
allocations = 73470
bytes = 3336936
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002178401
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000534701
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6663
bytes = 244328
compile_seconds = 0.0
samples = 3
seconds = 0.0001846

[probes.negative]
allocations = 10998
bytes = 384704
compile_seconds = 0.0
samples = 3
seconds = 0.0002034

[probes.negative_unit]
allocations = 9206
bytes = 311232
compile_seconds = 0.0
samples = 3
seconds = 0.0001759

[probes.positive]
allocations = 10998
bytes = 382720
compile_seconds = 0.0
samples = 3
seconds = 0.000224

[probes.unequal]
allocations = 15094
bytes = 526464
compile_seconds = 0.0
samples = 3
seconds = 0.0002702

[probes.unit]
allocations = 8438
bytes = 288560
compile_seconds = 0.0
samples = 3
seconds = 0.00019
