julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122950
bytes = 5683672
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003740301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1330
bytes = 464632
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009969
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 123748
bytes = 5960584
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038434
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1903
bytes = 610288
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011217
status = "OPTIMAL"

[datasets.adlittle.relaxation]
allocations = 30
bytes = 18416
compile_seconds = 0.0
samples = 3
seconds = 4.44e-5

[datasets.afiro.dual]
allocations = 28543
bytes = 1318776
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008454
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 559
bytes = 91072
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002041
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28449
bytes = 1297400
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008016
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 763
bytes = 122928
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002197
status = "OPTIMAL"

[datasets.afiro.relaxation]
allocations = 28
bytes = 6320
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.dual]
allocations = 39994
bytes = 1616248
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000909
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 380
bytes = 43472
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001305
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40343
bytes = 1660712
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009436
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 743
bytes = 92416
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000184
status = "OPTIMAL"

[datasets.flugpl.relaxation]
allocations = 28
bytes = 4064
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.kb2.dual]
allocations = 293732
bytes = 13642688
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020975703
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1512
bytes = 879792
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008567
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 293899
bytes = 13656336
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020730602
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1058
bytes = 262368
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006317
status = "OPTIMAL"

[datasets.kb2.relaxation]
allocations = 30
bytes = 11184
compile_seconds = 0.0
samples = 3
seconds = 1.12e-5

[datasets.sc50a.dual]
allocations = 107404
bytes = 4663168
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024691
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 965
bytes = 308336
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006211
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107349
bytes = 4615872
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025897
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 968
bytes = 233944
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000501701
status = "OPTIMAL"

[datasets.sc50a.relaxation]
allocations = 28
bytes = 9632
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[probes.continuous]
allocations = 30
bytes = 336704
compile_seconds = 0.0
samples = 3
seconds = 0.0001494

[probes.integer]
allocations = 30
bytes = 336704
compile_seconds = 0.0
samples = 3
seconds = 0.0001114

[probes.semi_integer]
allocations = 30
bytes = 336704
compile_seconds = 0.0
samples = 3
seconds = 0.0001135
