julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122946
bytes = 5682040
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0038449
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009397
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 123744
bytes = 5958424
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038215
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607296
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011001
status = "OPTIMAL"

[datasets.adlittle.relaxation]
allocations = 26
bytes = 15088
compile_seconds = 0.0
samples = 3
seconds = 1.18e-5

[datasets.afiro.dual]
allocations = 28539
bytes = 1319352
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009876
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 90096
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001997
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28445
bytes = 1297192
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008666
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002122
status = "OPTIMAL"

[datasets.afiro.relaxation]
allocations = 24
bytes = 5168
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.dual]
allocations = 39990
bytes = 1616264
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009303
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001297
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40339
bytes = 1660728
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009288
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001935
status = "OPTIMAL"

[datasets.flugpl.relaxation]
allocations = 24
bytes = 3328
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.dual]
allocations = 293728
bytes = 13642416
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021368701
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878096
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007679
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 293895
bytes = 13656192
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021152201
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000602
status = "OPTIMAL"

[datasets.kb2.relaxation]
allocations = 26
bytes = 9648
compile_seconds = 0.0
samples = 3
seconds = 9.3e-6

[datasets.sc50a.dual]
allocations = 107400
bytes = 4662512
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023423
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306512
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005808
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107345
bytes = 4615152
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023425
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004967
status = "OPTIMAL"

[datasets.sc50a.relaxation]
allocations = 24
bytes = 7936
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[probes.continuous]
allocations = 24
bytes = 205488
compile_seconds = 0.0
samples = 3
seconds = 3.59e-5

[probes.integer]
allocations = 24
bytes = 205488
compile_seconds = 0.0
samples = 3
seconds = 3.8e-5

[probes.semi_integer]
allocations = 30
bytes = 336704
compile_seconds = 0.0
samples = 3
seconds = 0.000102
