julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123664
bytes = 5878536
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0040987
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1352
bytes = 474504
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009476
status = "OPTIMAL"

[datasets.adlittle.postsolve]
allocations = 14
bytes = 5936
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.adlittle.primal]
allocations = 124517
bytes = 6166264
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0041424
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1980
bytes = 632640
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011459
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28770
bytes = 1357112
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007437
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 581
bytes = 95136
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002139
status = "OPTIMAL"

[datasets.afiro.postsolve]
allocations = 16
bytes = 2272
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.afiro.primal]
allocations = 28672
bytes = 1335192
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008277
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 840
bytes = 132464
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002227
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40053
bytes = 1628840
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008659
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 402
bytes = 46288
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001369
status = "OPTIMAL"

[datasets.flugpl.postsolve]
allocations = 10
bytes = 1008
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.flugpl.primal]
allocations = 40457
bytes = 1678520
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009349
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 820
bytes = 100944
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001946
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294398
bytes = 13814240
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0211639
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1534
bytes = 885184
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007631
status = "OPTIMAL"

[datasets.kb2.postsolve]
allocations = 8
bytes = 1360
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.kb2.primal]
allocations = 294561
bytes = 13826032
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0209139
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1076
bytes = 266848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005828
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107625
bytes = 4713328
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024119
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 987
bytes = 314560
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005224
status = "OPTIMAL"

[datasets.sc50a.postsolve]
allocations = 14
bytes = 2528
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.sc50a.primal]
allocations = 107566
bytes = 4664704
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022051
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 986
bytes = 239000
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004772
status = "OPTIMAL"

[probes.identity_postsolve]
allocations = 3
bytes = 8264
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[probes.internal_solution]
allocations = 36
bytes = 67600
compile_seconds = 0.0
samples = 3
seconds = 4.08e-5
