julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123668
bytes = 5881992
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003465999
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1355
bytes = 476104
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008941
status = "OPTIMAL"

[datasets.adlittle.postsolve]
allocations = 16
bytes = 6784
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.primal]
allocations = 124522
bytes = 6170728
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037148
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1984
bytes = 635120
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010932
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28774
bytes = 1357592
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008201
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 584
bytes = 95696
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001794
status = "OPTIMAL"

[datasets.afiro.postsolve]
allocations = 18
bytes = 2592
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.afiro.primal]
allocations = 28676
bytes = 1335640
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007514
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 844
bytes = 133280
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001799
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40057
bytes = 1629752
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000925499
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 405
bytes = 46672
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.00011
status = "OPTIMAL"

[datasets.flugpl.postsolve]
allocations = 12
bytes = 1216
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.flugpl.primal]
allocations = 40462
bytes = 1679320
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009463
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 824
bytes = 101664
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001597
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294402
bytes = 13814976
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020866198
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1537
bytes = 885888
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007396
status = "OPTIMAL"

[datasets.kb2.postsolve]
allocations = 10
bytes = 1760
compile_seconds = 0.0
samples = 3
seconds = 4.5e-6

[datasets.kb2.primal]
allocations = 294565
bytes = 13827456
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021474299
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1079
bytes = 267584
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005728
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107629
bytes = 4715696
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023976
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 990
bytes = 315552
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0004898
status = "OPTIMAL"

[datasets.sc50a.postsolve]
allocations = 16
bytes = 3008
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.sc50a.primal]
allocations = 107570
bytes = 4666992
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024101
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 989
bytes = 239944
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004389
status = "OPTIMAL"

[probes.identity_postsolve]
allocations = 6
bytes = 16528
compile_seconds = 0.0
samples = 3
seconds = 2.15e-5

[probes.internal_solution]
allocations = 38
bytes = 75832
compile_seconds = 0.0
samples = 3
seconds = 3.95e-5
