julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.bounds_only]
allocations = 31
bytes = 17168
compile_seconds = 0.0
samples = 3
seconds = 1.17e-5

[datasets.adlittle.dual]
allocations = 122950
bytes = 5689160
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035322
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1330
bytes = 464712
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009106
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120931
bytes = 4897704
compile_seconds = 0.0
samples = 3
seconds = 0.002315401

[datasets.adlittle.primal]
allocations = 123748
bytes = 5965672
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0042058
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1903
bytes = 610832
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010778
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 30630
bytes = 1148712
compile_seconds = 0.0
samples = 3
seconds = 0.0004631

[datasets.afiro.bounds_only]
allocations = 29
bytes = 6048
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.afiro.dual]
allocations = 28543
bytes = 1323944
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008036
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 559
bytes = 91072
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002228
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27724
bytes = 1186840
compile_seconds = 0.0
samples = 3
seconds = 0.000747501

[datasets.afiro.primal]
allocations = 28449
bytes = 1301832
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008351
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 763
bytes = 122880
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002113
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 5092
bytes = 198416
compile_seconds = 0.0
samples = 3
seconds = 0.0001459

[datasets.flugpl.bounds_only]
allocations = 29
bytes = 3952
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.flugpl.dual]
allocations = 39994
bytes = 1624552
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008722
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 380
bytes = 43472
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000146
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39319
bytes = 1514208
compile_seconds = 0.0
samples = 3
seconds = 0.0007584

[datasets.flugpl.primal]
allocations = 40343
bytes = 1668872
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008692
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 743
bytes = 92416
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001539
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 5787
bytes = 228328
compile_seconds = 0.0
samples = 3
seconds = 0.0001284

[datasets.kb2.bounds_only]
allocations = 31
bytes = 10672
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.kb2.dual]
allocations = 293732
bytes = 13649008
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021755601
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1512
bytes = 879984
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007789
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292526
bytes = 13194432
compile_seconds = 0.0
samples = 3
seconds = 0.021239701

[datasets.kb2.primal]
allocations = 293899
bytes = 13662960
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021910501
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1058
bytes = 262352
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005641
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 24783
bytes = 938008
compile_seconds = 0.0
samples = 3
seconds = 0.0003678

[datasets.sc50a.bounds_only]
allocations = 29
bytes = 9136
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.sc50a.dual]
allocations = 107404
bytes = 4671856
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023543
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 965
bytes = 307840
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005259
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106328
bytes = 4325344
compile_seconds = 0.0
samples = 3
seconds = 0.0020523

[datasets.sc50a.primal]
allocations = 107349
bytes = 4624752
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022973
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 968
bytes = 233912
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004626
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 12941
bytes = 500880
compile_seconds = 0.0
samples = 3
seconds = 0.0002212

[probes.dense_bounds_only]
allocations = 33
bytes = 276048
compile_seconds = 0.0
samples = 3
seconds = 2.79e-5
