julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.bounds_only]
allocations = 46
bytes = 27408
compile_seconds = 0.0
samples = 3
seconds = 2.88e-5

[datasets.adlittle.dual]
allocations = 122965
bytes = 5699928
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003625301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1330
bytes = 464792
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008951
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120946
bytes = 4907096
compile_seconds = 0.0
samples = 3
seconds = 0.002407101

[datasets.adlittle.primal]
allocations = 123763
bytes = 5976952
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003891101
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1903
bytes = 610832
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001104
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 30645
bytes = 1157912
compile_seconds = 0.0
samples = 3
seconds = 0.0005216

[datasets.afiro.bounds_only]
allocations = 42
bytes = 9472
compile_seconds = 0.0
samples = 3
seconds = 1.13e-5

[datasets.afiro.dual]
allocations = 28556
bytes = 1326712
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008504
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 559
bytes = 91072
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001977
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27737
bytes = 1189592
compile_seconds = 0.0
samples = 3
seconds = 0.0006909

[datasets.afiro.primal]
allocations = 28462
bytes = 1304856
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008531
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 763
bytes = 122880
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002117
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 5105
bytes = 202688
compile_seconds = 0.0
samples = 3
seconds = 0.000134

[datasets.flugpl.bounds_only]
allocations = 42
bytes = 6144
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.flugpl.dual]
allocations = 40007
bytes = 1626568
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009823
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 380
bytes = 43488
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001464
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39332
bytes = 1515264
compile_seconds = 0.0
samples = 3
seconds = 0.0008177

[datasets.flugpl.primal]
allocations = 40356
bytes = 1671288
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009564
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 743
bytes = 92464
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000184
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 5800
bytes = 229608
compile_seconds = 0.0
samples = 3
seconds = 0.0001434

[datasets.kb2.bounds_only]
allocations = 46
bytes = 18128
compile_seconds = 0.0
samples = 3
seconds = 1.53e-5

[datasets.kb2.dual]
allocations = 293747
bytes = 13654752
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021313503
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1512
bytes = 880096
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008411
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292541
bytes = 13200064
compile_seconds = 0.0
samples = 3
seconds = 0.021009403

[datasets.kb2.primal]
allocations = 293914
bytes = 13669728
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020833603
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1058
bytes = 262416
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000613601
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 24798
bytes = 944280
compile_seconds = 0.0
samples = 3
seconds = 0.0004267

[datasets.sc50a.bounds_only]
allocations = 42
bytes = 14640
compile_seconds = 0.0
samples = 3
seconds = 1.19e-5

[datasets.sc50a.dual]
allocations = 107417
bytes = 4677024
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002457301
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 965
bytes = 307888
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005592
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106341
bytes = 4328912
compile_seconds = 0.0
samples = 3
seconds = 0.002099901

[datasets.sc50a.primal]
allocations = 107362
bytes = 4629776
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024606
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 968
bytes = 233880
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005199
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 12954
bytes = 506304
compile_seconds = 0.0
samples = 3
seconds = 0.0002475

[probes.dense_bounds_only]
allocations = 49
bytes = 544816
compile_seconds = 0.0
samples = 3
seconds = 8.41e-5
