julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123628
bytes = 5859048
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003448199
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1332
bytes = 465448
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008832
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 124469
bytes = 6140232
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036782
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1948
bytes = 616560
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0009716
status = "OPTIMAL"

[datasets.adlittle.scaling]
allocations = 51
bytes = 30320
compile_seconds = 0.0
samples = 3
seconds = 1.74e-5

[datasets.afiro.dual]
allocations = 28734
bytes = 1349400
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008088
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 561
bytes = 91328
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001876
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28640
bytes = 1328280
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007066
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 808
bytes = 125728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000181
status = "OPTIMAL"

[datasets.afiro.scaling]
allocations = 47
bytes = 10416
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.flugpl.dual]
allocations = 40017
bytes = 1621704
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008718
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 382
bytes = 43568
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001438
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40409
bytes = 1669096
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008601
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 788
bytes = 95728
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001814
status = "OPTIMAL"

[datasets.flugpl.scaling]
allocations = 47
bytes = 6720
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.dual]
allocations = 294362
bytes = 13803008
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021392598
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1514
bytes = 879920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008119
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 294529
bytes = 13816400
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021109599
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1060
bytes = 262688
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005632
status = "OPTIMAL"

[datasets.kb2.scaling]
allocations = 51
bytes = 19456
compile_seconds = 0.0
samples = 3
seconds = 1.33e-5

[datasets.sc50a.dual]
allocations = 107589
bytes = 4700512
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022992
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 967
bytes = 308528
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005215
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107534
bytes = 4653008
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023107
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 970
bytes = 234120
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005079
status = "OPTIMAL"

[datasets.sc50a.scaling]
allocations = 47
bytes = 16112
compile_seconds = 0.0
samples = 3
seconds = 8.6e-6

[probes.empty]
allocations = 26
bytes = 832
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[probes.square]
allocations = 49
bytes = 25296
compile_seconds = 0.0
samples = 3
seconds = 1.51e-5

[probes.tall]
allocations = 47
bytes = 83504
compile_seconds = 0.0
samples = 3
seconds = 3.15e-5

[probes.wide]
allocations = 50
bytes = 109128
compile_seconds = 0.0
samples = 3
seconds = 2.15e-5
