julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123632
bytes = 5862184
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036081
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1336
bytes = 466696
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000942
status = "OPTIMAL"

[datasets.adlittle.primal]
allocations = 124473
bytes = 6143528
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037954
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1952
bytes = 618032
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011459
status = "OPTIMAL"

[datasets.adlittle.scaling]
allocations = 55
bytes = 31696
compile_seconds = 0.0
samples = 3
seconds = 2.82e-5

[datasets.afiro.dual]
allocations = 28738
bytes = 1350040
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008867
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 565
bytes = 91888
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002152
status = "OPTIMAL"

[datasets.afiro.primal]
allocations = 28644
bytes = 1329160
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008487
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 812
bytes = 126256
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002275
status = "OPTIMAL"

[datasets.afiro.scaling]
allocations = 51
bytes = 11008
compile_seconds = 0.0
samples = 3
seconds = 9.5e-6

[datasets.flugpl.dual]
allocations = 40021
bytes = 1624184
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009381
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 386
bytes = 43984
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000147
status = "OPTIMAL"

[datasets.flugpl.primal]
allocations = 40413
bytes = 1671400
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009598
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 792
bytes = 96144
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001874
status = "OPTIMAL"

[datasets.flugpl.scaling]
allocations = 51
bytes = 7136
compile_seconds = 0.0
samples = 3
seconds = 8.3e-6

[datasets.kb2.dual]
allocations = 294366
bytes = 13804416
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021364401
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1518
bytes = 880672
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008317
status = "OPTIMAL"

[datasets.kb2.primal]
allocations = 294533
bytes = 13818448
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0213692
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1064
bytes = 263328
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006359
status = "OPTIMAL"

[datasets.kb2.scaling]
allocations = 55
bytes = 20256
compile_seconds = 0.0
samples = 3
seconds = 1.51e-5

[datasets.sc50a.dual]
allocations = 107593
bytes = 4703504
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0024832
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 971
bytes = 309344
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005847
status = "OPTIMAL"

[datasets.sc50a.primal]
allocations = 107538
bytes = 4655888
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024069
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 974
bytes = 235016
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005019
status = "OPTIMAL"

[datasets.sc50a.scaling]
allocations = 51
bytes = 17072
compile_seconds = 0.0
samples = 3
seconds = 1.13e-5

[probes.empty]
allocations = 28
bytes = 896
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[probes.square]
allocations = 53
bytes = 27536
compile_seconds = 0.0
samples = 3
seconds = 1.56e-5

[probes.tall]
allocations = 52
bytes = 91832
compile_seconds = 0.0
samples = 3
seconds = 3.48e-5

[probes.wide]
allocations = 55
bytes = 117456
compile_seconds = 0.0
samples = 3
seconds = 2.68e-5
