julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4116792
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034942
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461384
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0011452
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3328840
compile_seconds = 0.0
samples = 3
seconds = 0.0022445

[datasets.adlittle.primal]
allocations = 85246
bytes = 4393656
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037047
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607472
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012071
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 643544
compile_seconds = 0.0
samples = 3
seconds = 0.0003985

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.46e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174488
compile_seconds = 0.0
samples = 3
seconds = 0.0001324

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.afiro.dual]
allocations = 16936
bytes = 860936
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007927
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001907
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16121
bytes = 725992
compile_seconds = 0.0
samples = 3
seconds = 0.0006178

[datasets.afiro.primal]
allocations = 16842
bytes = 839960
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008003
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002041
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92664
compile_seconds = 0.0
samples = 3
seconds = 0.0001034

[datasets.afiro.singleton]
allocations = 747
bytes = 40896
compile_seconds = 0.0
samples = 3
seconds = 7.5e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214080
compile_seconds = 0.0
samples = 3
seconds = 0.000183

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1281016
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009127
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001501
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1172368
compile_seconds = 0.0
samples = 3
seconds = 0.0007442

[datasets.flugpl.primal]
allocations = 31811
bytes = 1326056
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010425
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002076
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123232
compile_seconds = 0.0
samples = 3
seconds = 0.0001101

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.87e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210984
compile_seconds = 0.0
samples = 3
seconds = 0.0001488

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.7e-6

[datasets.kb2.dual]
allocations = 230251
bytes = 11087096
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021478599
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008026
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229049
bytes = 10634504
compile_seconds = 0.0
samples = 3
seconds = 0.0204148

[datasets.kb2.primal]
allocations = 230418
bytes = 11101720
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0209678
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006167
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 455296
compile_seconds = 0.0
samples = 3
seconds = 0.0002965

[datasets.kb2.singleton]
allocations = 1915
bytes = 105704
compile_seconds = 0.0
samples = 3
seconds = 8.17e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162064
compile_seconds = 0.0
samples = 3
seconds = 0.0001314

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.69e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3194344
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020713
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306096
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006223
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2848184
compile_seconds = 0.0
samples = 3
seconds = 0.0016714

[datasets.sc50a.primal]
allocations = 68474
bytes = 3147128
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021391
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005723
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222448
compile_seconds = 0.0
samples = 3
seconds = 0.0001745

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.51e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299824
compile_seconds = 0.0
samples = 3
seconds = 0.0002101

[probes.negative]
allocations = 25920
bytes = 979592
compile_seconds = 0.0
samples = 3
seconds = 0.0005312

[probes.nonzero_cost]
allocations = 26880
bytes = 1016744
compile_seconds = 0.0
samples = 3
seconds = 0.0005596

[probes.positive]
allocations = 25920
bytes = 978472
compile_seconds = 0.0
samples = 3
seconds = 0.0005798

[probes.unit_negative]
allocations = 23872
bytes = 899576
compile_seconds = 0.0
samples = 3
seconds = 0.0004972

[probes.unit_positive]
allocations = 23872
bytes = 899384
compile_seconds = 0.0
samples = 3
seconds = 0.0004966

[probes.zero_ratio]
allocations = 19578
bytes = 768216
compile_seconds = 0.0
samples = 3
seconds = 0.0004286
