julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119556
bytes = 5514728
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0035111
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461688
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000941
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117541
bytes = 4726184
compile_seconds = 0.0
samples = 3
seconds = 0.0023792

[datasets.adlittle.primal]
allocations = 120354
bytes = 5792008
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038767
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607392
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011286
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 241
bytes = 40248
compile_seconds = 0.0
samples = 3
seconds = 5.85e-5

[datasets.afiro.dual]
allocations = 27432
bytes = 1262152
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008228
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002009
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26617
bytes = 1126248
compile_seconds = 0.0
samples = 3
seconds = 0.0006696

[datasets.afiro.primal]
allocations = 27338
bytes = 1240536
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000739
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001975
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 167
bytes = 15552
compile_seconds = 0.0
samples = 3
seconds = 3.0e-5

[datasets.flugpl.dual]
allocations = 39596
bytes = 1597104
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008567
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001346
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38925
bytes = 1487176
compile_seconds = 0.0
samples = 3
seconds = 0.0008996

[datasets.flugpl.primal]
allocations = 39945
bytes = 1641760
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008878
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001701
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 141
bytes = 11192
compile_seconds = 0.0
samples = 3
seconds = 2.13e-5

[datasets.kb2.dual]
allocations = 292761
bytes = 13572480
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0207022
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878576
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007763
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291559
bytes = 13118976
compile_seconds = 0.0
samples = 3
seconds = 0.0210777

[datasets.kb2.primal]
allocations = 292928
bytes = 13586288
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0217979
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005547
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 8
bytes = 1408
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.sc50a.dual]
allocations = 102738
bytes = 4457392
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022687
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005425
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101666
bytes = 4111296
compile_seconds = 0.0
samples = 3
seconds = 0.0018025

[datasets.sc50a.primal]
allocations = 102683
bytes = 4409904
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022924
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005004
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 8
bytes = 1648
compile_seconds = 0.0
samples = 3
seconds = 7.9e-6

[probes.nonunit]
allocations = 12852
bytes = 483752
compile_seconds = 0.0
samples = 3
seconds = 0.000277

[probes.unit]
allocations = 10548
bytes = 394408
compile_seconds = 0.0
samples = 3
seconds = 0.0002589
