julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4117912
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0031848
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461352
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009627
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3328280
compile_seconds = 0.0
samples = 3
seconds = 0.0021696

[datasets.adlittle.primal]
allocations = 85246
bytes = 4394808
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0036059
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607472
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010586
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641656
compile_seconds = 0.0
samples = 3
seconds = 0.0003618

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.37e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174696
compile_seconds = 0.0
samples = 3
seconds = 0.0001209

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.afiro.dual]
allocations = 16936
bytes = 860120
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007726
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002055
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16121
bytes = 724216
compile_seconds = 0.0
samples = 3
seconds = 0.0005689

[datasets.afiro.primal]
allocations = 16842
bytes = 838584
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007734
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001934
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92792
compile_seconds = 0.0
samples = 3
seconds = 0.0001073

[datasets.afiro.singleton]
allocations = 747
bytes = 41264
compile_seconds = 0.0
samples = 3
seconds = 7.6e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213776
compile_seconds = 0.0
samples = 3
seconds = 0.0001849

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1280296
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000849
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001293
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170816
compile_seconds = 0.0
samples = 3
seconds = 0.0006266

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324856
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009118
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001625
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123376
compile_seconds = 0.0
samples = 3
seconds = 8.63e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.9e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210824
compile_seconds = 0.0
samples = 3
seconds = 0.0001318

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.kb2.dual]
allocations = 230251
bytes = 11087704
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020955
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878096
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007569
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229049
bytes = 10634920
compile_seconds = 0.0
samples = 3
seconds = 0.019875899

[datasets.kb2.primal]
allocations = 230418
bytes = 11101832
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0205002
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005927
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454784
compile_seconds = 0.0
samples = 3
seconds = 0.0002599

[datasets.kb2.singleton]
allocations = 1915
bytes = 105192
compile_seconds = 0.0
samples = 3
seconds = 8.43e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162080
compile_seconds = 0.0
samples = 3
seconds = 0.0001171

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.72e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.8e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3193656
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0018874
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306144
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005824
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2847144
compile_seconds = 0.0
samples = 3
seconds = 0.0014245

[datasets.sc50a.primal]
allocations = 68474
bytes = 3146184
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0018866
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.00048
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222912
compile_seconds = 0.0
samples = 3
seconds = 0.0001228

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.45e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299856
compile_seconds = 0.0
samples = 3
seconds = 0.0001863

[probes.fraction_negative]
allocations = 53515
bytes = 2025144
compile_seconds = 0.0
samples = 3
seconds = 0.0009773

[probes.fraction_positive]
allocations = 53515
bytes = 2025224
compile_seconds = 0.0
samples = 3
seconds = 0.0009944

[probes.integer_negative]
allocations = 53643
bytes = 2027384
compile_seconds = 0.0
samples = 3
seconds = 0.000998

[probes.integer_positive]
allocations = 53643
bytes = 2025176
compile_seconds = 0.0
samples = 3
seconds = 0.0009838

[probes.unequal_denominator]
allocations = 53387
bytes = 2022952
compile_seconds = 0.0
samples = 3
seconds = 0.0009952

[probes.zero_ratio]
allocations = 39819
bytes = 1551624
compile_seconds = 0.0
samples = 3
seconds = 0.0007644
