julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4115544
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032056
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461496
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000918
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326664
compile_seconds = 0.0
samples = 3
seconds = 0.0020785

[datasets.adlittle.primal]
allocations = 85246
bytes = 4391272
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0035335
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607680
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010251
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641784
compile_seconds = 0.0
samples = 3
seconds = 0.000375

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 4.49e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174616
compile_seconds = 0.0
samples = 3
seconds = 0.0001301

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 16936
bytes = 860056
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000728
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000246
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16121
bytes = 724616
compile_seconds = 0.0
samples = 3
seconds = 0.0005959

[datasets.afiro.primal]
allocations = 16842
bytes = 838424
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006598
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002106
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92536
compile_seconds = 0.0
samples = 3
seconds = 9.08e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40640
compile_seconds = 0.0
samples = 3
seconds = 7.13e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213504
compile_seconds = 0.0
samples = 3
seconds = 0.0001697

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279400
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008273
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001538
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169920
compile_seconds = 0.0
samples = 3
seconds = 0.000687

[datasets.flugpl.primal]
allocations = 31811
bytes = 1323848
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008792
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001891
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122976
compile_seconds = 0.0
samples = 3
seconds = 0.0001028

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.77e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209432
compile_seconds = 0.0
samples = 3
seconds = 0.0001421

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.kb2.dual]
allocations = 230251
bytes = 11085864
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0202398
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008322
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229049
bytes = 10632712
compile_seconds = 0.0
samples = 3
seconds = 0.019924999

[datasets.kb2.primal]
allocations = 230418
bytes = 11100728
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0211855
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260896
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006121
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454400
compile_seconds = 0.0
samples = 3
seconds = 0.0002669

[datasets.kb2.singleton]
allocations = 1915
bytes = 105192
compile_seconds = 0.0
samples = 3
seconds = 8.91e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161920
compile_seconds = 0.0
samples = 3
seconds = 0.0001172

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.44e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191800
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020622
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306176
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005591
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2845800
compile_seconds = 0.0
samples = 3
seconds = 0.0015527

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144664
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0019799
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005272
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221648
compile_seconds = 0.0
samples = 3
seconds = 0.0001442

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.99e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 298992
compile_seconds = 0.0
samples = 3
seconds = 0.0001853

[probes.negative]
allocations = 26240
bytes = 992328
compile_seconds = 0.0
samples = 3
seconds = 0.0005121

[probes.nonzero_cost]
allocations = 26880
bytes = 1015432
compile_seconds = 0.0
samples = 3
seconds = 0.0005554

[probes.positive]
allocations = 26240
bytes = 992104
compile_seconds = 0.0
samples = 3
seconds = 0.0005439

[probes.unit_negative]
allocations = 24192
bytes = 912904
compile_seconds = 0.0
samples = 3
seconds = 0.0005031

[probes.unit_positive]
allocations = 24192
bytes = 912760
compile_seconds = 0.0
samples = 3
seconds = 0.0004755

[probes.zero_ratio]
allocations = 19578
bytes = 766856
compile_seconds = 0.0
samples = 3
seconds = 0.0004625
