julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4117160
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003215102
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461576
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000930701
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3327640
compile_seconds = 0.0
samples = 3
seconds = 0.002223801

[datasets.adlittle.primal]
allocations = 85246
bytes = 4394040
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003634101
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001063901
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642984
compile_seconds = 0.0
samples = 3
seconds = 0.0003679

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.75e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174104
compile_seconds = 0.0
samples = 3
seconds = 0.0001242

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.afiro.dual]
allocations = 16971
bytes = 862656
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000861
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89936
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002095
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16156
bytes = 727264
compile_seconds = 0.0
samples = 3
seconds = 0.0005759

[datasets.afiro.primal]
allocations = 16877
bytes = 841728
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007267
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001824
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93192
compile_seconds = 0.0
samples = 3
seconds = 9.18e-5

[datasets.afiro.singleton]
allocations = 782
bytes = 42248
compile_seconds = 0.0
samples = 3
seconds = 7.27e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214768
compile_seconds = 0.0
samples = 3
seconds = 0.0001785

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1280840
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000851605
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000139
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1172096
compile_seconds = 0.0
samples = 3
seconds = 0.000637601

[datasets.flugpl.primal]
allocations = 31811
bytes = 1325800
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000878605
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000191201
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123792
compile_seconds = 0.0
samples = 3
seconds = 9.38e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.54e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210904
compile_seconds = 0.0
samples = 3
seconds = 0.0001285

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.6e-6

[datasets.kb2.dual]
allocations = 230300
bytes = 11091696
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.02107761
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877984
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008199
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229098
bytes = 10637728
compile_seconds = 0.0
samples = 3
seconds = 0.020179409

[datasets.kb2.primal]
allocations = 230467
bytes = 11105680
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020097509
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006213
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 455600
compile_seconds = 0.0
samples = 3
seconds = 0.0002513

[datasets.kb2.singleton]
allocations = 1964
bytes = 107072
compile_seconds = 0.0
samples = 3
seconds = 8.5e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162400
compile_seconds = 0.0
samples = 3
seconds = 0.0001159

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.67e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3193768
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001941801
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306176
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005666
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2847512
compile_seconds = 0.0
samples = 3
seconds = 0.001472601

[datasets.sc50a.primal]
allocations = 68474
bytes = 3146184
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001942001
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004981
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 223456
compile_seconds = 0.0
samples = 3
seconds = 0.000138401

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.95e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 300256
compile_seconds = 0.0
samples = 3
seconds = 0.0001697

[probes.negative]
allocations = 26682
bytes = 1011816
compile_seconds = 0.0
samples = 3
seconds = 0.0005321

[probes.nonzero_cost]
allocations = 26880
bytes = 1016488
compile_seconds = 0.0
samples = 3
seconds = 0.0004621

[probes.positive]
allocations = 26682
bytes = 1011256
compile_seconds = 0.0
samples = 3
seconds = 0.000537

[probes.unit_negative]
allocations = 24634
bytes = 931976
compile_seconds = 0.0
samples = 3
seconds = 0.0004775

[probes.unit_positive]
allocations = 24634
bytes = 931928
compile_seconds = 0.0
samples = 3
seconds = 0.0004896

[probes.zero_ratio]
allocations = 19578
bytes = 767880
compile_seconds = 0.0
samples = 3
seconds = 0.0003617
