julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 119588
bytes = 5518024
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0039564
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461688
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009671
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 117573
bytes = 4727896
compile_seconds = 0.0
samples = 3
seconds = 0.0024571

[datasets.adlittle.primal]
allocations = 120386
bytes = 5794344
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038599
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607616
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011169
status = "OPTIMAL"

[datasets.adlittle.singleton]
allocations = 273
bytes = 41528
compile_seconds = 0.0
samples = 3
seconds = 7.51e-5

[datasets.afiro.dual]
allocations = 27450
bytes = 1263096
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008962
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001799
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 26635
bytes = 1126920
compile_seconds = 0.0
samples = 3
seconds = 0.0007023

[datasets.afiro.primal]
allocations = 27356
bytes = 1241912
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008307
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121776
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000179
status = "OPTIMAL"

[datasets.afiro.singleton]
allocations = 185
bytes = 16224
compile_seconds = 0.0
samples = 3
seconds = 3.85e-5

[datasets.flugpl.dual]
allocations = 39614
bytes = 1598000
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001005
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001536
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 38943
bytes = 1487640
compile_seconds = 0.0
samples = 3
seconds = 0.0008458

[datasets.flugpl.primal]
allocations = 39963
bytes = 1642352
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010335
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001936
status = "OPTIMAL"

[datasets.flugpl.singleton]
allocations = 159
bytes = 11864
compile_seconds = 0.0
samples = 3
seconds = 3.83e-5

[datasets.kb2.dual]
allocations = 292777
bytes = 13574400
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0212852
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878336
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008526
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 291575
bytes = 13121824
compile_seconds = 0.0
samples = 3
seconds = 0.0202693

[datasets.kb2.primal]
allocations = 292944
bytes = 13587344
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0210849
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006036
status = "OPTIMAL"

[datasets.kb2.singleton]
allocations = 8
bytes = 1408
compile_seconds = 0.0
samples = 3
seconds = 7.5e-6

[datasets.sc50a.dual]
allocations = 102738
bytes = 4458928
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002583
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306336
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000579
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 101666
bytes = 4111456
compile_seconds = 0.0
samples = 3
seconds = 0.0020689

[datasets.sc50a.primal]
allocations = 102683
bytes = 4411632
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0025768
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000528
status = "OPTIMAL"

[datasets.sc50a.singleton]
allocations = 8
bytes = 1648
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[probes.nonunit]
allocations = 12852
bytes = 483176
compile_seconds = 0.0
samples = 3
seconds = 0.0002751

[probes.unit]
allocations = 12852
bytes = 481928
compile_seconds = 0.0
samples = 3
seconds = 0.0002746
