julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 5.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4115928
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0032948
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461672
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008963
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3328136
compile_seconds = 0.0
samples = 3
seconds = 0.0020626

[datasets.adlittle.primal]
allocations = 85246
bytes = 4392856
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0033619
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607424
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010453
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641912
compile_seconds = 0.0
samples = 3
seconds = 0.0003741

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 5.58e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174088
compile_seconds = 0.0
samples = 3
seconds = 0.0001122

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 864328
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007314
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002283
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 728424
compile_seconds = 0.0
samples = 3
seconds = 0.0006273

[datasets.afiro.primal]
allocations = 16938
bytes = 842728
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006664
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121744
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002022
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92648
compile_seconds = 0.0
samples = 3
seconds = 0.0001015

[datasets.afiro.singleton]
allocations = 843
bytes = 44688
compile_seconds = 0.0
samples = 3
seconds = 7.31e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214816
compile_seconds = 0.0
samples = 3
seconds = 0.0001683

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1280328
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000928
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001643
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170416
compile_seconds = 0.0
samples = 3
seconds = 0.0006844

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324696
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008877
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000179
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123296
compile_seconds = 0.0
samples = 3
seconds = 7.89e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.8e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210824
compile_seconds = 0.0
samples = 3
seconds = 0.0001435

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.kb2.dual]
allocations = 230396
bytes = 11095088
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.019853099
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878032
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008208
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229194
bytes = 10641920
compile_seconds = 0.0
samples = 3
seconds = 0.0197647

[datasets.kb2.primal]
allocations = 230563
bytes = 11108960
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0200873
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260896
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006269
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 455200
compile_seconds = 0.0
samples = 3
seconds = 0.0002713

[datasets.kb2.singleton]
allocations = 2060
bytes = 111296
compile_seconds = 0.0
samples = 3
seconds = 9.52e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162160
compile_seconds = 0.0
samples = 3
seconds = 0.0001228

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.59e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191560
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021538
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306256
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005688
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2845944
compile_seconds = 0.0
samples = 3
seconds = 0.0015888

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144248
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020546
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004899
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 223632
compile_seconds = 0.0
samples = 3
seconds = 0.0001541

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.06e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 300560
compile_seconds = 0.0
samples = 3
seconds = 0.0001826

[probes.negative]
allocations = 25216
bytes = 970712
compile_seconds = 0.0
samples = 3
seconds = 0.000585

[probes.nonzero_rhs]
allocations = 27136
bytes = 1029896
compile_seconds = 0.0
samples = 3
seconds = 0.0005083

[probes.positive]
allocations = 25216
bytes = 969112
compile_seconds = 0.0
samples = 3
seconds = 0.0004894

[probes.unit_negative]
allocations = 25216
bytes = 970712
compile_seconds = 0.0
samples = 3
seconds = 0.0004968

[probes.unit_positive]
allocations = 25213
bytes = 970720
compile_seconds = 0.0
samples = 3
seconds = 0.0004897

[probes.zero_ratio]
allocations = 18304
bytes = 722568
compile_seconds = 0.0
samples = 3
seconds = 0.0003868
