julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122938
bytes = 5681864
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0037735
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461224
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0008733
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120923
bytes = 4892664
compile_seconds = 0.0
samples = 3
seconds = 0.0023593

[datasets.adlittle.primal]
allocations = 123736
bytes = 5958600
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037522
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607088
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010853
status = "OPTIMAL"

[datasets.adlittle.singleton_rows]
allocations = 389
bytes = 53016
compile_seconds = 0.0
samples = 3
seconds = 6.79e-5

[datasets.afiro.dual]
allocations = 28527
bytes = 1318760
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009481
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001996
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27712
bytes = 1182184
compile_seconds = 0.0
samples = 3
seconds = 0.0006713

[datasets.afiro.primal]
allocations = 28433
bytes = 1296648
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000791
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002082
status = "OPTIMAL"

[datasets.afiro.singleton_rows]
allocations = 243
bytes = 19872
compile_seconds = 0.0
samples = 3
seconds = 3.89e-5

[datasets.flugpl.dual]
allocations = 39978
bytes = 1620104
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000896
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001418
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39307
bytes = 1510000
compile_seconds = 0.0
samples = 3
seconds = 0.0006618

[datasets.flugpl.primal]
allocations = 40327
bytes = 1665160
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008421
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001925
status = "OPTIMAL"

[datasets.flugpl.singleton_rows]
allocations = 197
bytes = 13800
compile_seconds = 0.0
samples = 3
seconds = 3.47e-5

[datasets.kb2.dual]
allocations = 293716
bytes = 13640880
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020691801
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878400
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008648
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292514
bytes = 13189024
compile_seconds = 0.0
samples = 3
seconds = 0.021282402

[datasets.kb2.primal]
allocations = 293883
bytes = 13655328
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021102401
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260864
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006362
status = "OPTIMAL"

[datasets.kb2.singleton_rows]
allocations = 104
bytes = 11840
compile_seconds = 0.0
samples = 3
seconds = 8.1e-6

[datasets.sc50a.dual]
allocations = 107388
bytes = 4664112
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023791
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005274
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106316
bytes = 4318752
compile_seconds = 0.0
samples = 3
seconds = 0.001832101

[datasets.sc50a.primal]
allocations = 107333
bytes = 4616672
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002389699
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004536
status = "OPTIMAL"

[datasets.sc50a.singleton_rows]
allocations = 117
bytes = 10480
compile_seconds = 0.0
samples = 3
seconds = 9.7e-6

[probes.all_singletons]
allocations = 13107
bytes = 493424
compile_seconds = 0.0
samples = 3
seconds = 0.000275

[probes.no_singletons]
allocations = 406
bytes = 283712
compile_seconds = 0.0
samples = 3
seconds = 9.26e-5
