julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4118552
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036425
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010244
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3329784
compile_seconds = 0.0
samples = 3
seconds = 0.0023008

[datasets.adlittle.primal]
allocations = 85246
bytes = 4395368
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0044755
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012668
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642664
compile_seconds = 0.0
samples = 3
seconds = 0.0003965

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.22e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174296
compile_seconds = 0.0
samples = 3
seconds = 0.0001418

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.afiro.dual]
allocations = 17023
bytes = 865000
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008607
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002187
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16208
bytes = 729016
compile_seconds = 0.0
samples = 3
seconds = 0.0006438

[datasets.afiro.primal]
allocations = 16929
bytes = 843080
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008155
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.00022
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93160
compile_seconds = 0.0
samples = 3
seconds = 0.0001047

[datasets.afiro.singleton]
allocations = 834
bytes = 44448
compile_seconds = 0.0
samples = 3
seconds = 8.86e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214880
compile_seconds = 0.0
samples = 3
seconds = 0.0001594

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.9e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1280856
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008381
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001536
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1171696
compile_seconds = 0.0
samples = 3
seconds = 0.0007129

[datasets.flugpl.primal]
allocations = 31811
bytes = 1325768
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009688
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002006
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123296
compile_seconds = 0.0
samples = 3
seconds = 0.0001043

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.66e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210824
compile_seconds = 0.0
samples = 3
seconds = 0.0001309

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.kb2.dual]
allocations = 230351
bytes = 11092272
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.024326899
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878256
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008741
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229149
bytes = 10640288
compile_seconds = 0.0
samples = 3
seconds = 0.021424199

[datasets.kb2.primal]
allocations = 230518
bytes = 11106464
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0216175
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000717
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 455744
compile_seconds = 0.0
samples = 3
seconds = 0.0003074

[datasets.kb2.singleton]
allocations = 2015
bytes = 109760
compile_seconds = 0.0
samples = 3
seconds = 9.75e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162288
compile_seconds = 0.0
samples = 3
seconds = 0.000134

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.85e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3193976
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021068
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306576
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006068
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2848024
compile_seconds = 0.0
samples = 3
seconds = 0.0016249

[datasets.sc50a.primal]
allocations = 68474
bytes = 3146616
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022601
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005366
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 223504
compile_seconds = 0.0
samples = 3
seconds = 0.0001782

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.64e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 300528
compile_seconds = 0.0
samples = 3
seconds = 0.0002044

[probes.cancel_fraction]
allocations = 53259
bytes = 2036248
compile_seconds = 0.0
samples = 3
seconds = 0.001010699

[probes.cancel_integer]
allocations = 49931
bytes = 1893032
compile_seconds = 0.0
samples = 3
seconds = 0.000986899

[probes.sum_fraction]
allocations = 54923
bytes = 2097048
compile_seconds = 0.0
samples = 3
seconds = 0.001016

[probes.sum_integer]
allocations = 51339
bytes = 1942696
compile_seconds = 0.0
samples = 3
seconds = 0.0010041

[probes.unequal_denominator]
allocations = 54923
bytes = 2106200
compile_seconds = 0.0
samples = 3
seconds = 0.0010503

[probes.zero_rhs]
allocations = 46219
bytes = 1774072
compile_seconds = 0.0
samples = 3
seconds = 0.0009358
