julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4117256
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003413815
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461112
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001016204
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3327752
compile_seconds = 0.0
samples = 3
seconds = 0.002057209

[datasets.adlittle.primal]
allocations = 85246
bytes = 4394456
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003698117
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607536
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001121205
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642136
compile_seconds = 0.0
samples = 3
seconds = 0.000412002

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.35e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174632
compile_seconds = 0.0
samples = 3
seconds = 0.0001283

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.afiro.dual]
allocations = 17023
bytes = 863208
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000829502
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002233
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16208
bytes = 728376
compile_seconds = 0.0
samples = 3
seconds = 0.000629202

[datasets.afiro.primal]
allocations = 16929
bytes = 842584
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000922701
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.000247201
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92648
compile_seconds = 0.0
samples = 3
seconds = 0.0001111

[datasets.afiro.singleton]
allocations = 834
bytes = 44336
compile_seconds = 0.0
samples = 3
seconds = 7.95e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214016
compile_seconds = 0.0
samples = 3
seconds = 0.0001718

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 7.3e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1280808
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009214
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000168
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1171008
compile_seconds = 0.0
samples = 3
seconds = 0.0006595

[datasets.flugpl.primal]
allocations = 31811
bytes = 1325384
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000959001
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000184
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123504
compile_seconds = 0.0
samples = 3
seconds = 0.0001035

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 2.0e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 211240
compile_seconds = 0.0
samples = 3
seconds = 0.00015

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.dual]
allocations = 230351
bytes = 11092192
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021197295
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877792
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000834604
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229149
bytes = 10640096
compile_seconds = 0.0
samples = 3
seconds = 0.02000909

[datasets.kb2.primal]
allocations = 230518
bytes = 11106272
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021545596
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000619803
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 455520
compile_seconds = 0.0
samples = 3
seconds = 0.000269901

[datasets.kb2.singleton]
allocations = 2015
bytes = 109776
compile_seconds = 0.0
samples = 3
seconds = 0.0001049

[datasets.kb2.sparse]
allocations = 2836
bytes = 162336
compile_seconds = 0.0
samples = 3
seconds = 0.000106301

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.82e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3192424
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002132101
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000591103
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846488
compile_seconds = 0.0
samples = 3
seconds = 0.001614807

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144824
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002259101
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005254
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 223632
compile_seconds = 0.0
samples = 3
seconds = 0.000174001

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.82e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 300576
compile_seconds = 0.0
samples = 3
seconds = 0.000194601

[probes.negative]
allocations = 26362
bytes = 1003656
compile_seconds = 0.0
samples = 3
seconds = 0.0005748

[probes.nonzero_constant]
allocations = 27136
bytes = 1030328
compile_seconds = 0.0
samples = 3
seconds = 0.000553201

[probes.positive]
allocations = 26362
bytes = 1002632
compile_seconds = 0.0
samples = 3
seconds = 0.000544999

[probes.unit_negative]
allocations = 25338
bytes = 963752
compile_seconds = 0.0
samples = 3
seconds = 0.000501999

[probes.unit_positive]
allocations = 25338
bytes = 963992
compile_seconds = 0.0
samples = 3
seconds = 0.0005193

[probes.zero_rhs]
allocations = 22778
bytes = 879016
compile_seconds = 0.0
samples = 3
seconds = 0.000471501
