julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4115512
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034842
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461400
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010093
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3327096
compile_seconds = 0.0
samples = 3
seconds = 0.0022475

[datasets.adlittle.primal]
allocations = 85246
bytes = 4392280
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037903
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607296
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011785
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641384
compile_seconds = 0.0
samples = 3
seconds = 0.0004744

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.98e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174008
compile_seconds = 0.0
samples = 3
seconds = 0.0001582

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.afiro.dual]
allocations = 16971
bytes = 861088
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007822
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002209
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16156
bytes = 725104
compile_seconds = 0.0
samples = 3
seconds = 0.0006181

[datasets.afiro.primal]
allocations = 16877
bytes = 839120
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007393
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002101
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92504
compile_seconds = 0.0
samples = 3
seconds = 9.71e-5

[datasets.afiro.singleton]
allocations = 782
bytes = 42024
compile_seconds = 0.0
samples = 3
seconds = 7.34e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213424
compile_seconds = 0.0
samples = 3
seconds = 0.0001573

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.8e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279624
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001133
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001649
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170416
compile_seconds = 0.0
samples = 3
seconds = 0.0007508

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324328
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0010059
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001967
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122272
compile_seconds = 0.0
samples = 3
seconds = 0.0001066

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.52e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209784
compile_seconds = 0.0
samples = 3
seconds = 0.0001434

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 7.1e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.kb2.dual]
allocations = 230300
bytes = 11087392
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020833399
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009031
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229098
bytes = 10635824
compile_seconds = 0.0
samples = 3
seconds = 0.0204701

[datasets.kb2.primal]
allocations = 230467
bytes = 11101792
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022034199
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006233
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454400
compile_seconds = 0.0
samples = 3
seconds = 0.000285

[datasets.kb2.singleton]
allocations = 1964
bytes = 107616
compile_seconds = 0.0
samples = 3
seconds = 9.24e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161504
compile_seconds = 0.0
samples = 3
seconds = 0.0001285

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.57e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191928
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0021997
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306208
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005553
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2845912
compile_seconds = 0.0
samples = 3
seconds = 0.001638899

[datasets.sc50a.primal]
allocations = 68474
bytes = 3145128
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0021867
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005126
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221888
compile_seconds = 0.0
samples = 3
seconds = 0.0001692

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.83e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299168
compile_seconds = 0.0
samples = 3
seconds = 0.0002132

[probes.nonunit]
allocations = 26880
bytes = 1016584
compile_seconds = 0.0
samples = 3
seconds = 0.0005607

[probes.ratio_negative]
allocations = 25088
bytes = 943896
compile_seconds = 0.0
samples = 3
seconds = 0.0005318

[probes.ratio_positive]
allocations = 24576
bytes = 928184
compile_seconds = 0.0
samples = 3
seconds = 0.0005907

[probes.term_negative]
allocations = 25984
bytes = 980312
compile_seconds = 0.0
samples = 3
seconds = 0.0005182

[probes.term_positive]
allocations = 25728
bytes = 972936
compile_seconds = 0.0
samples = 3
seconds = 0.0005716

[probes.zero_ratio]
allocations = 19968
bytes = 777480
compile_seconds = 0.0
samples = 3
seconds = 0.0004554
