julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4116760
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0030527
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000889
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3328296
compile_seconds = 0.0
samples = 3
seconds = 0.0019549

[datasets.adlittle.primal]
allocations = 85246
bytes = 4394536
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0032164
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607456
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011203
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641400
compile_seconds = 0.0
samples = 3
seconds = 0.0003937

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.38e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174040
compile_seconds = 0.0
samples = 3
seconds = 0.0001025

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.afiro.dual]
allocations = 17023
bytes = 863416
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007749
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001994
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16208
bytes = 727224
compile_seconds = 0.0
samples = 3
seconds = 0.0007207

[datasets.afiro.primal]
allocations = 16929
bytes = 841240
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007369
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002231
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92664
compile_seconds = 0.0
samples = 3
seconds = 0.0001042

[datasets.afiro.singleton]
allocations = 834
bytes = 44592
compile_seconds = 0.0
samples = 3
seconds = 9.11e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213456
compile_seconds = 0.0
samples = 3
seconds = 0.0001818

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279400
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008816
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001538
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170384
compile_seconds = 0.0
samples = 3
seconds = 0.0007318

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324296
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009413
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001852
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122608
compile_seconds = 0.0
samples = 3
seconds = 0.0001035

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.93e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209720
compile_seconds = 0.0
samples = 3
seconds = 0.00013

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.kb2.dual]
allocations = 230351
bytes = 11091888
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0198012
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007492
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229149
bytes = 10639536
compile_seconds = 0.0
samples = 3
seconds = 0.0193354

[datasets.kb2.primal]
allocations = 230518
bytes = 11104912
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023431
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005729
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454288
compile_seconds = 0.0
samples = 3
seconds = 0.0002212

[datasets.kb2.singleton]
allocations = 2015
bytes = 109520
compile_seconds = 0.0
samples = 3
seconds = 6.46e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161504
compile_seconds = 0.0
samples = 3
seconds = 8.78e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.89e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191976
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020849
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306112
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006217
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846696
compile_seconds = 0.0
samples = 3
seconds = 0.0015353

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144760
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022711
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005107
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221888
compile_seconds = 0.0
samples = 3
seconds = 0.0001589

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.79e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299168
compile_seconds = 0.0
samples = 3
seconds = 0.0002004

[probes.cancel_fraction]
allocations = 53515
bytes = 2054056
compile_seconds = 0.0
samples = 3
seconds = 0.0009775

[probes.cancel_integer]
allocations = 50315
bytes = 1913096
compile_seconds = 0.0
samples = 3
seconds = 0.0009903

[probes.sum_fraction]
allocations = 55051
bytes = 2106744
compile_seconds = 0.0
samples = 3
seconds = 0.0011083

[probes.sum_integer]
allocations = 51851
bytes = 1968008
compile_seconds = 0.0
samples = 3
seconds = 0.0009841

[probes.unequal_denominator]
allocations = 54923
bytes = 2104360
compile_seconds = 0.0
samples = 3
seconds = 0.0011099

[probes.zero_rhs]
allocations = 46219
bytes = 1772248
compile_seconds = 0.0
samples = 3
seconds = 0.0008681
