julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 122716
bytes = 5663912
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.004569399
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461416
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009159
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 120701
bytes = 4874296
compile_seconds = 0.0
samples = 3
seconds = 0.0023285

[datasets.adlittle.primal]
allocations = 123514
bytes = 5939624
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003970399
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607280
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.00114
status = "OPTIMAL"

[datasets.adlittle.singleton_rows]
allocations = 275
bytes = 43192
compile_seconds = 0.0
samples = 3
seconds = 6.21e-5

[datasets.afiro.dual]
allocations = 28383
bytes = 1310664
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008128
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001949
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 27568
bytes = 1174648
compile_seconds = 0.0
samples = 3
seconds = 0.000629

[datasets.afiro.primal]
allocations = 28289
bytes = 1288344
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007981
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001954
status = "OPTIMAL"

[datasets.afiro.singleton_rows]
allocations = 187
bytes = 16800
compile_seconds = 0.0
samples = 3
seconds = 3.81e-5

[datasets.flugpl.dual]
allocations = 39870
bytes = 1615592
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.00089
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001533
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 39199
bytes = 1505040
compile_seconds = 0.0
samples = 3
seconds = 0.0007084

[datasets.flugpl.primal]
allocations = 40219
bytes = 1660104
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008702
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001617
status = "OPTIMAL"

[datasets.flugpl.singleton_rows]
allocations = 159
bytes = 11864
compile_seconds = 0.0
samples = 3
seconds = 2.55e-5

[datasets.kb2.dual]
allocations = 293454
bytes = 13621056
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021539599
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878192
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007885
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 292252
bytes = 13166096
compile_seconds = 0.0
samples = 3
seconds = 0.021210099

[datasets.kb2.primal]
allocations = 293621
bytes = 13634896
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021195598
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005747
status = "OPTIMAL"

[datasets.kb2.singleton_rows]
allocations = 16
bytes = 4480
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.sc50a.dual]
allocations = 107114
bytes = 4650576
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022762
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306480
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000525
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 106042
bytes = 4304176
compile_seconds = 0.0
samples = 3
seconds = 0.0019417

[datasets.sc50a.primal]
allocations = 107059
bytes = 4603648
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002749
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004796
status = "OPTIMAL"

[datasets.sc50a.singleton_rows]
allocations = 16
bytes = 5200
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[probes.all_singletons]
allocations = 12852
bytes = 481816
compile_seconds = 0.0
samples = 3
seconds = 0.0002671

[probes.no_singletons]
allocations = 21
bytes = 12232
compile_seconds = 0.0
samples = 3
seconds = 3.21e-5
