julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4117608
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003495301
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461240
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000965701
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3328648
compile_seconds = 0.0
samples = 3
seconds = 0.0022222

[datasets.adlittle.primal]
allocations = 85246
bytes = 4394584
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0034669
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607728
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011444
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641624
compile_seconds = 0.0
samples = 3
seconds = 0.000431

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 4.81e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174024
compile_seconds = 0.0
samples = 3
seconds = 0.0001053

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 864200
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007403
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002522
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 728168
compile_seconds = 0.0
samples = 3
seconds = 0.0005847

[datasets.afiro.primal]
allocations = 16938
bytes = 842392
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000795801
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001839
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92040
compile_seconds = 0.0
samples = 3
seconds = 0.0001041

[datasets.afiro.singleton]
allocations = 843
bytes = 44720
compile_seconds = 0.0
samples = 3
seconds = 8.16e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213568
compile_seconds = 0.0
samples = 3
seconds = 0.0002438

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.1e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279512
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009078
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001766
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1169584
compile_seconds = 0.0
samples = 3
seconds = 0.000795

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324168
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009653
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001938
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 122528
compile_seconds = 0.0
samples = 3
seconds = 0.0001212

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.86e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210120
compile_seconds = 0.0
samples = 3
seconds = 0.0001432

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 5.9e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.kb2.dual]
allocations = 230351
bytes = 11090256
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021063804
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877856
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008657
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229149
bytes = 10638688
compile_seconds = 0.0
samples = 3
seconds = 0.020803603

[datasets.kb2.primal]
allocations = 230518
bytes = 11104368
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021740203
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006071
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454912
compile_seconds = 0.0
samples = 3
seconds = 0.0002887

[datasets.kb2.singleton]
allocations = 2015
bytes = 110160
compile_seconds = 0.0
samples = 3
seconds = 9.98e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 161680
compile_seconds = 0.0
samples = 3
seconds = 0.0001251

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.84e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.9e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3192840
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002315001
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005885
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846344
compile_seconds = 0.0
samples = 3
seconds = 0.0014966

[datasets.sc50a.primal]
allocations = 68474
bytes = 3145352
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002239601
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232184
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005732
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222064
compile_seconds = 0.0
samples = 3
seconds = 0.0001673

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.71e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299328
compile_seconds = 0.0
samples = 3
seconds = 0.0001985

[probes.nonunit]
allocations = 27136
bytes = 1030824
compile_seconds = 0.0
samples = 3
seconds = 0.000550601

[probes.ratio_negative]
allocations = 26240
bytes = 994440
compile_seconds = 0.0
samples = 3
seconds = 0.000500201

[probes.ratio_positive]
allocations = 25981
bytes = 986096
compile_seconds = 0.0
samples = 3
seconds = 0.0005403

[probes.rhs_negative]
allocations = 26240
bytes = 994280
compile_seconds = 0.0
samples = 3
seconds = 0.000525601

[probes.rhs_positive]
allocations = 25984
bytes = 987368
compile_seconds = 0.0
samples = 3
seconds = 0.000546501

[probes.zero_rhs]
allocations = 23168
bytes = 888936
compile_seconds = 0.0
samples = 3
seconds = 0.000456601
