julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 8.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4116696
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0033556
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461064
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009788
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3327432
compile_seconds = 0.0
samples = 3
seconds = 0.0021333

[datasets.adlittle.primal]
allocations = 85246
bytes = 4393624
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037866
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607328
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010834
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641368
compile_seconds = 0.0
samples = 3
seconds = 0.0003844

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.69e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174104
compile_seconds = 0.0
samples = 3
seconds = 0.0001257

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.afiro.dual]
allocations = 16936
bytes = 859432
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008278
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.000213
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16121
bytes = 724104
compile_seconds = 0.0
samples = 3
seconds = 0.0005879

[datasets.afiro.primal]
allocations = 16842
bytes = 838328
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008416
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002293
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92376
compile_seconds = 0.0
samples = 3
seconds = 0.0001021

[datasets.afiro.singleton]
allocations = 747
bytes = 40688
compile_seconds = 0.0
samples = 3
seconds = 7.47e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 213600
compile_seconds = 0.0
samples = 3
seconds = 0.0001728

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.2e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279864
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009357
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001596
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170368
compile_seconds = 0.0
samples = 3
seconds = 0.0007517

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324568
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001006
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001805
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123520
compile_seconds = 0.0
samples = 3
seconds = 0.0001099

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.65e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210024
compile_seconds = 0.0
samples = 3
seconds = 0.0001472

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 4.4e-6

[datasets.kb2.dual]
allocations = 230251
bytes = 11087432
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021420699
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878064
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000838
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229049
bytes = 10634216
compile_seconds = 0.0
samples = 3
seconds = 0.0201075

[datasets.kb2.primal]
allocations = 230418
bytes = 11100456
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021599999
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006216
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454320
compile_seconds = 0.0
samples = 3
seconds = 0.0002434

[datasets.kb2.singleton]
allocations = 1915
bytes = 104792
compile_seconds = 0.0
samples = 3
seconds = 8.88e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162368
compile_seconds = 0.0
samples = 3
seconds = 0.0001191

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.87e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.8e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3192760
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0020423
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306528
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000599
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846584
compile_seconds = 0.0
samples = 3
seconds = 0.0015575

[datasets.sc50a.primal]
allocations = 68474
bytes = 3145448
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020629
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005091
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222368
compile_seconds = 0.0
samples = 3
seconds = 0.0001986

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.35e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299264
compile_seconds = 0.0
samples = 3
seconds = 0.0001957

[probes.fraction_negative]
allocations = 53387
bytes = 2013736
compile_seconds = 0.0
samples = 3
seconds = 0.0011816

[probes.fraction_positive]
allocations = 53387
bytes = 2013800
compile_seconds = 0.0
samples = 3
seconds = 0.001074

[probes.integer_negative]
allocations = 53131
bytes = 2000264
compile_seconds = 0.0
samples = 3
seconds = 0.0009935

[probes.integer_positive]
allocations = 53131
bytes = 1997192
compile_seconds = 0.0
samples = 3
seconds = 0.0010546

[probes.unequal_denominator]
allocations = 53387
bytes = 2022856
compile_seconds = 0.0
samples = 3
seconds = 0.0010913

[probes.zero_ratio]
allocations = 39819
bytes = 1551304
compile_seconds = 0.0
samples = 3
seconds = 0.000794
