julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4116808
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0034043
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461224
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009916
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3328424
compile_seconds = 0.0
samples = 3
seconds = 0.0021492

[datasets.adlittle.primal]
allocations = 85246
bytes = 4394568
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0038539
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607792
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011971
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 642264
compile_seconds = 0.0
samples = 3
seconds = 0.000387

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 6.78e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 175000
compile_seconds = 0.0
samples = 3
seconds = 0.0001123

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.1e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.0e-6

[datasets.afiro.dual]
allocations = 16936
bytes = 861032
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007604
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002123
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16121
bytes = 724824
compile_seconds = 0.0
samples = 3
seconds = 0.0006215

[datasets.afiro.primal]
allocations = 16842
bytes = 839096
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0006522
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002256
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92888
compile_seconds = 0.0
samples = 3
seconds = 0.0001026

[datasets.afiro.singleton]
allocations = 747
bytes = 41008
compile_seconds = 0.0
samples = 3
seconds = 7.33e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214240
compile_seconds = 0.0
samples = 3
seconds = 0.000170299

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.6e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279784
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009429
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001544
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170352
compile_seconds = 0.0
samples = 3
seconds = 0.0007426

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324232
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009722
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001921
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123024
compile_seconds = 0.0
samples = 3
seconds = 0.000114

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.77e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 210792
compile_seconds = 0.0
samples = 3
seconds = 0.0001442

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 8.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.dual]
allocations = 230251
bytes = 11087752
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.021039899
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878240
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008968
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229049
bytes = 10635784
compile_seconds = 0.0
samples = 3
seconds = 0.021690098

[datasets.kb2.primal]
allocations = 230418
bytes = 11100568
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021355699
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260816
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006458
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 455520
compile_seconds = 0.0
samples = 3
seconds = 0.0002888

[datasets.kb2.singleton]
allocations = 1915
bytes = 105544
compile_seconds = 0.0
samples = 3
seconds = 9.08e-5

[datasets.kb2.sparse]
allocations = 2836
bytes = 162448
compile_seconds = 0.0
samples = 3
seconds = 0.0001217

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.78e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.3e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191848
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0019832
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306288
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006132
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846936
compile_seconds = 0.0
samples = 3
seconds = 0.0016926

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144952
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0020875
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232200
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005057
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222720
compile_seconds = 0.0
samples = 3
seconds = 0.0001409

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.27e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 300016
compile_seconds = 0.0
samples = 3
seconds = 0.0001921

[probes.negative]
allocations = 26234
bytes = 994296
compile_seconds = 0.0
samples = 3
seconds = 0.0005297

[probes.nonzero_cost]
allocations = 26880
bytes = 1017272
compile_seconds = 0.0
samples = 3
seconds = 0.0005212

[probes.positive]
allocations = 26234
bytes = 992792
compile_seconds = 0.0
samples = 3
seconds = 0.0005325

[probes.unit_negative]
allocations = 24186
bytes = 914376
compile_seconds = 0.0
samples = 3
seconds = 0.0005808

[probes.unit_positive]
allocations = 24186
bytes = 914296
compile_seconds = 0.0
samples = 3
seconds = 0.0004913

[probes.zero_ratio]
allocations = 19578
bytes = 768696
compile_seconds = 0.0
samples = 3
seconds = 0.0004535
