julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 6.3e-6

[datasets.adlittle.dual]
allocations = 84448
bytes = 4115912
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003322966
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.001047089
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 82433
bytes = 3326504
compile_seconds = 0.0
samples = 3
seconds = 0.002194377

[datasets.adlittle.primal]
allocations = 85246
bytes = 4392792
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.004128357
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607536
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001302786
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18182
bytes = 641800
compile_seconds = 0.0
samples = 3
seconds = 0.0004193

[datasets.adlittle.singleton]
allocations = 608
bytes = 60816
compile_seconds = 0.0
samples = 3
seconds = 7.39e-5

[datasets.adlittle.sparse]
allocations = 2747
bytes = 174264
compile_seconds = 0.0
samples = 3
seconds = 0.0001424

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.5e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 17032
bytes = 864088
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000757899
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002368
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 16217
bytes = 728632
compile_seconds = 0.0
samples = 3
seconds = 0.000607599

[datasets.afiro.primal]
allocations = 16938
bytes = 842536
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000678599
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002004
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93208
compile_seconds = 0.0
samples = 3
seconds = 8.06e-5

[datasets.afiro.singleton]
allocations = 843
bytes = 45024
compile_seconds = 0.0
samples = 3
seconds = 7.63e-5

[datasets.afiro.sparse]
allocations = 4891
bytes = 214448
compile_seconds = 0.0
samples = 3
seconds = 0.000182499

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 4.0e-6

[datasets.flugpl.dual]
allocations = 31462
bytes = 1279992
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001072103
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000162501
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 30791
bytes = 1170528
compile_seconds = 0.0
samples = 3
seconds = 0.000835103

[datasets.flugpl.primal]
allocations = 31811
bytes = 1324920
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.001014503
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000200401
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123088
compile_seconds = 0.0
samples = 3
seconds = 0.0001215

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.74e-5

[datasets.flugpl.sparse]
allocations = 5598
bytes = 209992
compile_seconds = 0.0
samples = 3
seconds = 0.0001763

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.4e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.kb2.dual]
allocations = 230351
bytes = 11092336
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020996382
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877984
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.000857291
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 229149
bytes = 10639040
compile_seconds = 0.0
samples = 3
seconds = 0.020965382

[datasets.kb2.primal]
allocations = 230518
bytes = 11106384
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.021449077
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260960
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.000630293
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454656
compile_seconds = 0.0
samples = 3
seconds = 0.000262797

[datasets.kb2.singleton]
allocations = 2015
bytes = 109584
compile_seconds = 0.0
samples = 3
seconds = 0.000119298

[datasets.kb2.sparse]
allocations = 2836
bytes = 161984
compile_seconds = 0.0
samples = 3
seconds = 0.000132599

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.93e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.6e-6

[datasets.sc50a.dual]
allocations = 68529
bytes = 3191352
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002218699
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306128
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005818
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 67457
bytes = 2846504
compile_seconds = 0.0
samples = 3
seconds = 0.0015197

[datasets.sc50a.primal]
allocations = 68474
bytes = 3144120
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.002275199
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232232
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000562
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 223008
compile_seconds = 0.0
samples = 3
seconds = 0.0001764

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.95e-5

[datasets.sc50a.sparse]
allocations = 6618
bytes = 299920
compile_seconds = 0.0
samples = 3
seconds = 0.0002227

[probes.negative]
allocations = 23168
bytes = 888184
compile_seconds = 0.0
samples = 3
seconds = 0.000456401

[probes.nonzero_rhs]
allocations = 27136
bytes = 1030296
compile_seconds = 0.0
samples = 3
seconds = 0.000583999

[probes.positive]
allocations = 23168
bytes = 886408
compile_seconds = 0.0
samples = 3
seconds = 0.000519201

[probes.unit_negative]
allocations = 23168
bytes = 888408
compile_seconds = 0.0
samples = 3
seconds = 0.000469699

[probes.unit_positive]
allocations = 23165
bytes = 888304
compile_seconds = 0.0
samples = 3
seconds = 0.000436701

[probes.zero_ratio]
allocations = 18304
bytes = 722872
compile_seconds = 0.0
samples = 3
seconds = 0.0003779
