julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "after"
presolve = false
scaling = "off"
threads = 1

[[kernels]]
allocations = 0
basis_refactorization = "native"
basis_update = "forrest_tomlin"
bytes = 0
compile_seconds = 0.0
dimension = 4
samples = 3
seconds = 8.6e-6
updates = 16
[[kernels]]
allocations = 0
basis_refactorization = "native"
basis_update = "suhl_suhl"
bytes = 0
compile_seconds = 0.0
dimension = 4
samples = 3
seconds = 1.2e-5
updates = 16
[[kernels]]
allocations = 0
basis_refactorization = "native"
basis_update = "bartels_golub"
bytes = 0
compile_seconds = 0.0
dimension = 4
samples = 3
seconds = 1.03e-5
updates = 16
[[kernels]]
allocations = 0
basis_refactorization = "native"
basis_update = "forrest_tomlin"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 4.51e-5
updates = 64
[[kernels]]
allocations = 0
basis_refactorization = "native"
basis_update = "suhl_suhl"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 3.83e-5
updates = 64
[[kernels]]
allocations = 0
basis_refactorization = "native"
basis_update = "bartels_golub"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.0001091
updates = 64
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
basis_update = "forrest_tomlin"
bytes = 0
compile_seconds = 0.0
dimension = 4
samples = 3
seconds = 1.05e-5
updates = 16
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
basis_update = "suhl_suhl"
bytes = 0
compile_seconds = 0.0
dimension = 4
samples = 3
seconds = 1.58e-5
updates = 16
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
basis_update = "bartels_golub"
bytes = 0
compile_seconds = 0.0
dimension = 4
samples = 3
seconds = 1.09e-5
updates = 16
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
basis_update = "forrest_tomlin"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 4.91e-5
updates = 64
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
basis_update = "suhl_suhl"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 3.92e-5
updates = 64
[[kernels]]
allocations = 0
basis_refactorization = "markowitz"
basis_update = "bartels_golub"
bytes = 0
compile_seconds = 0.0
dimension = 64
samples = 3
seconds = 0.0001059
updates = 64

[[rows]]
algorithm = "dual"
allocations = 1734
basis_update = "pfi"
bytes = 412040
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004804
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 460
basis_update = "pfi"
bytes = 78784
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002145
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1887
basis_update = "pfi"
bytes = 413360
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004037
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 614
basis_update = "pfi"
bytes = 109104
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002075
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1990
basis_update = "forrest_tomlin"
bytes = 423992
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005137
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 714
basis_update = "forrest_tomlin"
bytes = 89904
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000266
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2145
basis_update = "forrest_tomlin"
bytes = 427664
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004481
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 876
basis_update = "forrest_tomlin"
bytes = 121168
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002101
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1992
basis_update = "suhl_suhl"
bytes = 425080
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004436
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 706
basis_update = "suhl_suhl"
bytes = 89856
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002561
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2141
basis_update = "suhl_suhl"
bytes = 428480
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0003937
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 874
basis_update = "suhl_suhl"
bytes = 122432
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002117
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2106
basis_update = "bartels_golub"
bytes = 430600
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005859
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 825
basis_update = "bartels_golub"
bytes = 96576
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002397
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2233
basis_update = "bartels_golub"
bytes = 432624
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000507
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 965
basis_update = "bartels_golub"
bytes = 128544
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002775
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1763
basis_update = "pfi"
bytes = 903432
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0013546
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 920
basis_update = "pfi"
bytes = 508528
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001518499
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7252
basis_update = "pfi"
bytes = 5878200
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003297399
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1025
basis_update = "pfi"
bytes = 567272
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0013869
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2409
basis_update = "forrest_tomlin"
bytes = 972136
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017329
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1556
basis_update = "forrest_tomlin"
bytes = 550560
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016162
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7832
basis_update = "forrest_tomlin"
bytes = 5927992
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0034291
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1655
basis_update = "forrest_tomlin"
bytes = 619976
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016407
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2425
basis_update = "suhl_suhl"
bytes = 987128
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017568
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1546
basis_update = "suhl_suhl"
bytes = 551536
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015488
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7836
basis_update = "suhl_suhl"
bytes = 5930568
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0034341
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1661
basis_update = "suhl_suhl"
bytes = 626744
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001686099
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2677
basis_update = "bartels_golub"
bytes = 982184
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0018995
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1828
basis_update = "bartels_golub"
bytes = 568704
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016681
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8007
basis_update = "bartels_golub"
bytes = 5935624
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0035411
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1836
basis_update = "bartels_golub"
bytes = 634488
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017949
status = "OPTIMAL"
