julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "before"
presolve = false
scaling = "off"
threads = 1

[[rows]]
algorithm = "dual"
allocations = 1880
basis_update = "pfi"
bytes = 430808
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004782
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 461
basis_update = "pfi"
bytes = 78496
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002108
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2038
basis_update = "pfi"
bytes = 434480
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004496
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 616
basis_update = "pfi"
bytes = 109712
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002516
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 4022
basis_update = "forrest_tomlin"
bytes = 510120
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005726
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 871
basis_update = "forrest_tomlin"
bytes = 95216
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0003421
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 4172
basis_update = "forrest_tomlin"
bytes = 513392
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.00051
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1024
basis_update = "forrest_tomlin"
bytes = 126880
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002119
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 4022
basis_update = "suhl_suhl"
bytes = 510440
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006289
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 863
basis_update = "suhl_suhl"
bytes = 95168
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002682
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 4174
basis_update = "suhl_suhl"
bytes = 514240
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004799
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1024
basis_update = "suhl_suhl"
bytes = 128240
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000295
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 4138
basis_update = "bartels_golub"
bytes = 517336
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005339
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 978
basis_update = "bartels_golub"
bytes = 101504
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002623
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 4260
basis_update = "bartels_golub"
bytes = 519072
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000454
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1111
basis_update = "bartels_golub"
bytes = 133936
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.00027
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2110
basis_update = "pfi"
bytes = 944728
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0011994
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1206
basis_update = "pfi"
bytes = 541888
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015033
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8059
basis_update = "pfi"
bytes = 6181560
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0032797
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1244
basis_update = "pfi"
bytes = 583448
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0013194
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 6654
basis_update = "forrest_tomlin"
bytes = 1162872
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017473
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3266
basis_update = "forrest_tomlin"
bytes = 641824
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015752
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 27445
basis_update = "forrest_tomlin"
bytes = 6889224
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0033887
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 3272
basis_update = "forrest_tomlin"
bytes = 702536
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017313
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 6644
basis_update = "suhl_suhl"
bytes = 1169816
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017102
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3242
basis_update = "suhl_suhl"
bytes = 642256
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015318
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 27445
basis_update = "suhl_suhl"
bytes = 6889016
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003718699
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 3258
basis_update = "suhl_suhl"
bytes = 703752
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016315
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 6741
basis_update = "bartels_golub"
bytes = 1157096
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0020366
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3399
basis_update = "bartels_golub"
bytes = 639888
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0018137
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 27619
basis_update = "bartels_golub"
bytes = 6904136
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0035408
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 3329
basis_update = "bartels_golub"
bytes = 702888
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0018661
status = "OPTIMAL"
