julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "after"
presolve = false
scaling = "off"
threads = 1

[[rows]]
algorithm = "dual"
allocations = 1880
basis_update = "pfi"
bytes = 429976
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004896
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 461
basis_update = "pfi"
bytes = 78496
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002137
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2038
basis_update = "pfi"
bytes = 433984
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004812
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 616
basis_update = "pfi"
bytes = 109712
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002214
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2152
basis_update = "forrest_tomlin"
bytes = 441848
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005752
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 761
basis_update = "forrest_tomlin"
bytes = 91232
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002773
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2302
basis_update = "forrest_tomlin"
bytes = 445312
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005262
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 914
basis_update = "forrest_tomlin"
bytes = 122896
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002121
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2152
basis_update = "suhl_suhl"
bytes = 442136
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006772
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 753
basis_update = "suhl_suhl"
bytes = 91184
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002772
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2304
basis_update = "suhl_suhl"
bytes = 445600
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004569
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 914
basis_update = "suhl_suhl"
bytes = 124256
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002923
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2268
basis_update = "bartels_golub"
bytes = 449176
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005738
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 868
basis_update = "bartels_golub"
bytes = 97520
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002853
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2390
basis_update = "bartels_golub"
bytes = 451072
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005382
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1001
basis_update = "bartels_golub"
bytes = 129952
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.000274
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2110
basis_update = "pfi"
bytes = 944664
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0013166
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1206
basis_update = "pfi"
bytes = 541824
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0014243
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8059
basis_update = "pfi"
bytes = 6180104
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0032758
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1244
basis_update = "pfi"
bytes = 583320
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0013615
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3038
basis_update = "forrest_tomlin"
bytes = 1031512
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001698899
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2136
basis_update = "forrest_tomlin"
bytes = 601056
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0014968
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8687
basis_update = "forrest_tomlin"
bytes = 6206296
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0034227
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2142
basis_update = "forrest_tomlin"
bytes = 661400
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016035
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3028
basis_update = "suhl_suhl"
bytes = 1038472
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017371
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2112
basis_update = "suhl_suhl"
bytes = 601504
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015095
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8687
basis_update = "suhl_suhl"
bytes = 6206200
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.00359
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2128
basis_update = "suhl_suhl"
bytes = 662600
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016485
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 3125
basis_update = "bartels_golub"
bytes = 1025736
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0016786
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2269
basis_update = "bartels_golub"
bytes = 598944
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016981
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8861
basis_update = "bartels_golub"
bytes = 6221624
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0032149
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2199
basis_update = "bartels_golub"
bytes = 661752
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001801
status = "OPTIMAL"
