julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "after"
presolve = false
scaling = "off"
threads = 1

[[kernels]]
allocations = 32
basis_update = "pfi"
bytes = 54400
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 6.91e-5
[[kernels]]
allocations = 32
basis_update = "forrest_tomlin"
bytes = 54400
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 5.24e-5
[[kernels]]
allocations = 32
basis_update = "suhl_suhl"
bytes = 54400
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 5.5e-5
[[kernels]]
allocations = 32
basis_update = "bartels_golub"
bytes = 54400
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 5.69e-5
[[kernels]]
allocations = 64
basis_update = "pfi"
bytes = 91424
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.000263899
[[kernels]]
allocations = 64
basis_update = "forrest_tomlin"
bytes = 91424
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.00026
[[kernels]]
allocations = 64
basis_update = "suhl_suhl"
bytes = 91424
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.0002488
[[kernels]]
allocations = 64
basis_update = "bartels_golub"
bytes = 91424
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.0002648
[[kernels]]
allocations = 32
basis_update = "pfi"
bytes = 331088
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.0001938
[[kernels]]
allocations = 32
basis_update = "forrest_tomlin"
bytes = 331088
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.0002106
[[kernels]]
allocations = 32
basis_update = "suhl_suhl"
bytes = 331088
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.000185
[[kernels]]
allocations = 32
basis_update = "bartels_golub"
bytes = 331088
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.0002091
[[kernels]]
allocations = 64
basis_update = "pfi"
bytes = 592816
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.0003827
[[kernels]]
allocations = 64
basis_update = "forrest_tomlin"
bytes = 592816
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.0003738
[[kernels]]
allocations = 64
basis_update = "suhl_suhl"
bytes = 592816
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.000434599
[[kernels]]
allocations = 64
basis_update = "bartels_golub"
bytes = 592816
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.0004026
[[kernels]]
allocations = 32
basis_update = "pfi"
bytes = 2544560
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.000734099
[[kernels]]
allocations = 32
basis_update = "forrest_tomlin"
bytes = 2544560
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.0009794
[[kernels]]
allocations = 32
basis_update = "suhl_suhl"
bytes = 2544560
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.000943199
[[kernels]]
allocations = 32
basis_update = "bartels_golub"
bytes = 2544560
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.000945399
[[kernels]]
allocations = 64
basis_update = "pfi"
bytes = 4628384
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.0011997
[[kernels]]
allocations = 64
basis_update = "forrest_tomlin"
bytes = 4628384
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.001337599
[[kernels]]
allocations = 64
basis_update = "suhl_suhl"
bytes = 4628384
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.001296299
[[kernels]]
allocations = 64
basis_update = "bartels_golub"
bytes = 4628384
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.0014126

[[rows]]
algorithm = "dual"
allocations = 1471
basis_update = "pfi"
bytes = 378280
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005404
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 462
basis_update = "pfi"
bytes = 78832
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002282
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1529
basis_update = "pfi"
bytes = 359296
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0003873
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 616
basis_update = "pfi"
bytes = 109168
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0001783
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1727
basis_update = "forrest_tomlin"
bytes = 390728
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005294
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 716
basis_update = "forrest_tomlin"
bytes = 89968
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002769
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1787
basis_update = "forrest_tomlin"
bytes = 372352
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0003796
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 878
basis_update = "forrest_tomlin"
bytes = 121232
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002455
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1729
basis_update = "suhl_suhl"
bytes = 392056
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005943
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 708
basis_update = "suhl_suhl"
bytes = 89920
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002637
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1783
basis_update = "suhl_suhl"
bytes = 372800
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005056
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 876
basis_update = "suhl_suhl"
bytes = 122496
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002624
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1843
basis_update = "bartels_golub"
bytes = 396696
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006207
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 827
basis_update = "bartels_golub"
bytes = 96640
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002925
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1875
basis_update = "bartels_golub"
bytes = 376512
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006031
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 967
basis_update = "bartels_golub"
bytes = 128608
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002774
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1527
basis_update = "pfi"
bytes = 857512
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0013206
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 867
basis_update = "pfi"
bytes = 503024
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015102
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 5544
basis_update = "pfi"
bytes = 5410504
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.002942899
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 955
basis_update = "pfi"
bytes = 567192
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0013857
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2173
basis_update = "forrest_tomlin"
bytes = 926024
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017328
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1503
basis_update = "forrest_tomlin"
bytes = 545536
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016269
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 6124
basis_update = "forrest_tomlin"
bytes = 5460440
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0031146
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1585
basis_update = "forrest_tomlin"
bytes = 619864
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0015362
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2189
basis_update = "suhl_suhl"
bytes = 941112
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0016517
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1493
basis_update = "suhl_suhl"
bytes = 546480
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016813
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 6128
basis_update = "suhl_suhl"
bytes = 5463128
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003412399
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1591
basis_update = "suhl_suhl"
bytes = 626488
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001770599
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2441
basis_update = "bartels_golub"
bytes = 936616
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017563
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1775
basis_update = "bartels_golub"
bytes = 564304
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017997
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 6299
basis_update = "bartels_golub"
bytes = 5467976
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003350099
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1766
basis_update = "bartels_golub"
bytes = 634376
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001912499
status = "OPTIMAL"
