julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
mode = "before"
presolve = false
scaling = "off"
threads = 1

[[kernels]]
allocations = 81
basis_update = "pfi"
bytes = 84128
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 0.0001355
[[kernels]]
allocations = 81
basis_update = "forrest_tomlin"
bytes = 84128
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 0.0001401
[[kernels]]
allocations = 81
basis_update = "suhl_suhl"
bytes = 84128
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 0.000127599
[[kernels]]
allocations = 81
basis_update = "bartels_golub"
bytes = 84128
compile_seconds = 0.0
dimension = 64
pattern = "same"
samples = 3
seconds = 0.000123
[[kernels]]
allocations = 81
basis_update = "pfi"
bytes = 88336
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.0001388
[[kernels]]
allocations = 81
basis_update = "forrest_tomlin"
bytes = 88336
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.0001307
[[kernels]]
allocations = 81
basis_update = "suhl_suhl"
bytes = 88336
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.000133
[[kernels]]
allocations = 81
basis_update = "bartels_golub"
bytes = 88336
compile_seconds = 0.0
dimension = 64
pattern = "changed"
samples = 3
seconds = 0.0001194
[[kernels]]
allocations = 86
basis_update = "pfi"
bytes = 549336
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.0003718
[[kernels]]
allocations = 86
basis_update = "forrest_tomlin"
bytes = 549336
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.0003957
[[kernels]]
allocations = 86
basis_update = "suhl_suhl"
bytes = 549336
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.000384899
[[kernels]]
allocations = 86
basis_update = "bartels_golub"
bytes = 549336
compile_seconds = 0.0
dimension = 512
pattern = "same"
samples = 3
seconds = 0.000374999
[[kernels]]
allocations = 86
basis_update = "pfi"
bytes = 579352
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.0003582
[[kernels]]
allocations = 86
basis_update = "forrest_tomlin"
bytes = 579352
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.000367
[[kernels]]
allocations = 86
basis_update = "suhl_suhl"
bytes = 579352
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.000383499
[[kernels]]
allocations = 86
basis_update = "bartels_golub"
bytes = 579352
compile_seconds = 0.0
dimension = 512
pattern = "changed"
samples = 3
seconds = 0.0003937
[[kernels]]
allocations = 86
basis_update = "pfi"
bytes = 4272936
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.001685599
[[kernels]]
allocations = 86
basis_update = "forrest_tomlin"
bytes = 4272936
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.001792699
[[kernels]]
allocations = 86
basis_update = "suhl_suhl"
bytes = 4272936
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.001658799
[[kernels]]
allocations = 86
basis_update = "bartels_golub"
bytes = 4272936
compile_seconds = 0.0
dimension = 4096
pattern = "same"
samples = 3
seconds = 0.001718899
[[kernels]]
allocations = 86
basis_update = "pfi"
bytes = 4510504
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.001822299
[[kernels]]
allocations = 86
basis_update = "forrest_tomlin"
bytes = 4510504
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.001734599
[[kernels]]
allocations = 86
basis_update = "suhl_suhl"
bytes = 4510504
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.001853499
[[kernels]]
allocations = 86
basis_update = "bartels_golub"
bytes = 4510504
compile_seconds = 0.0
dimension = 4096
pattern = "changed"
samples = 3
seconds = 0.001771099

[[rows]]
algorithm = "dual"
allocations = 1736
basis_update = "pfi"
bytes = 412712
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.000432
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 462
basis_update = "pfi"
bytes = 78848
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0001903
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1889
basis_update = "pfi"
bytes = 414832
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004192
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 616
basis_update = "pfi"
bytes = 109168
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002316
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1992
basis_update = "forrest_tomlin"
bytes = 424360
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0005327
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 716
basis_update = "forrest_tomlin"
bytes = 89968
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002407
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2147
basis_update = "forrest_tomlin"
bytes = 428272
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004991
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 878
basis_update = "forrest_tomlin"
bytes = 121232
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002547
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1994
basis_update = "suhl_suhl"
bytes = 425288
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004895
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 708
basis_update = "suhl_suhl"
bytes = 89920
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002591
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2143
basis_update = "suhl_suhl"
bytes = 428288
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004612
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 876
basis_update = "suhl_suhl"
bytes = 122496
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002701
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2108
basis_update = "bartels_golub"
bytes = 429816
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.7531428571428
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0006003
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 827
basis_update = "bartels_golub"
bytes = 96640
compile_seconds = 0.0
dataset = "afiro"
iterations = 20
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002738
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 2235
basis_update = "bartels_golub"
bytes = 432192
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714273
refactorization_interval = 1
refactorizations = 17
samples = 3
seconds = 0.0004985
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 967
basis_update = "bartels_golub"
bytes = 128608
compile_seconds = 0.0
dataset = "afiro"
iterations = 16
objective = -464.75314285714285
refactorization_interval = 20
refactorizations = 1
samples = 3
seconds = 0.0002894
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1765
basis_update = "pfi"
bytes = 903256
compile_seconds = 0.0
dataset = "adlittle"
iterations = 97
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001238
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 922
basis_update = "pfi"
bytes = 508240
compile_seconds = 0.0
dataset = "adlittle"
iterations = 115
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0014834
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7254
basis_update = "pfi"
bytes = 5878616
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003025599
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1027
basis_update = "pfi"
bytes = 567576
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0013468
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2411
basis_update = "forrest_tomlin"
bytes = 972264
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.0017093
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1558
basis_update = "forrest_tomlin"
bytes = 550208
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.001583899
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7834
basis_update = "forrest_tomlin"
bytes = 5927992
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.003231199
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1657
basis_update = "forrest_tomlin"
bytes = 620248
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0016753
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2427
basis_update = "suhl_suhl"
bytes = 987208
compile_seconds = 0.0
dataset = "adlittle"
iterations = 101
objective = 225494.96316238027
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001643899
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1548
basis_update = "suhl_suhl"
bytes = 551152
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.9631623804
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0014949
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 7838
basis_update = "suhl_suhl"
bytes = 5930776
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0035063
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1663
basis_update = "suhl_suhl"
bytes = 626872
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017001
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 2679
basis_update = "bartels_golub"
bytes = 982376
compile_seconds = 0.0
dataset = "adlittle"
iterations = 93
objective = 225494.9631623804
refactorization_interval = 1
refactorizations = 16
samples = 3
seconds = 0.001769699
status = "OPTIMAL"
[[rows]]
algorithm = "dual"
allocations = 1830
basis_update = "bartels_golub"
bytes = 568608
compile_seconds = 0.0
dataset = "adlittle"
iterations = 102
objective = 225494.96316238045
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0017908
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 8009
basis_update = "bartels_golub"
bytes = 5934920
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.96316238036
refactorization_interval = 1
refactorizations = 83
samples = 3
seconds = 0.0035177
status = "OPTIMAL"
[[rows]]
algorithm = "primal"
allocations = 1838
basis_update = "bartels_golub"
bytes = 634872
compile_seconds = 0.0
dataset = "adlittle"
iterations = 82
objective = 225494.9631623803
refactorization_interval = 20
refactorizations = 5
samples = 3
seconds = 0.0018429
status = "OPTIMAL"
