julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.adlittle.dual]
allocations = 82230
bytes = 4041720
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.004235401
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461480
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010507
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80215
bytes = 3252824
compile_seconds = 0.0
samples = 3
seconds = 0.0024603

[datasets.adlittle.primal]
allocations = 83028
bytes = 4319064
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003940401
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607104
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0012493
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18173
bytes = 640552
compile_seconds = 0.0
samples = 3
seconds = 0.0004767

[datasets.adlittle.singleton]
allocations = 554
bytes = 59088
compile_seconds = 0.0
samples = 3
seconds = 7.13e-5

[datasets.adlittle.sparse]
allocations = 1518
bytes = 125768
compile_seconds = 0.0
samples = 3
seconds = 0.0001261

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.5e-6

[datasets.afiro.dual]
allocations = 16072
bytes = 828952
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0011064
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002311
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15257
bytes = 694136
compile_seconds = 0.0
samples = 3
seconds = 0.0006471

[datasets.afiro.primal]
allocations = 15978
bytes = 807336
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008567
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002393
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 92840
compile_seconds = 0.0
samples = 3
seconds = 0.0001298

[datasets.afiro.singleton]
allocations = 747
bytes = 41024
compile_seconds = 0.0
samples = 3
seconds = 8.8e-5

[datasets.afiro.sparse]
allocations = 3238
bytes = 157904
compile_seconds = 0.0
samples = 3
seconds = 0.0001289

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.7e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.5e-6

[datasets.flugpl.dual]
allocations = 26010
bytes = 1086528
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009755
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001695
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25339
bytes = 976760
compile_seconds = 0.0
samples = 3
seconds = 0.0008497

[datasets.flugpl.primal]
allocations = 26359
bytes = 1130624
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009703
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000213
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123760
compile_seconds = 0.0
samples = 3
seconds = 0.0001284

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.8e-5

[datasets.flugpl.sparse]
allocations = 3812
bytes = 145256
compile_seconds = 0.0
samples = 3
seconds = 0.0001418

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.9e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.kb2.dual]
allocations = 227499
bytes = 10992424
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022084201
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 878176
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009213
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 226297
bytes = 10539192
compile_seconds = 0.0
samples = 3
seconds = 0.023177301

[datasets.kb2.primal]
allocations = 227666
bytes = 11005560
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023045201
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260832
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006268
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454032
compile_seconds = 0.0
samples = 3
seconds = 0.0003683

[datasets.kb2.singleton]
allocations = 1492
bytes = 88904
compile_seconds = 0.0
samples = 3
seconds = 8.23e-5

[datasets.kb2.sparse]
allocations = 1765
bytes = 118840
compile_seconds = 0.0
samples = 3
seconds = 0.0001176

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.66e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 3.3e-6

[datasets.sc50a.dual]
allocations = 64369
bytes = 3056608
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022311
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306496
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0006408
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 63297
bytes = 2710240
compile_seconds = 0.0
samples = 3
seconds = 0.0018178

[datasets.sc50a.primal]
allocations = 64314
bytes = 3008784
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023281
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000554
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221312
compile_seconds = 0.0
samples = 3
seconds = 0.000179

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.85e-5

[datasets.sc50a.sparse]
allocations = 4415
bytes = 227800
compile_seconds = 0.0
samples = 3
seconds = 0.0001895

[probes.negative_unit]
allocations = 386
bytes = 37984
compile_seconds = 0.0
samples = 3
seconds = 3.08e-5

[probes.nonunit]
allocations = 1922
bytes = 90976
compile_seconds = 0.0
samples = 3
seconds = 8.69e-5

[probes.positive_unit]
allocations = 386
bytes = 37984
compile_seconds = 0.0
samples = 3
seconds = 3.18e-5

[probes.rounded_negative]
allocations = 386
bytes = 36928
compile_seconds = 0.0
samples = 3
seconds = 3.15e-5

[probes.rounded_positive]
allocations = 386
bytes = 36928
compile_seconds = 0.0
samples = 3
seconds = 2.53e-5

[probes.zero]
allocations = 386
bytes = 37984
compile_seconds = 0.0
samples = 3
seconds = 1.73e-5
