julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 6.8e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.3e-6

[datasets.adlittle.dual]
allocations = 82230
bytes = 4041864
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003071702
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461176
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.000937801
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80215
bytes = 3254904
compile_seconds = 0.0
samples = 3
seconds = 0.002019501

[datasets.adlittle.primal]
allocations = 83028
bytes = 4318696
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003247001
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 606880
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.001046901
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18173
bytes = 641416
compile_seconds = 0.0
samples = 3
seconds = 0.000364301

[datasets.adlittle.singleton]
allocations = 554
bytes = 59088
compile_seconds = 0.0
samples = 3
seconds = 5.59e-5

[datasets.adlittle.sparse]
allocations = 1518
bytes = 125640
compile_seconds = 0.0
samples = 3
seconds = 9.54e-5

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 5.4e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.9e-6

[datasets.afiro.dual]
allocations = 16072
bytes = 830872
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.00073
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0001772
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15257
bytes = 694936
compile_seconds = 0.0
samples = 3
seconds = 0.0006157

[datasets.afiro.primal]
allocations = 15978
bytes = 808104
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000725801
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001978
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93224
compile_seconds = 0.0
samples = 3
seconds = 8.6e-5

[datasets.afiro.singleton]
allocations = 747
bytes = 40720
compile_seconds = 0.0
samples = 3
seconds = 7.05e-5

[datasets.afiro.sparse]
allocations = 3502
bytes = 166560
compile_seconds = 0.0
samples = 3
seconds = 0.0001285

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 5.5e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 3.7e-6

[datasets.flugpl.dual]
allocations = 26010
bytes = 1085936
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007342
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000149901
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25339
bytes = 976392
compile_seconds = 0.0
samples = 3
seconds = 0.000585703

[datasets.flugpl.primal]
allocations = 26359
bytes = 1130224
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0007969
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001625
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123952
compile_seconds = 0.0
samples = 3
seconds = 9.9e-5

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.6401e-5

[datasets.flugpl.sparse]
allocations = 3812
bytes = 145672
compile_seconds = 0.0
samples = 3
seconds = 9.3601e-5

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 6.2e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.0e-6

[datasets.kb2.dual]
allocations = 227499
bytes = 10992744
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.020875207
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877648
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007748
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 226297
bytes = 10539096
compile_seconds = 0.0
samples = 3
seconds = 0.019950608

[datasets.kb2.primal]
allocations = 227666
bytes = 11005896
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.020837507
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260912
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005971
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454800
compile_seconds = 0.0
samples = 3
seconds = 0.0002543

[datasets.kb2.singleton]
allocations = 1492
bytes = 88744
compile_seconds = 0.0
samples = 3
seconds = 7.47e-5

[datasets.kb2.sparse]
allocations = 1765
bytes = 118664
compile_seconds = 0.0
samples = 3
seconds = 9.93e-5

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.43e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.1e-6

[datasets.sc50a.dual]
allocations = 64897
bytes = 3072656
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.001910308
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306480
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000562002
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 63825
bytes = 2726912
compile_seconds = 0.0
samples = 3
seconds = 0.001425807

[datasets.sc50a.primal]
allocations = 64842
bytes = 3025488
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.001871908
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.000512903
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 221872
compile_seconds = 0.0
samples = 3
seconds = 0.000164301

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 1.51e-5

[datasets.sc50a.sparse]
allocations = 4859
bytes = 241680
compile_seconds = 0.0
samples = 3
seconds = 0.000142301

[probes.negative_unit]
allocations = 1922
bytes = 90832
compile_seconds = 0.0
samples = 3
seconds = 7.08e-5

[probes.nonunit]
allocations = 1922
bytes = 90848
compile_seconds = 0.0
samples = 3
seconds = 5.85e-5

[probes.positive_unit]
allocations = 1922
bytes = 90976
compile_seconds = 0.0
samples = 3
seconds = 7.25e-5

[probes.rounded_negative]
allocations = 1922
bytes = 89760
compile_seconds = 0.0
samples = 3
seconds = 5.82e-5

[probes.rounded_positive]
allocations = 1922
bytes = 89760
compile_seconds = 0.0
samples = 3
seconds = 5.74e-5

[probes.zero]
allocations = 386
bytes = 37984
compile_seconds = 0.0
samples = 3
seconds = 1.41e-5
