[BigFloat]
columns = 32
rows = 32

    [BigFloat.after]
    allocations = 29014
    bytes = 2796120
    compile_seconds = 0.0
    samples = 3
    seconds = 0.0004742

    [BigFloat.before]
    allocations = 29028
    bytes = 2799384
    compile_seconds = 0.0
    samples = 3
    seconds = 0.0004872

[Float32]
columns = 32
rows = 32

    [Float32.after]
    allocations = 80
    bytes = 14184
    compile_seconds = 0.0
    samples = 3
    seconds = 4.41e-5

    [Float32.before]
    allocations = 94
    bytes = 16168
    compile_seconds = 0.0
    samples = 3
    seconds = 4.08e-5

[Float64]
columns = 32
rows = 32

    [Float64.after]
    allocations = 156
    bytes = 35072
    compile_seconds = 0.0
    samples = 3
    seconds = 6.49e-5

    [Float64.before]
    allocations = 170
    bytes = 38368
    compile_seconds = 0.0
    samples = 3
    seconds = 4.39e-5

["Rational{BigInt}"]
columns = 32
rows = 32

    ["Rational{BigInt}".after]
    allocations = 203613
    bytes = 8381536
    compile_seconds = 0.0
    samples = 3
    seconds = 0.0025267

    ["Rational{BigInt}".before]
    allocations = 203627
    bytes = 8384704
    compile_seconds = 0.0
    samples = 3
    seconds = 0.0024845

[greenbea]
columns = 5405
rows = 2392

    [greenbea.after]
    allocations = 192
    bytes = 2297104
    compile_seconds = 0.0
    samples = 3
    seconds = 0.0003509

    [greenbea.before]
    allocations = 213
    bytes = 2628744
    compile_seconds = 0.0
    samples = 3
    seconds = 0.0003456
