julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123668
bytes = 5880712
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036807
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1355
bytes = 476344
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009084
status = "OPTIMAL"

[datasets.adlittle.initialize]
allocations = 158
bytes = 59568
compile_seconds = 0.0
samples = 3
seconds = 5.73e-5

[datasets.adlittle.primal]
allocations = 124522
bytes = 6169736
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.0037394
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1984
bytes = 635312
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0010265
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28774
bytes = 1357160
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0008557
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 584
bytes = 95840
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002353
status = "OPTIMAL"

[datasets.afiro.initialize]
allocations = 156
bytes = 31056
compile_seconds = 0.0
samples = 3
seconds = 4.18e-5

[datasets.afiro.primal]
allocations = 28676
bytes = 1334984
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000749501
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 844
bytes = 133392
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002471
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40057
bytes = 1629048
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008596
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 405
bytes = 46672
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000124
status = "OPTIMAL"

[datasets.flugpl.initialize]
allocations = 156
bytes = 22608
compile_seconds = 0.0
samples = 3
seconds = 4.55e-5

[datasets.flugpl.primal]
allocations = 40462
bytes = 1679176
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009362
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 824
bytes = 101664
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001558
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294402
bytes = 13814176
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.0216092
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1537
bytes = 886112
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0008082
status = "OPTIMAL"

[datasets.kb2.initialize]
allocations = 156
bytes = 44320
compile_seconds = 0.0
samples = 3
seconds = 5.56e-5

[datasets.kb2.primal]
allocations = 294565
bytes = 13827168
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.0222304
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1079
bytes = 267600
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006048
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107629
bytes = 4714032
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0023958
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 990
bytes = 315888
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005423
status = "OPTIMAL"

[datasets.sc50a.initialize]
allocations = 156
bytes = 50128
compile_seconds = 0.0
samples = 3
seconds = 4.99e-5

[datasets.sc50a.primal]
allocations = 107570
bytes = 4665664
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0023356
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 989
bytes = 239912
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004647
status = "OPTIMAL"
