julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.dual]
allocations = 123696
bytes = 5895096
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.0036017
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1369
bytes = 483368
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0009256
status = "OPTIMAL"

[datasets.adlittle.initialize]
allocations = 172
bytes = 66880
compile_seconds = 0.0
samples = 3
seconds = 6.69e-5

[datasets.adlittle.primal]
allocations = 124564
bytes = 6191896
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003693
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 2012
bytes = 650656
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011067
status = "OPTIMAL"

[datasets.afiro.dual]
allocations = 28802
bytes = 1362184
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007718
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 598
bytes = 98768
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002271
status = "OPTIMAL"

[datasets.afiro.initialize]
allocations = 170
bytes = 34080
compile_seconds = 0.0
samples = 3
seconds = 4.52e-5

[datasets.afiro.primal]
allocations = 28704
bytes = 1341304
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0007264
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 872
bytes = 139488
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0001947
status = "OPTIMAL"

[datasets.flugpl.dual]
allocations = 40085
bytes = 1633928
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000846
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 419
bytes = 48768
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.000128
status = "OPTIMAL"

[datasets.flugpl.initialize]
allocations = 170
bytes = 24704
compile_seconds = 0.0
samples = 3
seconds = 4.67e-5

[datasets.flugpl.primal]
allocations = 40504
bytes = 1685720
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0008585
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 852
bytes = 106256
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001714
status = "OPTIMAL"

[datasets.kb2.dual]
allocations = 294430
bytes = 13821968
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.022257699
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1551
bytes = 890272
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0007326
status = "OPTIMAL"

[datasets.kb2.initialize]
allocations = 170
bytes = 48576
compile_seconds = 0.0
samples = 3
seconds = 5.33e-5

[datasets.kb2.primal]
allocations = 294593
bytes = 13835328
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.022628899
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1093
bytes = 271888
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0005776
status = "OPTIMAL"

[datasets.sc50a.dual]
allocations = 107657
bytes = 4722832
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.002327
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 1004
bytes = 320896
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.0005479
status = "OPTIMAL"

[datasets.sc50a.initialize]
allocations = 170
bytes = 55120
compile_seconds = 0.0
samples = 3
seconds = 6.17e-5

[datasets.sc50a.primal]
allocations = 107598
bytes = 4674880
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0022229
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 1003
bytes = 244936
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0004437
status = "OPTIMAL"
