julia_version = "1.13.0"
machine = "aarch64-linux-gnu"
threads = 1

[datasets.adlittle.basic]
allocations = 15
bytes = 2928
compile_seconds = 0.0
samples = 3
seconds = 7.7e-6

[datasets.adlittle.doubleton]
allocations = 3
bytes = 2208
compile_seconds = 0.0
samples = 3
seconds = 5.2e-6

[datasets.adlittle.dual]
allocations = 82230
bytes = 4042680
compile_seconds = 0.0
iterations = 102
objective = 225494.9631623804
samples = 3
seconds = 0.003669801
status = "OPTIMAL"

[datasets.adlittle.dual_no_presolve]
allocations = 1326
bytes = 461464
compile_seconds = 0.0
iterations = 91
objective = 225494.96316238047
samples = 3
seconds = 0.0010406
status = "OPTIMAL"

[datasets.adlittle.presolve]
allocations = 80215
bytes = 3253976
compile_seconds = 0.0
samples = 3
seconds = 0.002418101

[datasets.adlittle.primal]
allocations = 83028
bytes = 4319416
compile_seconds = 0.0
iterations = 117
objective = 225494.96316238027
samples = 3
seconds = 0.003672101
status = "OPTIMAL"

[datasets.adlittle.primal_no_presolve]
allocations = 1899
bytes = 607008
compile_seconds = 0.0
iterations = 87
objective = 225494.96316238036
samples = 3
seconds = 0.0011889
status = "OPTIMAL"

[datasets.adlittle.propagation]
allocations = 18173
bytes = 640968
compile_seconds = 0.0
samples = 3
seconds = 0.0004337

[datasets.adlittle.singleton]
allocations = 554
bytes = 59088
compile_seconds = 0.0
samples = 3
seconds = 6.56e-5

[datasets.adlittle.sparse]
allocations = 1518
bytes = 125160
compile_seconds = 0.0
samples = 3
seconds = 0.0001178

[datasets.afiro.basic]
allocations = 15
bytes = 1392
compile_seconds = 0.0
samples = 3
seconds = 6.6e-6

[datasets.afiro.doubleton]
allocations = 3
bytes = 1072
compile_seconds = 0.0
samples = 3
seconds = 3.4e-6

[datasets.afiro.dual]
allocations = 16072
bytes = 830184
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.0009631
status = "OPTIMAL"

[datasets.afiro.dual_no_presolve]
allocations = 555
bytes = 89920
compile_seconds = 0.0
iterations = 20
objective = -464.7531428571428
samples = 3
seconds = 0.0002345
status = "OPTIMAL"

[datasets.afiro.presolve]
allocations = 15257
bytes = 693976
compile_seconds = 0.0
samples = 3
seconds = 0.000767801

[datasets.afiro.primal]
allocations = 15978
bytes = 807928
compile_seconds = 0.0
iterations = 9
objective = -464.75314285714273
samples = 3
seconds = 0.000906301
status = "OPTIMAL"

[datasets.afiro.primal_no_presolve]
allocations = 759
bytes = 121728
compile_seconds = 0.0
iterations = 16
objective = -464.75314285714285
samples = 3
seconds = 0.0002445
status = "OPTIMAL"

[datasets.afiro.propagation]
allocations = 2437
bytes = 93288
compile_seconds = 0.0
samples = 3
seconds = 0.000107

[datasets.afiro.singleton]
allocations = 747
bytes = 40992
compile_seconds = 0.0
samples = 3
seconds = 8.64e-5

[datasets.afiro.sparse]
allocations = 3502
bytes = 166736
compile_seconds = 0.0
samples = 3
seconds = 0.0001474

[datasets.flugpl.basic]
allocations = 15
bytes = 1056
compile_seconds = 0.0
samples = 3
seconds = 6.0e-6

[datasets.flugpl.doubleton]
allocations = 3
bytes = 800
compile_seconds = 0.0
samples = 3
seconds = 2.2e-6

[datasets.flugpl.dual]
allocations = 26010
bytes = 1085840
compile_seconds = 0.0
iterations = 12
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009877
status = "OPTIMAL"

[datasets.flugpl.dual_no_presolve]
allocations = 376
bytes = 42736
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0001649
status = "OPTIMAL"

[datasets.flugpl.presolve]
allocations = 25339
bytes = 976152
compile_seconds = 0.0
samples = 3
seconds = 0.0007878

[datasets.flugpl.primal]
allocations = 26359
bytes = 1131072
compile_seconds = 0.0
iterations = 11
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0009977
status = "OPTIMAL"

[datasets.flugpl.primal_no_presolve]
allocations = 739
bytes = 91680
compile_seconds = 0.0
iterations = 14
objective = 1.1671857255923203e6
samples = 3
seconds = 0.0002119
status = "OPTIMAL"

[datasets.flugpl.propagation]
allocations = 3253
bytes = 123280
compile_seconds = 0.0
samples = 3
seconds = 0.0001137

[datasets.flugpl.singleton]
allocations = 100
bytes = 4384
compile_seconds = 0.0
samples = 3
seconds = 1.76e-5

[datasets.flugpl.sparse]
allocations = 3812
bytes = 144952
compile_seconds = 0.0
samples = 3
seconds = 0.0001235

[datasets.kb2.basic]
allocations = 15
bytes = 1680
compile_seconds = 0.0
samples = 3
seconds = 9.0e-6

[datasets.kb2.doubleton]
allocations = 3
bytes = 1664
compile_seconds = 0.0
samples = 3
seconds = 5.1e-6

[datasets.kb2.dual]
allocations = 227499
bytes = 10992200
compile_seconds = 0.0
iterations = 41
objective = -1749.9001299062058
samples = 3
seconds = 0.023289304
status = "OPTIMAL"

[datasets.kb2.dual_no_presolve]
allocations = 1508
bytes = 877920
compile_seconds = 0.0
iterations = 50
objective = -1749.900129906206
samples = 3
seconds = 0.0009348
status = "OPTIMAL"

[datasets.kb2.presolve]
allocations = 226297
bytes = 10539656
compile_seconds = 0.0
samples = 3
seconds = 0.023084006

[datasets.kb2.primal]
allocations = 227666
bytes = 11005816
compile_seconds = 0.0
iterations = 45
objective = -1749.9001299062054
samples = 3
seconds = 0.023280504
status = "OPTIMAL"

[datasets.kb2.primal_no_presolve]
allocations = 1054
bytes = 260848
compile_seconds = 0.0
iterations = 54
objective = -1749.9001299062058
samples = 3
seconds = 0.0006255
status = "OPTIMAL"

[datasets.kb2.propagation]
allocations = 12948
bytes = 454800
compile_seconds = 0.0
samples = 3
seconds = 0.0003224

[datasets.kb2.singleton]
allocations = 1492
bytes = 88168
compile_seconds = 0.0
samples = 3
seconds = 7.92e-5

[datasets.kb2.sparse]
allocations = 1765
bytes = 118104
compile_seconds = 0.0
samples = 3
seconds = 0.0001125

[datasets.sc50a.basic]
allocations = 60
bytes = 17760
compile_seconds = 0.0
samples = 3
seconds = 1.43e-5

[datasets.sc50a.doubleton]
allocations = 3
bytes = 1808
compile_seconds = 0.0
samples = 3
seconds = 4.2e-6

[datasets.sc50a.dual]
allocations = 64897
bytes = 3071376
compile_seconds = 0.0
iterations = 34
objective = -64.57507705856449
samples = 3
seconds = 0.0022704
status = "OPTIMAL"

[datasets.sc50a.dual_no_presolve]
allocations = 961
bytes = 306192
compile_seconds = 0.0
iterations = 52
objective = -64.57507705856449
samples = 3
seconds = 0.000610601
status = "OPTIMAL"

[datasets.sc50a.presolve]
allocations = 63825
bytes = 2725440
compile_seconds = 0.0
samples = 3
seconds = 0.0017364

[datasets.sc50a.primal]
allocations = 64842
bytes = 3024208
compile_seconds = 0.0
iterations = 29
objective = -64.57507705856447
samples = 3
seconds = 0.0024089
status = "OPTIMAL"

[datasets.sc50a.primal_no_presolve]
allocations = 964
bytes = 232216
compile_seconds = 0.0
iterations = 46
objective = -64.57507705856449
samples = 3
seconds = 0.0005503
status = "OPTIMAL"

[datasets.sc50a.propagation]
allocations = 6020
bytes = 222448
compile_seconds = 0.0
samples = 3
seconds = 0.0001652

[datasets.sc50a.singleton]
allocations = 298
bytes = 12608
compile_seconds = 0.0
samples = 3
seconds = 2.21e-5

[datasets.sc50a.sparse]
allocations = 4859
bytes = 241680
compile_seconds = 0.0
samples = 3
seconds = 0.0001734

[probes.inexact_nonzero]
allocations = 1922
bytes = 90208
compile_seconds = 0.0
samples = 3
seconds = 7.97e-5

[probes.nonzero]
allocations = 1922
bytes = 91840
compile_seconds = 0.0
samples = 3
seconds = 8.65e-5

[probes.underflow_float32]
allocations = 386
bytes = 36928
compile_seconds = 0.0
samples = 3
seconds = 4.14e-5

[probes.underflow_float64]
allocations = 386
bytes = 36928
compile_seconds = 0.0
samples = 3
seconds = 4.07e-5

[probes.zero_float32]
allocations = 386
bytes = 37440
compile_seconds = 0.0
samples = 3
seconds = 1.81e-5

[probes.zero_float64]
allocations = 386
bytes = 37984
compile_seconds = 0.0
samples = 3
seconds = 1.82e-5
