using Test, JSimplex, SparseArrays, LinearAlgebra
@testset "Legacy compilation guard validation" begin
    println("START primal_bound_snap_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "primal_bound_snap_tests.jl"))
    println("END primal_bound_snap_tests.jl");flush(stdout)
    println("START primal_candidate_retry_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "primal_candidate_retry_tests.jl"))
    println("END primal_candidate_retry_tests.jl");flush(stdout)
    println("START legacy_primal_row_value_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_primal_row_value_tests.jl"))
    println("END legacy_primal_row_value_tests.jl");flush(stdout)
    println("START primal_initial_tolerance_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "primal_initial_tolerance_tests.jl"))
    println("END primal_initial_tolerance_tests.jl");flush(stdout)
    println("START legacy_dual_correction_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_dual_correction_tests.jl"))
    println("END legacy_dual_correction_tests.jl");flush(stdout)
    println("START legacy_correction_cycle_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_correction_cycle_tests.jl"))
    println("END legacy_correction_cycle_tests.jl");flush(stdout)
    println("START legacy_retry_edge_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_retry_edge_tests.jl"))
    println("END legacy_retry_edge_tests.jl");flush(stdout)
    println("START legacy_harris_feasibility_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_harris_feasibility_tests.jl"))
    println("END legacy_harris_feasibility_tests.jl");flush(stdout)
    println("START legacy_primal_point_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_primal_point_tests.jl"))
    println("END legacy_primal_point_tests.jl");flush(stdout)
    println("START legacy_primal_pivot_row_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_primal_pivot_row_tests.jl"))
    println("END legacy_primal_pivot_row_tests.jl");flush(stdout)
    println("START legacy_hardware_guard_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "legacy_hardware_guard_tests.jl"))
    println("END legacy_hardware_guard_tests.jl");flush(stdout)
    println("START solver_policy_precision_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "solver_policy_precision_tests.jl"))
    println("END solver_policy_precision_tests.jl");flush(stdout)
    println("START simplex_precision_phase_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "simplex_precision_phase_tests.jl"))
    println("END simplex_precision_phase_tests.jl");flush(stdout)
    println("START simplex_precision_exception_tests.jl");flush(stdout)
    include(joinpath(dirname(dirname(pathof(JSimplex))), "test", "simplex_precision_exception_tests.jl"))
    println("END simplex_precision_exception_tests.jl");flush(stdout)
end
